# syntax=docker/dockerfile:1.7

FROM --platform=$BUILDPLATFORM golang:1.26.2-bookworm@sha256:47ce5636e9936b2c5cbf708925578ef386b4f8872aec74a67bd13a627d242b19 AS build
ARG TARGETOS
ARG TARGETARCH
WORKDIR /src
COPY go.mod go.sum ./
COPY cmd/blazn-sandbox-io ./cmd/blazn-sandbox-io
COPY internal/sandboxio ./internal/sandboxio
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -buildvcs=false -trimpath -tags netgo,osusergo -ldflags='-s -w' -o /out/blazn-sandbox-io ./cmd/blazn-sandbox-io

FROM scratch
COPY --from=build --chmod=0555 /out/blazn-sandbox-io /blazn-sandbox-io
USER 65532:65532
ENTRYPOINT ["/blazn-sandbox-io"]
