apiVersion: v1
data:
  object-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBhTCCASygAwIBAgIUAt/UTD4A5OpusUpVYNPjVAE7Hr0wCgYIKoZIzj0EAwIw
    ITEfMB0GA1UEAxMWYmxhem4tdGVzdC1pbnRlcm5hbC1jYTAeFw0yNjA5MjgyMTAy
    MDhaFw0yNzA5MjgyMTAyMDhaMCExHzAdBgNVBAMTFmJsYXpuLXRlc3QtaW50ZXJu
    YWwtY2EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARFpo+wHWu8Y/bSC0W4pzKd
    veuh3ikcJ02dp8ZtBpMFGzt6l6HKIpEHY0n7J5C77AxXRJUmpkN9FKrfyEGSgBOn
    o0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU
    l8iaFw8CO0SXjRa5ue55KUXgoeUwCgYIKoZIzj0EAwIDRwAwRAIgNsgHJTqTx4UP
    vmfLmTlyg41g4vpPHBxTlqBJtMfQAiACIGDgDLFZb/xoiLeeWoEfwfUCvGoI6XUp
    ai7SA8aOu6KC
    -----END CERTIFICATE-----
  postgres-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEQjCCAqqgAwIBAgIQPkfPPHebqs4HRtX+XHcZUzANBgkqhkiG9w0BAQsFADAp
    MScwJQYDVQQDDB5Gcm9udHJvIFBvc3RncmVTUUwgSW50ZXJuYWwgQ0EwHhcNMjYw
    OTI3MDQ1MzE5WhcNMzYwOTI0MDQ1MzE5WjApMScwJQYDVQQDDB5Gcm9udHJvIFBv
    c3RncmVTUUwgSW50ZXJuYWwgQ0EwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGK
    AoIBgQDUTcAy9pWsJvobOaoOCB/wpj0x0LGNox287eeEQd48XtkXJz+cqRaVJzfI
    cl8LK866PoFne6pOr/0RjSRw+9k+QFpWEvjXi7baMxrb1vy2BjY7EsKM7PpGaX17
    lNqys63MnwX1b+aqLT/c9pz24AFkiMtdKJZPypaoG1K1xs2vhj3/Gtud6XH8hbF9
    LRQ6yKoOcAp83jd2gpIU7icHGAslBlamuh3fk7ISKjcpu56yy8h5+FJLqRThVK3c
    4WkUuYQVrtgwpq4EO+vGCHKFBl25N5qMDi01cPC3iflLT3CyRzeUPdUcnf8s5OwQ
    jyKK9otZ4kIY9L+B26Yym83l2cPbxd9G/0zPNMJXkQfuPWbJG7a/LAZy7Oe1HmYO
    eLmYXPrCYLZEuhsKVLt1m5dOVSA9KsZQ+s3SBw6sckC1grMjIqMRsLCOsIXOlni6
    743RT3jbWFo0r1F0r6nZux5SRvAZyMyV9Kqx30a9i85T7EztD9uh6DK4fefpQPwM
    m9TR6wECAwEAAaNmMGQwHwYDVR0jBBgwFoAUM/yNPPMk785J7VR74urXS4sL4ckw
    EgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFDP8
    jTzzJO/OSe1Ue+Lq10uLC+HJMA0GCSqGSIb3DQEBCwUAA4IBgQCXIi7umlHPAwsS
    HkZkkBqLVow2x2BC7IMhBCl+3uKTaYrswS9Q9IFRRGYx7p5sRcfKxELQNLPkzM3a
    MyI2HGC41fHnvZ5j9v5nit/arJYSg2AFdz/cmMK7NEoCVBkxOX+btoGIztYOnzuP
    9Fz85SzEwGxMozkoQHurX7B1Fhb/rtBEvL89JLRxPpnXgfP2UrmmZY6hOW8pISo6
    m3j/FnIFM6od2ABKsAS94Uj3zQnuTEz8djjm4vOLP8bPcQQqxhY/wwY2CRBV6dYP
    IxfHT4cEiCVrXvukIu4MSs3mj/LI6DVcKLmiyQAuozOXRW7Gj6NivgHTIBBlgHkF
    5YQNVsor8DSaFbmZ5yaY14R2hpRjmYBdCg4wfIbarOb//HhytjOmwlQzm6SNMqY1
    9z9GY76i0yeOfxxvPr4sAVXulWCdzW0eLmQg0jcy3D1Cv+rmfs9OofXucQAgNuX/
    8Y7QxRmC4ppidy6xngRodHWnt32lmap+hJDpi3JmH5RuAEmc1QQ=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: api-public-ca
  namespace: blazn-test
