apiVersion: v1
data:
  nginx.conf: |
    pid /tmp/nginx.pid;
    events {}
    http {
     access_log off;
     error_log /dev/stderr warn;
     client_body_temp_path /tmp/client;
     proxy_temp_path /tmp/proxy;
     fastcgi_temp_path /tmp/fastcgi;
     uwsgi_temp_path /tmp/uwsgi;
     scgi_temp_path /tmp/scgi;
     server {
      listen 8081;
      client_max_body_size 1m;
      location / {
       proxy_pass http://127.0.0.1:8080;
       proxy_set_header Host api.blazn.frontro.com;
       proxy_set_header X-Forwarded-Proto https;
       proxy_set_header X-Forwarded-For $http_x_forwarded_for;
       include /secrets/proxy-header.conf;
       proxy_read_timeout 65;
       proxy_buffering off;
      }
     }
    }
kind: ConfigMap
metadata:
  name: api-proxy-dev
  namespace: blazn-test
