apiVersion: v1
data:
  agent.hcl: |
    exit_after_auth = true
    pid_file = "/tmp/agent.pid"
    vault { address = "https://openbao.frontro-secrets.svc.cluster.local:8200" ca_cert = "/ca/ca.crt" }
    auto_auth { method "kubernetes" { mount_path = "auth/kubernetes" config = { role = "blazn-test-registry", token_path = "/identity/token" } } }
    template { error_on_missing_key = true destination = "/rendered/all.htpasswd" perms = "0400" contents = <<EOT
    {{ with secret "apps/data/blazn/test/registry" }}{{ .Data.data.all_htpasswd }}{{ end }}
    EOT
    }
    template { error_on_missing_key = true destination = "/rendered/push.htpasswd" perms = "0400" contents = <<EOT
    {{ with secret "apps/data/blazn/test/registry" }}{{ .Data.data.push_htpasswd }}{{ end }}
    EOT
    }
kind: ConfigMap
metadata:
  name: registry-agent
  namespace: blazn-test
