apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-api-agent-dev.yaml
- configmap-api-proxy-dev.yaml
- configmap-api-public-ca.yaml
- configmap-openbao-client-ca.yaml
- configmap-registry-agent.yaml
- configmap-registry-nginx.yaml
- configmap-storage-agent.yaml
- deployment-api-dev.yaml
- deployment-objectstore.yaml
- deployment-registry.yaml
- networkpolicy-api-data-egress-dev.yaml
- networkpolicy-api-dev-email-capture-egress.yaml
- networkpolicy-api-dev-email-egress.yaml
- networkpolicy-api-dev-node-broker-egress.yaml
- networkpolicy-api-dev-sandbox-access-egress.yaml
- networkpolicy-api-from-edge-dev.yaml
- networkpolicy-default-deny.yaml
- networkpolicy-dns.yaml
- networkpolicy-openbao-egress.yaml
- networkpolicy-registry-from-ben5.yaml
- networkpolicy-storage-from-api-dev.yaml
- networkpolicy-storage-from-sandbox-controller.yaml
- persistentvolumeclaim-registry-data.yaml
- persistentvolumeclaim-storage-data.yaml
- service-api-dev.yaml
- service-objectstore.yaml
- service-registry.yaml
- serviceaccount-blazn-api.yaml
- serviceaccount-blazn-api-dev.yaml
- serviceaccount-blazn-dev-identity-database.yaml
- serviceaccount-blazn-dev-identity-server.yaml
- serviceaccount-blazn-migrate.yaml
- serviceaccount-blazn-registry.yaml
- serviceaccount-blazn-storage.yaml
