apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data
  namespace: blazn-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: frontro-hostpath-srv
  volumeMode: Filesystem
