apiVersion: v1
kind: Service
metadata:
  name: objectstore
  namespace: blazn-test
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: objectstore
  sessionAffinity: None
  type: ClusterIP
