apiVersion: v1
data:
  init.hcl: |
    exit_after_auth=true
    pid_file="/tmp/agent.pid"
    vault { address="https://openbao.frontro-secrets.svc.cluster.local:8200" ca_cert="/ca/ca.crt" }
    auto_auth { method "kubernetes" { mount_path="auth/kubernetes" config={role="blazn-dev-identity-server",token_path="/identity/token"} } }
    template { error_on_missing_key=true destination="/rendered/config.yaml" perms="0400" contents=<<EOT
    Log:
      Level: error
    Database:
      postgres:
        Host: frontro-db-1
        Port: 5432
        Database: zitadel
        User:
          Username: zitadel
          Password: {{ with secret "apps/data/blazn/development/identity/database" }}{{ .Data.data.user_password }}{{ end }}
          SSL:
            Mode: verify-full
            RootCert: /tls/ca.crt
        Admin:
          Username: postgres
          Password: {{ with secret "apps/data/blazn/development/identity/database" }}{{ .Data.data.admin_password }}{{ end }}
          ExistingDatabase: postgres
          SSL:
            Mode: verify-full
            RootCert: /tls/ca.crt
    DefaultInstance:
      LoginPolicy:
        AllowRegister: false
        ForceMFA: true
        IgnoreUnknownUsernames: true

    EOT
    }
    template { error_on_missing_key=true destination="/rendered/steps.yaml" perms="0400" contents=<<EOT
    FirstInstance:
      Org:
        Name: Blazn Development
        Human:
          Username: blazn-dev-admin
          FirstName: Development
          LastName: Administrator
          Email:
            Address: admin@blazn.invalid
            Verified: true
          Password: {{ with secret "apps/data/blazn/development/identity/server" }}{{ .Data.data.admin_password }}{{ end }}
          PasswordChangeRequired: true

    EOT
    }
    template { error_on_missing_key=true destination="/rendered/masterkey" perms="0400" contents=<<EOT
    {{- with secret "apps/data/blazn/development/identity/server" -}}{{ .Data.data.master_key }}{{- end -}}
    EOT
    }
  sidecar.hcl: |
    exit_after_auth=false
    pid_file="/tmp/agent.pid"
    vault { address="https://openbao.frontro-secrets.svc.cluster.local:8200" ca_cert="/ca/ca.crt" }
    auto_auth { method "kubernetes" { mount_path="auth/kubernetes" config={role="blazn-dev-identity-server",token_path="/identity/token"} } }
    template { error_on_missing_key=true destination="/rendered/config.yaml" perms="0400" contents=<<EOT
    Log:
      Level: error
    Database:
      postgres:
        Host: frontro-db-1
        Port: 5432
        Database: zitadel
        User:
          Username: zitadel
          Password: {{ with secret "apps/data/blazn/development/identity/database" }}{{ .Data.data.user_password }}{{ end }}
          SSL:
            Mode: verify-full
            RootCert: /tls/ca.crt
        Admin:
          Username: postgres
          Password: {{ with secret "apps/data/blazn/development/identity/database" }}{{ .Data.data.admin_password }}{{ end }}
          ExistingDatabase: postgres
          SSL:
            Mode: verify-full
            RootCert: /tls/ca.crt
    DefaultInstance:
      LoginPolicy:
        AllowRegister: false
        ForceMFA: true
        IgnoreUnknownUsernames: true

    EOT
    }
    template { error_on_missing_key=true destination="/rendered/steps.yaml" perms="0400" contents=<<EOT
    FirstInstance:
      Org:
        Name: Blazn Development
        Human:
          Username: blazn-dev-admin
          FirstName: Development
          LastName: Administrator
          Email:
            Address: admin@blazn.invalid
            Verified: true
          Password: {{ with secret "apps/data/blazn/development/identity/server" }}{{ .Data.data.admin_password }}{{ end }}
          PasswordChangeRequired: true

    EOT
    }
    template { error_on_missing_key=true destination="/rendered/masterkey" perms="0400" contents=<<EOT
    {{- with secret "apps/data/blazn/development/identity/server" -}}{{ .Data.data.master_key }}{{- end -}}
    EOT
    }
kind: ConfigMap
metadata:
  name: identity-api-agent
  namespace: blazn-identity-dev
