apiVersion: v1
data:
  init.hcl: |
    exit_after_auth=true
    pid_file="/tmp/agent.pid"
    vault { address="https://openbao.frontro-secrets.svc.cluster.local:8200" ca_cert="/ca/ca.crt" }
    auto_auth { method "kubernetes" { mount_path="auth/kubernetes" config={role="blazn-dev-identity-database",token_path="/identity/token"} } }
    template { error_on_missing_key=true destination="/rendered/pg-password" perms="0400" contents=<<EOT
    {{ with secret "apps/data/blazn/development/identity/database" }}{{ .Data.data.admin_password }}{{ end }}
    EOT
    }
  sidecar.hcl: |
    exit_after_auth=false
    pid_file="/tmp/agent.pid"
    vault { address="https://openbao.frontro-secrets.svc.cluster.local:8200" ca_cert="/ca/ca.crt" }
    auto_auth { method "kubernetes" { mount_path="auth/kubernetes" config={role="blazn-dev-identity-database",token_path="/identity/token"} } }
    template { error_on_missing_key=true destination="/rendered/pg-password" perms="0400" contents=<<EOT
    {{ with secret "apps/data/blazn/development/identity/database" }}{{ .Data.data.admin_password }}{{ end }}
    EOT
    }
kind: ConfigMap
metadata:
  name: identity-postgres-agent
  namespace: blazn-identity-dev
