apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-identity-api-agent.yaml
- configmap-identity-login-agent.yaml
- configmap-identity-login-scripts.yaml
- configmap-identity-postgres-agent.yaml
- configmap-openbao-client-ca.yaml
- deployment-identity-api.yaml
- deployment-identity-login.yaml
- deployment-identity-mail.yaml
- deployment-identity-postgres.yaml
- networkpolicy-api-egress.yaml
- networkpolicy-api-login.yaml
- networkpolicy-api-mail.yaml
- networkpolicy-api-sendgrid.yaml
- networkpolicy-dedicated-db-egress.yaml
- networkpolicy-default-deny.yaml
- networkpolicy-dns.yaml
- networkpolicy-identity-edge-api.yaml
- networkpolicy-identity-edge-login.yaml
- networkpolicy-login-api.yaml
- networkpolicy-mail-from-blazn-api-dev.yaml
- networkpolicy-mail-ingress.yaml
- networkpolicy-openbao.yaml
- networkpolicy-postgres-ingress.yaml
- persistentvolumeclaim-bootstrap.yaml
- persistentvolumeclaim-database.yaml
- service-identity-api.yaml
- service-identity-login.yaml
- service-identity-mail.yaml
- service-postgres.yaml
- service-zitadel-api.yaml
- serviceaccount-blazn-dev-identity-database.yaml
- serviceaccount-blazn-dev-identity-login.yaml
- serviceaccount-blazn-dev-identity-server.yaml
