apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-identity-mail.yaml
- networkpolicy-default-deny.yaml
- networkpolicy-dns.yaml
- networkpolicy-mail-from-blazn-api-dev.yaml
- networkpolicy-mail-ingress.yaml
- service-identity-mail.yaml
