apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: blazn-identity-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: frontro-hostpath-srv
  volumeMode: Filesystem
