apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: blazn
    environment: development
    pod-security.kubernetes.io/enforce: baseline
  name: blazn-identity-dev
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: blazn
    environment: test
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.35
  name: blazn-test
