import assert from "node:assert/strict";import {createHash,randomBytes,randomUUID} from "node:crypto";import {readFile} from "node:fs/promises";import path from "node:path";import test from "node:test";import {fileURLToPath} from "node:url";
import {createDatabase} from "./db.js";import {DevelopmentService} from "./development-service.js";import {PgDevelopmentStore} from "./development-store.js";import {DevelopmentHttpError,type DevelopmentPrincipal} from "./development-types.js";import {SandboxService} from "./sandbox-service.js";import {PgSandboxStore} from "./sandbox-store.js";import type {SandboxPrincipal,SandboxTemplateManifest} from "./sandbox-types.js";
const runtimeUrl=process.env.BLAZN_DEVELOPMENT_TEST_DATABASE_URL,adminUrl=process.env.BLAZN_DEVELOPMENT_TEST_ADMIN_DATABASE_URL;
test("restricted Development runtime snapshots authority and keeps finalization closed",{skip:!runtimeUrl||!adminUrl},async()=>{const runtime=createDatabase(runtimeUrl!),admin=createDatabase(adminUrl!),owner=principal(),viewer=principal(),outsider=principal(),w=randomUUID(),otherW=randomUUID(),p=randomUUID(),otherP=randomUUID();try{
  for(const user of [owner,viewer,outsider]){await admin.query("INSERT INTO users(id,email,display_name,password_salt,password_hash) VALUES($1,$2,$3,'salt','hash')",[user.userId,user.email,user.displayName]);await admin.query("INSERT INTO devices(id,user_id,name,platform,public_key) VALUES($1,$2,'test','linux','public')",[user.deviceId,user.userId]);await admin.query("INSERT INTO sessions(id,user_id,device_id,token_hash,refresh_token_hash,access_expires_at,refresh_expires_at) VALUES($1,$2,$3,$4,$5,now()+interval '10 minutes',now()+interval '1 hour')",[user.sessionId,user.userId,user.deviceId,sha256(user.accessToken),sha256(`refresh-${user.userId}`)]);}
  await admin.query("INSERT INTO workspaces(id,slug,name,created_by) VALUES($1,$2,'Development',$3),($4,$5,'Other',$6)",[w,`dev-${owner.userId.slice(0,8)}`,owner.userId,otherW,`other-${outsider.userId.slice(0,8)}`,outsider.userId]);await admin.query("INSERT INTO workspace_memberships(workspace_id,user_id,role) VALUES($1,$2,'owner'),($1,$3,'viewer'),($4,$5,'owner')",[w,owner.userId,viewer.userId,otherW,outsider.userId]);await admin.query("INSERT INTO projects(id,workspace_id,slug,kind,name,created_by) VALUES($1,$2,'development','development','Development',$3),($4,$5,'other','development','Other',$6)",[p,w,owner.userId,otherP,otherW,outsider.userId]);
  const registryAudit=randomUUID();await admin.query("INSERT INTO workspace_audit_events(id,workspace_id,actor_user_id,event_type,payload) VALUES($1,$2,$3,'development.registry.authorized',$4)",[registryAudit,w,owner.userId,{repository:"registry.blazn.invalid/poc/coding-agent"}]);await admin.query("INSERT INTO development_registry_repositories(workspace_id,repository,authorized_by,audit_event_id) VALUES($1,'registry.blazn.invalid/poc/coding-agent',$2,$3)",[w,owner.userId,registryAudit]);
  const sandbox=new SandboxService(new PgSandboxStore(runtime)),template=JSON.parse(await readFile(path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../../packages/contracts/testdata/sandbox/template-good.json"),"utf8")) as SandboxTemplateManifest,created=await sandbox.createTemplate(owner,w,"development-template-1",template),published=await sandbox.publishVersion(owner,created.template.id,"development-template-publish-1",{expectedDraftVersion:1});
  const manifest=JSON.parse(await readFile(path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../../packages/contracts/testdata/development/project-good.json"),"utf8")) as Record<string,unknown>;manifest.projectId=p;manifest.template={versionId:published.version.id,digest:published.version.contentDigest};manifest.publicationTarget={templateId:created.template.id};const service=new DevelopmentService(new PgDevelopmentStore(runtime));const [project,replay]=await Promise.all([service.putProject(owner,w,p,"development-project-pg-1",0,manifest),service.putProject(owner,w,p,"development-project-pg-1",0,manifest)]);assert.equal(project.project.version,1);assert.equal(replay.project.manifestDigest,project.project.manifestDigest);
  await admin.query("UPDATE sandbox_template_version_status SET status='prohibited',version=version+1,changed_at=clock_timestamp() WHERE version_id=$1",[published.version.id]);await assert.rejects(()=>service.putProject(owner,w,p,"development-project-pg-prohibited",1,manifest),isCode("version_conflict"));await admin.query("UPDATE sandbox_template_version_status SET status='published',version=version+1,changed_at=clock_timestamp() WHERE version_id=$1",[published.version.id]);
  const [requested,replayed]=await Promise.all([service.requestBuild(owner,w,p,"development-build-pg-1","1".repeat(40)),service.requestBuild(owner,w,p,"development-build-pg-1","1".repeat(40))]);const build=requested.build;assert.equal(build.id,replayed.build.id);assert.equal(build.projectVersion,1);assert.equal(build.template.digest,published.version.contentDigest);assert.equal(build.publication.eligible,false);assert.equal("finalDocument" in build,false);assert.equal((await service.listBuilds(viewer,w,p)).items.length,1);
  const authority=await admin.query("SELECT d.policy_snapshot,d.registry_authorization,b.policy_snapshot build_policy,b.registry_authorization build_registry FROM development_projects d JOIN development_builds b ON b.project_id=d.project_id WHERE d.project_id=$1",[p]);assert.equal(authority.rows[0]?.policy_snapshot.builder.version,1);assert.equal(authority.rows[0]?.registry_authorization.auditEventId,registryAudit);assert.deepEqual(authority.rows[0]?.build_policy,authority.rows[0]?.policy_snapshot);assert.deepEqual(authority.rows[0]?.build_registry,authority.rows[0]?.registry_authorization);
  await admin.query("UPDATE sandbox_template_version_status SET status='prohibited',version=version+1,changed_at=clock_timestamp() WHERE version_id=$1",[published.version.id]);await assert.rejects(()=>service.requestBuild(owner,w,p,"development-build-pg-template-prohibited","5".repeat(40)),isCode("version_conflict"));await admin.query("UPDATE sandbox_template_version_status SET status='published',version=version+1,changed_at=clock_timestamp() WHERE version_id=$1",[published.version.id]);
  await admin.query("UPDATE development_registry_repositories SET status='revoked' WHERE workspace_id=$1",[w]);await assert.rejects(()=>service.requestBuild(owner,w,p,"development-build-pg-revoked","2".repeat(40)),isCode("version_conflict"));await admin.query("UPDATE development_registry_repositories SET status='active' WHERE workspace_id=$1",[w]);await admin.query("UPDATE development_policy_profiles SET active=false WHERE kind='builder'");await assert.rejects(()=>service.requestBuild(owner,w,p,"development-build-pg-policy","3".repeat(40)),isCode("version_conflict"));await admin.query("UPDATE development_policy_profiles SET active=true WHERE kind='builder'");
  await assert.rejects(()=>runtime.query("SELECT * FROM development_projects"),pgCode("42501"));await assert.rejects(()=>runtime.query("SELECT * FROM development_builds"),pgCode("42501"));
  assert.equal((await runtime.query("SELECT count(*)::int count FROM development_runtime_get_build($1,$2,$3,$4,$5)",[w,p,viewer.sessionId,viewer.accessToken,build.id])).rows[0]?.count,1);
  await runtime.query("SELECT set_config('blazn.development_user_id',$1,false)",[owner.userId]);assert.equal((await runtime.query("SELECT count(*)::int count FROM development_runtime_get_build($1,$2,$3,$4,$5)",[w,p,outsider.sessionId,outsider.accessToken,build.id])).rows[0]?.count,0);assert.equal((await runtime.query("SELECT count(*)::int count FROM development_runtime_get_build($1,$2,$3,$4,$5)",[w,p,owner.sessionId,viewer.accessToken,build.id])).rows[0]?.count,0);
  const actors=await admin.query("SELECT d.created_by,b.requested_by FROM development_projects d JOIN development_builds b ON b.project_id=d.project_id WHERE d.project_id=$1",[p]);assert.equal(actors.rows[0]?.created_by,owner.userId);assert.equal(actors.rows[0]?.requested_by,owner.userId);
  await assert.rejects(()=>runtime.query("SELECT * FROM development_runtime_create_build($1,$2,$3,$4,$5,$6,$7)",[randomUUID(),w,p,randomUUID(),viewer.userId,"2".repeat(40),build.planDigest]),pgCode("42883"));
  assert.equal((await runtime.query("SELECT count(*)::int count FROM development_runtime_create_build($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),w,p,randomUUID(),owner.sessionId,owner.accessToken,999,build.projectManifestDigest,"4".repeat(40),build.planDigest])).rows[0]?.count,0);
  assert.equal((await admin.query("SELECT development_controller_finalize($1,$2,$3) completed",[build.id,1,{}])).rows[0]?.completed,false);const safe=(await service.getBuild(owner,w,p,build.id)).build;assert.equal(safe.status,"queued");assert.equal(safe.receiptDigest,null);assert.equal("finalDocument" in safe,false);
  await admin.query("UPDATE projects SET status='archived' WHERE id=$1",[p]);await assert.rejects(()=>service.requestBuild(owner,w,p,"development-build-pg-2","2".repeat(40)),isCode("project_not_found"));
}finally{await admin.query("DELETE FROM workspaces WHERE id=ANY($1::uuid[])",[[w,otherW]]).catch(()=>{});await admin.query("DELETE FROM users WHERE id=ANY($1::uuid[])",[[owner.userId,viewer.userId,outsider.userId]]).catch(()=>{});await runtime.end();await admin.end();}});
function principal():DevelopmentPrincipal&SandboxPrincipal&{deviceId:string;sessionId:string}{const userId=randomUUID();return{userId,deviceId:randomUUID(),sessionId:randomUUID(),accessToken:randomBytes(32).toString("base64url"),email:`${userId}@example.test`,displayName:userId.slice(0,8)};}function sha256(value:string){return createHash("sha256").update(value).digest("hex");}function isCode(code:string){return(error:unknown)=>error instanceof DevelopmentHttpError&&error.code===code;}function pgCode(code:string){return(error:unknown)=>!!error&&typeof error==="object"&&"code" in error&&error.code===code;}
