import assert from "node:assert/strict";
import test from "node:test";
import type {DevelopmentStore,DevelopmentTransaction} from "./development-store.js";
import {DevelopmentService} from "./development-service.js";
import {DevelopmentHttpError,type DevelopmentAccess,type DevelopmentBuildRecord,type DevelopmentBuildStatus,type DevelopmentPrincipal,type DevelopmentProjectRecord} from "./development-types.js";
import type {IdempotencyReceipt} from "./workspace-store.js";

const workspaceId="40000000-0000-4000-8000-000000000001",projectId="20000000-0000-4000-8000-000000000001",owner:DevelopmentPrincipal={userId:"10000000-0000-4000-8000-000000000001",email:"owner@example.test",displayName:"Owner"},viewer:DevelopmentPrincipal={...owner,userId:"10000000-0000-4000-8000-000000000002"};
const manifest={schemaVersion:"blazn.dev/project/v1alpha1",projectId,repository:{url:"https://github.com/blazncloud/blazn.git"},template:{versionId:"60000000-0000-4000-8000-000000000001",digest:`sha256:${"a".repeat(64)}`},publicationTarget:{templateId:"50000000-0000-4000-8000-000000000001"},platforms:["linux/amd64","linux/arm64"],build:{context:".",dockerfile:"Dockerfile",registryRepository:"registry.blazn.invalid/poc/coding-agent"},dependencyLocks:{"package-lock.json":`sha256:${"b".repeat(64)}`},tests:{poc:{argv:["npm","test"],timeoutSeconds:900}},policy:{builderProfile:"trusted-buildkit-v1",networkProfile:"build-egress-v1",resourceProfile:"poc-build-small-v1",publicationPolicy:"poc-development-v1"}};

class MemoryStore implements DevelopmentStore,DevelopmentTransaction {project?:DevelopmentProjectRecord;builds=new Map<string,DevelopmentBuildRecord>();receipts=new Map<string,IdempotencyReceipt>();audits:string[]=[];async transaction<T>(fn:(tx:DevelopmentTransaction)=>Promise<T>){return fn(this);}async lockIdempotency(){}async getIdempotency(p:string,o:string,k:string){return this.receipts.get(`${p}:${o}:${k}`);}async putIdempotency(p:string,o:string,k:string,r:IdempotencyReceipt){this.receipts.set(`${p}:${o}:${k}`,r);}async getAccess(w:string,p:string,u:string):Promise<DevelopmentAccess|undefined>{if(w!==workspaceId)return undefined;return{workspaceStatus:"active",role:u===viewer.userId?"viewer":"owner",...(p===projectId?{projectStatus:"active" as const}:{})};}async getProject(w:string,p:string){return this.project?.workspaceId===w&&this.project.projectId===p?this.project:undefined;}async putProject(i:{workspaceId:string;projectId:string;expectedVersion:number;manifest:Record<string,unknown>;manifestDigest:string;createdBy:string}){if((this.project?.version??0)!==i.expectedVersion)return undefined;const now="2026-08-22T00:00:00Z";this.project={workspaceId:i.workspaceId,projectId:i.projectId,version:i.expectedVersion+1,manifest:i.manifest,manifestDigest:i.manifestDigest,createdBy:i.createdBy,createdAt:this.project?.createdAt??now,updatedAt:now};return this.project;}async createBuild(i:{id:string;workspaceId:string;projectId:string;runId:string;requestedBy:string;repository:string;commit:string;projectManifestDigest:string;planDigest:string}){const build:DevelopmentBuildRecord={schemaVersion:"blazn.dev/build-status/v1alpha1",id:i.id,workspaceId:i.workspaceId,projectId:i.projectId,runId:i.runId,version:1,status:"queued",requestedBy:i.requestedBy,source:{repository:i.repository,commit:i.commit},projectManifestDigest:i.projectManifestDigest,planDigest:i.planDigest,publication:{eligible:false,refusalReasons:["build_not_succeeded"],published:null},finalDocument:null,createdAt:"2026-08-22T00:00:00Z"};this.builds.set(build.id,build);return build;}async getBuild(w:string,p:string,id:string){const build=this.builds.get(id);return build?.workspaceId===w&&build.projectId===p?build:undefined;}async listBuilds(w:string,p:string,status:DevelopmentBuildStatus|"all"){return{items:[...this.builds.values()].filter(b=>b.workspaceId===w&&b.projectId===p&&(status==="all"||b.status===status)),nextCursor:null};}async insertAudit(_i:string,_w:string,_u:string,type:string){this.audits.push(type);}}

test("Development project and Build requests are versioned, idempotent, tenant-bound, and ineligible",async()=>{const store=new MemoryStore(),service=new DevelopmentService(store);const created=await service.putProject(owner,workspaceId,projectId,"development-project-1",0,manifest),replay=await service.putProject(owner,workspaceId,projectId,"development-project-1",0,manifest);assert.equal(created.project.version,1);assert.equal(replay.project.manifestDigest,created.project.manifestDigest);await assert.rejects(()=>service.putProject(owner,workspaceId,projectId,"development-project-2",0,manifest),isCode("version_conflict"));const first=await service.requestBuild(owner,workspaceId,projectId,"development-build-1","1".repeat(40)),buildReplay=await service.requestBuild(owner,workspaceId,projectId,"development-build-1","1".repeat(40));assert.equal(first.build.id,buildReplay.build.id);assert.equal(first.build.publication.eligible,false);assert.deepEqual(first.build.publication.refusalReasons,["build_not_succeeded"]);assert.equal((await service.listBuilds(viewer,workspaceId,projectId)).items.length,1);assert.equal((await service.getBuild(viewer,workspaceId,projectId,first.build.id)).build.runId,first.build.runId);assert.deepEqual(store.audits,["development.project.updated","development.build.requested"]);});
test("Development requests reject viewer mutation, unsafe manifests, mutable refs, and cross-tenant lookup",async()=>{const store=new MemoryStore(),service=new DevelopmentService(store);await assert.rejects(()=>service.putProject(viewer,workspaceId,projectId,"development-project-3",0,manifest),isCode("permission_denied"));await assert.rejects(()=>service.putProject(owner,workspaceId,projectId,"development-project-4",0,{...manifest,tests:{poc:{argv:["sh","-c","echo ok"],timeoutSeconds:1}}}),isCode("invalid_request"));await service.putProject(owner,workspaceId,projectId,"development-project-5",0,manifest);await assert.rejects(()=>service.requestBuild(owner,workspaceId,projectId,"development-build-2","main"),isCode("invalid_request"));await assert.rejects(()=>service.getBuild(owner,workspaceId,"20000000-0000-4000-8000-000000000099","30000000-0000-4000-8000-000000000001"),isCode("project_not_found"));});
function isCode(code:string){return(error:unknown)=>error instanceof DevelopmentHttpError&&error.code===code;}
