import assert from "node:assert/strict";
import test from "node:test";
import { DevelopmentSandboxEvidenceOrchestrator,type DevelopmentSandboxCommandTransport,type DevelopmentSandboxEvidenceStore,type DevelopmentSandboxTestRun } from "./development-sandbox-evidence.js";

const buildId="30000000-0000-4000-8000-000000000001",workspaceId="40000000-0000-4000-8000-000000000001",digest=`sha256:${"c".repeat(64)}`,image=`registry.example/blazn/agent@${digest}`,children={"linux/amd64":`registry.example/blazn/agent@sha256:${"d".repeat(64)}`,"linux/arm64":`registry.example/blazn/agent@sha256:${"e".repeat(64)}`} as const,snapshot={build:{registryRepository:"registry.example/blazn/agent"},tests:{poc:{argv:["npm","test"],timeoutSeconds:60}}},input={workItem:{buildId,workspaceId,generation:6,projectSnapshot:snapshot},build:{imageIndexDigest:digest,imageChildren:children}};
function run(bound=false,state="ready"):DevelopmentSandboxTestRun{return{buildId,workspaceId,projectId:"20000000-0000-4000-8000-000000000001",platform:"linux/amd64",testName:"poc",sandboxId:"71000000-0000-4000-8000-000000000001",status:"ready",sandboxState:state,candidateImageIndex:image,candidateImageChild:children["linux/amd64"],candidateImageBound:bound,argv:["npm","test"],argvDigest:`sha256:${"a".repeat(64)}`,timeoutSeconds:60,backendUid:"sandbox-uid",backendResourceVersion:"sandbox-rv",podNamespace:"blazn-poc-sandboxes",podName:"sandbox-test",podUid:"pod-uid",podResourceVersion:"pod-rv",observationDigest:`sha256:${"b".repeat(64)}`};}

test("collector fails before Sandbox preparation when immutable candidate binding is fenced",async()=>{let prepared=false;const store:DevelopmentSandboxEvidenceStore={bindCandidateImages:async()=>false,prepare:async()=>{prepared=true;return run();},resolve:async()=>run(),authorizeExecution:async()=>false};const transport:DevelopmentSandboxCommandTransport={execute:async()=>{throw new Error("must not execute")}};await assert.rejects(new DevelopmentSandboxEvidenceOrchestrator(store,transport,1).execute(input,new AbortController().signal),/binding was fenced/);assert.equal(prepared,false);});

test("collector rejects ready state without frozen Pod admission identity",async()=>{const {podUid:_,...incomplete}=run(true);const store:DevelopmentSandboxEvidenceStore={bindCandidateImages:async()=>true,prepare:async()=>incomplete,resolve:async()=>incomplete,authorizeExecution:async()=>false};const transport:DevelopmentSandboxCommandTransport={execute:async()=>{throw new Error("must not execute")}};await assert.rejects(new DevelopmentSandboxEvidenceOrchestrator(store,transport,1).execute(input,new AbortController().signal),/lacks frozen admission evidence/);});

test("collector cancellation interrupts readiness polling without executing",async()=>{const pending=run(true,"queued"),controller=new AbortController();const store:DevelopmentSandboxEvidenceStore={bindCandidateImages:async()=>true,prepare:async()=>pending,resolve:async()=>pending,authorizeExecution:async()=>false};const transport:DevelopmentSandboxCommandTransport={execute:async()=>{throw new Error("must not execute")}};setTimeout(()=>controller.abort(new Error("cancelled")),10);await assert.rejects(new DevelopmentSandboxEvidenceOrchestrator(store,transport,1000).execute(input,controller.signal),/cancelled/);});
