import {randomUUID} from "node:crypto";
import {developmentDigest,verifyDevelopmentProjectCommands} from "./development-contract.js";
import type {DevelopmentStore,DevelopmentTransaction} from "./development-store.js";
import {DevelopmentHttpError,type DevelopmentBuildStatus,type DevelopmentPrincipal} from "./development-types.js";
import {requestDigest} from "./workspace-crypto.js";
import {roleAllows} from "./workspace-types.js";
import type {IdempotencyReceipt} from "./workspace-store.js";

export class DevelopmentService {
  constructor(private readonly store:DevelopmentStore){}
  async putProject(principal:DevelopmentPrincipal,w:string,p:string,key:string,expectedVersion:number,manifest:Record<string,unknown>){positiveOrZero(expectedVersion);const normalized=validateProject(manifest,p),digest=requestDigest({w,p,expectedVersion,manifest:normalized});return this.idempotent(principal,w,p,"development.project.put",key,`development-project:${p}`,digest,async tx=>{const current=await tx.getProject(w,p,true);if((current?.version??0)!==expectedVersion)throw new DevelopmentHttpError("version_conflict","DevelopmentProject version changed");const template=record(normalized.template),publication=record(normalized.publicationTarget);const project=await tx.putProject({workspaceId:w,projectId:p,expectedVersion,manifest:normalized,manifestDigest:developmentDigest(normalized),templateVersionId:string(template.versionId),templateDigest:string(template.digest),publicationTemplateId:string(publication.templateId),createdBy:principal.userId});if(!project)throw new DevelopmentHttpError("version_conflict","DevelopmentProject version changed");await tx.insertAudit(randomUUID(),w,principal.userId,"development.project.updated",{projectId:p,version:project.version,manifestDigest:project.manifestDigest});return{project};},"operate",expectedVersion===0?201:200);}
  async getProject(principal:DevelopmentPrincipal,w:string,p:string){return this.store.transaction(async tx=>{await this.authorize(tx,principal,w,p,"read",false);const project=await tx.getProject(w,p);if(!project)throw new DevelopmentHttpError("development_project_not_found","DevelopmentProject was not found");return{project};});}
  async requestBuild(principal:DevelopmentPrincipal,w:string,p:string,key:string,commit:string){if(!/^(?:[0-9a-f]{40}|[0-9a-f]{64})$/.test(commit))invalid("commit must be an exact lowercase hexadecimal commit");const digest=requestDigest({w,p,commit});return this.idempotent(principal,w,p,"development.build.request",key,`development-project:${p}`,digest,async tx=>{const project=await tx.getProject(w,p,true);if(!project)throw new DevelopmentHttpError("development_project_not_found","DevelopmentProject was not found");const repository=string(record(project.manifest.repository).url),planDigest=developmentDigest({schemaVersion:"blazn.dev/build-plan-request/v1alpha1",source:{repository,commit},projectManifestDigest:project.manifestDigest,template:project.manifest.template,dependencyLocks:project.manifest.dependencyLocks,platforms:project.manifest.platforms,build:project.manifest.build,policy:project.manifest.policy});const build=await tx.createBuild({id:randomUUID(),workspaceId:w,projectId:p,runId:randomUUID(),requestedBy:principal.userId,repository,commit,projectManifestDigest:project.manifestDigest,planDigest});await tx.insertAudit(randomUUID(),w,principal.userId,"development.build.requested",{projectId:p,buildId:build.id,runId:build.runId,sourceCommit:commit,projectManifestDigest:project.manifestDigest,planDigest});return{build};},"operate",202);}
  async getBuild(principal:DevelopmentPrincipal,w:string,p:string,id:string){return this.store.transaction(async tx=>{await this.authorize(tx,principal,w,p,"read",false);const build=await tx.getBuild(w,p,id);if(!build)throw new DevelopmentHttpError("development_build_not_found","Development Build was not found");return{build};});}
  async listBuilds(principal:DevelopmentPrincipal,w:string,p:string,status:DevelopmentBuildStatus|"all"="all",cursor=""){validStatus(status);validCursor(cursor);return this.store.transaction(async tx=>{await this.authorize(tx,principal,w,p,"read",false);return tx.listBuilds(w,p,status,cursor);});}
  private async authorize(tx:DevelopmentTransaction,principal:DevelopmentPrincipal,w:string,p:string,capability:"read"|"operate",lock:boolean){const access=await tx.getAccess(w,p,principal.userId,lock);if(!access||access.workspaceStatus!=="active")throw new DevelopmentHttpError("workspace_not_found","Workspace was not found");if(!access.projectStatus||access.projectStatus!=="active"&&capability==="operate")throw new DevelopmentHttpError("project_not_found","Project was not found");if(!roleAllows(access.role,capability))throw new DevelopmentHttpError("permission_denied","Development action is not permitted");}
  private async idempotent<T>(principal:DevelopmentPrincipal,w:string,p:string,operation:string,key:string,target:string,digest:string,execute:(tx:DevelopmentTransaction)=>Promise<T>,capability:"read"|"operate",status:number){validKey(key);return this.store.transaction(async tx=>{await tx.lockIdempotency(principal.userId,operation,key);const receipt=await tx.getIdempotency(principal.userId,operation,key);if(receipt){verifyReceipt(receipt,w,target,digest);await this.authorize(tx,principal,w,p,capability,true);return receipt.responseBody as T;}await this.authorize(tx,principal,w,p,capability,true);const response=await execute(tx);await tx.putIdempotency(principal.userId,operation,key,{workspaceId:w,targetKey:target,requestDigest:digest,responseStatus:status,responseBody:response});return response;});}
}

function validateProject(value:Record<string,unknown>,projectId:string){exact(value,["schemaVersion","projectId","repository","template","publicationTarget","platforms","build","dependencyLocks","tests","policy"]);if(value.schemaVersion!=="blazn.dev/project/v1alpha1"||value.projectId!==projectId)invalid("DevelopmentProject identity is invalid");const repository=record(value.repository);exact(repository,["url"]);if(!/^https:\/\/[A-Za-z0-9.-]+(?::[0-9]+)?\/[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+(?:\.git)?$/.test(string(repository.url)))invalid("repository URL is invalid");const template=record(value.template);exact(template,["versionId","digest"]);uuid(template.versionId);digest(template.digest);const publication=record(value.publicationTarget);exact(publication,["templateId"]);uuid(publication.templateId);if(JSON.stringify(value.platforms)!==JSON.stringify(["linux/amd64","linux/arm64"]))invalid("platforms must be the canonical AMD64 and ARM64 set");const build=record(value.build);exact(build,["context","dockerfile","registryRepository"]);repositoryPath(build.context);repositoryPath(build.dockerfile);if(!/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?(?::[0-9]{1,5})?\/[a-z0-9][a-z0-9._/-]{0,510}$/.test(string(build.registryRepository))||String(build.registryRepository).includes("@"))invalid("registry repository is invalid");const locks=record(value.dependencyLocks);if(Object.keys(locks).length<1||Object.keys(locks).length>32)invalid("dependencyLocks are invalid");for(const [path,hash] of Object.entries(locks)){repositoryPath(path);digest(hash);}const tests=record(value.tests);if(Object.keys(tests).length<1||Object.keys(tests).length>32)invalid("tests are invalid");for(const [name,raw] of Object.entries(tests)){nameValue(name);const test=record(raw);exact(test,["argv","timeoutSeconds"]);if(!Array.isArray(test.argv)||test.argv.length<1||test.argv.length>64||test.argv.some(arg=>typeof arg!=="string"||!arg||arg.length>1024)||!Number.isSafeInteger(test.timeoutSeconds)||Number(test.timeoutSeconds)<1||Number(test.timeoutSeconds)>1800)invalid("test definition is invalid");}if(verifyDevelopmentProjectCommands(value).length)invalid("test argv violates the DevelopmentProject credential boundary");const policy=record(value.policy);exact(policy,["builderProfile","networkProfile","resourceProfile","publicationPolicy"]);for(const item of Object.values(policy))nameValue(string(item));return structuredClone(value);}
function record(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))invalid("object field is invalid");return value as Record<string,unknown>;}
function exact(value:Record<string,unknown>,keys:string[]){if(keys.some(k=>!(k in value))||Object.keys(value).some(k=>!keys.includes(k)))invalid("request fields are invalid");}
function string(value:unknown){if(typeof value!=="string")invalid("string field is invalid");return value;}
function uuid(value:unknown){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(string(value)))invalid("UUID is invalid");return value as string;}
function digest(value:unknown){if(!/^sha256:[0-9a-f]{64}$/.test(string(value)))invalid("digest is invalid");}
function repositoryPath(value:unknown){const path=string(value);if(path.length<1||path.length>512||path.startsWith("/")||path.split("/").includes("..")||/[\u0000-\u001f]/.test(path))invalid("repository path is invalid");}
function nameValue(value:string){if(!/^[a-z][a-z0-9-]{0,62}$/.test(value))invalid("policy or test name is invalid");}
function validStatus(value:string){if(!["queued","building","testing","succeeded","failed","cancelled","all"].includes(value))invalid("status is invalid");}
function validCursor(value:string){if(value&& !/^[0-9a-f-]{36}$/.test(value))invalid("cursor is invalid");}
function validKey(value:string){if(typeof value!=="string"||value.length<8||value.length>128)invalid("Idempotency-Key is invalid");}
function positiveOrZero(value:number){if(!Number.isSafeInteger(value)||value<0)invalid("expectedVersion is invalid");}
function verifyReceipt(receipt:IdempotencyReceipt,w:string,target:string,digestValue:string){if(receipt.workspaceId!==w||receipt.targetKey!==target||receipt.requestDigest!==digestValue)throw new DevelopmentHttpError("idempotency_conflict","Idempotency key is bound to another request");}
function invalid(message:string):never{throw new DevelopmentHttpError("invalid_request",message);}
