import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import test from "node:test";
import { BuildKitDevelopmentExecutor,buildctlArguments,developmentArtifactIds,metadataImageDigest,parseCollectorResult,qualifiedBuildKit,runDevelopmentCommand,type BuildKitExecutorConfig } from "./development-build-executor.js";
import type { DevelopmentControllerWorkItem } from "./development-controller-store.js";

const item:DevelopmentControllerWorkItem={buildId:"30000000-0000-4000-8000-000000000001",workspaceId:"40000000-0000-4000-8000-000000000001",projectId:"20000000-0000-4000-8000-000000000001",runId:"31000000-0000-4000-8000-000000000001",buildVersion:3,leaseToken:"32000000-0000-4000-8000-000000000001",leaseExpiresAt:"2026-08-24T20:00:00.000Z",attempt:1,generation:6,requestedBy:"10000000-0000-4000-8000-000000000001",source:{repository:"https://github.com/blazncloud/blazn.git",commit:"1".repeat(40)},projectManifestDigest:`sha256:${"a".repeat(64)}`,projectSnapshot:{build:{context:".",dockerfile:"Dockerfile",registryRepository:"registry.example/blazn/agent"},platforms:["linux/amd64","linux/arm64"],tests:{poc:{argv:["npm","test"]}},policy:{builderProfile:"trusted-buildkit-v1"}},planDigest:`sha256:${"b".repeat(64)}`,createdAt:"2026-08-24T19:00:00.000Z"};
const builder={id:"50000000-0000-4000-8000-000000000001",profile:"trusted-buildkit-v1",...qualifiedBuildKit},imageIndexReference=`registry.example/blazn/agent@sha256:${"c".repeat(64)}`,actual={imageIndexReference,builder};
const config:BuildKitExecutorConfig={buildctlPath:"/usr/local/bin/buildctl",address:"tcp://buildkit.internal:1234",serverName:"buildkit.internal",builderId:builder.id,caPath:"/secrets/ca.pem",certificatePath:"/secrets/cert.pem",keyPath:"/secrets/key.pem",evidenceCommand:"/usr/local/libexec/evidence",evidenceSecretsRoot:"/custom/secrets",maximumArtifactBytes:1024,maximumTotalArtifactBytes:8192,executionTimeoutSeconds:60};

test("BuildKit invocation pins the exact source, platforms, mTLS material, and immutable metadata output",()=>{
  const args=buildctlArguments(item,{context:".",dockerfile:"Dockerfile",registryRepository:"registry.example/blazn/agent",platforms:["linux/amd64","linux/arm64"]},"/tmp/metadata.json",config);
  assert.deepEqual(args.slice(0,8),["--tlscacert","/secrets/ca.pem","--tlscert","/secrets/cert.pem","--tlskey","/secrets/key.pem","--tlservername","buildkit.internal"]);
  assert.ok(args.includes(`context=${item.source.repository}#${item.source.commit}`));
  assert.ok(args.includes("platform=linux/amd64,linux/arm64"));
  assert.ok(args.includes(`type=image,name=registry.example/blazn/agent:build-${item.buildId},push=true`));
  assert.equal(args.includes(config.address),false);
  assert.equal(metadataImageDigest({"containerimage.digest":`sha256:${"c".repeat(64)}`}),`sha256:${"c".repeat(64)}`);
  assert.throws(()=>metadataImageDigest({"containerimage.digest":"latest"}),/immutable image index/);
});

test("BuildKit invocation binds a repository subdirectory into the immutable Git context",()=>{const args=buildctlArguments(item,{context:"examples/coding-agent",dockerfile:"Dockerfile",registryRepository:"registry.example/blazn/agent",platforms:["linux/amd64","linux/arm64"]},"/tmp/metadata.json",config);assert.ok(args.includes(`context=${item.source.repository}#${item.source.commit}:examples/coding-agent`));assert.equal(args.some(value=>value.startsWith("contextsubdir=")),false);});

test("collector response is exact, deterministic, content-addressed, bounded, and redacted",()=>{
  const ids=developmentArtifactIds(item),artifacts=Object.entries(ids).map(([role,id])=>{const content=Buffer.from(JSON.stringify({passed:true,role}));return{id,role,kind:role.startsWith("refresh/")?"development.refresh":"development.test",contentDigest:`sha256:${createHash("sha256").update(content).digest("hex")}`,contentBase64:content.toString("base64")};});
  const document={id:item.buildId,workspaceId:item.workspaceId,projectId:item.projectId,runId:item.runId,status:"succeeded",outputs:{imageIndexDigest:imageIndexReference},builder};
  const result=parseCollectorResult(Buffer.from(JSON.stringify({execution:{nodeId:"70000000-0000-4000-8000-000000000001",sandboxId:"71000000-0000-4000-8000-000000000001"},document,artifacts})),item,ids,config,actual);
  assert.equal(result.artifacts.length,Object.keys(ids).length);assert.equal(result.artifacts[0]?.id,Object.values(developmentArtifactIds(item))[0]);
  const poisoned={...artifacts[0],contentBase64:Buffer.from(JSON.stringify({authorization:"Bearer abcdef"})).toString("base64")};
  poisoned.contentDigest=`sha256:${createHash("sha256").update(Buffer.from(poisoned.contentBase64,"base64")).digest("hex")}`;
  assert.throws(()=>parseCollectorResult(Buffer.from(JSON.stringify({execution:{nodeId:"70000000-0000-4000-8000-000000000001",sandboxId:"71000000-0000-4000-8000-000000000001"},document,artifacts:[poisoned,...artifacts.slice(1)]})),item,ids,config,actual),/forbidden authorization/);
  for(const raw of ['{"output":"github_pat_abcdefghijklmnopqrstuvwxyz"}','{"output":"safe","output":"github_pat_abcdefghijklmnopqrstuvwxyz"}']){const hidden={...artifacts[0],contentBase64:Buffer.from(raw).toString("base64")};hidden.contentDigest=`sha256:${createHash("sha256").update(Buffer.from(raw)).digest("hex")}`;assert.throws(()=>parseCollectorResult(Buffer.from(JSON.stringify({execution:{nodeId:"70000000-0000-4000-8000-000000000001",sandboxId:"71000000-0000-4000-8000-000000000001"},document,artifacts:[hidden,...artifacts.slice(1)]})),item,ids,config,actual),/provider token|canonical JSON/);}
  for(const candidate of [{...document,outputs:{imageIndexDigest:`registry.example/blazn/agent@sha256:${"f".repeat(64)}`}},{...document,builder:{...builder,version:"v0.0.0"}}])assert.throws(()=>parseCollectorResult(Buffer.from(JSON.stringify({execution:{nodeId:"70000000-0000-4000-8000-000000000001",sandboxId:"71000000-0000-4000-8000-000000000001"},document:candidate,artifacts})),item,ids,config,actual),/not bound/);
  assert.throws(()=>parseCollectorResult(Buffer.from(JSON.stringify({execution:{nodeId:"70000000-0000-4000-8000-000000000001",sandboxId:"71000000-0000-4000-8000-000000000001"},document:{...document,status:"failed"},artifacts})),item,ids,config,actual),/not bound/);
});

test("artifact identities remain stable across retries",()=>assert.deepEqual(developmentArtifactIds({...item,attempt:4,leaseToken:"32000000-0000-4000-8000-000000000002"}),developmentArtifactIds(item)));
test("qualified builder identity matches the pinned controller image",()=>assert.deepEqual(qualifiedBuildKit,{imageDigest:"moby/buildkit@sha256:79cc6476ab1a3371c9afd8b44e7c55610057c43e18d9b39b68e2b0c2475cc1b6",version:"v0.25.1"}));

test("executor gives BuildKit and evidence collection only a minimal environment and delegates generation but never its lease token",async()=>{let call=0;const runner=async(_file:string,args:string[],options:{input?:Buffer;env?:NodeJS.ProcessEnv})=>{call++;assert.deepEqual(Object.keys(options.env??{}).sort(),call===1?["BUILDKIT_HOST","HOME","LANG","PATH"]:["BLAZN_DEVELOPMENT_SECRETS_ROOT","HOME","LANG","PATH"]);if(call===1){const index=args.indexOf("--metadata-file");await writeFile(args[index+1]!,JSON.stringify({"containerimage.digest":`sha256:${"c".repeat(64)}`}));return{code:0,logDigest:`sha256:${"d".repeat(64)}`,stdout:Buffer.alloc(0)};}assert.equal(options.env?.BLAZN_DEVELOPMENT_SECRETS_ROOT,"/custom/secrets");const request=JSON.parse(options.input!.toString("utf8")) as {workItem:Record<string,unknown>;artifactIds:Record<string,string>};assert.equal("leaseToken" in request.workItem,false);assert.equal("leaseExpiresAt" in request.workItem,false);assert.equal(request.workItem.generation,6);const artifacts=Object.entries(request.artifactIds).map(([role,id])=>{const content=Buffer.from(JSON.stringify({passed:true,role}));return{id,role,kind:role.startsWith("refresh/")?"development.refresh":"development.test",contentDigest:`sha256:${createHash("sha256").update(content).digest("hex")}`,contentBase64:content.toString("base64")};});return{code:0,logDigest:`sha256:${"e".repeat(64)}`,stdout:Buffer.from(JSON.stringify({execution:{nodeId:"70000000-0000-4000-8000-000000000001",sandboxId:"71000000-0000-4000-8000-000000000001"},document:{id:item.buildId,workspaceId:item.workspaceId,projectId:item.projectId,runId:item.runId,status:"succeeded",outputs:{imageIndexDigest:imageIndexReference},builder},artifacts}))};};const result=await new BuildKitDevelopmentExecutor(config,runner).execute(item,new AbortController().signal);assert.equal(call,2);assert.equal(result.document.id,item.buildId);});

test("BuildKit nonzero is an operational retry and never invokes evidence finalization",async()=>{let calls=0;const runner=async()=>{calls++;return{code:1,logDigest:`sha256:${"d".repeat(64)}`,stdout:Buffer.from("untrusted failure output")};};await assert.rejects(new BuildKitDevelopmentExecutor(config,runner).execute(item,new AbortController().signal),/BuildKit build failed/);assert.equal(calls,1);});

test("executor deadline aborts a stalled command so the queue can recover",async()=>{const stalled=async(_file:string,_args:string[],options:{signal:AbortSignal})=>new Promise<never>((_resolve,reject)=>options.signal.addEventListener("abort",()=>reject(options.signal.reason),{once:true}));let guard:NodeJS.Timeout|undefined;try{await assert.rejects(Promise.race([new BuildKitDevelopmentExecutor({...config,executionTimeoutSeconds:0.01},stalled).execute(item,new AbortController().signal),new Promise<never>((_resolve,reject)=>{guard=setTimeout(()=>reject(new Error("deadline did not abort stalled command")),1000);})]),/timeout|aborted/i);}finally{if(guard)clearTimeout(guard);}});
test("command cancellation escalates from TERM to KILL for an uncooperative child",async()=>{const controller=new AbortController(),started=Date.now(),pending=runDevelopmentCommand(process.execPath,["-e","process.on('SIGTERM',()=>{});setInterval(()=>{},1000)"],{signal:controller.signal,killGraceMilliseconds:25,env:{PATH:process.env.PATH??"/usr/bin:/bin"}});setTimeout(()=>controller.abort(),50);const result=await pending;assert.notEqual(result.code,0);assert.ok(Date.now()-started<2000);});
