import assert from "node:assert/strict";
import test from "node:test";
import { DevelopmentSandboxEvidenceOrchestrator,type DevelopmentSandboxCommandTransport,type DevelopmentSandboxEvidenceStore,type DevelopmentSandboxTestRun } from "./development-sandbox-evidence.js";

const buildId="30000000-0000-4000-8000-000000000001",digest=`sha256:${"c".repeat(64)}`,image=`registry.example/blazn/agent@${digest}`,snapshot={build:{registryRepository:"registry.example/blazn/agent"},tests:{poc:{argv:["npm","test"],timeoutSeconds:60}}};
function run(bound=false,state="ready"):DevelopmentSandboxTestRun{return{buildId,workspaceId:"40000000-0000-4000-8000-000000000001",projectId:"20000000-0000-4000-8000-000000000001",platform:"linux/amd64",testName:"poc",sandboxId:"71000000-0000-4000-8000-000000000001",status:"ready",sandboxState:state,candidateImageIndex:image,candidateImageBound:bound,argv:["npm","test"],argvDigest:`sha256:${"a".repeat(64)}`,timeoutSeconds:60,backendUid:"sandbox-uid",backendResourceVersion:"sandbox-rv",podNamespace:"blazn-poc-sandboxes",podName:"sandbox-test",podUid:"pod-uid",podResourceVersion:"pod-rv",observationDigest:`sha256:${"b".repeat(64)}`};}

test("collector durably prepares the complete exact matrix before refusing unbound execution",async()=>{let executions=0;const prepared:string[]=[];const store:DevelopmentSandboxEvidenceStore={prepare:async(_build,generation,platform,name)=>{assert.equal(generation,6);prepared.push(`${platform}/${name}`);return run(false);},resolve:async()=>run(false),authorizeExecution:async()=>{throw new Error("must not authorize")}};const transport:DevelopmentSandboxCommandTransport={execute:async()=>{executions++;return{remoteExitCode:0,stdoutDigest:`sha256:${"d".repeat(64)}`,stderrDigest:`sha256:${"e".repeat(64)}`,stdoutBytes:0,stderrBytes:0};}};const collector=new DevelopmentSandboxEvidenceOrchestrator(store,transport,1);await assert.rejects(collector.execute({workItem:{buildId,generation:6,projectSnapshot:snapshot},build:{imageIndexDigest:digest}},new AbortController().signal),/candidate image is not bound/);assert.deepEqual(prepared,["linux/amd64/poc","linux/arm64/poc"]);assert.equal(executions,0);});

test("collector rejects ready state without frozen Pod admission identity",async()=>{const {podUid:_,...incomplete}=run(false);const store:DevelopmentSandboxEvidenceStore={prepare:async()=>incomplete,resolve:async()=>incomplete,authorizeExecution:async()=>false};const transport:DevelopmentSandboxCommandTransport={execute:async()=>{throw new Error("must not execute")}};await assert.rejects(new DevelopmentSandboxEvidenceOrchestrator(store,transport,1).execute({workItem:{buildId,generation:1,projectSnapshot:snapshot},build:{imageIndexDigest:digest}},new AbortController().signal),/lacks frozen admission evidence/);});

test("collector cancellation interrupts readiness polling without executing",async()=>{const pending=run(false,"queued"),controller=new AbortController();const store:DevelopmentSandboxEvidenceStore={prepare:async()=>pending,resolve:async()=>pending,authorizeExecution:async()=>false};const transport:DevelopmentSandboxCommandTransport={execute:async()=>{throw new Error("must not execute")}};setTimeout(()=>controller.abort(new Error("cancelled")),10);await assert.rejects(new DevelopmentSandboxEvidenceOrchestrator(store,transport,1000).execute({workItem:{buildId,generation:1,projectSnapshot:snapshot},build:{imageIndexDigest:digest}},controller.signal),/cancelled/);});
