import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import type { DevelopmentBuildExecutor,DevelopmentExecutionResult } from "./development-build-executor.js";
import { DevelopmentControllerRuntime,type RuntimeEvent } from "./development-controller-runtime.js";
import type { DevelopmentControllerStore,DevelopmentControllerWorkItem } from "./development-controller-store.js";

const root=new URL("../../../packages/contracts/testdata/development/",import.meta.url);
async function fixture(name:string){return JSON.parse(await readFile(new URL(name,root),"utf8")) as Record<string,unknown>;}
class MemoryStore implements DevelopmentControllerStore{
  renewed=0;stored=0;released=0;failed=0;finalized=0;
  constructor(readonly item:DevelopmentControllerWorkItem){}
  async claim(){return this.item;}async renew(){this.renewed++;return this.item.leaseExpiresAt;}async resolve(){return this.item;}
  async storeArtifact(){this.stored++;return true;}async commitExecution(){this.stored++;this.finalized++;return true;}async release(){this.released++;return true;}
  async finalize(){this.finalized++;return true;}
}
class Executor implements DevelopmentBuildExecutor{constructor(private readonly result:DevelopmentExecutionResult|Error){}async execute(){if(this.result instanceof Error)throw this.result;return this.result;}}
async function setup(attempt=1){const project=await fixture("project-good.json"),document=await fixture("build-good.json");const item:DevelopmentControllerWorkItem={buildId:String(document.id),workspaceId:String(document.workspaceId),projectId:String(document.projectId),runId:String(document.runId),buildVersion:Number(document.version)-1,leaseToken:"32000000-0000-4000-8000-000000000001",leaseExpiresAt:new Date(Date.now()+60000).toISOString(),attempt,generation:attempt,requestedBy:String(document.requestedBy),source:document.source as {repository:string;commit:string},projectManifestDigest:String(document.projectManifestDigest),projectSnapshot:project,planDigest:String(document.planDigest),createdAt:String(document.createdAt)};return{item,document};}

test("runtime claims, stores normalized Artifacts, and finalizes through the fenced service",async()=>{const{item,document}=await setup(),store=new MemoryStore(item),events:RuntimeEvent[]=[];const result:DevelopmentExecutionResult={execution:{nodeId:"70000000-0000-4000-8000-000000000001",sandboxId:"71000000-0000-4000-8000-000000000001"},document,artifacts:[{id:"80000000-0000-4000-8000-000000000001",role:"provenance",kind:"development.provenance",contentDigest:`sha256:${"a".repeat(64)}`,content:Buffer.from("x")}]};const runtime=new DevelopmentControllerRuntime(store,new Executor(result),{workerId:"worker-1",leaseSeconds:30,retryDelaySeconds:1,pollMilliseconds:10},event=>events.push(event));assert.equal(await runtime.runOnce(new AbortController().signal),true);assert.equal(store.stored,1);assert.equal(store.finalized,1);assert.equal(events.at(-1)?.type,"completed");});
test("runtime durably releases failures and surfaces each fifth-attempt exhaustion without forging a terminal sandbox receipt",async()=>{for(const attempt of [1,5]){const{item}=await setup(attempt),store=new MemoryStore(item),events:RuntimeEvent[]=[],runtime=new DevelopmentControllerRuntime(store,new Executor(new Error("collector failed")),{workerId:"worker-1",leaseSeconds:30,retryDelaySeconds:1,pollMilliseconds:10},event=>events.push(event));await runtime.runOnce(new AbortController().signal);assert.equal(store.released,1);assert.equal(events.at(-1)?.type,attempt===5?"operational-failure":"retry");}});
test("runtime uses one atomic evidence/finalization commit and never exposes a partial Artifact phase",async()=>{const{item,document}=await setup(),store=new MemoryStore(item);store.commitExecution=async()=>{store.finalized++;throw new Error("database response lost");};store.release=async()=>false;const events:RuntimeEvent[]=[];await new DevelopmentControllerRuntime(store,new Executor({execution:{nodeId:"70000000-0000-4000-8000-000000000001",sandboxId:"71000000-0000-4000-8000-000000000001"},document,artifacts:[{id:"80000000-0000-4000-8000-000000000001",role:"provenance",kind:"development.provenance",contentDigest:`sha256:${"a".repeat(64)}`,content:Buffer.from("first attempt bytes")}]}),{workerId:"worker-1",leaseSeconds:30,retryDelaySeconds:1,pollMilliseconds:10},event=>events.push(event)).runOnce(new AbortController().signal);assert.equal(store.stored,0);assert.equal(store.finalized,1);assert.equal(events.at(-1)?.type,"lease-lost");});
