import type {PoolClient,QueryResultRow} from "pg";
import type {Database} from "./db.js";
import type {IdempotencyReceipt} from "./workspace-store.js";
import type {DevelopmentAccess,DevelopmentBuildRecord,DevelopmentBuildStatus,DevelopmentProjectRecord} from "./development-types.js";

export interface DevelopmentTransaction {
  lockIdempotency(principalId:string,operation:string,key:string):Promise<void>;
  getIdempotency(principalId:string,operation:string,key:string):Promise<IdempotencyReceipt|undefined>;
  putIdempotency(principalId:string,operation:string,key:string,receipt:IdempotencyReceipt):Promise<void>;
  getAccess(workspaceId:string,projectId:string,userId:string,lock?:boolean):Promise<DevelopmentAccess|undefined>;
  getProject(workspaceId:string,projectId:string,lock?:boolean):Promise<DevelopmentProjectRecord|undefined>;
  putProject(input:{workspaceId:string;projectId:string;expectedVersion:number;manifest:Record<string,unknown>;manifestDigest:string;templateVersionId:string;templateDigest:string;publicationTemplateId:string;createdBy:string}):Promise<DevelopmentProjectRecord|undefined>;
  createBuild(input:{id:string;workspaceId:string;projectId:string;runId:string;requestedBy:string;commit:string;planDigest:string}):Promise<DevelopmentBuildRecord|undefined>;
  getBuild(workspaceId:string,projectId:string,id:string):Promise<DevelopmentBuildRecord|undefined>;
  listBuilds(workspaceId:string,projectId:string,status:DevelopmentBuildStatus|"all",cursor:string):Promise<{items:DevelopmentBuildRecord[];nextCursor:string|null}>;
  insertAudit(id:string,workspaceId:string,actorUserId:string,type:string,payload:unknown):Promise<void>;
}
export interface DevelopmentStore {transaction<T>(action:(transaction:DevelopmentTransaction)=>Promise<T>):Promise<T>}
export class PgDevelopmentStore implements DevelopmentStore {constructor(private readonly database:Database){}async transaction<T>(action:(transaction:DevelopmentTransaction)=>Promise<T>):Promise<T>{const client=await this.database.connect();try{await client.query("BEGIN");const value=await action(new PgDevelopmentTransaction(client));await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}}
class PgDevelopmentTransaction implements DevelopmentTransaction {
  constructor(private readonly client:PoolClient){}
  async lockIdempotency(p:string,o:string,k:string){await this.client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`${p}\n${o}\n${k}`]);}
  async getIdempotency(p:string,o:string,k:string){const result=await this.client.query("SELECT workspace_id,target_key,request_digest,response_status,response_body FROM workspace_idempotency_receipts WHERE principal_id=$1 AND operation=$2 AND idempotency_key=$3",[p,o,k]);const row=result.rows[0];return row?{workspaceId:row.workspace_id,targetKey:row.target_key,requestDigest:row.request_digest.trim(),responseStatus:row.response_status,responseBody:row.response_body}:undefined;}
  async putIdempotency(p:string,o:string,k:string,r:IdempotencyReceipt){await this.client.query("INSERT INTO workspace_idempotency_receipts(principal_id,workspace_id,operation,target_key,idempotency_key,request_digest,response_status,response_body) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[p,r.workspaceId,o,r.targetKey,k,r.requestDigest,r.responseStatus,r.responseBody]);}
  async getAccess(w:string,p:string,u:string,lock=false){const query=lock?"SELECT w.status workspace_status,m.role,p.status project_status FROM workspaces w JOIN workspace_memberships m ON m.workspace_id=w.id JOIN projects p ON p.workspace_id=w.id AND p.id=$2 WHERE w.id=$1 AND m.user_id=$3 AND m.status='active' FOR UPDATE OF w,m,p":"SELECT w.status workspace_status,m.role,p.status project_status FROM workspaces w JOIN workspace_memberships m ON m.workspace_id=w.id LEFT JOIN projects p ON p.workspace_id=w.id AND p.id=$2 WHERE w.id=$1 AND m.user_id=$3 AND m.status='active'";const result=await this.client.query(query,[w,p,u]);const row=result.rows[0];if(row)await this.client.query("SELECT set_config('blazn.development_user_id',$1,true)",[u]);return row?{workspaceStatus:row.workspace_status,role:row.role,...(row.project_status?{projectStatus:row.project_status}:{})}:undefined;}
  async getProject(w:string,p:string,_lock=false){const result=await this.client.query("SELECT * FROM development_runtime_get_project($1,$2)",[w,p]);return result.rows[0]?projectRow(result.rows[0]):undefined;}
  async putProject(i:{workspaceId:string;projectId:string;expectedVersion:number;manifest:Record<string,unknown>;manifestDigest:string;templateVersionId:string;templateDigest:string;publicationTemplateId:string;createdBy:string}){const result=await this.client.query("SELECT * FROM development_runtime_put_project($1,$2,$3,$4,$5,$6,$7,$8,$9)",[i.workspaceId,i.projectId,i.expectedVersion,i.manifest,i.manifestDigest,i.templateVersionId,i.templateDigest,i.publicationTemplateId,i.createdBy]);return result.rows[0]?projectRow(result.rows[0]):undefined;}
  async createBuild(i:{id:string;workspaceId:string;projectId:string;runId:string;requestedBy:string;commit:string;planDigest:string}){const result=await this.client.query("SELECT * FROM development_runtime_create_build($1,$2,$3,$4,$5,$6,$7)",[i.id,i.workspaceId,i.projectId,i.runId,i.requestedBy,i.commit,i.planDigest]);return result.rows[0]?buildRow(result.rows[0]):undefined;}
  async getBuild(w:string,p:string,id:string){const result=await this.client.query("SELECT * FROM development_runtime_get_build($1,$2,$3)",[w,p,id]);return result.rows[0]?buildRow(result.rows[0]):undefined;}
  async listBuilds(w:string,p:string,status:DevelopmentBuildStatus|"all",cursor:string){const result=await this.client.query("SELECT * FROM development_runtime_list_builds($1,$2,$3,$4)",[w,p,status,cursor||null]);const items=result.rows.slice(0,100).map(buildRow);return{items,nextCursor:result.rows.length>100?items.at(-1)?.id??null:null};}
  async insertAudit(id:string,w:string,u:string,type:string,payload:unknown){await this.client.query("INSERT INTO workspace_audit_events(id,workspace_id,actor_user_id,event_type,payload) VALUES($1,$2,$3,$4,$5)",[id,w,u,type,payload]);}
}
function projectRow(row:QueryResultRow):DevelopmentProjectRecord{return{workspaceId:row.workspace_id,projectId:row.project_id,version:Number(row.version),manifest:row.manifest,manifestDigest:row.manifest_digest,createdBy:row.created_by,createdAt:timestamp(row.created_at),updatedAt:timestamp(row.updated_at)};}
function buildRow(row:QueryResultRow):DevelopmentBuildRecord{const value:DevelopmentBuildRecord={schemaVersion:"blazn.dev/build-status/v1alpha1",id:row.id,workspaceId:row.workspace_id,projectId:row.project_id,runId:row.run_id,version:Number(row.version),status:row.status,requestedBy:row.requested_by,source:{repository:row.source_repository,commit:row.source_commit},projectVersion:Number(row.project_version),projectManifestDigest:row.project_manifest_digest,template:{versionId:row.template_version_id,digest:`sha256:${String(row.template_digest).trim()}`},publicationTarget:{templateId:row.publication_template_id,candidateVersionId:row.publication_candidate_version_id,expectedDraftVersion:Number(row.publication_draft_version),candidateDigest:`sha256:${String(row.publication_candidate_digest).trim()}`},registryRepository:row.registry_repository,planDigest:row.plan_digest,publication:{eligible:row.publication_eligible,refusalReasons:row.refusal_reasons,published:null},receiptDigest:row.final_document?.receiptDigest??null,evidenceAvailable:Boolean(row.final_document?.evidence),createdAt:timestamp(row.created_at)};if(row.started_at)value.startedAt=timestamp(row.started_at);if(row.completed_at)value.completedAt=timestamp(row.completed_at);if(row.error_code)value.errorCode=row.error_code;return value;}
function timestamp(value:Date|string){return value instanceof Date?value.toISOString():new Date(value).toISOString();}
