import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { resolveDevelopmentImageChildren } from "./development-registry-resolver.js";

function fixture(){const body=Buffer.from(JSON.stringify({schemaVersion:2,mediaType:"application/vnd.oci.image.index.v1+json",manifests:[{mediaType:"application/vnd.oci.image.manifest.v1+json",digest:`sha256:${"a".repeat(64)}`,size:100,platform:{os:"linux",architecture:"amd64"}},{mediaType:"application/vnd.oci.image.manifest.v1+json",digest:`sha256:${"b".repeat(64)}`,size:101,platform:{os:"linux",architecture:"arm64"}}]})),digest=`sha256:${createHash("sha256").update(body).digest("hex")}`,reference=`registry.example/repo/agent@${digest}`;return{body,digest,reference};}
test("registry resolver binds exact response bytes and canonical two-platform children",async()=>{const f=fixture(),fetcher=async(input:string,init:RequestInit)=>{assert.equal(input,`https://registry.example/v2/repo/agent/manifests/${f.digest}`);assert.equal(init.redirect,"manual");assert.equal(init.credentials,"omit");return new Response(f.body,{status:200,headers:{"content-type":"application/vnd.oci.image.index.v1+json","content-length":String(f.body.length)}});};assert.deepEqual(await resolveDevelopmentImageChildren(f.reference,new AbortController().signal,{allowedAuthority:"registry.example",fetcher}),{"linux/amd64":`registry.example/repo/agent@sha256:${"a".repeat(64)}`,"linux/arm64":`registry.example/repo/agent@sha256:${"b".repeat(64)}`});});
test("registry resolver refuses digest drift, redirects, and malformed platform sets",async()=>{const f=fixture(),options=(fetcher:(input:string,init:RequestInit)=>Promise<Response>)=>({allowedAuthority:"registry.example",fetcher});await assert.rejects(resolveDevelopmentImageChildren(`registry.example/repo/agent@sha256:${"c".repeat(64)}`,new AbortController().signal,options(async()=>new Response(f.body,{status:200,headers:{"content-type":"application/vnd.oci.image.index.v1+json"}}))),/digest/);await assert.rejects(resolveDevelopmentImageChildren(f.reference,new AbortController().signal,options(async()=>new Response(null,{status:307}))),/HTTP 307/);for(const root of [{mediaType:"application/vnd.oci.image.index.v1+json",manifests:[]},{schemaVersion:2,mediaType:"application/vnd.oci.image.index.v1+json",manifests:[{digest:`sha256:${"a".repeat(64)}`,size:1,platform:{os:"linux",architecture:"amd64"}}]}]){const body=Buffer.from(JSON.stringify(root)),reference=`registry.example/repo/agent@sha256:${createHash("sha256").update(body).digest("hex")}`;await assert.rejects(resolveDevelopmentImageChildren(reference,new AbortController().signal,options(async()=>new Response(body,{status:200,headers:{"content-type":"application/vnd.oci.image.index.v1+json"}}))),/shape|platform/);}});
test("registry resolver requires an exact trusted authority before issuing a request",async()=>{const f=fixture();for(const [reference,allowed] of [[f.reference,"other.example"],[`metadata.google.internal/repo@sha256:${"a".repeat(64)}`,"registry.example"],[`localhost:5000/repo@sha256:${"a".repeat(64)}`,"localhost:5000"]] as const){let called=false;await assert.rejects(resolveDevelopmentImageChildren(reference,new AbortController().signal,{allowedAuthority:allowed,fetcher:async()=>{called=true;return new Response();}}),/authority|allowlisted/);assert.equal(called,false);}});
test("registry resolver rejects oversized responses and propagates cancellation",async()=>{const f=fixture();await assert.rejects(resolveDevelopmentImageChildren(f.reference,new AbortController().signal,{allowedAuthority:"registry.example",fetcher:async()=>new Response(f.body,{status:200,headers:{"content-type":"application/vnd.oci.image.index.v1+json","content-length":String(1024*1024+1)}})}),/too large/);const controller=new AbortController();controller.abort(new Error("cancelled"));await assert.rejects(resolveDevelopmentImageChildren(f.reference,controller.signal,{allowedAuthority:"registry.example",fetcher:async(_input,init)=>{if(init.signal?.aborted)throw init.signal.reason;return new Response();}}),/cancelled/);});
