import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { Ajv2020 } from "ajv/dist/2020.js";
import type { FormatsPlugin } from "ajv-formats";
import { agentVersionDigest, harnessProfileDigest, harnessSecretViolations, harnessTerminalReceiptDigest, harnessVersionDigest, portableResultDigest, verifyAgentCompatibility, verifyHarnessBundle, verifyHarnessRun, verifyPortableEvaluation, verifyPortableParity } from "./harness-contract.js";

const here=path.dirname(fileURLToPath(import.meta.url)),contracts=path.resolve(here,"../../../packages/contracts"),fixtures=path.join(contracts,"testdata/harness");
const require=createRequire(import.meta.url),formatsModule=require("ajv-formats") as {default?:FormatsPlugin}|FormatsPlugin,addFormats=("default" in formatsModule?formatsModule.default:formatsModule) as FormatsPlugin;
const json=async(file:string)=>JSON.parse(await readFile(file,"utf8")) as Record<string,unknown>;
function validate(schema:Record<string,unknown>,value:unknown){const ajv=new Ajv2020({allErrors:true,strict:false});addFormats(ajv);const fn=ajv.compile(schema);assert.equal(fn(value),true,JSON.stringify(fn.errors));}

test("Agent and four adapter profiles validate one shared resource model",async()=>{
  const agent=await json(path.join(fixtures,"agent-good.json")),agentSchema=await json(path.join(contracts,"agent.schema.json")),harnessSchema=await json(path.join(contracts,"harness.schema.json"));validate(agentSchema,agent);assert.equal((agent.version as Record<string,unknown>).digest,agentVersionDigest(agent.version));
  const bundles=[];for(const name of ["hermes-profile.json","codex-profile.json","claude-profile.json","generic-profile.json"]){const bundle=await json(path.join(fixtures,name));validate(harnessSchema,bundle);assert.equal((bundle.version as Record<string,unknown>).digest,harnessVersionDigest(bundle.version));assert.equal((bundle.profile as Record<string,unknown>).digest,harnessProfileDigest(bundle.profile));assert.deepEqual(verifyHarnessBundle(bundle),[],name);bundles.push(bundle);}
  assert.deepEqual(verifyAgentCompatibility(agent,bundles),[]);
  assert.match(verifyAgentCompatibility(agent,bundles.slice(0,3)).join(" "),/every allowed HarnessProfile/);
  const implementationTamper=structuredClone(bundles[0]!);((implementationTamper.version as Record<string,Record<string,unknown>>).implementation!).digest=`sha256:${"f".repeat(64)}`;assert.match(verifyHarnessBundle(implementationTamper).join(" "),/semantic digest/);
  const provenanceTamper=structuredClone(bundles[0]!);((provenanceTamper.version as Record<string,Record<string,unknown>>).provenance!).commit="2".repeat(40);assert.match(verifyHarnessBundle(provenanceTamper).join(" "),/semantic digest/);
  const profileTamper=structuredClone(bundles[0]!);((profileTamper.profile as Record<string,unknown>).overrides as Record<string,unknown>).format="yaml";assert.match(verifyHarnessBundle(profileTamper).join(" "),/semantic digest/);
  const agentTamper=structuredClone(agent);(agentTamper.version as Record<string,unknown>).instructions="substituted";assert.match(verifyAgentCompatibility(agentTamper,bundles).join(" "),/AgentVersion semantic digest/);
});

test("raw credentials, oversized overrides, undeclared credentials and capability mismatch fail before Sandbox",async()=>{
  const schema=await json(path.join(contracts,"harness.schema.json")),bad=await json(path.join(fixtures,"profile-bad-secret.json"));validate(schema,bad);assert.notDeepEqual(verifyHarnessBundle(bad),[]);
  const hermes=await json(path.join(fixtures,"hermes-profile.json")),secret=structuredClone(hermes);((secret.profile as Record<string,unknown>).overrides as Record<string,unknown>).authorization="Bearer forbidden-value";assert.ok(harnessSecretViolations(secret).length);
  const ajv=new Ajv2020({allErrors:true,strict:false});addFormats(ajv);const schemaValidator=ajv.compile(schema),oversized=structuredClone(hermes);((oversized.profile as Record<string,unknown>).overrides as Record<string,unknown>).format="x".repeat(513);assert.equal(schemaValidator(oversized),false,"oversized override passed schema");
  const undeclared=structuredClone(hermes);(undeclared.profile as Record<string,unknown>).credentials=[{capability:"model.anthropic",scope:"route:x",leaseSeconds:60}];assert.notDeepEqual(verifyHarnessBundle(undeclared),[]);
  const wrongScope=structuredClone(hermes);(wrongScope.profile as Record<string,unknown>).credentials=[{capability:"repository.read",scope:"route:not-a-repository",leaseSeconds:60}];assert.match(verifyHarnessBundle(wrongScope).join(" "),/scope/);
  const opaque=structuredClone(hermes);((opaque.profile as Record<string,unknown>).overrides as Record<string,unknown>).value="a".repeat(43);assert.match(verifyHarnessBundle(opaque).join(" "),/raw credential/);
  const agent=await json(path.join(fixtures,"agent-good.json")),limited=structuredClone(hermes);(limited.version as Record<string,unknown>).capabilities=["task.one-shot"];
  assert.match(verifyAgentCompatibility(agent,[limited]).join(" "),/missing capabilities/);
  const secretAgent=structuredClone(agent);(secretAgent.version as Record<string,unknown>).instructions="Use API_KEY=forbidden";assert.ok(verifyAgentCompatibility(secretAgent,[hermes]).some((error)=>error.includes("credential-like")));
  const run=await json(path.join(fixtures,"run-good.json")),incompatible=structuredClone(run),compatibility=incompatible.compatibility as Record<string,unknown>;compatibility.available=["task.one-shot"];compatibility.missing=["message.follow-up","conversation.resume","event.structured","event.streaming","output.patch","output.artifact","cancel.graceful"];compatibility.compatible=false;(incompatible.run as Record<string,unknown>).status="failed";(incompatible.run as Record<string,unknown>).sandboxId=null;(incompatible.result as Record<string,unknown>).status="failed";(incompatible.provenance as Record<string,unknown>).node=null;(incompatible.provenance as Record<string,unknown>).proxyDecision=null;validate(await json(path.join(contracts,"harness-run.schema.json")),incompatible);
  assert.doesNotMatch(verifyHarnessRun(agent,hermes,incompatible).join(" "),/before Sandbox/);
  (incompatible.run as Record<string,unknown>).sandboxId="32000000-0000-4000-8000-000000000001";assert.match(verifyHarnessRun(agent,hermes,incompatible).join(" "),/before Sandbox/);
});

test("normalized lifecycle, follow-up, resume, cancellation, provenance and terminal events are coherent",async()=>{
  const agent=await json(path.join(fixtures,"agent-good.json")),bundle=await json(path.join(fixtures,"hermes-profile.json")),run=await json(path.join(fixtures,"run-good.json")),schema=await json(path.join(contracts,"harness-run.schema.json"));validate(schema,run);assert.deepEqual(verifyHarnessRun(agent,bundle,run),[]);
  assert.equal((run.result as Record<string,unknown>).receiptDigest,harnessTerminalReceiptDigest(run));
  const wrongLease=structuredClone(run);((wrongLease.credentialLeases as Array<Record<string,unknown>>)[0]!).scope="route:70000000-0000-4000-8000-000000000099:1";assert.match(verifyHarnessRun(agent,bundle,wrongLease).join(" "),/credential leases/);
  const wrongMessage=structuredClone(run);((wrongMessage.messages as Array<Record<string,unknown>>)[1]!).followUpToMessageId="35000000-0000-4000-8000-000000000099";assert.match(verifyHarnessRun(agent,bundle,wrongMessage).join(" "),/follow-up Message/);
  const wrongProxy=structuredClone(run);((wrongProxy.provenance as Record<string,Record<string,unknown>>).proxyDecision!).policyVersion=2;assert.match(verifyHarnessRun(agent,bundle,wrongProxy).join(" "),/proxy decision/);
  const wrongArtifact=structuredClone(run);((wrongArtifact.result as {artifacts:Array<Record<string,unknown>>}).artifacts[0]!).mediaType="text/plain";assert.match(verifyHarnessRun(agent,bundle,wrongArtifact).join(" "),/wrong kind or media/);
  const wrongReceipt=structuredClone(run);(wrongReceipt.result as Record<string,unknown>).receiptDigest=`sha256:${"f".repeat(64)}`;assert.match(verifyHarnessRun(agent,bundle,wrongReceipt).join(" "),/receipt semantic digest/);
  for(const mutate of [(v:Record<string,unknown>)=>{((v.events as Array<Record<string,unknown>>)[1]!).sequence=0;},(v:Record<string,unknown>)=>{((v.provenance as Record<string,Record<string,unknown>>).modelRoute!).version=2;},(v:Record<string,unknown>)=>{((v.session as Record<string,unknown>)).followUpCount=0;},(v:Record<string,unknown>)=>{((v.events as Array<Record<string,unknown>>).at(-1)!).type="harness.exited";},(v:Record<string,unknown>)=>{const event=(v.events as Array<Record<string,unknown>>)[2]!;event.type="tool.requested";event.payload={};}]){const candidate=structuredClone(run);mutate(candidate);assert.notDeepEqual(verifyHarnessRun(agent,bundle,candidate),[]);}
  const cancelled=structuredClone(run),events=cancelled.events as Array<Record<string,unknown>>,terminal=events.pop()!,base=structuredClone(events.at(-1)!);events.push({...base,id:"80000000-0000-4000-8000-000000000008",cursor:"cancel-request",type:"cancellation.requested",source:"control-plane",payload:{cancellationId:"37000000-0000-4000-8000-000000000001"},extensions:{}},{...base,id:"80000000-0000-4000-8000-000000000009",cursor:"cancel-ack",type:"cancellation.acknowledged",source:"adapter",payload:{cancellationId:"37000000-0000-4000-8000-000000000001"},extensions:{}},terminal);events.forEach((event,index)=>{event.sequence=index;});(cancelled.session as Record<string,unknown>).eventCursor=events.length-1;(cancelled.run as Record<string,unknown>).status="cancelled";(cancelled.result as Record<string,unknown>).status="cancelled";(terminal.payload as Record<string,unknown>).status="cancelled";(cancelled.session as Record<string,unknown>).cancellation={requested:true,acknowledged:true,processTreeTerminated:true,cleanupComplete:true,credentialsRevoked:true,artifactsHandled:true};(cancelled.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(cancelled);assert.deepEqual(verifyHarnessRun(agent,bundle,cancelled),[]);
  ((cancelled.session as Record<string,Record<string,unknown>>).cancellation!).processTreeTerminated=false;assert.match(verifyHarnessRun(agent,bundle,cancelled).join(" "),/termination/);
  ((cancelled.session as Record<string,Record<string,unknown>>).cancellation!).processTreeTerminated=true;((cancelled.session as Record<string,Record<string,unknown>>).cancellation!).credentialsRevoked=false;assert.match(verifyHarnessRun(agent,bundle,cancelled).join(" "),/credential revocation/);
});

test("portable evaluation requires identical conformance cases and Artifact evidence",async()=>{
  const value=await json(path.join(fixtures,"evaluation-good.json")),schema=await json(path.join(contracts,"harness-conformance.schema.json")),agent=await json(path.join(fixtures,"agent-good.json")),parity=[];
  const hermesBundle=await json(path.join(fixtures,"hermes-profile.json"));validate(schema,value);assert.deepEqual(verifyPortableEvaluation(value,hermesBundle,agent),[]);
  const specifications=[["hermes","hermes-profile.json","1"],["codex-cli","codex-profile.json","2"],["claude-code","claude-profile.json","3"],["generic-cli","generic-profile.json","4"]];
  for(const [kind,file,suffix] of specifications){const bundle=await json(path.join(fixtures,file!)),candidate=structuredClone(value),definition=bundle.definition as Record<string,unknown>,version=bundle.version as Record<string,unknown>,profile=bundle.profile as Record<string,unknown>,resolved=candidate.resolvedHarness as Record<string,Record<string,unknown>>,result=candidate.result as Record<string,unknown>,receipt=result.runReceipt as Record<string,unknown>,runId=`30000000-0000-4000-8000-00000000000${suffix}`,receiptDigest=`sha256:${suffix!.repeat(64)}`,evidence=result.evidenceArtifacts as Array<Record<string,unknown>>,caseResults=result.caseResults as Array<Record<string,unknown>>;candidate.adapterKind=kind;candidate.harnessVersionId=version.id;candidate.profileId=profile.id;resolved.definition={id:definition.id,kind:definition.kind,resourceVersion:definition.resourceVersion};resolved.version={id:version.id,digest:version.digest};resolved.profile={id:profile.id,workspaceId:profile.workspaceId,digest:profile.digest};evidence.forEach((artifact,index)=>{const id=`9${suffix}000000-0000-4000-8000-${String(index+1).padStart(12,"0")}`;artifact.id=id;artifact.contentDigest=`sha256:${String(Number(suffix)*10+index+1).padStart(2,"0").repeat(32)}`;caseResults[index]!.evidenceArtifactId=id;});result.artifactIds=evidence.map((artifact)=>artifact.id);result.runId=runId;result.receiptDigest=receiptDigest;receipt.runId=runId;receipt.receiptDigest=receiptDigest;receipt.harnessVersionId=version.id;receipt.harnessVersionDigest=version.digest;receipt.profileId=profile.id;receipt.profileDigest=profile.digest;receipt.resultDigest=portableResultDigest(candidate);validate(schema,candidate);assert.deepEqual(verifyPortableEvaluation(candidate,bundle,agent),[],kind);parity.push(candidate);}
  assert.deepEqual(verifyPortableParity(parity),[]);
  const missing=structuredClone(parity[0]!);(missing.result as {caseResults:Array<unknown>}).caseResults.pop();assert.notDeepEqual(verifyPortableEvaluation(missing),[]);
  const wrongRole=structuredClone(parity[0]!),artifacts=(wrongRole.result as {evidenceArtifacts:Array<Record<string,unknown>>}).evidenceArtifacts;artifacts[1]!.role=artifacts[0]!.role;assert.notDeepEqual(verifyPortableEvaluation(wrongRole),[]);
  const reusedContent=structuredClone(parity[0]!),reusedArtifacts=(reusedContent.result as {evidenceArtifacts:Array<Record<string,unknown>>}).evidenceArtifacts;reusedArtifacts[1]!.contentDigest=reusedArtifacts[0]!.contentDigest;assert.notDeepEqual(verifyPortableEvaluation(reusedContent),[]);
  const wrongHarness=structuredClone(parity[0]!);((wrongHarness.resolvedHarness as Record<string,Record<string,unknown>>).profile!).digest=`sha256:${"f".repeat(64)}`;assert.notDeepEqual(verifyPortableEvaluation(wrongHarness,await json(path.join(fixtures,"hermes-profile.json")),agent),[]);
  const reused=structuredClone(parity);((reused[1]!.result as Record<string,unknown>)).receiptDigest=(reused[0]!.result as Record<string,unknown>).receiptDigest;assert.notDeepEqual(verifyPortableParity(reused),[]);
});
