import { createHash } from "node:crypto";
type RecordValue = Record<string, unknown>;
const capabilities = new Set(["task.one-shot","message.follow-up","conversation.resume","event.structured","event.streaming","tool.native","tool.mcp","output.patch","output.artifact","checkpoint.recovery","model.select","provider.configure","approval.prompt","cancel.graceful"]);
const secretKeys = new Set(["token","apitoken","authtoken","sessiontoken","accesstoken","refreshtoken","password","secret","credential","authorization","apikey","privatekey","kubeconfig","nodecredential","bearertoken","clientsecret"]);
const providerSecretKeys = new Set(["awsaccesskeyid","awssecretaccesskey","awssessiontoken","githubtoken","gitlabtoken","openaiapikey","anthropicapikey","azureclientsecret","googleclientsecret","gcpserviceaccountkey","stripesecretkey","slacktoken","npmtoken","dockerhubtoken","huggingfacetoken","hftoken"]);
const credentialMetadataKeys = new Set(["directproviderauthorization"]);
const secretKeySuffixes = ["token","password","secret","credential","authorization","apikey","privatekey","accesskey"];
const terminal = new Set(["succeeded","failed","cancelled","timed_out","recovery_required"]);
const approvedExecutables:Record<string,{identity:string,path:string}>={
  hermes:{identity:"blazn-hermes-adapter",path:"/opt/blazn/hermes"},
  "codex-cli":{identity:"blazn-codex-adapter",path:"/opt/blazn/codex"},
  "claude-code":{identity:"blazn-claude-adapter",path:"/opt/blazn/claude"},
  "generic-cli":{identity:"blazn-generic-adapter",path:"/opt/blazn/generic-fixture"},
};
const record = (value: unknown): RecordValue => value !== null && typeof value === "object" && !Array.isArray(value) ? value as RecordValue : {};
const text = (value: unknown): string => typeof value === "string" ? value : "";
const strings = (value: unknown): string[] => Array.isArray(value) && value.every((item) => typeof item === "string") ? value : [];
const normalizedKey = (value: string): string => value.toLowerCase().replace(/[^a-z0-9]/g, "");
function isSecretKey(value:string):boolean{const normalized=normalizedKey(value);if(credentialMetadataKeys.has(normalized))return false;if(secretKeys.has(normalized)||providerSecretKeys.has(normalized)||secretKeySuffixes.some((suffix)=>normalized.endsWith(suffix)))return true;return /(?:^|[_-])(?:token|password|secret|credential|authorization|api[_-]?key|private[_-]?key|access[_-]?key)(?:$|[_-])/i.test(value);}
function resemblesProviderToken(value:string):boolean{return /\b(?:sk-(?:proj-|svcacct-|ant-)?[A-Za-z0-9_-]{16,}|github_pat_[A-Za-z0-9_]{20,}|gh[pousr]_[A-Za-z0-9]{20,}|(?:AKIA|ASIA)[A-Z0-9]{16}|xox[baprs]-[A-Za-z0-9-]{10,}|hf_[A-Za-z0-9]{20,}|npm_[A-Za-z0-9]{20,}|(?:sk|rk)_(?:live|test)_[A-Za-z0-9]{16,})\b/.test(value);}
function canonical(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;const item=value as RecordValue;return`{${Object.keys(item).sort().map((key)=>`${JSON.stringify(key)}:${canonical(item[key])}`).join(",")}}`;}
function semanticDigest(domain:string,value:unknown):string{return`sha256:${createHash("sha256").update(`${domain}\n${canonical(value)}`).digest("hex")}`;}
function without(value:unknown,...keys:string[]):RecordValue{const copy={...record(value)};for(const key of keys)delete copy[key];return copy;}
export const agentVersionDigest=(value:unknown)=>semanticDigest("blazn-agent-version-v1",without(value,"digest"));
export const harnessVersionDigest=(value:unknown)=>semanticDigest("blazn-harness-version-v1",without(value,"digest"));
export const harnessProfileDigest=(value:unknown)=>semanticDigest("blazn-harness-profile-v1",without(value,"digest","resourceVersion"));
export function harnessTerminalReceiptDigest(value:unknown):string{const snapshot=record(value),result=without(snapshot.result,"receiptDigest");return semanticDigest("blazn-harness-terminal-receipt-v1",{run:snapshot.run,session:snapshot.session,provenance:snapshot.provenance,compatibility:snapshot.compatibility,credentialLeases:snapshot.credentialLeases,messages:snapshot.messages,events:snapshot.events,result});}
export function portableResultDigest(value:unknown):string{const result=record(record(value).result);return semanticDigest("blazn-portable-evaluation-result-v1",{caseResults:result.caseResults,evidenceArtifacts:result.evidenceArtifacts});}

export function harnessSecretViolations(value: unknown, path = "$", output: string[] = []): string[] {
  if (Array.isArray(value)) value.forEach((item, index) => harnessSecretViolations(item, `${path}[${index}]`, output));
  else if (value !== null && typeof value === "object") for (const [key, child] of Object.entries(value as RecordValue)) {
    if (isSecretKey(key)) output.push(`${path}.${key} is a forbidden raw credential field`);
    harnessSecretViolations(child, `${path}.${key}`, output);
  } else if (typeof value === "string" && (/\bBearer\s+[A-Za-z0-9._~-]{8,}/i.test(value) || /(?:api[_-]?key|token|password|secret|authorization)\s*[:=]\s*\S+/i.test(value) || /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(value) || /:\/\/[^/\s]+@/.test(value) || resemblesProviderToken(value))) output.push(`${path} contains credential-like material`);
  return output;
}

export function verifyHarnessBundle(value: unknown): string[] {
  const errors = harnessSecretViolations(value), bundle = record(value), definition = record(bundle.definition), version = record(bundle.version), profile = record(bundle.profile);
  if (version.definitionId !== definition.id) errors.push("HarnessVersion does not belong to HarnessDefinition");
  if(version.digest!==harnessVersionDigest(version))errors.push("HarnessVersion semantic digest is invalid");
  if(profile.digest!==harnessProfileDigest(profile))errors.push("HarnessProfile semantic digest is invalid");
  const implementation=record(version.implementation),provenance=record(version.provenance),implementationDigest=text(implementation.digest),artifactDigest=text(provenance.artifactDigest);if(implementation.kind==="package"?implementationDigest!==artifactDigest:!implementationDigest.endsWith(`@${artifactDigest}`))errors.push("HarnessVersion implementation digest is not bound to provenance Artifact digest");
  if (profile.harnessVersionId !== version.id) errors.push("HarnessProfile does not select HarnessVersion");
  if (definition.status !== "approved" || profile.status !== "approved") errors.push("Harness definition and profile must be approved");
  const available = strings(version.capabilities);
  if (available.some((item) => !capabilities.has(item))) errors.push("HarnessVersion contains an unknown capability");
  const credentialCapabilities = new Set(strings(version.credentialCapabilities)),declaredCredentials=Array.isArray(profile.credentials)?profile.credentials.map(record):[],declaredIdentities=declaredCredentials.map(credentialIdentity);
  if(new Set(declaredIdentities).size!==declaredIdentities.length)errors.push("HarnessProfile credential capability and scope declarations must be unique");
  for (const credential of declaredCredentials) { const capability=text(credential.capability),scope=text(credential.scope),prefix=capability.startsWith("model.")?"route:":capability==="repository.read"?"repo:":"tool:";if(!credentialCapabilities.has(capability))errors.push("HarnessProfile requests an undeclared credential capability");if(!scope.startsWith(prefix))errors.push("HarnessProfile credential scope does not match its capability"); }
  const proxyProtocols = new Set(strings(record(version.compatibility).proxyProtocols));
  if (!proxyProtocols.has(text(record(profile.model).protocol))) errors.push("HarnessProfile model protocol is unsupported");
  const executable = record(version.executable), executablePath=text(executable.path), argv = strings(executable.fixedArgv), approvedExecutable=approvedExecutables[text(definition.kind)];
  if (!approvedExecutable || executable.identity!==approvedExecutable.identity || executablePath!==approvedExecutable.path || argv.some((arg) => /(?:^|[=\s])(?:token|password|secret|authorization|api[_-]?key)(?:[=:]|$)/i.test(decode(arg)) || /[;&|`$<>\r\n]/.test(arg))) errors.push("Harness executable contract is unsafe: only the reviewed adapter identity and path are allowed; interpreters, aliases, network clients, shell syntax, redirection, and credential argv are prohibited");
  for(const override of Object.values(record(profile.overrides)))if(typeof override==="string"&&/^[A-Za-z0-9_-]{32,}$/.test(override))errors.push("HarnessProfile override resembles raw credential material");
  const modelCredentials=(Array.isArray(profile.credentials)?profile.credentials.map(record):[]).filter((item)=>text(item.capability).startsWith("model.")),providerCredentials=modelCredentials.filter((item)=>item.capability!=="model.proxy"),directAuthorization=profile.directProviderAuthorization===null?null:record(profile.directProviderAuthorization);if(modelCredentials.length!==1)errors.push("HarnessProfile must declare exactly one model credential capability");
  if(providerCredentials.length){const credential=providerCredentials[0]!,capability=text(credential.capability),protocol=text(record(profile.model).protocol),expectedProvider=capability==="model.openai"?"openai":capability==="model.anthropic"?"anthropic":"",protocolMatches=expectedProvider==="openai"?protocol.startsWith("openai-"):expectedProvider==="anthropic"&&protocol==="anthropic-messages";if(providerCredentials.length!==1||!directAuthorization||!text(directAuthorization.id)||directAuthorization.workspaceId!==profile.workspaceId||directAuthorization.profileId!==profile.id||directAuthorization.routeId!==record(profile.model).routeId||directAuthorization.routeVersion!==record(profile.model).routeVersion||directAuthorization.capability!==capability||directAuthorization.provider!==expectedProvider||directAuthorization.status!=="approved"||!protocolMatches)errors.push("provider credential requires resolved same-workspace approved DIRECT authorization");}else if(directAuthorization!==null)errors.push("proxy-routed HarnessProfile cannot carry DIRECT authorization");
  return errors;
}

function decode(value: string): string { let current=value; for(let i=0;i<3;i++){try{const next=decodeURIComponent(current);if(next===current)break;current=next;}catch{break;}}return current; }
function repositoryScope(value:unknown):string{try{const url=new URL(text(value));return`repo:${url.pathname.replace(/^\//,"").replace(/\.git$/,"")}`;}catch{return"";}}
function credentialIdentity(value:unknown):string{const item=record(value);return`${text(item.capability)}|${text(item.scope)}`;}
function allowedProfileRefs(value:unknown):RecordValue[]{return Array.isArray(record(value).allowedHarnessProfiles)?(record(value).allowedHarnessProfiles as unknown[]).map(record):[];}
function verifySelectedProfileCompatibility(agentVersion:RecordValue,bundle:RecordValue):string[]{const errors:string[]=[],definition=record(bundle.definition),harnessVersion=record(bundle.version),profile=record(bundle.profile),agentTools=new Set(strings(agentVersion.tools)),profileTools=new Set(strings(profile.tools)),available=new Set(strings(harnessVersion.capabilities)),definitionPlatforms=new Set(strings(definition.supportedPlatforms)),modelPolicy=record(agentVersion.modelPolicy),profileModel=record(profile.model),expectedModelScope=`route:${text(modelPolicy.routeId)}:${String(modelPolicy.routeVersion)}`,expectedRepositoryScope=repositoryScope(record(agentVersion.repository).url);if(profile.workspaceId!==agentVersion.workspaceId)errors.push("selected HarnessProfile is outside Agent workspace");if(strings(harnessVersion.supportedPlatforms).some((platform)=>!definitionPlatforms.has(platform)))errors.push("selected HarnessVersion platform exceeds HarnessDefinition");if(strings(agentVersion.requiredCapabilities).some((capability)=>!available.has(capability)))errors.push("selected HarnessProfile is missing AgentVersion capabilities");if(profileModel.routeId!==modelPolicy.routeId||profileModel.routeVersion!==modelPolicy.routeVersion||!strings(modelPolicy.requiredProtocols).includes(text(profileModel.protocol)))errors.push("selected HarnessProfile model route or protocol is incompatible with AgentVersion");if(JSON.stringify([...agentTools].sort())!==JSON.stringify([...profileTools].sort()))errors.push("selected HarnessProfile tools differ from AgentVersion");for(const rawCredential of Array.isArray(profile.credentials)?profile.credentials:[]){const credential=record(rawCredential),capability=text(credential.capability),scope=text(credential.scope);if(capability.startsWith("model.")&&scope!==expectedModelScope)errors.push("selected HarnessProfile model credential is not bound to Agent route");if(capability==="repository.read"&&scope!==expectedRepositoryScope)errors.push("selected HarnessProfile repository credential is not bound to Agent source");if(capability==="tool.mcp"&&(!scope.startsWith("tool:")||!agentTools.has(scope.slice(5))))errors.push("selected HarnessProfile tool credential is not bound to Agent tools");}return errors;}

export const harnessEventSources:Record<string,ReadonlySet<string>>={
  "harness.preparing":new Set(["control-plane"]),"harness.ready":new Set(["adapter"]),"harness.started":new Set(["adapter"]),"harness.waiting":new Set(["adapter"]),"harness.resumed":new Set(["adapter"]),"harness.stopping":new Set(["adapter"]),"harness.exited":new Set(["adapter"]),
  "message.user":new Set(["control-plane"]),"message.assistant":new Set(["adapter","harness"]),"message.tool":new Set(["adapter","harness"]),
  "tool.requested":new Set(["adapter","harness"]),"tool.approved":new Set(["control-plane"]),"tool.denied":new Set(["control-plane"]),"tool.started":new Set(["adapter","harness"]),"tool.completed":new Set(["adapter","harness"]),"tool.failed":new Set(["adapter","harness"]),
  "approval.requested":new Set(["adapter","harness"]),"approval.resolved":new Set(["control-plane"]),"model.requested":new Set(["control-plane","proxy"]),"model.proxy-decided":new Set(["control-plane","proxy"]),"model.usage":new Set(["control-plane","proxy"]),"model.fallback-authorized":new Set(["control-plane"]),"model.fallback-decided":new Set(["proxy"]),"billing.recorded":new Set(["control-plane","proxy"]),
  "artifact.created":new Set(["adapter","harness"]),"patch.created":new Set(["adapter","harness"]),"progress":new Set(["adapter","harness","sandbox"]),"warning":new Set(["control-plane","adapter","harness","proxy","sandbox"]),"error":new Set(["control-plane","adapter","harness","proxy","sandbox"]),
  "followup.accepted":new Set(["control-plane"]),"cancellation.requested":new Set(["control-plane"]),"cancellation.acknowledged":new Set(["adapter"]),"timeout":new Set(["control-plane"]),"result.terminal":new Set(["control-plane"]),
};

function verifyEventCausality(events:RecordValue[],errors:string[],createdAt:string,completedAt:string|null):void{
  const ids=new Set<string>();let previousTime=-Infinity;
  const created=Date.parse(createdAt),completed=completedAt===null?null:Date.parse(completedAt);
  for(const event of events){const id=text(event.id),type=text(event.type),time=Date.parse(text(event.observedAt)),allowed=harnessEventSources[type];if(!id||ids.has(id))errors.push("normalized event identity is duplicated");ids.add(id);if(!Number.isFinite(time)||time<previousTime)errors.push("normalized event observation time violates sequence causality");previousTime=time;if(!allowed||!allowed.has(text(event.source)))errors.push(`${type} event has a non-authoritative source`);if(!Number.isFinite(created)||!Number.isFinite(time)||time<created||completed!==null&&(!Number.isFinite(completed)||time>completed))errors.push("normalized event observation time is outside the authoritative Run lifecycle");}
  const terminalEvent=events.find((event)=>event.type==="result.terminal");if(completed!==null&&terminalEvent&&Date.parse(text(terminalEvent.observedAt))!==completed)errors.push("terminal event observation time does not equal authoritative Run completion time");
  const indexOf=(type:string)=>events.findIndex((event)=>event.type===type),count=(type:string)=>events.filter((event)=>event.type===type).length;
  const preparing=indexOf("harness.preparing"),started=indexOf("harness.started"),ready=indexOf("harness.ready"),stopping=indexOf("harness.stopping"),exited=indexOf("harness.exited");
  if(count("harness.preparing")>1||count("harness.ready")>1||count("harness.started")>1||count("harness.stopping")>1||count("harness.exited")>1||(started>=0&&(preparing<0||preparing>=started))||(ready>=0&&(preparing<0||preparing>=ready))||(stopping>=0&&(started<0||started>=stopping))||(exited>=0&&(started<0||started>=exited))||(stopping>=0&&exited>=0&&stopping>=exited))errors.push("Harness lifecycle events violate preparation, start, stop, and exit causality");
  const groups=(prefix:string,idKey:string)=>{const grouped=new Map<string,RecordValue[]>();for(const event of events){if(!text(event.type).startsWith(prefix))continue;const id=text(record(event.payload)[idKey]);if(!id)continue;const values=grouped.get(id)??[];values.push(event);grouped.set(id,values);}return grouped;};
  for(const group of groups("tool.","toolCallId").values()){const position=(type:string)=>group.findIndex((event)=>event.type===type),occurs=(type:string)=>group.filter((event)=>event.type===type).length,requested=position("tool.requested"),approved=position("tool.approved"),startedAt=position("tool.started"),completed=position("tool.completed"),failed=position("tool.failed"),denied=position("tool.denied"),terminals=[completed,failed,denied].filter((value)=>value>=0);if(requested!==0||["tool.requested","tool.approved","tool.started","tool.completed","tool.failed","tool.denied"].some((type)=>occurs(type)>1)||terminals.length>1||(approved>=0&&approved<=requested)||(startedAt>=0&&(startedAt<=requested||denied>=0||(approved>=0&&approved>=startedAt)))||((completed>=0||failed>=0)&&(startedAt<0||Math.max(completed,failed)<=startedAt))||(denied>=0&&denied<=requested))errors.push("tool events violate request, decision, start, and terminal causality");}
  for(const group of groups("approval.","approvalId").values()){const requested=group.findIndex((event)=>event.type==="approval.requested"),resolved=group.findIndex((event)=>event.type==="approval.resolved");if(requested!==0||group.filter((event)=>event.type==="approval.requested").length!==1||group.filter((event)=>event.type==="approval.resolved").length>1||(resolved>=0&&resolved<=requested))errors.push("approval events violate request and resolution causality");}
  for(const group of groups("model.","requestId").values()){const requested=group.findIndex((event)=>event.type==="model.requested"),usage=group.findIndex((event)=>event.type==="model.usage");if(usage>=0&&(requested<0||usage<=requested)||group.filter((event)=>event.type==="model.requested").length>1||group.filter((event)=>event.type==="model.usage").length>1)errors.push("model events violate request and usage causality");}
}

export function verifyAgentCompatibility(agentValue: unknown, bundles: unknown[]): string[] {
  const errors: string[] = harnessSecretViolations(agentValue), root = record(agentValue), agent = record(root.agent), version = record(root.version);
  if (agent.currentVersionId !== version.id || agent.id !== version.agentId || agent.workspaceId !== version.workspaceId) errors.push("Agent and immutable AgentVersion identity mismatch");
  if(version.digest!==agentVersionDigest(version))errors.push("AgentVersion semantic digest is invalid");
  const pinned=allowedProfileRefs(version),pinnedIds=pinned.map((item)=>text(item.id)),allowed=new Set(pinnedIds);
  if(allowed.size!==pinned.length)errors.push("AgentVersion allowed HarnessProfile pins must have unique IDs");
  if (!allowed.has(text(version.defaultHarnessProfileId))) errors.push("default HarnessProfile is not allowed");
  if(strings(record(version.outputContract).artifacts).some((role)=>!new Set(["patch","summary","output"]).has(role)))errors.push("AgentVersion output contract contains an unrunnable Artifact role");
  const modelPolicy=record(version.modelPolicy),fallbackRoute=modelPolicy.fallbackRoute===null?null:record(modelPolicy.fallbackRoute);if(modelPolicy.fallback==="one-approved-attempt"&&(!fallbackRoute||fallbackRoute.routeId===modelPolicy.routeId&&fallbackRoute.routeVersion===modelPolicy.routeVersion||!text(fallbackRoute.authorizationId)||!text(fallbackRoute.approvalReceiptId)))errors.push("AgentVersion fallback route is not a distinct frozen approved route");if(modelPolicy.fallback==="disabled"&&fallbackRoute!==null)errors.push("disabled AgentVersion fallback carries a route");
  const suppliedProfiles=bundles.map((item)=>text(record(record(item).profile).id));
  if(suppliedProfiles.length!==new Set(suppliedProfiles).size||JSON.stringify([...new Set(suppliedProfiles)].sort())!==JSON.stringify([...allowed].sort()))errors.push("Agent publication did not validate every allowed HarnessProfile exactly once");
  for (const raw of bundles) {
    errors.push(...verifyHarnessBundle(raw));
    const bundle = record(raw), profile = record(bundle.profile), harnessVersion = record(bundle.version);
    if (!allowed.has(text(profile.id))) { errors.push("HarnessProfile is not allowed by AgentVersion"); continue; }
    if(pinned.find((item)=>item.id===profile.id)?.digest!==profile.digest)errors.push("HarnessProfile semantic digest differs from immutable AgentVersion pin");
    if (profile.workspaceId !== version.workspaceId) errors.push("HarnessProfile is outside Agent workspace");
    const definitionPlatforms=new Set(strings(record(bundle.definition).supportedPlatforms));if(strings(harnessVersion.supportedPlatforms).some((platform)=>!definitionPlatforms.has(platform)))errors.push("HarnessVersion platform exceeds HarnessDefinition");
    const available = new Set(strings(harnessVersion.capabilities));
    const missing = strings(version.requiredCapabilities).filter((item) => !available.has(item));
    if (missing.length) errors.push(`HarnessProfile ${text(profile.id)} is missing capabilities: ${missing.join(",")}`);
    if (record(profile.model).routeId !== record(version.modelPolicy).routeId || record(profile.model).routeVersion !== record(version.modelPolicy).routeVersion) errors.push("HarnessProfile model route does not match AgentVersion");
    if (!strings(record(version.modelPolicy).requiredProtocols).includes(text(record(profile.model).protocol))) errors.push("HarnessProfile model protocol is not allowed by AgentVersion");
    const agentTools=new Set(strings(version.tools)),profileTools=new Set(strings(profile.tools));if(JSON.stringify([...agentTools].sort())!==JSON.stringify([...profileTools].sort()))errors.push("HarnessProfile tools do not exactly match AgentVersion tools");
    const expectedModelScope=`route:${text(record(version.modelPolicy).routeId)}:${String(record(version.modelPolicy).routeVersion)}`,expectedRepositoryScope=repositoryScope(record(version.repository).url);
    for(const rawCredential of Array.isArray(profile.credentials)?profile.credentials:[]){const credential=record(rawCredential),capability=text(credential.capability),scope=text(credential.scope);if(capability.startsWith("model.")&&scope!==expectedModelScope)errors.push("HarnessProfile model credential is not bound to Agent model route");if(capability==="repository.read"&&scope!==expectedRepositoryScope)errors.push("HarnessProfile repository credential is not bound to Agent repository");if(capability==="tool.mcp"&&(!scope.startsWith("tool:")||!agentTools.has(scope.slice(5))))errors.push("HarnessProfile tool credential is not bound to Agent tools");}
  }
  return errors;
}

export function verifyHarnessRun(agentValue: unknown, bundleValue: unknown, runValue: unknown): string[] {
  const errors = harnessSecretViolations(runValue), agentVersion = record(record(agentValue).version), bundle = record(bundleValue), profile = record(bundle.profile), harnessVersion = record(bundle.version), snapshot = record(runValue), run = record(snapshot.run), session = record(snapshot.session), provenance = record(snapshot.provenance), compatibility = record(snapshot.compatibility);
  errors.push(...verifyHarnessBundle(bundleValue));
  if(agentVersion.digest!==agentVersionDigest(agentVersion))errors.push("Run AgentVersion semantic digest is invalid");
  const pinnedProfile=allowedProfileRefs(agentVersion).find((item)=>item.id===profile.id);if(!pinnedProfile)errors.push("Run HarnessProfile is not allowed by AgentVersion");else if(pinnedProfile.digest!==profile.digest)errors.push("Run HarnessProfile semantic digest differs from immutable AgentVersion pin");
  if (run.agentId !== agentVersion.agentId || run.agentVersionId !== agentVersion.id || run.harnessProfileId !== profile.id || run.harnessVersionId !== harnessVersion.id) errors.push("Run does not capture exact Agent, AgentVersion, and Harness identities");
  if (run.workspaceId !== agentVersion.workspaceId || profile.workspaceId !== run.workspaceId) errors.push("Run resources cross a workspace boundary");
  const agentModel=record(agentVersion.modelPolicy),profileModel=record(profile.model),expectedModelScope=`route:${text(agentModel.routeId)}:${String(agentModel.routeVersion)}`,expectedRepositoryScope=repositoryScope(record(agentVersion.repository).url),agentTools=new Set(strings(agentVersion.tools)),profileTools=new Set(strings(profile.tools));
  if(profileModel.routeId!==agentModel.routeId||profileModel.routeVersion!==agentModel.routeVersion||!strings(agentModel.requiredProtocols).includes(text(profileModel.protocol)))errors.push("selected HarnessProfile model route is incompatible with AgentVersion");
  if(JSON.stringify([...agentTools].sort())!==JSON.stringify([...profileTools].sort()))errors.push("selected HarnessProfile tools differ from AgentVersion");
  for(const rawCredential of Array.isArray(profile.credentials)?profile.credentials:[]){const credential=record(rawCredential),capability=text(credential.capability),scope=text(credential.scope);if(capability.startsWith("model.")&&scope!==expectedModelScope)errors.push("selected HarnessProfile model credential is not bound to Agent route");if(capability==="repository.read"&&scope!==expectedRepositoryScope)errors.push("selected HarnessProfile repository credential is not bound to Agent source");if(capability==="tool.mcp"&&(!scope.startsWith("tool:")||!agentTools.has(scope.slice(5))))errors.push("selected HarnessProfile tool credential is not bound to Agent tools");}
  const selectedDirect=profile.directProviderAuthorization===null?null:record(profile.directProviderAuthorization),selectedProviderCredential=(Array.isArray(profile.credentials)?profile.credentials.map(record):[]).find((credential)=>text(credential.capability).startsWith("model.")&&credential.capability!=="model.proxy");if(selectedProviderCredential&&(selectedDirect===null||selectedDirect.routeId!==agentModel.routeId||selectedDirect.routeVersion!==agentModel.routeVersion||selectedDirect.capability!==selectedProviderCredential.capability))errors.push("selected HarnessProfile DIRECT authorization is not bound to Agent route and model capability");
  if (record(provenance.agentVersion).id !== agentVersion.id || record(provenance.agentVersion).digest !== agentVersion.digest || record(provenance.harnessVersion).id !== harnessVersion.id || record(provenance.harnessVersion).digest !== harnessVersion.digest || record(provenance.harnessProfile).id !== profile.id || record(provenance.harnessProfile).digest !== profile.digest) errors.push("Run provenance does not bind immutable Agent and Harness versions");
  if (record(provenance.sandboxTemplateVersion).id !== record(agentVersion.template).versionId || record(provenance.sandboxTemplateVersion).digest !== record(agentVersion.template).digest || record(provenance.modelRoute).id !== record(agentVersion.modelPolicy).routeId || record(provenance.modelRoute).version !== record(agentVersion.modelPolicy).routeVersion || record(provenance.modelRoute).protocol!==record(profile.model).protocol) errors.push("Run provenance does not bind exact template and model route");
  if (record(provenance.source).repository !== record(agentVersion.repository).url || record(provenance.source).commit !== record(agentVersion.repository).commit) errors.push("Run source provenance differs from AgentVersion");
  const proxy=provenance.proxyDecision===null?{}:record(provenance.proxyDecision),fallback=provenance.fallbackAttempt===null?null:record(provenance.fallbackAttempt),billing=record(provenance.billing),modelPolicy=record(agentVersion.modelPolicy),profileModelCredentials=(Array.isArray(profile.credentials)?profile.credentials.map(record):[]).filter((item)=>text(item.capability).startsWith("model.")),providerCredential=profileModelCredentials.find((item)=>item.capability!=="model.proxy"),expectedOutcome=providerCredential?"DIRECT":"ROUTED",expectedAuthentication=providerCredential?"provider-capability-proof":"proxy-workload-proof",expectedAuthorization=providerCredential?record(profile.directProviderAuthorization).id:null;if(compatibility.compatible===true&&(proxy.outcome!==expectedOutcome||proxy.authentication!==expectedAuthentication||proxy.authorizationId!==expectedAuthorization||proxy.routeId!==modelPolicy.routeId||proxy.routeVersion!==modelPolicy.routeVersion||proxy.policyId!==modelPolicy.policyId||proxy.policyVersion!==modelPolicy.policyVersion||!text(proxy.requestId)||!text(proxy.eventId)))errors.push("proxy decision does not bind exact authenticated route and policy");
  const approvedFallback=record(modelPolicy.fallbackRoute);if(fallback&&(modelPolicy.fallback!=="one-approved-attempt"||fallback.attempt!==1||fallback.approved!==true||fallback.primaryRouteId!==modelPolicy.routeId||fallback.primaryRouteVersion!==modelPolicy.routeVersion||fallback.policyId!==modelPolicy.policyId||fallback.policyVersion!==modelPolicy.policyVersion||fallback.fallbackRouteId!==approvedFallback.routeId||fallback.fallbackRouteVersion!==approvedFallback.routeVersion||fallback.authorizationId!==approvedFallback.authorizationId||fallback.approvalReceiptId!==approvedFallback.approvalReceiptId||fallback.requestId===proxy.requestId||!text(fallback.receiptId)))errors.push("fallback attempt is not one approved attempt bound to the frozen fallback route, authorization, receipt, and policy");if(!fallback&&modelPolicy.fallback==="disabled"&&record(modelPolicy.fallbackRoute).routeId)errors.push("disabled fallback carries an approved route");
  const expectedBillingSource=billing.mode==="zero-cost"||expectedOutcome==="DIRECT"?"control-plane-receipt":"proxy-receipt";if(billing.mode!=="zero-cost"&&billing.mode!=="priced"||(billing.mode==="zero-cost")!==(billing.amountMicros===0)||billing.mode==="priced"&&Number(billing.amountMicros)<=0||billing.currency!=="USD"||!text(billing.pricingId)||!text(billing.receiptId)||typeof billing.pricingVersion!=="number"||!Number.isInteger(billing.pricingVersion)||compatibility.compatible===true&&billing.source!==expectedBillingSource)errors.push("cost provenance lacks the authoritative receipt required for routed priced, DIRECT, or explicit zero-cost execution");
  const required = new Set(strings(compatibility.required)), available = new Set(strings(compatibility.available)), missing = strings(compatibility.missing), computedMissing = [...required].filter((item) => !available.has(item)).sort();
  if (JSON.stringify([...missing].sort()) !== JSON.stringify(computedMissing) || compatibility.compatible !== (computedMissing.length === 0)) errors.push("capability compatibility result is inconsistent");
  if(JSON.stringify([...required].sort())!==JSON.stringify([...strings(agentVersion.requiredCapabilities)].sort())||JSON.stringify([...available].sort())!==JSON.stringify([...strings(harnessVersion.capabilities)].sort()))errors.push("compatibility did not compare the exact Agent and Harness capability sets");
  const leases=Array.isArray(snapshot.credentialLeases)?snapshot.credentialLeases.map(record):[],refusalMessages=Array.isArray(snapshot.messages)?snapshot.messages.map(record):[],refusalEvents=Array.isArray(snapshot.events)?snapshot.events.map(record):[],refusalResult=record(snapshot.result),refusalUsage=record(refusalResult.usage),refusalArtifacts=Array.isArray(refusalResult.artifacts)?refusalResult.artifacts:[],refusalArtifactIds=strings(refusalResult.artifactIds),refusalError=refusalEvents[0],refusalTerminal=refusalEvents[1],refusalErrorPayload=record(refusalError?.payload),refusalTerminalPayload=record(refusalTerminal?.payload),refusalCancellation=record(session.cancellation),expectedMissing=computedMissing.join(","),exactRefusalErrorPayload=JSON.stringify(Object.keys(refusalErrorPayload).sort())===JSON.stringify(["code","missingCapabilities"]),exactRefusalTerminalPayload=JSON.stringify(Object.keys(refusalTerminalPayload).sort())===JSON.stringify(["status"]),emptyRefusalExtensions=refusalEvents.every((event)=>Object.keys(record(event.extensions)).length===0),emptyRefusalCancellation=["requested","acknowledged","processTreeTerminated","cleanupComplete","credentialsRevoked","artifactsHandled"].every((key)=>refusalCancellation[key]===false),refusalBilling=billing.mode==="zero-cost"&&billing.amountMicros===0&&billing.source==="control-plane-receipt";if (compatibility.checkedBeforeSandbox !== true || (compatibility.compatible === false && (run.sandboxId !== null || provenance.node !== null || provenance.proxyDecision !== null || provenance.fallbackAttempt !== null || !refusalBilling || leases.length!==0 || refusalMessages.length!==0 || refusalEvents.length!==2 || refusalError?.type!=="error" || refusalError?.source!=="control-plane" || !exactRefusalErrorPayload || refusalErrorPayload.code!=="capability-mismatch" || refusalErrorPayload.missingCapabilities!==expectedMissing || refusalTerminal?.type!=="result.terminal" || refusalTerminal?.source!=="control-plane" || !exactRefusalTerminalPayload || refusalTerminalPayload.status!=="failed" || !emptyRefusalExtensions || session.messageCursor!==0 || session.eventCursor!==1 || session.followUpCount!==0 || session.resumeGeneration!==0 || !emptyRefusalCancellation || refusalResult.status!=="failed" || refusalResult.summary!=="Harness capability mismatch refused before Sandbox allocation." || refusalArtifactIds.length!==0 || refusalArtifacts.length!==0 || refusalResult.patchArtifactId!==null || refusalUsage.modelRequests!==0 || refusalUsage.inputTokens!==0 || refusalUsage.outputTokens!==0))) errors.push("capability mismatch did not remain an execution-free control-plane refusal before Sandbox allocation or credential issuance");
  if(compatibility.compatible===true&&terminal.has(text(run.status))&&!text(run.sandboxId))errors.push("compatible terminal Run lacks its allocated Sandbox identity");
  const declarations=Array.isArray(profile.credentials)?profile.credentials.map(record):[],declarationIdentityValues=declarations.map(credentialIdentity),declaredCredentialSet=new Set(declarationIdentityValues),leaseIdentityValues=leases.map(credentialIdentity),leaseIdentities=new Set(leaseIdentityValues),leaseIDs=leases.map((lease)=>text(lease.id)),runCreated=Date.parse(text(run.createdAt)),eventTimes=(Array.isArray(snapshot.events)?snapshot.events:[]).map((event)=>Date.parse(text(record(event).observedAt))).filter(Number.isFinite),firstEvent=eventTimes.length?Math.min(...eventTimes):runCreated,lifecycleEnd=terminal.has(text(run.status))?Date.parse(text(run.completedAt)):(eventTimes.length?Math.max(...eventTimes):runCreated);if(compatibility.compatible===true&&(declaredCredentialSet.size!==declarations.length||leaseIdentities.size!==leases.length||new Set(leaseIDs).size!==leaseIDs.length||JSON.stringify([...declaredCredentialSet].sort())!==JSON.stringify([...leaseIdentities].sort())))errors.push("credential declarations and leases must match injectively one-to-one with unique IDs");for(const lease of leases){const declaration=declarations.find((item)=>credentialIdentity(item)===credentialIdentity(lease)),issued=Date.parse(text(lease.issuedAt)),expires=Date.parse(text(lease.expiresAt)),revoked=lease.revokedAt===null?NaN:Date.parse(text(lease.revokedAt)),ttl=(expires-issued)/1000;if(!declaration||ttl!==declaration.leaseSeconds||!Number.isFinite(issued)||!Number.isFinite(expires)||expires<=issued)errors.push("credential lease lifetime differs from HarnessProfile");if(!Number.isFinite(runCreated)||!Number.isFinite(firstEvent)||!Number.isFinite(lifecycleEnd)||issued<runCreated||issued>firstEvent||expires<lifecycleEnd)errors.push("credential lease was not issued and valid for the authoritative Run lifecycle");if(lease.status==="active"&&lease.revokedAt!==null||lease.status==="revoked"&&(!Number.isFinite(revoked)||revoked<issued||revoked>expires))errors.push("credential lease state and revocation time are incoherent");}const modelLeases=leases.filter((lease)=>text(lease.capability).startsWith("model."));if(compatibility.compatible===true&&(modelLeases.length!==1||modelLeases[0]?.scope!==expectedModelScope))errors.push("Run must carry exactly one Agent-route-bound model credential lease");if(terminal.has(text(run.status))&&leases.some((lease)=>lease.status!=="revoked"||!text(lease.revokedAt)))errors.push("terminal Run retained a credential lease");
  const messages=Array.isArray(snapshot.messages)?snapshot.messages.map(record):[],messageIds=new Set<string>(),messageIndexes=new Map<string,number>(),messageById=new Map<string,RecordValue>();messages.forEach((message,index)=>{const id=text(message.id);if(!id||messageIds.has(id)||message.runId!==run.id||message.sessionId!==session.id||message.conversationId!==session.conversationId||message.ordinal!==index+1||Number(message.generation)>Number(session.resumeGeneration)||(index>0&&Number(message.generation)<Number(messages[index-1]!.generation)))errors.push("normalized Message identity, cursor, ordinal, or generation is invalid");messageIds.add(id);messageIndexes.set(id,index);messageById.set(id,message);});if(session.messageCursor!==messages.length)errors.push("Session message cursor is stale");const followUps=messages.filter((message)=>message.followUpToMessageId!==null&&message.followUpToMessageId!==undefined),followUpGenerations=followUps.map((message)=>Number(message.generation));if(followUps.length!==Number(session.followUpCount)||Number(session.resumeGeneration)!==followUps.length||new Set(followUpGenerations).size!==followUps.length||followUpGenerations.some((generation,index)=>generation!==index+1)||followUps.some((message)=>{const target=text(message.followUpToMessageId),index=messageIndexes.get(text(message.id))!;return !messageIndexes.has(target)||messageIndexes.get(target)!>=index||Number(message.generation)<1||message.role!=="user";}))errors.push("follow-up Message relationship is invalid and must map one-to-one to contiguous resume generations");
  const events = Array.isArray(snapshot.events) ? snapshot.events.map(record) : [], cursors = new Set<string>();
  events.forEach((event,index)=>{if(event.sequence!==index||event.runId!==run.id||event.sessionId!==session.id)errors.push("normalized event identity or sequence is invalid");const cursor=text(event.cursor);if(cursors.has(cursor))errors.push("normalized event cursor is duplicated");cursors.add(cursor);const type=text(event.type),payload=record(event.payload),tool=text(payload.tool);if(type.startsWith("message.")&&!text(payload.messageId))errors.push("message event lacks message identity");if(type.startsWith("tool.")&&(!text(payload.toolCallId)||!tool))errors.push("tool event lacks normalized tool identity");if(type.startsWith("tool.")&&tool&&(!agentTools.has(tool)||!profileTools.has(tool)))errors.push("tool event names a tool outside the AgentVersion and selected HarnessProfile allowlists");if(type.startsWith("approval.")&&!text(payload.approvalId))errors.push("approval event lacks approval identity");if((type==="model.requested"||type==="model.usage")&&(!text(payload.requestId)||!text(payload.routeId)))errors.push("model event lacks normalized request and route identity");if((type==="artifact.created"||type==="patch.created")&&!text(payload.artifactId))errors.push("Artifact event lacks Artifact identity");if((type==="cancellation.requested"||type==="cancellation.acknowledged")&&!text(payload.cancellationId))errors.push("cancellation event lacks cancellation identity");});
  const messageEventCounts=new Map<string,number>(),messageEventIndexes=new Map<string,number>(),messageEventById=new Map<string,RecordValue>();for(const [eventIndex,event] of events.entries()){const type=text(event.type);if(!type.startsWith("message."))continue;const messageId=text(record(event.payload).messageId),message=messageById.get(messageId),role=text(message?.role),expectedType=`message.${role}`,allowedSources=harnessEventSources[expectedType];messageEventCounts.set(messageId,(messageEventCounts.get(messageId)??0)+1);if(!messageEventIndexes.has(messageId)){messageEventIndexes.set(messageId,eventIndex);messageEventById.set(messageId,event);}if(!message||type!==expectedType||!allowedSources?.has(text(event.source))||event.observedAt!==message.createdAt)errors.push("message event does not bind one exact Message role, authoritative source, and creation timestamp");}if([...messageIds].some((id)=>messageEventCounts.get(id)!==1)||[...messageEventCounts].some(([id,count])=>!messageIds.has(id)||count!==1))errors.push("normalized Message event identity is not one-to-one");
  const messagePrecedes=(ancestor:RecordValue,child:RecordValue):boolean=>{const ancestorIndex=messageIndexes.get(text(ancestor.id)),childIndex=messageIndexes.get(text(child.id)),ancestorEventIndex=messageEventIndexes.get(text(ancestor.id)),childEventIndex=messageEventIndexes.get(text(child.id)),ancestorTime=Date.parse(text(ancestor.createdAt)),childTime=Date.parse(text(child.createdAt)),ancestorEventTime=Date.parse(text(messageEventById.get(text(ancestor.id))?.observedAt)),childEventTime=Date.parse(text(messageEventById.get(text(child.id))?.observedAt));return ancestorIndex!==undefined&&childIndex!==undefined&&ancestorIndex<childIndex&&ancestorEventIndex!==undefined&&childEventIndex!==undefined&&ancestorEventIndex<childEventIndex&&Number.isFinite(ancestorTime)&&Number.isFinite(childTime)&&ancestorTime<childTime&&Number.isFinite(ancestorEventTime)&&Number.isFinite(childEventTime)&&ancestorEventTime<childEventTime;};
  if(messages.some((message,index)=>index>0&&messageEventIndexes.get(text(messages[index-1]!.id))!>=messageEventIndexes.get(text(message.id))!))errors.push("normalized Message events do not follow canonical Message ordinal");messages.forEach((message,index)=>{const parent=message.parentMessageId===null?null:messageById.get(text(message.parentMessageId));if(index===0&&message.parentMessageId!==null||index>0&&(!parent||!messagePrecedes(parent,message)))errors.push("normalized Message parent causality is invalid across ordinal, creation time, and event order");const followUpTarget=message.followUpToMessageId===null||message.followUpToMessageId===undefined?null:messageById.get(text(message.followUpToMessageId));if(message.followUpToMessageId!==null&&message.followUpToMessageId!==undefined&&(!followUpTarget||!messagePrecedes(followUpTarget,message)))errors.push("follow-up Message target does not precede the child across ordinal, creation time, and event order");});
  verifyEventCausality(events,errors,text(run.createdAt),terminal.has(text(run.status))?text(run.completedAt):null);
  const fallbackEventTypes=new Set(["model.fallback-authorized","model.fallback-decided"]),fallbackEvents=events.filter((event)=>fallbackEventTypes.has(text(event.type))),approvedFallbackRouteRequests=events.filter((event)=>{const payload=record(event.payload);return event.type==="model.requested"&&payload.routeId===approvedFallback.routeId&&payload.routeVersion===approvedFallback.routeVersion;});if(!fallback&&(fallbackEvents.length||approvedFallbackRouteRequests.length))errors.push("Run without fallback carries fallback authority events or fallback route requests");if(fallback){
    const primaryRequest=events.find((event)=>event.type==="model.requested"&&record(event.payload).requestId===proxy.requestId),primaryDecision=events.find((event)=>event.id===proxy.eventId),primary=events.find((event)=>event.id===fallback.primaryFailureEventId),approval=events.find((event)=>event.id===fallback.approvalEventId),request=events.find((event)=>event.id===fallback.requestEventId),decision=events.find((event)=>event.id===fallback.decisionEventId),primaryPayload=record(primary?.payload),approvalPayload=record(approval?.payload),requestPayload=record(request?.payload),decisionPayload=record(decision?.payload),indexes=[primaryRequest,primaryDecision,primary,approval,request,decision].map((event)=>event?events.indexOf(event):-1),fallbackRouteRequests=events.filter((event)=>{const payload=record(event.payload);return event.type==="model.requested"&&payload.routeId===fallback.fallbackRouteId&&payload.routeVersion===fallback.fallbackRouteVersion;});
    if(!primary||primary.type!=="error"||primary.source!=="proxy"||primaryPayload.requestId!==proxy.requestId||primaryPayload.routeId!==modelPolicy.routeId||primaryPayload.routeVersion!==modelPolicy.routeVersion||primaryPayload.policyId!==modelPolicy.policyId||primaryPayload.policyVersion!==modelPolicy.policyVersion)errors.push("fallback attempt lacks exact authoritative primary failure event evidence");
    if(!approval||approval.type!=="model.fallback-authorized"||approval.source!=="control-plane"||approvalPayload.routeId!==fallback.fallbackRouteId||approvalPayload.routeVersion!==fallback.fallbackRouteVersion||approvalPayload.authorizationId!==fallback.authorizationId||approvalPayload.approvalReceiptId!==fallback.approvalReceiptId||approvalPayload.policyId!==fallback.policyId||approvalPayload.policyVersion!==fallback.policyVersion)errors.push("fallback authorization event does not bind the frozen route, policy, and approval receipt");
    if(!request||request.type!=="model.requested"||request.source!=="control-plane"||requestPayload.requestId!==fallback.requestId||requestPayload.routeId!==fallback.fallbackRouteId||requestPayload.routeVersion!==fallback.fallbackRouteVersion||requestPayload.attempt!==1||requestPayload.authorizationId!==fallback.authorizationId)errors.push("fallback request event does not bind the single authorized attempt");
    if(!decision||decision.type!=="model.fallback-decided"||decision.source!=="proxy"||decisionPayload.requestId!==fallback.requestId||decisionPayload.routeId!==fallback.fallbackRouteId||decisionPayload.routeVersion!==fallback.fallbackRouteVersion||decisionPayload.authorizationId!==fallback.authorizationId||decisionPayload.receiptId!==fallback.receiptId||decisionPayload.policyId!==fallback.policyId||decisionPayload.policyVersion!==fallback.policyVersion)errors.push("fallback decision event does not bind the authoritative proxy receipt");
    if(indexes.some((index)=>index<0)||!(indexes[0]!<indexes[1]!&&indexes[1]!<indexes[2]!&&indexes[2]!<indexes[3]!&&indexes[3]!<indexes[4]!&&indexes[4]!<indexes[5]!))errors.push("fallback evidence does not follow primary request, route decision, failure, authorization, fallback request, and fallback decision ordering");
    const forbiddenEffectTypes=new Set(["patch.created","artifact.created"]),primaryRequestIndex=indexes[0]!,approvalIndex=indexes[3]!,preAuthorizationEffects=events.filter((event,index)=>{const type=text(event.type),payload=record(event.payload),resolvedMessage=type.startsWith("message.")?messageById.get(text(payload.messageId)):undefined,resolvedRole=text(resolvedMessage?.role);return index>primaryRequestIndex&&index<approvalIndex&&(type==="model.usage"&&payload.requestId===proxy.requestId||type==="model.requested"&&event!==primaryRequest||type.startsWith("tool.")||type.startsWith("approval.")||resolvedRole==="assistant"||resolvedRole==="tool"||forbiddenEffectTypes.has(type));}),primaryRequestTime=Date.parse(text(primaryRequest?.observedAt)),approvalTime=Date.parse(text(approval?.observedAt)),preAuthorizationMessages=messages.filter((message)=>{const role=text(message.role),createdAt=Date.parse(text(message.createdAt));return(role==="assistant"||role==="tool")&&Number.isFinite(createdAt)&&createdAt>=primaryRequestTime&&createdAt<=approvalTime;});
    if(preAuthorizationEffects.length||preAuthorizationMessages.length)errors.push("fallback eligibility was invalidated by primary usage, response, tool, approval, Artifact effect, or a later logical model request before authorization");
    if(fallbackEvents.length!==2||fallbackRouteRequests.length!==1||fallbackRouteRequests[0]!==request||record(fallbackRouteRequests[0]?.payload).attempt!==1)errors.push("fallback evidence does not represent exactly one requestEventId-bound attempt");
  }
  if(compatibility.compatible===true){
    const isTerminal=terminal.has(text(run.status)),resultUsage=record(record(snapshot.result).usage),requestEvents=events.filter((event)=>event.type==="model.requested"),usageEvents=events.filter((event)=>event.type==="model.usage"),proxyEvents=events.filter((event)=>event.type==="model.proxy-decided"),billingEvents=events.filter((event)=>event.type==="billing.recorded"),requestById=new Map(requestEvents.map((event)=>[text(record(event.payload).requestId),event])),proxyEvent=events.find((event)=>event.id===proxy.eventId),fallbackDecisionEvent=fallback?events.find((event)=>event.id===fallback.decisionEventId):undefined,proxyPayload=record(proxyEvent?.payload),proxyRequest=requestById.get(text(proxy.requestId)),proxyRequestPayload=record(proxyRequest?.payload),billingEvent=billingEvents[0],billingPayload=record(billingEvent?.payload),proxyKeys=["authentication","authorizationId","outcome","policyId","policyVersion","requestId","routeId","routeVersion"],billingKeys=["amountMicros","currency","mode","pricingId","pricingVersion","receiptId","source"],expectedDecisionSource=proxy.outcome==="DIRECT"?"control-plane":"proxy",expectedBillingEventSource=billing.source==="proxy-receipt"?"proxy":"control-plane";
    if(proxyEvents.length!==1||!proxyEvent||proxyEvent.type!=="model.proxy-decided"||proxyEvent.source!==expectedDecisionSource||JSON.stringify(Object.keys(proxyPayload).sort())!==JSON.stringify(proxyKeys)||proxyPayload.requestId!==proxy.requestId||proxyPayload.outcome!==proxy.outcome||proxyPayload.routeId!==proxy.routeId||proxyPayload.routeVersion!==proxy.routeVersion||proxyPayload.policyId!==proxy.policyId||proxyPayload.policyVersion!==proxy.policyVersion||proxyPayload.authentication!==proxy.authentication||proxyPayload.authorizationId!==proxy.authorizationId||!proxyRequest||proxyRequestPayload.routeId!==proxy.routeId||proxyRequestPayload.routeVersion!==proxy.routeVersion||proxyRequestPayload.routeId!==modelPolicy.routeId||proxyRequestPayload.routeVersion!==modelPolicy.routeVersion||events.indexOf(proxyRequest)>=events.indexOf(proxyEvent))errors.push("proxy decision lacks exact normalized authoritative request and event evidence");
    for(const requestEvent of requestEvents){const requestPayload=record(requestEvent.payload),isFallback=requestEvent.id===fallback?.requestEventId;if(!isFallback&&(requestPayload.routeId!==proxy.routeId||requestPayload.routeVersion!==proxy.routeVersion||requestPayload.routeId!==modelPolicy.routeId||requestPayload.routeVersion!==modelPolicy.routeVersion))errors.push("model request is outside the frozen primary route and authorized fallback");}
    if((isTerminal||billingEvents.length>0)&&(billingEvents.length!==1||!billingEvent||billingEvent.source!==expectedBillingEventSource||JSON.stringify(Object.keys(billingPayload).sort())!==JSON.stringify(billingKeys)||billingPayload.mode!==billing.mode||billingPayload.currency!==billing.currency||billingPayload.amountMicros!==billing.amountMicros||billingPayload.pricingId!==billing.pricingId||billingPayload.pricingVersion!==billing.pricingVersion||billingPayload.receiptId!==billing.receiptId||billingPayload.source!==billing.source))errors.push("billing receipt lacks exact normalized authoritative event evidence");
    const billingIndex=billingEvent?events.indexOf(billingEvent):-1,modelEvidenceEvents=events.filter((event)=>text(event.type).startsWith("model."));if(billingEvent&&modelEvidenceEvents.some((event)=>events.indexOf(event)>=billingIndex))errors.push("billing receipt precedes normalized model request, route-decision, or usage evidence");
    let inputTokens=0,outputTokens=0;for(const usageEvent of usageEvents){const usagePayload=record(usageEvent.payload),requestId=text(usagePayload.requestId),requestEvent=requestById.get(requestId),requestPayload=record(requestEvent?.payload),routeDecision=requestId===proxy.requestId?proxyEvent:requestId===fallback?.requestId?fallbackDecisionEvent:undefined,input=Number(usagePayload.inputTokens),output=Number(usagePayload.outputTokens);if(!requestEvent||events.indexOf(requestEvent)>=events.indexOf(usageEvent)||routeDecision&&events.indexOf(routeDecision)>=events.indexOf(usageEvent)||usagePayload.routeId!==requestPayload.routeId||usagePayload.routeVersion!==requestPayload.routeVersion||usagePayload.requestId===proxy.requestId&&(usagePayload.routeId!==proxy.routeId||usagePayload.routeVersion!==proxy.routeVersion||usagePayload.routeId!==modelPolicy.routeId||usagePayload.routeVersion!==modelPolicy.routeVersion)||!Number.isInteger(input)||input<0||!Number.isInteger(output)||output<0)errors.push("model usage lacks an exact earlier normalized request and authoritative route decision");inputTokens+=input;outputTokens+=output;}
    if(isTerminal&&(requestEvents.length!==Number(resultUsage.modelRequests)||inputTokens!==Number(resultUsage.inputTokens)||outputTokens!==Number(resultUsage.outputTokens)))errors.push("terminal model usage does not equal normalized request and token evidence");
  }
  if(!terminal.has(text(run.status))&&(snapshot.result!==null||events.some((event)=>event.type==="result.terminal")||run.completedAt!==undefined))errors.push("nonterminal Run carries terminal result, event, or completion state");
  if(terminal.has(text(run.status))&&(!text(run.completedAt)||Date.parse(text(run.completedAt))<Date.parse(text(run.createdAt))))errors.push("terminal Run completion time is missing or invalid");
  for(const event of events){const payload=record(event.payload);if((text(event.type).startsWith("message.")||event.type==="followup.accepted")&&!messageIds.has(text(payload.messageId)))errors.push("message event references an unresolved Message");if(event.type==="followup.accepted"&&!followUps.some((message)=>message.id===payload.messageId))errors.push("follow-up event is not bound to a follow-up Message");if(event.type==="harness.resumed"){const generation=Number(payload.generation),resumeIndex=events.indexOf(event),followUp=followUps.find((message)=>Number(message.generation)===generation),accepted=events.filter((candidate,index)=>index<resumeIndex&&candidate.type==="followup.accepted"&&record(candidate.payload).messageId===followUp?.id);if(!followUp||accepted.length!==1)errors.push("resume generation lacks one exact earlier follow-up cursor boundary");}}
  if (session.eventCursor !== (events.length?events.length-1:0)) errors.push("Session event cursor is stale");
  const acceptedEvents=events.filter((event)=>event.type==="followup.accepted"),acceptedMessageIds=acceptedEvents.map((event)=>text(record(event.payload).messageId));if(Number(session.followUpCount)!==acceptedEvents.length||new Set(acceptedMessageIds).size!==acceptedMessageIds.length||JSON.stringify([...acceptedMessageIds].sort())!==JSON.stringify(followUps.map((message)=>text(message.id)).sort())) errors.push("follow-up count is not bound one-to-one to unique accepted Message events");
  const resumeEvents=events.filter((event)=>event.type==="harness.resumed");if(Number(session.resumeGeneration)!==resumeEvents.length||resumeEvents.some((event,index)=>record(event.payload).generation!==index+1)) errors.push("resume generation is not ordered and event-bound");
  const cancellation=record(session.cancellation),cancelRequests=events.filter((event)=>event.type==="cancellation.requested"),cancelAcks=events.filter((event)=>event.type==="cancellation.acknowledged");if(cancellation.acknowledged===true&&cancellation.requested!==true)errors.push("cancellation was acknowledged without a request");if((cancellation.requested===true)!==(cancelRequests.length===1)||(cancellation.acknowledged===true)!==(cancelAcks.length===1))errors.push("cancellation state is not bound to one request and acknowledgement");if(cancelAcks.length===1&&cancelRequests.length===1&&(record(cancelAcks[0]!.payload).cancellationId!==record(cancelRequests[0]!.payload).cancellationId||events.indexOf(cancelRequests[0]!)>=events.indexOf(cancelAcks[0]!)))errors.push("cancellation acknowledgement does not match and follow its request");if(cancellation.acknowledged===true&&run.status!=="cancelled"&&run.status!=="recovery_required")errors.push("acknowledged cancellation must end cancelled or recovery_required");if(run.status==="cancelled"&&(cancellation.acknowledged!==true||cancellation.processTreeTerminated!==true||cancellation.cleanupComplete!==true||cancellation.credentialsRevoked!==true||cancellation.artifactsHandled!==true))errors.push("cancelled Run lacks acknowledged termination, credential revocation, Artifact handling, and cleanup");if(compatibility.compatible===true&&run.status==="succeeded"&&(cancellation.requested!==false||cancellation.acknowledged!==false||cancellation.processTreeTerminated!==false||cancellation.cleanupComplete!==true||cancellation.credentialsRevoked!==true||cancellation.artifactsHandled!==true))errors.push("successful Run carries cancellation claims or incomplete credential, Artifact, and cleanup evidence");
  if(run.status==="succeeded"){const result=record(snapshot.result),resolved=Array.isArray(result.artifacts)?result.artifacts.map(record):[],patchArtifact=resolved.find((artifact)=>artifact.role==="patch");if(!patchArtifact||result.patchArtifactId!==patchArtifact.id)errors.push("successful Run patchArtifactId must equal the resolved patch Artifact");}
  if (terminal.has(text(run.status))) { const result=record(snapshot.result),last=events.at(-1),terminalEvents=events.filter((event)=>event.type==="result.terminal"); if(result.status!==run.status||last?.type!=="result.terminal"||terminalEvents.length!==1||record(last?.payload).status!==run.status)errors.push("terminal Run result or event is incoherent");if(Number(record(result.usage).durationMs)!==Date.parse(text(run.completedAt))-Date.parse(text(run.createdAt)))errors.push("terminal Run duration does not match authoritative lifecycle time");if(leases.some((lease)=>Date.parse(text(lease.revokedAt))>Date.parse(text(run.completedAt))))errors.push("terminal Run completed before credential revocation");const artifactIds=new Set(strings(result.artifactIds)),resolved=Array.isArray(result.artifacts)?result.artifacts.map(record):[],resolvedIds=new Set(resolved.map((item)=>text(item.id))),roles=new Set<string>(),digests=new Set<string>();if(JSON.stringify([...artifactIds].sort())!==JSON.stringify([...resolvedIds].sort())||resolved.length!==resolvedIds.size)errors.push("result Artifacts are not resolved exactly");for(const artifact of resolved){const role=text(artifact.role),digest=text(artifact.contentDigest);if(roles.has(role)||digests.has(digest)||artifact.workspaceId!==run.workspaceId||artifact.projectId!==run.projectId||!/^sha256:[0-9a-f]{64}$/.test(digest))errors.push("result Artifact role, tenant, or content identity is invalid");roles.add(role);digests.add(digest);const expected=role==="patch"?["agent.patch","text/x-diff"]:role==="summary"?["agent.summary","text/markdown"]:["agent.output","application/octet-stream"];if(artifact.kind!==expected[0]||artifact.mediaType!==expected[1])errors.push("result Artifact role has wrong kind or media type");const expectedEvent=role==="patch"?"patch.created":"artifact.created";if(!events.some((event)=>event.type===expectedEvent&&record(event.payload).artifactId===artifact.id))errors.push("resolved result Artifact lacks its normalized creation event");}if(run.status==="succeeded"){const output=record(agentVersion.outputContract),mandatory=new Set<string>(strings(output.artifacts));if(output.patch===true)mandatory.add("patch");if(output.summary===true)mandatory.add("summary");if(JSON.stringify([...mandatory].sort())!==JSON.stringify([...roles].sort()))errors.push("successful Run does not resolve every mandatory AgentVersion output role exactly");}if(result.patchArtifactId!==null&&(!artifactIds.has(text(result.patchArtifactId))||!resolved.some((artifact)=>artifact.id===result.patchArtifactId&&artifact.role==="patch")))errors.push("patch result is absent from resolved patch Artifact");if(result.receiptDigest!==harnessTerminalReceiptDigest(snapshot))errors.push("terminal Run receipt semantic digest is invalid"); }
  return errors;
}

export function verifyPortableEvaluation(value: unknown,bundleValue:unknown,agentValue:unknown): string[] {
  const errors=harnessSecretViolations(value), root=record(value), required=["discover-capabilities","reject-capability-mismatch-before-sandbox","prepare-no-raw-credentials","one-shot","follow-up","resume","tool-and-approval-events","graceful-cancel-process-tree","terminal-result-artifacts","cleanup-no-secrets"], cases=new Set(strings(root.cases)), result=record(root.result), results=Array.isArray(result.caseResults)?result.caseResults.map(record):[],resolved=record(root.resolvedHarness),evaluation=record(root.portableEvaluation),receipt=record(result.runReceipt);
  for(const name of required)if(!cases.has(name)||!results.some((item)=>item.case===name&&item.passed===true))errors.push(`portable evaluation did not pass ${name}`);
  const agentRoot=record(agentValue),agent=record(agentRoot.version),workspaceId=text(agent.workspaceId),declared=new Set(strings(result.artifactIds)),artifacts=Array.isArray(result.evidenceArtifacts)?result.evidenceArtifacts.map(record):[],ids=new Set<string>(),roles=new Set<string>(),digests=new Set<string>();for(const artifact of artifacts){const id=text(artifact.id),role=text(artifact.role),digest=text(artifact.contentDigest);if(ids.has(id)||roles.has(role)||digests.has(digest)||artifact.workspaceId!==workspaceId||artifact.kind!=="harness.conformance"||artifact.mediaType!=="application/vnd.blazn.harness-conformance+json"||!/^sha256:[0-9a-f]{64}$/.test(digest))errors.push("portable evaluation evidence identity or workspace is invalid");ids.add(id);roles.add(role);digests.add(digest);}for(const item of results)if(!declared.has(text(item.evidenceArtifactId))||!artifacts.some((artifact)=>artifact.id===item.evidenceArtifactId&&artifact.role===item.case))errors.push("conformance result references undeclared or wrong-role evidence");if(JSON.stringify([...declared].sort())!==JSON.stringify([...ids].sort()))errors.push("portable evaluation evidence set is not exact");
  if(receipt.runId!==result.runId||receipt.receiptDigest!==result.receiptDigest||receipt.agentVersionId!==evaluation.agentVersionId||receipt.agentVersionDigest!==evaluation.agentVersionDigest||receipt.sourceRepository!==evaluation.sourceRepository||receipt.sourceCommit!==evaluation.sourceCommit||receipt.templateVersionId!==evaluation.templateVersionId||receipt.templateDigest!==evaluation.templateDigest||receipt.taskDigest!==evaluation.taskDigest||receipt.resultDigest!==portableResultDigest(root))errors.push("portable evaluation Run receipt does not bind the exact Agent, source, template, task, and result");
  const bundle=record(bundleValue),definition=record(bundle.definition),version=record(bundle.version),profile=record(bundle.profile);errors.push(...verifyHarnessBundle(bundle),...verifySelectedProfileCompatibility(agent,bundle));if(root.adapterKind!==definition.kind||root.harnessVersionId!==version.id||root.profileId!==profile.id||record(resolved.definition).id!==definition.id||record(resolved.definition).kind!==definition.kind||record(resolved.definition).resourceVersion!==definition.resourceVersion||record(resolved.version).id!==version.id||record(resolved.version).digest!==version.digest||record(resolved.profile).id!==profile.id||record(resolved.profile).digest!==profile.digest||record(resolved.profile).workspaceId!==profile.workspaceId||receipt.harnessVersionId!==version.id||receipt.harnessVersionDigest!==version.digest||receipt.profileId!==profile.id||receipt.profileDigest!==profile.digest)errors.push("portable evaluation does not resolve the exact Harness definition, version, and profile");
  if(agent.digest!==agentVersionDigest(agent)||!allowedProfileRefs(agent).some((item)=>item.id===profile.id&&item.digest===profile.digest)||profile.workspaceId!==workspaceId||root.workspaceId!==workspaceId||receipt.workspaceId!==workspaceId||evaluation.id!==agent.evaluationId||evaluation.agentVersionId!==agent.id||evaluation.agentVersionDigest!==agent.digest||evaluation.sourceRepository!==record(agent.repository).url||evaluation.sourceCommit!==record(agent.repository).commit||evaluation.templateVersionId!==record(agent.template).versionId||evaluation.templateDigest!==record(agent.template).digest)errors.push("portable evaluation differs from the authoritative portable AgentVersion or workspace");
  if(result.passed!==true||results.some((item)=>item.passed!==true))errors.push("portable evaluation is not fully passing");
  return errors;
}
export function verifyPortableParity(values:unknown[],bundleValues:unknown[],agentValue:unknown):string[]{const errors:string[]=verifyAgentCompatibility(agentValue,bundleValues),roots=values.map(record),bundles=bundleValues.map(record),kinds=new Set(roots.map((value)=>text(value.adapterKind))),parity=new Set(roots.map((value)=>text(record(value.result).parityGroupId))),runs=new Set<string>(),receipts=new Set<string>(),evidenceIds=new Set<string>(),evidenceDigests=new Set<string>(),identities=new Set(roots.map((value)=>{const evaluation=record(value.portableEvaluation);return canonical({id:evaluation.id,version:evaluation.version,agentVersionId:evaluation.agentVersionId,agentVersionDigest:evaluation.agentVersionDigest,sourceRepository:evaluation.sourceRepository,sourceCommit:evaluation.sourceCommit,templateVersionId:evaluation.templateVersionId,templateDigest:evaluation.templateDigest,taskDigest:evaluation.taskDigest,assertions:evaluation.assertions});})),roleSets=new Set(roots.map((value)=>canonical((Array.isArray(record(value.result).evidenceArtifacts)?record(value.result).evidenceArtifacts as unknown[]:[]).map((item)=>text(record(item).role)).sort())));if(roots.length!==4||bundles.length!==4)errors.push("portable parity requires exactly four resolved adapters");for(const value of roots){const matching=bundles.find((bundle)=>record(bundle.definition).kind===value.adapterKind);if(!matching)errors.push("portable parity lacks resolved Harness inputs");else errors.push(...verifyPortableEvaluation(value,matching,agentValue));const result=record(value.result),run=text(result.runId),receipt=text(result.receiptDigest);if(runs.has(run)||receipts.has(receipt))errors.push("portable parity reused a Run or terminal receipt");runs.add(run);receipts.add(receipt);for(const raw of Array.isArray(result.evidenceArtifacts)?result.evidenceArtifacts:[]){const artifact=record(raw),id=text(artifact.id),digest=text(artifact.contentDigest);if(evidenceIds.has(id)||evidenceDigests.has(digest))errors.push("portable parity reused evidence identity or content");evidenceIds.add(id);evidenceDigests.add(digest);}}if(kinds.size!==4||!["hermes","codex-cli","claude-code","generic-cli"].every((kind)=>kinds.has(kind))||parity.size!==1||identities.size!==1||roleSets.size!==1)errors.push("portable parity did not preserve one evaluation and evidence role set across all four adapters");return errors;}
