import { createHash } from "node:crypto";
type RecordValue = Record<string, unknown>;
const capabilities = new Set(["task.one-shot","message.follow-up","conversation.resume","event.structured","event.streaming","tool.native","tool.mcp","output.patch","output.artifact","checkpoint.recovery","model.select","provider.configure","approval.prompt","cancel.graceful"]);
const secretKeys = new Set(["token","apitoken","authtoken","sessiontoken","accesstoken","refreshtoken","password","secret","credential","authorization","apikey","privatekey","kubeconfig","nodecredential","bearertoken","clientsecret"]);
const terminal = new Set(["succeeded","failed","cancelled","timed_out","recovery_required"]);
const record = (value: unknown): RecordValue => value !== null && typeof value === "object" && !Array.isArray(value) ? value as RecordValue : {};
const text = (value: unknown): string => typeof value === "string" ? value : "";
const strings = (value: unknown): string[] => Array.isArray(value) && value.every((item) => typeof item === "string") ? value : [];
const normalizedKey = (value: string): string => value.toLowerCase().replace(/[^a-z0-9]/g, "");
function canonical(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;const item=value as RecordValue;return`{${Object.keys(item).sort().map((key)=>`${JSON.stringify(key)}:${canonical(item[key])}`).join(",")}}`;}
function semanticDigest(domain:string,value:unknown):string{return`sha256:${createHash("sha256").update(`${domain}\n${canonical(value)}`).digest("hex")}`;}
function without(value:unknown,...keys:string[]):RecordValue{const copy={...record(value)};for(const key of keys)delete copy[key];return copy;}
export const agentVersionDigest=(value:unknown)=>semanticDigest("blazn-agent-version-v1",without(value,"digest"));
export const harnessVersionDigest=(value:unknown)=>semanticDigest("blazn-harness-version-v1",without(value,"digest"));
export const harnessProfileDigest=(value:unknown)=>semanticDigest("blazn-harness-profile-v1",without(value,"digest","resourceVersion"));
export function harnessTerminalReceiptDigest(value:unknown):string{const snapshot=record(value),result=without(snapshot.result,"receiptDigest");return semanticDigest("blazn-harness-terminal-receipt-v1",{run:snapshot.run,session:snapshot.session,provenance:snapshot.provenance,compatibility:snapshot.compatibility,credentialLeases:snapshot.credentialLeases,messages:snapshot.messages,events:snapshot.events,result});}
export function portableResultDigest(value:unknown):string{const result=record(record(value).result);return semanticDigest("blazn-portable-evaluation-result-v1",{caseResults:result.caseResults,evidenceArtifacts:result.evidenceArtifacts});}

export function harnessSecretViolations(value: unknown, path = "$", output: string[] = []): string[] {
  if (Array.isArray(value)) value.forEach((item, index) => harnessSecretViolations(item, `${path}[${index}]`, output));
  else if (value !== null && typeof value === "object") for (const [key, child] of Object.entries(value as RecordValue)) {
    if (secretKeys.has(normalizedKey(key))) output.push(`${path}.${key} is a forbidden raw credential field`);
    harnessSecretViolations(child, `${path}.${key}`, output);
  } else if (typeof value === "string" && (/\bBearer\s+[A-Za-z0-9._~-]{8,}/i.test(value) || /(?:api[_-]?key|token|password|secret|authorization)\s*[:=]\s*\S+/i.test(value) || /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(value) || /:\/\/[^/\s]+@/.test(value))) output.push(`${path} contains credential-like material`);
  return output;
}

export function verifyHarnessBundle(value: unknown): string[] {
  const errors = harnessSecretViolations(value), bundle = record(value), definition = record(bundle.definition), version = record(bundle.version), profile = record(bundle.profile);
  if (version.definitionId !== definition.id) errors.push("HarnessVersion does not belong to HarnessDefinition");
  if(version.digest!==harnessVersionDigest(version))errors.push("HarnessVersion semantic digest is invalid");
  if(profile.digest!==harnessProfileDigest(profile))errors.push("HarnessProfile semantic digest is invalid");
  if (profile.harnessVersionId !== version.id) errors.push("HarnessProfile does not select HarnessVersion");
  if (definition.status !== "approved" || profile.status !== "approved") errors.push("Harness definition and profile must be approved");
  const available = strings(version.capabilities);
  if (available.some((item) => !capabilities.has(item))) errors.push("HarnessVersion contains an unknown capability");
  const credentialCapabilities = new Set(strings(version.credentialCapabilities));
  for (const raw of Array.isArray(profile.credentials) ? profile.credentials : []) { const credential=record(raw),capability=text(credential.capability),scope=text(credential.scope),prefix=capability.startsWith("model.")?"route:":capability==="repository.read"?"repo:":"tool:";if(!credentialCapabilities.has(capability))errors.push("HarnessProfile requests an undeclared credential capability");if(!scope.startsWith(prefix))errors.push("HarnessProfile credential scope does not match its capability"); }
  const proxyProtocols = new Set(strings(record(version.compatibility).proxyProtocols));
  if (!proxyProtocols.has(text(record(profile.model).protocol))) errors.push("HarnessProfile model protocol is unsupported");
  const executable = record(version.executable), argv = strings(executable.fixedArgv);
  if (!text(executable.path).startsWith("/") || argv.some((arg) => /(?:^|[=\s])(?:token|password|secret|authorization|api[_-]?key)(?:[=:]|$)/i.test(decode(arg)))) errors.push("Harness executable contract is unsafe");
  for(const override of Object.values(record(profile.overrides)))if(typeof override==="string"&&/^[A-Za-z0-9_-]{32,}$/.test(override))errors.push("HarnessProfile override resembles raw credential material");
  return errors;
}

function decode(value: string): string { let current=value; for(let i=0;i<3;i++){try{const next=decodeURIComponent(current);if(next===current)break;current=next;}catch{break;}}return current; }
function repositoryScope(value:unknown):string{try{const url=new URL(text(value));return`repo:${url.pathname.replace(/^\//,"").replace(/\.git$/,"")}`;}catch{return"";}}
function credentialIdentity(value:unknown):string{const item=record(value);return`${text(item.capability)}|${text(item.scope)}`;}

export function verifyAgentCompatibility(agentValue: unknown, bundles: unknown[]): string[] {
  const errors: string[] = harnessSecretViolations(agentValue), root = record(agentValue), agent = record(root.agent), version = record(root.version);
  if (agent.currentVersionId !== version.id || agent.id !== version.agentId || agent.workspaceId !== version.workspaceId) errors.push("Agent and immutable AgentVersion identity mismatch");
  if(version.digest!==agentVersionDigest(version))errors.push("AgentVersion semantic digest is invalid");
  const allowed = new Set(strings(version.allowedHarnessProfileIds));
  if (!allowed.has(text(version.defaultHarnessProfileId))) errors.push("default HarnessProfile is not allowed");
  const suppliedProfiles=bundles.map((item)=>text(record(record(item).profile).id));
  if(suppliedProfiles.length!==new Set(suppliedProfiles).size||JSON.stringify([...new Set(suppliedProfiles)].sort())!==JSON.stringify([...allowed].sort()))errors.push("Agent publication did not validate every allowed HarnessProfile exactly once");
  for (const raw of bundles) {
    errors.push(...verifyHarnessBundle(raw));
    const bundle = record(raw), profile = record(bundle.profile), harnessVersion = record(bundle.version);
    if (!allowed.has(text(profile.id))) { errors.push("HarnessProfile is not allowed by AgentVersion"); continue; }
    if (profile.workspaceId !== version.workspaceId) errors.push("HarnessProfile is outside Agent workspace");
    const definitionPlatforms=new Set(strings(record(bundle.definition).supportedPlatforms));if(strings(harnessVersion.supportedPlatforms).some((platform)=>!definitionPlatforms.has(platform)))errors.push("HarnessVersion platform exceeds HarnessDefinition");
    const available = new Set(strings(harnessVersion.capabilities));
    const missing = strings(version.requiredCapabilities).filter((item) => !available.has(item));
    if (missing.length) errors.push(`HarnessProfile ${text(profile.id)} is missing capabilities: ${missing.join(",")}`);
    if (record(profile.model).routeId !== record(version.modelPolicy).routeId || record(profile.model).routeVersion !== record(version.modelPolicy).routeVersion) errors.push("HarnessProfile model route does not match AgentVersion");
    if (!strings(record(version.modelPolicy).requiredProtocols).includes(text(record(profile.model).protocol))) errors.push("HarnessProfile model protocol is not allowed by AgentVersion");
    const agentTools=new Set(strings(version.tools)),profileTools=new Set(strings(profile.tools));if(JSON.stringify([...agentTools].sort())!==JSON.stringify([...profileTools].sort()))errors.push("HarnessProfile tools do not exactly match AgentVersion tools");
    const expectedModelScope=`route:${text(record(version.modelPolicy).routeId)}:${String(record(version.modelPolicy).routeVersion)}`,expectedRepositoryScope=repositoryScope(record(version.repository).url);
    for(const rawCredential of Array.isArray(profile.credentials)?profile.credentials:[]){const credential=record(rawCredential),capability=text(credential.capability),scope=text(credential.scope);if(capability.startsWith("model.")&&scope!==expectedModelScope)errors.push("HarnessProfile model credential is not bound to Agent model route");if(capability==="repository.read"&&scope!==expectedRepositoryScope)errors.push("HarnessProfile repository credential is not bound to Agent repository");if(capability==="tool.mcp"&&(!scope.startsWith("tool:")||!agentTools.has(scope.slice(5))))errors.push("HarnessProfile tool credential is not bound to Agent tools");}
  }
  return errors;
}

export function verifyHarnessRun(agentValue: unknown, bundleValue: unknown, runValue: unknown): string[] {
  const errors = harnessSecretViolations(runValue), agentVersion = record(record(agentValue).version), bundle = record(bundleValue), profile = record(bundle.profile), harnessVersion = record(bundle.version), snapshot = record(runValue), run = record(snapshot.run), session = record(snapshot.session), provenance = record(snapshot.provenance), compatibility = record(snapshot.compatibility);
  if (run.agentVersionId !== agentVersion.id || run.harnessProfileId !== profile.id || run.harnessVersionId !== harnessVersion.id) errors.push("Run does not capture exact AgentVersion and Harness identities");
  if (run.workspaceId !== agentVersion.workspaceId || profile.workspaceId !== run.workspaceId) errors.push("Run resources cross a workspace boundary");
  if (record(provenance.agentVersion).id !== agentVersion.id || record(provenance.agentVersion).digest !== agentVersion.digest || record(provenance.harnessVersion).id !== harnessVersion.id || record(provenance.harnessVersion).digest !== harnessVersion.digest || record(provenance.harnessProfile).id !== profile.id || record(provenance.harnessProfile).digest !== profile.digest) errors.push("Run provenance does not bind immutable Agent and Harness versions");
  if (record(provenance.sandboxTemplateVersion).id !== record(agentVersion.template).versionId || record(provenance.sandboxTemplateVersion).digest !== record(agentVersion.template).digest || record(provenance.modelRoute).id !== record(agentVersion.modelPolicy).routeId || record(provenance.modelRoute).version !== record(agentVersion.modelPolicy).routeVersion || record(provenance.modelRoute).protocol!==record(profile.model).protocol) errors.push("Run provenance does not bind exact template and model route");
  if (record(provenance.source).repository !== record(agentVersion.repository).url || record(provenance.source).commit !== record(agentVersion.repository).commit) errors.push("Run source provenance differs from AgentVersion");
  const proxy=provenance.proxyDecision===null?{}:record(provenance.proxyDecision),modelPolicy=record(agentVersion.modelPolicy);if(compatibility.compatible===true&&(proxy.authentication!=="proxy-workload-proof"||proxy.routeId!==modelPolicy.routeId||proxy.routeVersion!==modelPolicy.routeVersion||proxy.policyId!==modelPolicy.policyId||proxy.policyVersion!==modelPolicy.policyVersion||!text(proxy.requestId)||!text(proxy.eventId)))errors.push("proxy decision does not bind exact authenticated route and policy");
  const required = new Set(strings(compatibility.required)), available = new Set(strings(compatibility.available)), missing = strings(compatibility.missing), computedMissing = [...required].filter((item) => !available.has(item)).sort();
  if (JSON.stringify([...missing].sort()) !== JSON.stringify(computedMissing) || compatibility.compatible !== (computedMissing.length === 0)) errors.push("capability compatibility result is inconsistent");
  if(JSON.stringify([...required].sort())!==JSON.stringify(strings(agentVersion.requiredCapabilities).sort())||JSON.stringify([...available].sort())!==JSON.stringify(strings(harnessVersion.capabilities).sort()))errors.push("compatibility did not compare the exact Agent and Harness capability sets");
  if (compatibility.checkedBeforeSandbox !== true || (compatibility.compatible === false && (run.sandboxId !== null || provenance.node !== null || provenance.proxyDecision !== null))) errors.push("capability mismatch did not fail before Sandbox allocation");
  const declarations=Array.isArray(profile.credentials)?profile.credentials.map(record):[],declaredCredentials=new Set(declarations.map(credentialIdentity)),leases=Array.isArray(snapshot.credentialLeases)?snapshot.credentialLeases.map(record):[],leaseIdentities=new Set(leases.map(credentialIdentity));if(JSON.stringify([...declaredCredentials].sort())!==JSON.stringify([...leaseIdentities].sort())||leases.length!==leaseIdentities.size)errors.push("credential leases do not exactly match HarnessProfile capabilities and scopes");for(const lease of leases){const declaration=declarations.find((item)=>credentialIdentity(item)===credentialIdentity(lease)),ttl=(Date.parse(text(lease.expiresAt))-Date.parse(text(lease.issuedAt)))/1000;if(!declaration||ttl!==declaration.leaseSeconds)errors.push("credential lease lifetime differs from HarnessProfile");}if(terminal.has(text(run.status))&&leases.some((lease)=>lease.status!=="revoked"||!text(lease.revokedAt)))errors.push("terminal Run retained a credential lease");
  const messages=Array.isArray(snapshot.messages)?snapshot.messages.map(record):[],messageIds=new Set<string>();messages.forEach((message,index)=>{const id=text(message.id);if(!id||messageIds.has(id)||message.runId!==run.id||message.sessionId!==session.id||message.conversationId!==session.conversationId||message.ordinal!==index+1||Number(message.generation)>Number(session.resumeGeneration))errors.push("normalized Message identity, cursor, or generation is invalid");messageIds.add(id);if(index>0&&message.parentMessageId!==messages[index-1]!.id)errors.push("normalized Message parent chain is invalid");});if(messages.length&&session.messageCursor!==messages.length)errors.push("Session message cursor is stale");const followUps=messages.filter((message)=>message.followUpToMessageId!==null&&message.followUpToMessageId!==undefined);if(followUps.length!==Number(session.followUpCount)||followUps.some((message)=>!messageIds.has(text(message.followUpToMessageId))||Number(message.generation)<1))errors.push("follow-up Message relationship is invalid");
  const events = Array.isArray(snapshot.events) ? snapshot.events.map(record) : [], cursors = new Set<string>();
  events.forEach((event,index)=>{if(event.sequence!==index||event.runId!==run.id||event.sessionId!==session.id)errors.push("normalized event identity or sequence is invalid");const cursor=text(event.cursor);if(cursors.has(cursor))errors.push("normalized event cursor is duplicated");cursors.add(cursor);const type=text(event.type),payload=record(event.payload);if(type.startsWith("message.")&&!text(payload.messageId))errors.push("message event lacks message identity");if(type.startsWith("tool.")&&(!text(payload.toolCallId)||!text(payload.tool)))errors.push("tool event lacks normalized tool identity");if(type.startsWith("approval.")&&!text(payload.approvalId))errors.push("approval event lacks approval identity");if((type==="artifact.created"||type==="patch.created")&&!text(payload.artifactId))errors.push("Artifact event lacks Artifact identity");if((type==="cancellation.requested"||type==="cancellation.acknowledged")&&!text(payload.cancellationId))errors.push("cancellation event lacks cancellation identity");});
  for(const event of events){const payload=record(event.payload);if((text(event.type).startsWith("message.")||event.type==="followup.accepted")&&!messageIds.has(text(payload.messageId)))errors.push("message event references an unresolved Message");if(event.type==="followup.accepted"&&!followUps.some((message)=>message.id===payload.messageId))errors.push("follow-up event is not bound to a follow-up Message");if(event.type==="harness.resumed"&&payload.generation!==session.resumeGeneration)errors.push("resume event generation differs from Session");}
  if (events.length && session.eventCursor !== events.length-1) errors.push("Session event cursor is stale");
  if (Number(session.followUpCount)!==events.filter((event)=>event.type==="followup.accepted").length) errors.push("follow-up count is not event-bound");
  if (Number(session.resumeGeneration)!==events.filter((event)=>event.type==="harness.resumed").length) errors.push("resume generation is not event-bound");
  const cancellation=record(session.cancellation);if(cancellation.acknowledged===true&&cancellation.requested!==true)errors.push("cancellation was acknowledged without a request");if(cancellation.requested===true&&!events.some((event)=>event.type==="cancellation.requested"))errors.push("cancellation request is not event-bound");if(cancellation.acknowledged===true&&!events.some((event)=>event.type==="cancellation.acknowledged"))errors.push("cancellation acknowledgement is not event-bound");if(run.status==="cancelled"&&(cancellation.acknowledged!==true||cancellation.processTreeTerminated!==true||cancellation.cleanupComplete!==true||cancellation.credentialsRevoked!==true||cancellation.artifactsHandled!==true))errors.push("cancelled Run lacks acknowledged termination, credential revocation, Artifact handling, and cleanup");
  if (terminal.has(text(run.status))) { const result=record(snapshot.result),last=events.at(-1); if(result.status!==run.status||last?.type!=="result.terminal"||record(last?.payload).status!==run.status)errors.push("terminal Run result or event is incoherent");const artifactIds=new Set(strings(result.artifactIds)),resolved=Array.isArray(result.artifacts)?result.artifacts.map(record):[],resolvedIds=new Set(resolved.map((item)=>text(item.id))),roles=new Set<string>(),digests=new Set<string>();if(JSON.stringify([...artifactIds].sort())!==JSON.stringify([...resolvedIds].sort())||resolved.length!==resolvedIds.size)errors.push("result Artifacts are not resolved exactly");for(const artifact of resolved){const role=text(artifact.role),digest=text(artifact.contentDigest);if(roles.has(role)||digests.has(digest)||artifact.workspaceId!==run.workspaceId||artifact.projectId!==run.projectId||!/^sha256:[0-9a-f]{64}$/.test(digest))errors.push("result Artifact role, tenant, or content identity is invalid");roles.add(role);digests.add(digest);const expected=role==="patch"?["agent.patch","text/x-diff"]:role==="summary"?["agent.summary","text/markdown"]:["agent.output","application/octet-stream"];if(artifact.kind!==expected[0]||artifact.mediaType!==expected[1])errors.push("result Artifact role has wrong kind or media type");}if(result.patchArtifactId!==null&&(!artifactIds.has(text(result.patchArtifactId))||!resolved.some((artifact)=>artifact.id===result.patchArtifactId&&artifact.role==="patch")))errors.push("patch result is absent from resolved patch Artifact");if(result.receiptDigest!==harnessTerminalReceiptDigest(snapshot))errors.push("terminal Run receipt semantic digest is invalid"); }
  return errors;
}

export function verifyPortableEvaluation(value: unknown,bundleValue?:unknown,agentValue?:unknown): string[] {
  const errors=harnessSecretViolations(value), root=record(value), required=["discover-capabilities","reject-capability-mismatch-before-sandbox","prepare-no-raw-credentials","one-shot","follow-up","resume","tool-and-approval-events","graceful-cancel-process-tree","terminal-result-artifacts","cleanup-no-secrets"], cases=new Set(strings(root.cases)), result=record(root.result), results=Array.isArray(result.caseResults)?result.caseResults.map(record):[],resolved=record(root.resolvedHarness),evaluation=record(root.portableEvaluation),receipt=record(result.runReceipt);
  for(const name of required)if(!cases.has(name)||!results.some((item)=>item.case===name&&item.passed===true))errors.push(`portable evaluation did not pass ${name}`);
  const declared=new Set(strings(result.artifactIds)),artifacts=Array.isArray(result.evidenceArtifacts)?result.evidenceArtifacts.map(record):[],ids=new Set<string>(),roles=new Set<string>(),digests=new Set<string>();for(const artifact of artifacts){const id=text(artifact.id),role=text(artifact.role),digest=text(artifact.contentDigest);if(ids.has(id)||roles.has(role)||digests.has(digest)||artifact.kind!=="harness.conformance"||artifact.mediaType!=="application/vnd.blazn.harness-conformance+json"||!/^sha256:[0-9a-f]{64}$/.test(digest))errors.push("portable evaluation evidence identity is invalid");ids.add(id);roles.add(role);digests.add(digest);}for(const item of results)if(!declared.has(text(item.evidenceArtifactId))||!artifacts.some((artifact)=>artifact.id===item.evidenceArtifactId&&artifact.role===item.case))errors.push("conformance result references undeclared or wrong-role evidence");if(JSON.stringify([...declared].sort())!==JSON.stringify([...ids].sort()))errors.push("portable evaluation evidence set is not exact");
  if(receipt.runId!==result.runId||receipt.receiptDigest!==result.receiptDigest||receipt.agentVersionId!==evaluation.agentVersionId||receipt.agentVersionDigest!==evaluation.agentVersionDigest||receipt.sourceRepository!==evaluation.sourceRepository||receipt.sourceCommit!==evaluation.sourceCommit||receipt.templateVersionId!==evaluation.templateVersionId||receipt.templateDigest!==evaluation.templateDigest||receipt.taskDigest!==evaluation.taskDigest||receipt.resultDigest!==portableResultDigest(root))errors.push("portable evaluation Run receipt does not bind the exact Agent, source, template, task, and result");
  if(bundleValue){const bundle=record(bundleValue),definition=record(bundle.definition),version=record(bundle.version),profile=record(bundle.profile);if(record(resolved.definition).id!==definition.id||record(resolved.definition).kind!==definition.kind||record(resolved.definition).resourceVersion!==definition.resourceVersion||record(resolved.version).id!==version.id||record(resolved.version).digest!==version.digest||record(resolved.profile).id!==profile.id||record(resolved.profile).digest!==profile.digest||record(resolved.profile).workspaceId!==profile.workspaceId||receipt.harnessVersionId!==version.id||receipt.harnessVersionDigest!==version.digest||receipt.profileId!==profile.id||receipt.profileDigest!==profile.digest)errors.push("portable evaluation does not resolve the exact Harness definition, version, and profile");}
  if(agentValue){const agent=record(record(agentValue).version);if(evaluation.agentVersionId!==agent.id||evaluation.agentVersionDigest!==agent.digest||evaluation.sourceRepository!==record(agent.repository).url||evaluation.sourceCommit!==record(agent.repository).commit||evaluation.templateVersionId!==record(agent.template).versionId||evaluation.templateDigest!==record(agent.template).digest)errors.push("portable evaluation differs from the portable AgentVersion");}
  if(result.passed!==true||results.some((item)=>item.passed!==true))errors.push("portable evaluation is not fully passing");
  return errors;
}
export function verifyPortableParity(values:unknown[]):string[]{const errors:string[]=[],roots=values.map(record),kinds=new Set(roots.map((value)=>text(value.adapterKind))),parity=new Set(roots.map((value)=>text(record(value.result).parityGroupId))),runs=new Set<string>(),receipts=new Set<string>(),evidenceIds=new Set<string>(),evidenceDigests=new Set<string>(),identities=new Set(roots.map((value)=>{const evaluation=record(value.portableEvaluation);return canonical({id:evaluation.id,version:evaluation.version,agentVersionId:evaluation.agentVersionId,agentVersionDigest:evaluation.agentVersionDigest,sourceRepository:evaluation.sourceRepository,sourceCommit:evaluation.sourceCommit,templateVersionId:evaluation.templateVersionId,templateDigest:evaluation.templateDigest,taskDigest:evaluation.taskDigest,assertions:evaluation.assertions});})),roleSets=new Set(roots.map((value)=>canonical((Array.isArray(record(value.result).evidenceArtifacts)?record(value.result).evidenceArtifacts as unknown[]:[]).map((item)=>text(record(item).role)).sort())));for(const value of roots){const result=record(value.result),run=text(result.runId),receipt=text(result.receiptDigest);if(runs.has(run)||receipts.has(receipt))errors.push("portable parity reused a Run or terminal receipt");runs.add(run);receipts.add(receipt);for(const raw of Array.isArray(result.evidenceArtifacts)?result.evidenceArtifacts:[]){const artifact=record(raw),id=text(artifact.id),digest=text(artifact.contentDigest);if(evidenceIds.has(id)||evidenceDigests.has(digest))errors.push("portable parity reused evidence identity or content");evidenceIds.add(id);evidenceDigests.add(digest);}}if(kinds.size!==4||!["hermes","codex-cli","claude-code","generic-cli"].every((kind)=>kinds.has(kind))||parity.size!==1||identities.size!==1||roleSets.size!==1)errors.push("portable parity did not preserve one evaluation and evidence role set across all four adapters");return errors;}
