import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { Ajv2020 } from "ajv/dist/2020.js";
import type { FormatsPlugin } from "ajv-formats";
import { agentVersionDigest, harnessProfileDigest, harnessSecretViolations, harnessTerminalReceiptDigest, harnessVersionDigest, portableResultDigest, verifyAgentCompatibility, verifyHarnessBundle, verifyHarnessRun, verifyPortableEvaluation, verifyPortableParity } from "./harness-contract.js";

const here=path.dirname(fileURLToPath(import.meta.url)),contracts=path.resolve(here,"../../../packages/contracts"),fixtures=path.join(contracts,"testdata/harness");
const require=createRequire(import.meta.url),formatsModule=require("ajv-formats") as {default?:FormatsPlugin}|FormatsPlugin,addFormats=("default" in formatsModule?formatsModule.default:formatsModule) as FormatsPlugin;
const json=async(file:string)=>JSON.parse(await readFile(file,"utf8")) as Record<string,unknown>;
function validate(schema:Record<string,unknown>,value:unknown){const ajv=new Ajv2020({allErrors:true,strict:false});addFormats(ajv);const fn=ajv.compile(schema);assert.equal(fn(value),true,JSON.stringify(fn.errors));}

test("Agent and four adapter profiles validate one shared resource model",async()=>{
  const agent=await json(path.join(fixtures,"agent-good.json")),agentSchema=await json(path.join(contracts,"agent.schema.json")),harnessSchema=await json(path.join(contracts,"harness.schema.json"));validate(agentSchema,agent);assert.equal((agent.version as Record<string,unknown>).digest,agentVersionDigest(agent.version));
  const bundles=[];for(const name of ["hermes-profile.json","codex-profile.json","claude-profile.json","generic-profile.json"]){const bundle=await json(path.join(fixtures,name));validate(harnessSchema,bundle);assert.equal((bundle.version as Record<string,unknown>).digest,harnessVersionDigest(bundle.version));assert.equal((bundle.profile as Record<string,unknown>).digest,harnessProfileDigest(bundle.profile));assert.deepEqual(verifyHarnessBundle(bundle),[],name);bundles.push(bundle);}
  assert.deepEqual(verifyAgentCompatibility(agent,bundles),[]);
  assert.match(verifyAgentCompatibility(agent,bundles.slice(0,3)).join(" "),/every allowed HarnessProfile/);
  const implementationTamper=structuredClone(bundles[0]!);((implementationTamper.version as Record<string,Record<string,unknown>>).implementation!).digest=`registry.blazn.invalid/harness/hermes@sha256:${"f".repeat(64)}`;(implementationTamper.version as Record<string,unknown>).digest=harnessVersionDigest(implementationTamper.version);assert.match(verifyHarnessBundle(implementationTamper).join(" "),/provenance Artifact digest/);
  const shellAdapter=structuredClone(bundles[0]!),shellVersion=shellAdapter.version as Record<string,unknown>;shellVersion.executable={...(shellVersion.executable as Record<string,unknown>),path:"/bin/sh",fixedArgv:["-c","curl https://example.invalid/run"]};shellVersion.digest=harnessVersionDigest(shellVersion);assert.match(verifyHarnessBundle(shellAdapter).join(" "),/interpreters/);
  const shellArgv=structuredClone(bundles[0]!),shellArgvVersion=shellArgv.version as Record<string,unknown>,shellArgvExecutable=shellArgvVersion.executable as Record<string,unknown>;shellArgvExecutable.fixedArgv=["run","output > /tmp/result"];shellArgvVersion.digest=harnessVersionDigest(shellArgvVersion);assert.match(verifyHarnessBundle(shellArgv).join(" "),/shell syntax/);
  const provenanceTamper=structuredClone(bundles[0]!);((provenanceTamper.version as Record<string,Record<string,unknown>>).provenance!).commit="2".repeat(40);assert.match(verifyHarnessBundle(provenanceTamper).join(" "),/semantic digest/);
  const profileTamper=structuredClone(bundles[0]!);((profileTamper.profile as Record<string,unknown>).overrides as Record<string,unknown>).format="yaml";assert.match(verifyHarnessBundle(profileTamper).join(" "),/semantic digest/);
  const claudeWithoutAuthorization=structuredClone(bundles[2]!);(claudeWithoutAuthorization.profile as Record<string,unknown>).directProviderAuthorization=null;(claudeWithoutAuthorization.profile as Record<string,unknown>).digest=harnessProfileDigest(claudeWithoutAuthorization.profile);assert.match(verifyHarnessBundle(claudeWithoutAuthorization).join(" "),/resolved same-workspace approved DIRECT authorization/);
  const substitutedAuthorization=structuredClone(bundles[2]!),substitutedProfile=substitutedAuthorization.profile as Record<string,unknown>,authorization=substitutedProfile.directProviderAuthorization as Record<string,unknown>;authorization.workspaceId="40000000-0000-4000-8000-000000000099";substitutedProfile.digest=harnessProfileDigest(substitutedProfile);assert.match(verifyHarnessBundle(substitutedAuthorization).join(" "),/same-workspace/);
  const duplicateDeclaration=structuredClone(bundles[0]!),duplicateProfile=duplicateDeclaration.profile as Record<string,unknown>,duplicateCredentials=duplicateProfile.credentials as Array<Record<string,unknown>>;duplicateCredentials.push({...duplicateCredentials[0]!,leaseSeconds:1200});duplicateProfile.digest=harnessProfileDigest(duplicateProfile);assert.match(verifyHarnessBundle(duplicateDeclaration).join(" "),/declarations must be unique/);
  const agentTamper=structuredClone(agent);(agentTamper.version as Record<string,unknown>).instructions="substituted";assert.match(verifyAgentCompatibility(agentTamper,bundles).join(" "),/AgentVersion semantic digest/);
  const republishedProfile=structuredClone(bundles[0]!),republishedProfileValue=republishedProfile.profile as Record<string,unknown>;((republishedProfileValue.overrides as Record<string,unknown>)).format="yaml";republishedProfileValue.digest=harnessProfileDigest(republishedProfileValue);assert.match(verifyAgentCompatibility(agent,[republishedProfile,...bundles.slice(1)]).join(" "),/immutable AgentVersion pin/);
  const unrunnable=structuredClone(agent),unrunnableVersion=unrunnable.version as Record<string,unknown>;((unrunnableVersion.outputContract as Record<string,unknown>).artifacts as string[]).push("test-report");unrunnableVersion.digest=agentVersionDigest(unrunnableVersion);const ajv=new Ajv2020({allErrors:true,strict:false});addFormats(ajv);assert.equal(ajv.compile(agentSchema)(unrunnable),false,"unrunnable Agent Artifact role passed schema");assert.match(verifyAgentCompatibility(unrunnable,bundles).join(" "),/unrunnable Artifact role/);
});

test("raw credentials, oversized overrides, undeclared credentials and capability mismatch fail before Sandbox",async()=>{
  const schema=await json(path.join(contracts,"harness.schema.json")),bad=await json(path.join(fixtures,"profile-bad-secret.json"));validate(schema,bad);assert.notDeepEqual(verifyHarnessBundle(bad),[]);
  const hermes=await json(path.join(fixtures,"hermes-profile.json")),secret=structuredClone(hermes);((secret.profile as Record<string,unknown>).overrides as Record<string,unknown>).authorization="Bearer forbidden-value";assert.ok(harnessSecretViolations(secret).length);
  const ajv=new Ajv2020({allErrors:true,strict:false});addFormats(ajv);const schemaValidator=ajv.compile(schema),oversized=structuredClone(hermes);((oversized.profile as Record<string,unknown>).overrides as Record<string,unknown>).format="x".repeat(513);assert.equal(schemaValidator(oversized),false,"oversized override passed schema");
  const undeclared=structuredClone(hermes);(undeclared.profile as Record<string,unknown>).credentials=[{capability:"model.anthropic",scope:"route:x",leaseSeconds:60}];assert.notDeepEqual(verifyHarnessBundle(undeclared),[]);
  const wrongScope=structuredClone(hermes);(wrongScope.profile as Record<string,unknown>).credentials=[{capability:"repository.read",scope:"route:not-a-repository",leaseSeconds:60}];assert.match(verifyHarnessBundle(wrongScope).join(" "),/scope/);
  const opaque=structuredClone(hermes);((opaque.profile as Record<string,unknown>).overrides as Record<string,unknown>).value="a".repeat(43);assert.match(verifyHarnessBundle(opaque).join(" "),/raw credential/);
  const agent=await json(path.join(fixtures,"agent-good.json")),limited=structuredClone(hermes);(limited.version as Record<string,unknown>).capabilities=["task.one-shot"];
  assert.match(verifyAgentCompatibility(agent,[limited]).join(" "),/missing capabilities/);
  const secretAgent=structuredClone(agent);(secretAgent.version as Record<string,unknown>).instructions="Use API_KEY=forbidden";assert.ok(verifyAgentCompatibility(secretAgent,[hermes]).some((error)=>error.includes("credential-like")));
  const run=await json(path.join(fixtures,"run-good.json")),incompatible=structuredClone(run),compatibility=incompatible.compatibility as Record<string,unknown>;compatibility.available=["task.one-shot"];compatibility.missing=["message.follow-up","conversation.resume","event.structured","event.streaming","output.patch","output.artifact","cancel.graceful"];compatibility.compatible=false;(incompatible.run as Record<string,unknown>).status="failed";(incompatible.run as Record<string,unknown>).sandboxId=null;(incompatible.result as Record<string,unknown>).status="failed";(incompatible.provenance as Record<string,unknown>).node=null;(incompatible.provenance as Record<string,unknown>).proxyDecision=null;incompatible.credentialLeases=[];(incompatible.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(incompatible);validate(await json(path.join(contracts,"harness-run.schema.json")),incompatible);
  assert.doesNotMatch(verifyHarnessRun(agent,hermes,incompatible).join(" "),/before Sandbox/);
  assert.doesNotMatch(verifyHarnessRun(agent,hermes,incompatible).join(" "),/injectively|model credential lease/);
  const incompatibleWithLease=structuredClone(incompatible);incompatibleWithLease.credentialLeases=structuredClone(run.credentialLeases);assert.match(verifyHarnessRun(agent,hermes,incompatibleWithLease).join(" "),/zero credential leases/);
  (incompatible.run as Record<string,unknown>).sandboxId="32000000-0000-4000-8000-000000000001";assert.match(verifyHarnessRun(agent,hermes,incompatible).join(" "),/before Sandbox/);
});

test("normalized lifecycle, follow-up, resume, cancellation, provenance and terminal events are coherent",async()=>{
  const agent=await json(path.join(fixtures,"agent-good.json")),bundle=await json(path.join(fixtures,"hermes-profile.json")),run=await json(path.join(fixtures,"run-good.json")),schema=await json(path.join(contracts,"harness-run.schema.json")),agentBefore=structuredClone(agent),bundleBefore=structuredClone(bundle);validate(schema,run);assert.deepEqual(verifyHarnessRun(agent,bundle,run),[]);assert.deepEqual(agent,agentBefore,"Run verification mutated Agent authority");assert.deepEqual(bundle,bundleBefore,"Run verification mutated Harness authority");
  assert.equal((run.result as Record<string,unknown>).receiptDigest,harnessTerminalReceiptDigest(run));
  const substitutedAgent=structuredClone(run);(substitutedAgent.run as Record<string,unknown>).agentId="10000000-0000-4000-8000-000000000098";(substitutedAgent.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(substitutedAgent);assert.match(verifyHarnessRun(agent,bundle,substitutedAgent).join(" "),/exact Agent and immutable Harness identities/);
  const claude=await json(path.join(fixtures,"claude-profile.json")),direct=structuredClone(run),claudeVersion=claude.version as Record<string,unknown>,claudeProfile=claude.profile as Record<string,unknown>,directRun=direct.run as Record<string,unknown>,directProvenance=direct.provenance as Record<string,Record<string,unknown>>,directProxy=directProvenance.proxyDecision!,directModel=directProvenance.modelRoute!,directLeases=direct.credentialLeases as Array<Record<string,unknown>>,directAuthorization=claudeProfile.directProviderAuthorization as Record<string,unknown>;directRun.harnessVersionId=claudeVersion.id;directRun.harnessProfileId=claudeProfile.id;directProvenance.harnessVersion={id:claudeVersion.id,digest:claudeVersion.digest};directProvenance.harnessProfile={id:claudeProfile.id,digest:claudeProfile.digest};directModel.protocol="anthropic-messages";directProxy.outcome="DIRECT";directProxy.authentication="provider-capability-proof";directProxy.authorizationId=directAuthorization.id;directLeases[0]!.capability="model.anthropic";(direct.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(direct);validate(schema,direct);assert.deepEqual(verifyHarnessRun(agent,claude,direct),[]);
  directProxy.authorizationId="76000000-0000-4000-8000-000000000099";(direct.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(direct);assert.match(verifyHarnessRun(agent,claude,direct).join(" "),/proxy decision/);
  const selectedRouteDrift=structuredClone(bundle),selectedRouteProfile=selectedRouteDrift.profile as Record<string,unknown>,selectedRouteModel=selectedRouteProfile.model as Record<string,unknown>;selectedRouteModel.routeId="70000000-0000-4000-8000-000000000099";selectedRouteProfile.digest=harnessProfileDigest(selectedRouteProfile);assert.match(verifyHarnessRun(agent,selectedRouteDrift,run).join(" "),/selected HarnessProfile model route/);
  const wrongLease=structuredClone(run);((wrongLease.credentialLeases as Array<Record<string,unknown>>)[0]!).scope="route:70000000-0000-4000-8000-000000000099:1";assert.match(verifyHarnessRun(agent,bundle,wrongLease).join(" "),/leases|model credential lease/);
  const duplicateLeaseID=structuredClone(run),duplicateLeases=duplicateLeaseID.credentialLeases as Array<Record<string,unknown>>;duplicateLeases[1]!.id=duplicateLeases[0]!.id;(duplicateLeaseID.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(duplicateLeaseID);assert.match(verifyHarnessRun(agent,bundle,duplicateLeaseID).join(" "),/injectively one-to-one with unique IDs/);
  const activeTerminalLease=structuredClone(run),activeTerminal=(activeTerminalLease.credentialLeases as Array<Record<string,unknown>>)[0]!;activeTerminal.status="active";activeTerminal.revokedAt=null;assert.match(verifyHarnessRun(agent,bundle,activeTerminalLease).join(" "),/retained a credential lease/);
  const running=structuredClone(run),runningRun=running.run as Record<string,unknown>,runningEvents=running.events as Array<Record<string,unknown>>;runningRun.status="running";delete runningRun.completedAt;running.result=null;runningEvents.pop();(running.session as Record<string,unknown>).eventCursor=runningEvents.length-1;for(const lease of running.credentialLeases as Array<Record<string,unknown>>){lease.status="active";lease.revokedAt=null;}validate(schema,running);assert.deepEqual(verifyHarnessRun(agent,bundle,running),[]);
  const prematureTerminal=structuredClone(running);prematureTerminal.result=structuredClone(run.result);(prematureTerminal.events as Array<Record<string,unknown>>).push(structuredClone((run.events as Array<Record<string,unknown>>).at(-1)!));(prematureTerminal.events as Array<Record<string,unknown>>).at(-1)!.sequence=(prematureTerminal.events as Array<Record<string,unknown>>).length-1;(prematureTerminal.session as Record<string,unknown>).eventCursor=(prematureTerminal.events as Array<Record<string,unknown>>).length-1;assert.match(verifyHarnessRun(agent,bundle,prematureTerminal).join(" "),/nonterminal Run carries terminal/);
  const wrongMessage=structuredClone(run);((wrongMessage.messages as Array<Record<string,unknown>>)[1]!).followUpToMessageId="35000000-0000-4000-8000-000000000099";assert.match(verifyHarnessRun(agent,bundle,wrongMessage).join(" "),/follow-up Message/);
  const futureParent=structuredClone(run);((futureParent.messages as Array<Record<string,unknown>>)[0]!).parentMessageId="35000000-0000-4000-8000-000000000002";assert.match(verifyHarnessRun(agent,bundle,futureParent).join(" "),/parent causality/);
  const staleEmpty=structuredClone(run);staleEmpty.messages=[];(staleEmpty.session as Record<string,unknown>).messageCursor=1;assert.match(verifyHarnessRun(agent,bundle,staleEmpty).join(" "),/message cursor/);
  const skippedResume=structuredClone(run);const resume=(skippedResume.events as Array<Record<string,unknown>>).find((event)=>event.type==="harness.resumed")!;(resume.payload as Record<string,unknown>).generation=2;assert.match(verifyHarnessRun(agent,bundle,skippedResume).join(" "),/resume generation/);
  const wrongProxy=structuredClone(run);((wrongProxy.provenance as Record<string,Record<string,unknown>>).proxyDecision!).policyVersion=2;assert.match(verifyHarnessRun(agent,bundle,wrongProxy).join(" "),/proxy decision/);
  const approvedFallback=structuredClone(run),approvedFallbackEvents=approvedFallback.events as Array<Record<string,unknown>>,approvedFallbackTerminal=approvedFallbackEvents.pop()!,approvedFallbackBase=structuredClone(approvedFallbackEvents.at(-1)!);approvedFallbackEvents.push({...approvedFallbackBase,id:"79000000-0000-4000-8000-000000000001",cursor:"primary-failed",type:"error",source:"proxy",payload:{requestId:"74000000-0000-4000-8000-000000000001",routeId:"70000000-0000-4000-8000-000000000001",code:"provider-unavailable"},extensions:{}},approvedFallbackTerminal);approvedFallbackEvents.forEach((event,index)=>event.sequence=index);(approvedFallback.session as Record<string,unknown>).eventCursor=approvedFallbackEvents.length-1;(approvedFallback.provenance as Record<string,unknown>).fallbackAttempt={attempt:1,approved:true,primaryFailureEventId:"79000000-0000-4000-8000-000000000001",primaryRouteId:"70000000-0000-4000-8000-000000000001",primaryRouteVersion:1,fallbackRouteId:"70000000-0000-4000-8000-000000000002",fallbackRouteVersion:1,requestId:"74000000-0000-4000-8000-000000000002",eventId:"71000000-0000-4000-8000-000000000002",policyId:"73000000-0000-4000-8000-000000000001",policyVersion:1};(approvedFallback.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(approvedFallback);validate(schema,approvedFallback);assert.deepEqual(verifyHarnessRun(agent,bundle,approvedFallback),[]);
  const unsupportedFallback=structuredClone(run),unsupportedFallbackProvenance=unsupportedFallback.provenance as Record<string,unknown>;unsupportedFallbackProvenance.fallbackAttempt={attempt:1,approved:true,primaryFailureEventId:"79000000-0000-4000-8000-000000000001",primaryRouteId:"70000000-0000-4000-8000-000000000001",primaryRouteVersion:1,fallbackRouteId:"70000000-0000-4000-8000-000000000002",fallbackRouteVersion:1,requestId:"74000000-0000-4000-8000-000000000002",eventId:"71000000-0000-4000-8000-000000000002",policyId:"73000000-0000-4000-8000-000000000001",policyVersion:1};(unsupportedFallback.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(unsupportedFallback);assert.match(verifyHarnessRun(agent,bundle,unsupportedFallback).join(" "),/primary failure event evidence/);
  const unpricedCost=structuredClone(run),unpricedBilling=(unpricedCost.provenance as Record<string,Record<string,unknown>>).billing!;unpricedBilling.amountMicros=1;(unpricedCost.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(unpricedCost);assert.match(verifyHarnessRun(agent,bundle,unpricedCost).join(" "),/cost provenance/);
  const falseDuration=structuredClone(run);((falseDuration.result as Record<string,Record<string,unknown>>).usage!).durationMs=1;(falseDuration.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(falseDuration);assert.match(verifyHarnessRun(agent,bundle,falseDuration).join(" "),/authoritative lifecycle time/);
  const directBypass=structuredClone(run);((directBypass.provenance as Record<string,Record<string,unknown>>).proxyDecision!).outcome="DIRECT";assert.match(verifyHarnessRun(agent,bundle,directBypass).join(" "),/proxy decision/);
  const wrongArtifact=structuredClone(run);((wrongArtifact.result as {artifacts:Array<Record<string,unknown>>}).artifacts[0]!).mediaType="text/plain";assert.match(verifyHarnessRun(agent,bundle,wrongArtifact).join(" "),/wrong kind or media/);
  const nullPatchIdentity=structuredClone(run);(nullPatchIdentity.result as Record<string,unknown>).patchArtifactId=null;(nullPatchIdentity.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(nullPatchIdentity);assert.match(verifyHarnessRun(agent,bundle,nullPatchIdentity).join(" "),/patchArtifactId must equal/);
  const substitutedPatchIdentity=structuredClone(run),substitutedPatchResult=substitutedPatchIdentity.result as Record<string,unknown>,substitutedArtifacts=substitutedPatchResult.artifacts as Array<Record<string,unknown>>;substitutedPatchResult.patchArtifactId=substitutedArtifacts.find((artifact)=>artifact.role==="summary")!.id;substitutedPatchResult.receiptDigest=harnessTerminalReceiptDigest(substitutedPatchIdentity);assert.match(verifyHarnessRun(agent,bundle,substitutedPatchIdentity).join(" "),/patchArtifactId must equal/);
  const missingSummary=structuredClone(run);(missingSummary.result as {artifacts:Array<Record<string,unknown>>}).artifacts.pop();(missingSummary.result as {artifactIds:Array<string>}).artifactIds.pop();assert.match(verifyHarnessRun(agent,bundle,missingSummary).join(" "),/mandatory AgentVersion output role/);
  const missingArtifactEvent=structuredClone(run);(missingArtifactEvent.events as Array<Record<string,unknown>>).splice(6,1);(missingArtifactEvent.events as Array<Record<string,unknown>>).forEach((event,index)=>event.sequence=index);(missingArtifactEvent.session as Record<string,unknown>).eventCursor=6;assert.match(verifyHarnessRun(agent,bundle,missingArtifactEvent).join(" "),/lacks its normalized creation event/);
  const wrongReceipt=structuredClone(run);(wrongReceipt.result as Record<string,unknown>).receiptDigest=`sha256:${"f".repeat(64)}`;assert.match(verifyHarnessRun(agent,bundle,wrongReceipt).join(" "),/receipt semantic digest/);
  const duplicateEventID=structuredClone(run),duplicateIDEvents=duplicateEventID.events as Array<Record<string,unknown>>;duplicateIDEvents[1]!.id=duplicateIDEvents[0]!.id;(duplicateEventID.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(duplicateEventID);assert.match(verifyHarnessRun(agent,bundle,duplicateEventID).join(" "),/event ID is empty or duplicated/);
  const emptyEventID=structuredClone(run);((emptyEventID.events as Array<Record<string,unknown>>)[0]!).id="";(emptyEventID.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(emptyEventID);assert.match(verifyHarnessRun(agent,bundle,emptyEventID).join(" "),/event ID is empty or duplicated/);
  const toolRun=structuredClone(run),toolEvents=toolRun.events as Array<Record<string,unknown>>,toolTerminal=toolEvents.pop()!,toolBase=structuredClone(toolEvents.at(-1)!);for(const [index,type] of ["tool.requested","tool.approved","tool.started","tool.completed"].entries()){const approved=type==="tool.approved";toolEvents.push({...structuredClone(toolBase),id:`81000000-0000-4000-8000-00000000000${index+1}`,cursor:`tool-${index+1}`,type,source:approved?"control-plane":"adapter",payload:{toolCallId:"82000000-0000-4000-8000-000000000001",tool:"repository",...(approved?{approvalId:"83000000-0000-4000-8000-000000000001"}:{})}});}toolEvents.push(toolTerminal);toolEvents.forEach((event,index)=>event.sequence=index);(toolRun.session as Record<string,unknown>).eventCursor=toolEvents.length-1;(toolRun.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(toolRun);assert.deepEqual(verifyHarnessRun(agent,bundle,toolRun),[]);
  const unlistedTool=structuredClone(toolRun),unlistedToolEvents=unlistedTool.events as Array<Record<string,unknown>>;for(const event of unlistedToolEvents)if(String(event.type).startsWith("tool."))(event.payload as Record<string,unknown>).tool="deployment";(unlistedTool.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(unlistedTool);assert.match(verifyHarnessRun(agent,bundle,unlistedTool).join(" "),/exact Agent and HarnessProfile tool/);
  const forgedToolApproval=structuredClone(toolRun),forgedApprovalEvent=(forgedToolApproval.events as Array<Record<string,unknown>>).find((event)=>event.type==="tool.approved")!;forgedApprovalEvent.source="adapter";(forgedToolApproval.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(forgedToolApproval);assert.match(verifyHarnessRun(agent,bundle,forgedToolApproval).join(" "),/unique control-plane authority/);
  const disorderedTool=structuredClone(toolRun),disorderedEvents=disorderedTool.events as Array<Record<string,unknown>>,approvedIndex=disorderedEvents.findIndex((event)=>event.type==="tool.approved"),startedIndex=disorderedEvents.findIndex((event)=>event.type==="tool.started");[disorderedEvents[approvedIndex],disorderedEvents[startedIndex]]=[disorderedEvents[startedIndex]!,disorderedEvents[approvedIndex]!];disorderedEvents.forEach((event,index)=>event.sequence=index);(disorderedTool.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(disorderedTool);assert.match(verifyHarnessRun(agent,bundle,disorderedTool).join(" "),/lifecycle or approval sequence/);
  const duplicateTerminal=structuredClone(run),duplicateTerminalEvents=duplicateTerminal.events as Array<Record<string,unknown>>,duplicateTerminalEvent=structuredClone(duplicateTerminalEvents.at(-1)!);duplicateTerminalEvent.id="80000000-0000-4000-8000-000000000099";duplicateTerminalEvent.cursor="terminal-duplicate";duplicateTerminalEvents.splice(duplicateTerminalEvents.length-1,0,duplicateTerminalEvent);duplicateTerminalEvents.forEach((event,index)=>event.sequence=index);(duplicateTerminal.session as Record<string,unknown>).eventCursor=duplicateTerminalEvents.length-1;(duplicateTerminal.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(duplicateTerminal);assert.match(verifyHarnessRun(agent,bundle,duplicateTerminal).join(" "),/terminal Run result or event/);
  const lateRevocation=structuredClone(run);((lateRevocation.credentialLeases as Array<Record<string,unknown>>)[0]!).revokedAt="2026-08-22T00:05:01Z";(lateRevocation.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(lateRevocation);assert.match(verifyHarnessRun(agent,bundle,lateRevocation).join(" "),/completed before credential revocation/);
  for(const mutate of [(v:Record<string,unknown>)=>{((v.events as Array<Record<string,unknown>>)[1]!).sequence=0;},(v:Record<string,unknown>)=>{((v.provenance as Record<string,Record<string,unknown>>).modelRoute!).version=2;},(v:Record<string,unknown>)=>{((v.session as Record<string,unknown>)).followUpCount=0;},(v:Record<string,unknown>)=>{((v.events as Array<Record<string,unknown>>).at(-1)!).type="harness.exited";},(v:Record<string,unknown>)=>{const event=(v.events as Array<Record<string,unknown>>)[2]!;event.type="tool.requested";event.payload={};}]){const candidate=structuredClone(run);mutate(candidate);assert.notDeepEqual(verifyHarnessRun(agent,bundle,candidate),[]);}
  const cancelled=structuredClone(run),events=cancelled.events as Array<Record<string,unknown>>,terminal=events.pop()!,base=structuredClone(events.at(-1)!);events.push({...base,id:"80000000-0000-4000-8000-000000000009",cursor:"cancel-request",type:"cancellation.requested",source:"control-plane",payload:{cancellationId:"37000000-0000-4000-8000-000000000001"},extensions:{}},{...base,id:"80000000-0000-4000-8000-000000000010",cursor:"cancel-ack",type:"cancellation.acknowledged",source:"adapter",payload:{cancellationId:"37000000-0000-4000-8000-000000000001"},extensions:{}},terminal);events.forEach((event,index)=>{event.sequence=index;});(cancelled.session as Record<string,unknown>).eventCursor=events.length-1;(cancelled.run as Record<string,unknown>).status="cancelled";(cancelled.result as Record<string,unknown>).status="cancelled";(terminal.payload as Record<string,unknown>).status="cancelled";(cancelled.session as Record<string,unknown>).cancellation={requested:true,acknowledged:true,processTreeTerminated:true,cleanupComplete:true,credentialsRevoked:true,artifactsHandled:true};(cancelled.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(cancelled);assert.deepEqual(verifyHarnessRun(agent,bundle,cancelled),[]);
  const cancelling=structuredClone(cancelled),cancellingRun=cancelling.run as Record<string,unknown>,cancellingEvents=cancelling.events as Array<Record<string,unknown>>;cancellingRun.status="cancelling";delete cancellingRun.completedAt;cancelling.result=null;cancellingEvents.pop();(cancelling.session as Record<string,unknown>).eventCursor=cancellingEvents.length-1;for(const lease of cancelling.credentialLeases as Array<Record<string,unknown>>){lease.status="active";lease.revokedAt=null;}validate(schema,cancelling);assert.deepEqual(verifyHarnessRun(agent,bundle,cancelling),[]);
  const wrongCancellationId=structuredClone(cancelled),wrongCancellationEvents=wrongCancellationId.events as Array<Record<string,unknown>>;((wrongCancellationEvents.find((event)=>event.type==="cancellation.acknowledged")!.payload) as Record<string,unknown>).cancellationId="37000000-0000-4000-8000-000000000099";(wrongCancellationId.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(wrongCancellationId);assert.match(verifyHarnessRun(agent,bundle,wrongCancellationId).join(" "),/does not match/);
  const wrongCancellationOrder=structuredClone(cancelled),wrongOrderEvents=wrongCancellationOrder.events as Array<Record<string,unknown>>,requestIndex=wrongOrderEvents.findIndex((event)=>event.type==="cancellation.requested"),ackIndex=wrongOrderEvents.findIndex((event)=>event.type==="cancellation.acknowledged");[wrongOrderEvents[requestIndex],wrongOrderEvents[ackIndex]]=[wrongOrderEvents[ackIndex]!,wrongOrderEvents[requestIndex]!];wrongOrderEvents.forEach((event,index)=>event.sequence=index);(wrongCancellationOrder.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(wrongCancellationOrder);assert.match(verifyHarnessRun(agent,bundle,wrongCancellationOrder).join(" "),/follow its request/);
  for(const status of ["succeeded","failed","timed_out"]){const invalidCancellationTerminal=structuredClone(cancelled),invalidResult=invalidCancellationTerminal.result as Record<string,unknown>,invalidTerminal=(invalidCancellationTerminal.events as Array<Record<string,unknown>>).at(-1)!;(invalidCancellationTerminal.run as Record<string,unknown>).status=status;invalidResult.status=status;(invalidTerminal.payload as Record<string,unknown>).status=status;invalidResult.receiptDigest=harnessTerminalReceiptDigest(invalidCancellationTerminal);assert.match(verifyHarnessRun(agent,bundle,invalidCancellationTerminal).join(" "),/acknowledged cancellation must end cancelled or recovery_required/,status);}
  const cancellationRecovery=structuredClone(cancelled),recoveryResult=cancellationRecovery.result as Record<string,unknown>,recoveryTerminal=(cancellationRecovery.events as Array<Record<string,unknown>>).at(-1)!;(cancellationRecovery.run as Record<string,unknown>).status="recovery_required";recoveryResult.status="recovery_required";(recoveryTerminal.payload as Record<string,unknown>).status="recovery_required";recoveryResult.receiptDigest=harnessTerminalReceiptDigest(cancellationRecovery);assert.deepEqual(verifyHarnessRun(agent,bundle,cancellationRecovery),[]);
  const duplicateFollowUp=structuredClone(run),duplicateMessages=duplicateFollowUp.messages as Array<Record<string,unknown>>,secondFollowUp={...structuredClone(duplicateMessages[1]!),id:"35000000-0000-4000-8000-000000000003",ordinal:3,parentMessageId:duplicateMessages[1]!.id},duplicateEvents=duplicateFollowUp.events as Array<Record<string,unknown>>,resumeIndex=duplicateEvents.findIndex((event)=>event.type==="harness.resumed"),duplicateAccepted={...structuredClone(duplicateEvents[resumeIndex-1]!),id:"80000000-0000-4000-8000-000000000099",cursor:"followup-duplicate"};duplicateMessages.push(secondFollowUp);duplicateEvents.splice(resumeIndex,0,duplicateAccepted);duplicateEvents.forEach((event,index)=>event.sequence=index);(duplicateFollowUp.session as Record<string,unknown>).messageCursor=3;(duplicateFollowUp.session as Record<string,unknown>).eventCursor=duplicateEvents.length-1;(duplicateFollowUp.session as Record<string,unknown>).followUpCount=2;(duplicateFollowUp.result as Record<string,unknown>).receiptDigest=harnessTerminalReceiptDigest(duplicateFollowUp);assert.match(verifyHarnessRun(agent,bundle,duplicateFollowUp).join(" "),/one-to-one|contiguous/);
  ((cancelled.session as Record<string,Record<string,unknown>>).cancellation!).processTreeTerminated=false;assert.match(verifyHarnessRun(agent,bundle,cancelled).join(" "),/termination/);
  ((cancelled.session as Record<string,Record<string,unknown>>).cancellation!).processTreeTerminated=true;((cancelled.session as Record<string,Record<string,unknown>>).cancellation!).credentialsRevoked=false;assert.match(verifyHarnessRun(agent,bundle,cancelled).join(" "),/credential revocation/);
});

test("portable evaluation requires identical conformance cases and Artifact evidence",async()=>{
  const value=await json(path.join(fixtures,"evaluation-good.json")),schema=await json(path.join(contracts,"harness-conformance.schema.json")),agent=await json(path.join(fixtures,"agent-good.json")),parity=[],parityBundles=[];
  const hermesBundle=await json(path.join(fixtures,"hermes-profile.json"));validate(schema,value);assert.deepEqual(verifyPortableEvaluation(value,hermesBundle,agent),[]);
  const incompatibleSelectedBundle=structuredClone(hermesBundle),incompatibleSelectedProfile=incompatibleSelectedBundle.profile as Record<string,unknown>;((incompatibleSelectedProfile.model as Record<string,unknown>)).routeId="70000000-0000-4000-8000-000000000099";incompatibleSelectedProfile.digest=harnessProfileDigest(incompatibleSelectedProfile);const incompatibleSelectedEvaluation=structuredClone(value),selectedResolved=(incompatibleSelectedEvaluation.resolvedHarness as Record<string,Record<string,unknown>>).profile!,selectedReceipt=(incompatibleSelectedEvaluation.result as Record<string,Record<string,unknown>>).runReceipt!;selectedResolved.digest=incompatibleSelectedProfile.digest;selectedReceipt.profileDigest=incompatibleSelectedProfile.digest;assert.match(verifyPortableEvaluation(incompatibleSelectedEvaluation,incompatibleSelectedBundle,agent).join(" "),/selected HarnessProfile model route/);
  const specifications=[["hermes","hermes-profile.json","1"],["codex-cli","codex-profile.json","2"],["claude-code","claude-profile.json","3"],["generic-cli","generic-profile.json","4"]];
  for(const [kind,file,suffix] of specifications){const bundle=await json(path.join(fixtures,file!)),candidate=structuredClone(value),definition=bundle.definition as Record<string,unknown>,version=bundle.version as Record<string,unknown>,profile=bundle.profile as Record<string,unknown>,resolved=candidate.resolvedHarness as Record<string,Record<string,unknown>>,result=candidate.result as Record<string,unknown>,receipt=result.runReceipt as Record<string,unknown>,runId=`30000000-0000-4000-8000-00000000000${suffix}`,receiptDigest=`sha256:${suffix!.repeat(64)}`,evidence=result.evidenceArtifacts as Array<Record<string,unknown>>,caseResults=result.caseResults as Array<Record<string,unknown>>;candidate.adapterKind=kind;candidate.harnessVersionId=version.id;candidate.profileId=profile.id;resolved.definition={id:definition.id,kind:definition.kind,resourceVersion:definition.resourceVersion};resolved.version={id:version.id,digest:version.digest};resolved.profile={id:profile.id,workspaceId:profile.workspaceId,digest:profile.digest};evidence.forEach((artifact,index)=>{const id=`9${suffix}000000-0000-4000-8000-${String(index+1).padStart(12,"0")}`;artifact.id=id;artifact.contentDigest=`sha256:${String(Number(suffix)*10+index+1).padStart(2,"0").repeat(32)}`;caseResults[index]!.evidenceArtifactId=id;});result.artifactIds=evidence.map((artifact)=>artifact.id);result.runId=runId;result.receiptDigest=receiptDigest;receipt.runId=runId;receipt.receiptDigest=receiptDigest;receipt.harnessVersionId=version.id;receipt.harnessVersionDigest=version.digest;receipt.profileId=profile.id;receipt.profileDigest=profile.digest;receipt.resultDigest=portableResultDigest(candidate);validate(schema,candidate);assert.deepEqual(verifyPortableEvaluation(candidate,bundle,agent),[],kind);parity.push(candidate);parityBundles.push(bundle);}
  assert.deepEqual(verifyPortableParity(parity,parityBundles,agent),[]);
  const missing=structuredClone(parity[0]!);(missing.result as {caseResults:Array<unknown>}).caseResults.pop();assert.notDeepEqual(verifyPortableEvaluation(missing,parityBundles[0],agent),[]);
  const wrongRole=structuredClone(parity[0]!),artifacts=(wrongRole.result as {evidenceArtifacts:Array<Record<string,unknown>>}).evidenceArtifacts;artifacts[1]!.role=artifacts[0]!.role;assert.notDeepEqual(verifyPortableEvaluation(wrongRole,parityBundles[0],agent),[]);
  const reusedContent=structuredClone(parity[0]!),reusedArtifacts=(reusedContent.result as {evidenceArtifacts:Array<Record<string,unknown>>}).evidenceArtifacts;reusedArtifacts[1]!.contentDigest=reusedArtifacts[0]!.contentDigest;assert.notDeepEqual(verifyPortableEvaluation(reusedContent,parityBundles[0],agent),[]);
  const wrongHarness=structuredClone(parity[0]!);((wrongHarness.resolvedHarness as Record<string,Record<string,unknown>>).profile!).digest=`sha256:${"f".repeat(64)}`;assert.notDeepEqual(verifyPortableEvaluation(wrongHarness,await json(path.join(fixtures,"hermes-profile.json")),agent),[]);
  const topIdentityDrift=structuredClone(parity[0]!);topIdentityDrift.harnessVersionId="20000000-0000-4000-8000-000000000099";assert.match(verifyPortableEvaluation(topIdentityDrift,parityBundles[0],agent).join(" "),/exact Harness/);
  const evaluationDrift=structuredClone(parity[0]!);(evaluationDrift.portableEvaluation as Record<string,unknown>).id="90000000-0000-4000-8000-000000000099";assert.match(verifyPortableEvaluation(evaluationDrift,parityBundles[0],agent).join(" "),/authoritative portable AgentVersion/);
  const evidenceWorkspaceDrift=structuredClone(parity[0]!);((evidenceWorkspaceDrift.result as {evidenceArtifacts:Array<Record<string,unknown>>}).evidenceArtifacts[0]!).workspaceId="40000000-0000-4000-8000-000000000099";assert.match(verifyPortableEvaluation(evidenceWorkspaceDrift,parityBundles[0],agent).join(" "),/workspace/);
  const unapprovedBundle=structuredClone(parityBundles[0]!),unapprovedProfile=unapprovedBundle.profile as Record<string,unknown>;unapprovedProfile.id="21000000-0000-4000-8000-000000000099";unapprovedProfile.digest=harnessProfileDigest(unapprovedProfile);const unapprovedResult=structuredClone(parity[0]!),unapprovedResolved=(unapprovedResult.resolvedHarness as Record<string,Record<string,unknown>>).profile!,unapprovedReceipt=(unapprovedResult.result as Record<string,Record<string,unknown>>).runReceipt!;unapprovedResult.profileId=unapprovedProfile.id;unapprovedResolved.id=unapprovedProfile.id;unapprovedResolved.digest=unapprovedProfile.digest;unapprovedReceipt.profileId=unapprovedProfile.id;unapprovedReceipt.profileDigest=unapprovedProfile.digest;assert.match(verifyPortableEvaluation(unapprovedResult,unapprovedBundle,agent).join(" "),/authoritative portable AgentVersion/);
  const reused=structuredClone(parity);((reused[1]!.result as Record<string,unknown>)).receiptDigest=(reused[0]!.result as Record<string,unknown>).receiptDigest;assert.notDeepEqual(verifyPortableParity(reused,parityBundles,agent),[]);
});
