import assert from "node:assert/strict";
import { generateKeyPairSync } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { FileNodePlanSigner } from "./node-crypto.js";
import { TemplateNodePlanFactory } from "./node-plan.js";
import type { EnrollmentRecord } from "./node-types.js";

test("raw Ed25519 seed signs fully validated plans for every exact template profile",async()=>{const fixture=await fixtureFiles();try{for(const [mode,platform,architecture,profile] of [["fresh","linux","amd64","ubuntu-26.04-amd64-worker/v1"],["adopt","linux","amd64","existing-linux-worker-adopt/v1"],["adopt","macos","arm64","macos-lima-worker-adopt/v1"]] as const){const factory=new TemplateNodePlanFactory(fixture.bundle,new FileNodePlanSigner("control-plane-node-plan/v1",fixture.key));const plan=await factory.create(context(mode,platform,architecture));assert.equal(plan.installProfile,profile);assert.match(String(plan.digest),/^sha256:[0-9a-f]{64}$/);assert.match(String(plan.signature),/^[A-Za-z0-9_-]{86}$/);}}finally{await rm(fixture.root,{recursive:true});}});

test("invalid nested template and profile semantics fail before persistence",async()=>{for(const mutate of [(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.cluster.extra=true;},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.nodeService.manager="launchd";},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.components[0]!.sourceHost="foreign.example";},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations[0]!.target="/../escape";}]){const fixture=await fixtureFiles(mutate);try{const factory=new TemplateNodePlanFactory(fixture.bundle,new FileNodePlanSigner("control-plane-node-plan/v1",fixture.key));await assert.rejects(()=>factory.create(context("fresh","linux","amd64")),/invalid NodeInstallPlan/);}finally{await rm(fixture.root,{recursive:true});}}});

type Profile={cluster:Record<string,unknown>;registryTrust:unknown[];components:Record<string,unknown>[];nodeService:Record<string,unknown>;labels:Record<string,string>;taints:unknown[];resourceBounds:Record<string,unknown>;mutations:Record<string,unknown>[];validationTests:string[];rollback:Record<string,unknown>};type Bundle={schemaVersion:string;templateId:string;profiles:Record<string,Profile>};
async function fixtureFiles(mutate?:(bundle:Bundle)=>void){const root=await mkdtemp(path.join(os.tmpdir(),"blazn-node-plan-"));const pair=generateKeyPairSync("ed25519");const der=pair.privateKey.export({format:"der",type:"pkcs8"});const key=path.join(root,"seed");await writeFile(key,`${der.subarray(der.length-32).toString("base64url")}\n`,{mode:0o600});const bundleObject=bundle();mutate?.(bundleObject);const bundlePath=path.join(root,"bundle.json");await writeFile(bundlePath,JSON.stringify(bundleObject),{mode:0o600});return{root,key,bundle:bundlePath};}
function bundle():Bundle{const linux=profile("systemd","blazn-node","blazn-node","linux_var_lib","/var/lib/blazn/install-backups/test");const mac=profile("launchd","root","wheel","macos_library_application_support","/Library/Application Support/Blazn/install-backups/test");return{schemaVersion:"blazn.dev/node-install-plan-templates/v1",templateId:"frontro-poc-worker/v1",profiles:{"ubuntu-26.04-amd64-worker/v1":linux,"existing-linux-worker-adopt/v1":structuredClone(linux),"macos-lima-worker-adopt/v1":mac}};}
function profile(manager:string,user:string,group:string,backupRootClass:string,backupRoot:string):Profile{return{cluster:{id:"frontro-poc",workerOnly:true,apiServer:"https://cluster.example.test:6443",kubernetesVersion:"v1.36.1",joinCredentialEndpoint:"/v1/node-service/join-credentials",bootstrapTaint:"blazn.dev/bootstrap=pending:NoSchedule",expectedCaFingerprint:`sha256:${"a".repeat(64)}`,registryEndpoints:[]},registryTrust:[],components:[{name:"blazn-node",artifactType:"binary",version:"v0.1.0",publisher:"Blazn",sourceHost:"downloads.example.test",source:"https://downloads.example.test/blazn",sha256:"b".repeat(64),ownership:"install"}],nodeService:{manager,unitName:manager==="systemd"?"blazn-node.service":"com.blazn.node",binaryPath:"/usr/local/bin/blazn",runAsUser:user,runAsGroup:group,definitionSha256:"c".repeat(64)},labels:{},taints:[],resourceBounds:{reservedCpuMillis:100,reservedMemoryBytes:1073741824,maxPods:10,maxConcurrentAgents:2},mutations:[{ordinal:1,kind:"directory",action:"create",target:"/var/lib/blazn",desired:{},desiredDigest:`sha256:${"d".repeat(64)}`,mode:493,uid:0,gid:0,rollback:"remove_if_owned"}],validationTests:["worker_only"],rollback:{preserveUserData:true,preserveControlPlane:true,ambiguousOwnership:"recovery_required",backupRootClass,backupRoot}};}
function context(mode:"fresh"|"adopt",platform:"linux"|"macos",architecture:"amd64"|"arm64"){const enrollment:EnrollmentRecord={id:"00000000-0000-4000-8000-000000000001",workspaceId:"00000000-0000-4000-8000-000000000002",requestedName:"node-test",mode,expectedPlatform:platform,expectedArchitecture:architecture,tokenHash:"a".repeat(64),tokenKeyId:"node-enrollment/v1",idempotencyKey:"node-plan-test",createdBy:"00000000-0000-4000-8000-000000000003",expiresAt:new Date("2030-01-01T00:00:00.000Z"),status:"pending",machineBinding:null,nodePublicKey:null,nodePublicKeyFingerprint:null,consumedByNodeId:null,version:1};return{planId:"00000000-0000-4000-8000-000000000004",nodeId:"00000000-0000-4000-8000-000000000005",enrollment,architecture,machineFingerprint:"e".repeat(64),nodePublicKeyFingerprint:"f".repeat(64),issuedAt:new Date("2029-01-01T00:00:00.000Z"),expiresAt:new Date("2029-01-01T00:15:00.000Z")};}
