import { randomUUID } from "node:crypto";
import { brokerRequestDigest, credentialHash, openJoinCredential, sealJoinCredential } from "./node-broker-crypto.js";
import { verifyNodePlanSignature, verifyNodeProof } from "./node-crypto.js";
import { NODE_INSTALL_PROFILES, validateSignedNodeInstallPlan, type NodeInstallProfile } from "./node-plan-validator.js";
import type { NodeBrokerStore } from "./node-broker-store.js";
import type { IssuedWorkerCredential, JoinCredentialRequest, JoinCredentialResponse, StoredJoinIssuance, WorkerCredentialIssuer } from "./node-broker-types.js";
import { NodeHttpError } from "./node-types.js";

export class NodeBrokerService {
  constructor(private readonly store:NodeBrokerStore,private readonly joinKey:()=>Promise<Buffer>,private readonly issuer:WorkerCredentialIssuer,private readonly now:()=>Date=()=>new Date()){}

  async issue(idempotencyKey:string,request:JoinCredentialRequest,proof:string):Promise<JoinCredentialResponse>{validateRequest(idempotencyKey,request,proof);const digest=brokerRequestDigest(request),key=await this.joinKey();if(key.length!==32)throw new Error("join credential key must be exactly 32 raw bytes");let external:IssuedWorkerCredential|undefined,committed=false;try{const result=await this.store.transaction(async tx=>{await tx.lockNode(request.nodeId);const binding=await tx.binding(request);if(!binding)throw new NodeHttpError("join_credential_invalid","join credential bindings were not found");validateBinding(binding,request,proof,this.now());const existing=await tx.issuance(request);if(existing)return replay(existing,idempotencyKey,digest,key,this.now());
      const plan=binding.canonicalPlan,cluster=record(plan.cluster,"plan.cluster"),clusterId=text(cluster.id,"cluster.id",128),ttlSeconds=Math.max(1,Math.min(300,Math.floor((binding.planExpiresAt.getTime()-this.now().getTime())/1000)));external=await this.issuer.issue({clusterId,expectedNodeName:text(plan.hostname,"hostname",253),bootstrapTaint:"blazn.dev/bootstrap=pending:NoSchedule",ttlSeconds,workerOnly:true});validateIssued(external,binding.planExpiresAt,cluster.id,this.now());const issuanceId=randomUUID(),context={workspaceId:binding.workspaceId,enrollmentId:binding.enrollmentId,planId:binding.planId,nodeId:binding.nodeId,issuanceId,idempotencyKey,requestDigest:digest},ciphertext=sealJoinCredential(key,external.credential,context);await tx.insertIssuance({id:issuanceId,workspaceId:binding.workspaceId,enrollmentId:binding.enrollmentId,planId:binding.planId,nodeId:binding.nodeId,clusterId,nodePublicKeyFingerprint:request.nodePublicKeyFingerprint,machineFingerprint:request.machineFingerprint,credentialHash:credentialHash(external.credential),credentialCiphertext:ciphertext,credentialKeyId:"node-join-credential/v1",idempotencyKey,requestDigest:digest,issuedAt:this.now(),expiresAt:external.expiresAt,consumedAt:null,revokedAt:null});return{issuanceId,credential:external.credential,expiresAt:external.expiresAt.toISOString(),clusterId,workerOnly:true as const,replayed:false};});committed=true;return result;}catch(error){if(external&&!committed)await external.revoke().catch(()=>{});throw mapStoreError(error);}}
}

function validateRequest(key:string,r:JoinCredentialRequest,proof:string){if(key.length<8||key.length>128)invalid("Idempotency-Key is invalid");for(const [name,value] of [["enrollmentId",r.enrollmentId],["planId",r.planId],["nodeId",r.nodeId]] as const)if(!UUID.test(value))invalid(`${name} is invalid`);if(!DIGEST.test(r.planDigest)||!HEX.test(r.machineFingerprint)||!DIGEST.test(r.nodePublicKeyFingerprint)||!/^[A-Za-z0-9_-]{86}$/.test(proof))invalid("join credential request binding is invalid");}
function validateBinding(b:import("./node-broker-types.js").BrokerBinding,r:JoinCredentialRequest,proof:string,now:Date):void{if(b.enrollmentId!==r.enrollmentId||b.planId!==r.planId||b.nodeId!==r.nodeId||b.planDigest!==r.planDigest||b.machineFingerprint!==r.machineFingerprint||b.nodePublicKeyFingerprint!==r.nodePublicKeyFingerprint)throw new NodeHttpError("join_credential_invalid","join credential request does not match its enrollment and plan");if(b.enrollmentStatus!=="exchanged"||b.planStatus!=="issued"||b.planExpiresAt.getTime()<=now.getTime()||b.nodeLifecycleState!=="installing"||b.nodeTrustState!=="verifying")throw new NodeHttpError("join_credential_invalid","join credential binding is not issuable");if(!verifyNodeProof(b.nodePublicKey,"blazn-node-join-v1",r,proof))throw new NodeHttpError("identity_rejected","node proof could not be verified");const plan=b.canonicalPlan,profile=plan.installProfile;if(typeof profile!=="string"||!NODE_INSTALL_PROFILES.includes(profile as NodeInstallProfile))throw new NodeHttpError("join_credential_invalid","install profile is invalid");try{validateSignedNodeInstallPlan(plan,profile as NodeInstallProfile,b.planSigningKeyId);}catch{throw new NodeHttpError("join_credential_invalid","stored install plan is invalid");}if(!verifyNodePlanSignature(b.planSigningPublicKey,String(plan.digest),String(plan.signature)))throw new NodeHttpError("join_credential_invalid","install plan signature is invalid");const cluster=record(plan.cluster,"plan.cluster"),target=record(plan.target,"plan.target");if(plan.workspaceId!==b.workspaceId||plan.enrollmentId!==b.enrollmentId||plan.planId!==b.planId||plan.nodeId!==b.nodeId||plan.digest!==b.planDigest||cluster.workerOnly!==true||cluster.joinCredentialEndpoint!=="/v1/node-service/join-credentials"||cluster.bootstrapTaint!=="blazn.dev/bootstrap=pending:NoSchedule"||target.machineFingerprint!==r.machineFingerprint||target.nodePublicKeyFingerprint!==r.nodePublicKeyFingerprint)throw new NodeHttpError("join_credential_invalid","stored install plan bindings are invalid");}
function validateIssued(v:IssuedWorkerCredential,planExpiry:Date,clusterId:unknown,now:Date){if(v.workerOnly!==true||v.clusterHealthy!==true||v.clusterId!==clusterId||v.credential.length<43||v.credential.length>4096||!(v.expiresAt instanceof Date)||!Number.isFinite(v.expiresAt.getTime())||v.expiresAt.getTime()<=now.getTime()||v.expiresAt.getTime()>planExpiry.getTime())throw new NodeHttpError("join_credential_invalid","worker credential provider returned an invalid credential");}
function replay(v:StoredJoinIssuance,key:string,digest:string,encryptionKey:Buffer,now:Date):JoinCredentialResponse{if(v.idempotencyKey!==key||v.requestDigest!==digest)throw new NodeHttpError("idempotency_conflict","join credential is bound to another request");if(v.consumedAt)throw new NodeHttpError("join_credential_consumed","join credential was consumed");if(v.revokedAt||v.expiresAt.getTime()<=now.getTime())throw new NodeHttpError("join_credential_invalid","join credential is revoked or expired");let credential:string;try{credential=openJoinCredential(encryptionKey,v.credentialCiphertext,{workspaceId:v.workspaceId,enrollmentId:v.enrollmentId,planId:v.planId,nodeId:v.nodeId,issuanceId:v.id,idempotencyKey:v.idempotencyKey,requestDigest:v.requestDigest});}catch{throw new Error("stored join credential could not be decrypted");}return{issuanceId:v.id,credential,expiresAt:v.expiresAt.toISOString(),clusterId:v.clusterId,workerOnly:true,replayed:true};}

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,HEX=/^[0-9a-f]{64}$/,DIGEST=/^sha256:[0-9a-f]{64}$/;
function record(v:unknown,name:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new NodeHttpError("join_credential_invalid",`${name} is invalid`);return v as Record<string,unknown>;}
function text(v:unknown,name:string,max:number):string{if(typeof v!=="string"||!v||v.length>max)throw new NodeHttpError("join_credential_invalid",`${name} is invalid`);return v;}
function invalid(message:string):never{throw new NodeHttpError("invalid_request",message);}
function mapStoreError(error:unknown):unknown{const e=error as {code?:string};if(e?.code==="23505")return new NodeHttpError("idempotency_conflict","join credential already exists for another request");return error;}
