import assert from "node:assert/strict";
import test from "node:test";
import { attachNodeBrokerDatabasePoolErrors, endNodeBrokerDatabase, nodeBrokerDatabasePoolError, startNodeBroker } from "./node-broker-main.js";

test("broker startup uses the fixed issuer socket and fails closed when it is absent",async()=>{process.env.BLAZN_MICROK8S_ISSUER_SOCKET="/tmp/must-not-be-used.sock";await assert.rejects(()=>startNodeBroker(),/microk8s-worker-issuer\.sock/);delete process.env.BLAZN_MICROK8S_ISSUER_SOCKET;});

test("broker database pool errors expose only fixed name and bounded code",()=>{const error=Object.assign(new Error("postgresql://broker:secret@example.test detail"),{name:"SecretToken",code:"57P01"});const line=nodeBrokerDatabasePoolError(error);assert.equal(line,"Node broker database pool error name=DatabasePoolError code=57P01");assert.doesNotMatch(line,/secret|postgresql|detail|example|token/i);assert.equal(nodeBrokerDatabasePoolError(Object.assign(new Error("private"),{name:"PasswordLeak",code:"invalid-code"})),"Node broker database pool error name=DatabasePoolError code=unknown");});

test("broker retains its pool error listener until shutdown settles",async()=>{const events:string[]=[],failure=Object.assign(new Error("private shutdown detail"),{code:"57P01"}),listener=(error:Error)=>events.push(`handled:${(error as Error&{code?:string}).code}`),database={end:async()=>{events.push("end");throw failure;},off:(event:"error",removed:(error:Error)=>void)=>{assert.equal(event,"error");assert.equal(removed,listener);events.push("off");}};await endNodeBrokerDatabase(database,listener);assert.deepEqual(events,["end","handled:57P01","off"]);});

test("broker attaches before use, sanitizes all pool events, and detaches after failed end",async()=>{const listeners=new Set<(error:Error)=>void>(),output:string[]=[],database={on:(event:"error",listener:(error:Error)=>void)=>{assert.equal(event,"error");listeners.add(listener);},off:(event:"error",listener:(error:Error)=>void)=>{assert.equal(event,"error");listeners.delete(listener);},end:async()=>{assert.equal(listeners.size,1);throw Object.assign(new Error("password detail"),{name:"SecretToken",code:"57P01"});}};const listener=attachNodeBrokerDatabasePoolErrors(database,(value)=>output.push(value));assert.equal(listeners.size,1);for(const error of [Object.assign(new Error("expected detail"),{code:"57P01"}),Object.assign(new Error("unexpected secret"),{name:"PasswordLeak",code:"bad"})])for(const active of listeners)active(error);await endNodeBrokerDatabase(database,listener);assert.equal(listeners.size,0);assert.deepEqual(output,["Node broker database pool error name=DatabasePoolError code=57P01\n","Node broker database pool error name=DatabasePoolError code=unknown\n","Node broker database pool error name=DatabasePoolError code=57P01\n"]);assert.doesNotMatch(output.join(""),/secret|password|detail|token/i);});
