import { pathToFileURL } from "node:url";
import { FileNodePlanSigner } from "./node-crypto.js";
import { TemplateNodePlanFactory } from "./node-plan.js";
import type { EnrollmentRecord, NodeArchitecture, NodePlatform } from "./node-types.js";

export async function validateNodePlanConfiguration(environment:NodeJS.ProcessEnv=process.env):Promise<void>{
  const template=required(environment,"NODE_INSTALL_PLAN_TEMPLATE_FILE");const privateKey=required(environment,"NODE_PLAN_SIGNING_PRIVATE_KEY_FILE");const keyId=required(environment,"NODE_PLAN_SIGNING_KEY_ID");
  const factory=new TemplateNodePlanFactory(template,new FileNodePlanSigner(keyId,privateKey));const cases:["fresh"|"adopt",NodePlatform,NodeArchitecture,string][]=[["fresh","linux","amd64","ubuntu-26.04-amd64-worker/v1"],["adopt","linux","amd64","existing-linux-worker-adopt/v1"],["adopt","macos","arm64","macos-lima-worker-adopt/v1"]];
  const planSigningKey=await factory.signingKey();for(let i=0;i<cases.length;i++){const [mode,platform,architecture,profile]=cases[i]!;const id=`00000000-0000-4000-8000-00000000000${i+1}`;const enrollment:EnrollmentRecord={id,workspaceId:"00000000-0000-4000-8000-000000000010",requestedName:mode==="fresh"?"fresh-node":platform==="macos"?"mac-mini-3":"existing-node",mode,expectedPlatform:platform,expectedArchitecture:architecture,tokenHash:"a".repeat(64),tokenKeyId:"node-enrollment/v1",idempotencyKey:`validate-profile-${i+1}`,createdBy:"00000000-0000-4000-8000-000000000011",planSigningKey,expiresAt:new Date("2030-01-01T00:00:00.000Z"),status:"pending",machineBinding:null,nodePublicKey:null,nodePublicKeyFingerprint:null,consumedByNodeId:null,version:1};const plan=await factory.create({planId:`00000000-0000-4000-8000-00000000002${i+1}`,nodeId:`00000000-0000-4000-8000-00000000003${i+1}`,enrollment,architecture,machineFingerprint:"b".repeat(64),nodePublicKeyFingerprint:"c".repeat(64),issuedAt:new Date("2029-01-01T00:00:00.000Z"),expiresAt:new Date("2029-01-01T00:15:00.000Z")});if(plan.installProfile!==profile)throw new Error(`expected rendered profile ${profile}`);}
}
function required(environment:NodeJS.ProcessEnv,name:string):string{const value=environment[name];if(!value)throw new Error(`${name} is required`);return value;}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){await validateNodePlanConfiguration();process.stdout.write("validated all Node install plan profiles\n");}
