import assert from "node:assert/strict";
import { generateKeyPairSync, randomUUID, sign } from "node:crypto";
import test from "node:test";
import { createDatabase } from "./db.js";
import { NodeService } from "./node-service.js";
import { PgNodeStore } from "./node-store.js";
import { NodeHttpError } from "./node-types.js";
import { canonicalJson, nodeInstallReceiptDigest, publicKeyFingerprint, renderedDigest } from "./node-crypto.js";

const adminUrl=process.env.NODE_TEST_ADMIN_DATABASE_URL;
const runtimeUrl=process.env.NODE_TEST_RUNTIME_DATABASE_URL;

test("PostgreSQL serializes enrollment replay and isolates workspaces",{skip:!adminUrl||!runtimeUrl},async()=>{
  const admin=createDatabase(adminUrl!),runtime=createDatabase(runtimeUrl!);const userId=randomUUID(),outsiderId=randomUUID(),workspaceId=randomUUID(),otherWorkspaceId=randomUUID();
  try{
    await admin.query("INSERT INTO users(id,email,display_name,password_salt,password_hash) VALUES($1,$2,'Node Operator','salt','hash'),($3,$4,'Outsider','salt','hash')",[userId,`node-${userId}@example.test`,outsiderId,`node-${outsiderId}@example.test`]);
    await admin.query("INSERT INTO workspaces(id,slug,name,created_by) VALUES($1,$2,'Node Test',$3),($4,$5,'Other',$6)",[workspaceId,`node-${userId.slice(0,8)}`,userId,otherWorkspaceId,`other-${outsiderId.slice(0,8)}`,outsiderId]);
    await admin.query("INSERT INTO workspace_memberships(workspace_id,user_id,role) VALUES($1,$2,'operator'),($3,$4,'owner'),($3,$2,'viewer')",[workspaceId,userId,otherWorkspaceId,outsiderId]);
    const serviceNow=(await admin.query<{now:Date}>("SELECT clock_timestamp()+interval '1 minute' AS now")).rows[0]!.now;const at=(seconds:number)=>new Date(serviceNow.getTime()+seconds*1000).toISOString();
    const signer=generateKeyPairSync("ed25519");
    const signingPublicKey=signer.publicKey.export({format:"jwk"}).x!;const planFactory={signingKey:async()=>({keyId:"test/v1",publicKey:signingPublicKey,fingerprint:`sha256:${publicKeyFingerprint(signingPublicKey)}`}),create:async(c:{planId:string;nodeId:string;enrollment:{id:string;workspaceId:string;idempotencyKey:string;createdBy:string;requestedName:string};issuedAt:Date;expiresAt:Date})=>{const digest=`sha256:${c.planId.replaceAll("-","").padEnd(64,"0")}`;return{schemaVersion:"nodes/v1alpha1",planId:c.planId,nodeId:c.nodeId,enrollmentId:c.enrollment.id,workspaceId:c.enrollment.workspaceId,idempotencyKey:c.enrollment.idempotencyKey,approvedBy:c.enrollment.createdBy,approvedAt:c.issuedAt.toISOString(),hostname:c.enrollment.requestedName,mode:"fresh",installProfile:"ubuntu-26.04-amd64-worker/v1",mutations:[],issuedAt:c.issuedAt.toISOString(),expiresAt:c.expiresAt.toISOString(),signingKeyId:"test/v1",digest,signature:sign(null,Buffer.from(`blazn-node-install-plan-v1\n${digest}`),signer.privateKey).toString("base64url")};}};
    const service=new NodeService(new PgNodeStore(runtime),async()=>Buffer.alloc(32,9),planFactory,()=>serviceNow);const principal={userId,email:"operator@example.test",displayName:"Operator"};
    const [first,second]=await Promise.all([service.createEnrollment(principal,workspaceId,"parallel-key",{name:"ben-fresh",mode:"fresh",platform:"linux",architecture:"amd64"}),service.createEnrollment(principal,workspaceId,"parallel-key",{name:"ben-fresh",mode:"fresh",platform:"linux",architecture:"amd64"})]);
    assert.equal(first.id,second.id);assert.equal(first.token,second.token);assert.equal([first.replayed,second.replayed].filter(Boolean).length,1);
    assert.deepEqual(first.planSigningKey,second.planSigningKey);
    const publicJwk=signer.publicKey.export({format:"jwk"});const exchange={token:first.token,machineFingerprint:"b".repeat(64),nodePublicKey:publicJwk.x!,platform:"linux" as const,architecture:"amd64" as const};
    const [planA,planB]=await Promise.all([service.exchangeEnrollment(first.id,exchange),service.exchangeEnrollment(first.id,exchange)]);assert.deepEqual(planA,planB);assert.equal(planA.identity.publicKeyFingerprint,`sha256:${publicKeyFingerprint(publicJwk.x!)}`);assert.equal(planA.identity.issuedAt,serviceNow.toISOString());
    const createdPlan=planA.plan as {planId:string;nodeId:string};const issuanceId=randomUUID();
    await admin.query(`INSERT INTO node_join_issuances(id,workspace_id,enrollment_id,plan_id,node_id,node_public_key_fingerprint,machine_fingerprint,credential_hash,credential_ciphertext,credential_key_id,idempotency_key,request_digest,issued_at,expires_at)
      VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'node-join-credential/v1','broker-issuance-key',$10,now(),now()+interval '10 minutes')`,[issuanceId,workspaceId,first.id,createdPlan.planId,createdPlan.nodeId,"b".repeat(64),"b".repeat(64),"c".repeat(64),Buffer.alloc(29),"d".repeat(64)]);
    const consumeBody={nodeId:createdPlan.nodeId,enrollmentId:first.id,planId:createdPlan.planId,joinedNodeUid:`uid-${createdPlan.nodeId}`,joinedNodeName:"ben-fresh",resourceVersion:"1",clusterId:`cluster-${createdPlan.nodeId}`};const consumeProof=nodeProof(signer.privateKey,"blazn-node-join-v1",consumeBody);
    const consumed=await Promise.all([service.consumeJoin(issuanceId,"consume-key",consumeBody,consumeProof),service.consumeJoin(issuanceId,"consume-key",consumeBody,consumeProof)]);assert.deepEqual(consumed[0],consumed[1]);
    const changed={...consumeBody,resourceVersion:"2"};await assert.rejects(()=>service.consumeJoin(issuanceId,"consume-key",changed,nodeProof(signer.privateKey,"blazn-node-join-v1",changed)),(e:unknown)=>e instanceof NodeHttpError&&e.code==="idempotency_conflict");
    await assert.rejects(()=>service.consumeJoin(issuanceId,"other-consume-key",consumeBody,consumeProof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="join_credential_consumed");
    const binding={clusterId:consumeBody.clusterId,nodeName:"ben-fresh",nodeUid:consumeBody.joinedNodeUid,resourceVersion:"1"};const capability=(version:number,resourceVersion="1")=>({version,host:{platform:"linux",architecture:"amd64",cpuMillis:1000,memoryBytes:1073741824,diskBytes:10737418240,accelerators:[],health:{status:"healthy",reasonCodes:[]}},worker:{platform:"linux",architecture:"amd64",allocatableCpuMillis:900,allocatableMemoryBytes:1073741824,allocatableDiskBytes:10737418240,labels:{},limits:{maxConcurrentSandboxes:2,maxConcurrentAgents:2},health:{status:"healthy",reasonCodes:[]},kubernetesBinding:{...binding,resourceVersion}},sandboxBackends:["agent-sandbox"],runtimeClasses:[],localModels:[]});
    const receipt:Record<string,unknown>={schemaVersion:"nodes/v1alpha1",receiptId:randomUUID(),planId:createdPlan.planId,planDigest:(planA.plan as {digest:string}).digest,nodeId:createdPlan.nodeId,generation:1,nodeIdentityGeneration:1,signerKind:"node_identity",signerFingerprint:`sha256:${publicKeyFingerprint(publicJwk.x!)}`,state:"active",currentStage:"complete",owner:{uid:0,pid:42,processStartIdentity:"start-1",nonce:"A".repeat(32)},binary:{path:"/usr/local/bin/blazn",digest:`sha256:${"b".repeat(64)}`},service:{manager:"systemd",name:"blazn-node.service",definitionDigest:`sha256:${"c".repeat(64)}`,priorEnabled:false,priorActive:false},mutations:[],residues:[],createdAt:at(0),updatedAt:at(1),signingKeyId:"node-identity/v1",digest:"",signature:""};receipt.digest=nodeInstallReceiptDigest(receipt);receipt.signature=sign(null,Buffer.from(`blazn-node-install-receipt-v1\n${receipt.digest}`),signer.privateKey).toString("base64url");const activation={expectedVersion:2,receipt,kubernetesBinding:binding},activationProof=nodeProof(signer.privateKey,"blazn-node-activation-v1",activation);const activated=await service.activate(activation,"activate-key",activationProof);assert.equal(activated.lifecycleState,"active");assert.equal(activated.trustState,"verified");assert.equal(activated.agentEligible,false);assert.deepEqual(await service.activate(activation,"activate-key",activationProof),activated);const conflicting={...activation,expectedVersion:3};await assert.rejects(()=>service.activate(conflicting,"activate-key",nodeProof(signer.privateKey,"blazn-node-activation-v1",conflicting)),(e:unknown)=>e instanceof NodeHttpError&&e.code==="idempotency_conflict");
    const heartbeat=(bootId:string,sequence:number,version:number,sentAt:string,resourceVersion="1")=>{const cap=capability(version,resourceVersion);const body={nodeId:createdPlan.nodeId,identityGeneration:1,bootId,sequence,sentAt,capabilityDigest:renderedDigest("blazn-node-capability-v1",cap),capability:cap};return{body,proof:nodeProof(signer.privateKey,"blazn-node-heartbeat-v1",body)};};
    const hb0=heartbeat("boot-a",0,1,at(0));await service.heartbeat(hb0.body,hb0.proof);assert.equal((await service.getNode(principal,createdPlan.nodeId)).agentEligible,true);const hb1=heartbeat("boot-a",1,1,at(1),"2");const heartbeatRace=await Promise.allSettled([service.heartbeat(hb1.body,hb1.proof),service.heartbeat(hb1.body,hb1.proof)]);assert.deepEqual(heartbeatRace.map(r=>r.status).sort(),["fulfilled","rejected"]);assert.equal((await service.getNode(principal,createdPlan.nodeId)).kubernetesBinding?.resourceVersion,"2");const stale=heartbeat("boot-a",2,1,at(2),"1");await assert.rejects(()=>service.heartbeat(stale.body,stale.proof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="state_conflict");
    const hbBootB=heartbeat("boot-b",0,2,at(3),"2");await service.heartbeat(hbBootB.body,hbBootB.proof);const alternating=heartbeat("boot-a",0,2,at(4),"2");await assert.rejects(()=>service.heartbeat(alternating.body,alternating.proof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="heartbeat_replay");const rollback=heartbeat("boot-b",1,1,at(5),"2");await assert.rejects(()=>service.heartbeat(rollback.body,rollback.proof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="state_conflict");
    const active=await service.getNode(principal,createdPlan.nodeId);const opRace=await Promise.allSettled([service.createOperation(principal,createdPlan.nodeId,"pause-race-a",{type:"pause",expectedVersion:active.version,parameters:{}}),service.createOperation(principal,createdPlan.nodeId,"pause-race-b",{type:"pause",expectedVersion:active.version,parameters:{}})]);assert.deepEqual(opRace.map(r=>r.status).sort(),["fulfilled","rejected"]);
    const event=(await service.eventBatch(principal,createdPlan.nodeId))[0];assert.ok(event);await assert.rejects(()=>service.eventBatch(principal,createdPlan.nodeId,randomUUID()),(e:unknown)=>e instanceof NodeHttpError&&e.code==="invalid_request");
    const foreignNode=randomUUID(),foreignOperation=randomUUID(),foreignEvent=randomUUID();await admin.query(`INSERT INTO nodes(id,workspace_id,name,kind,owner_user_id,machine_fingerprint,host_platform,host_architecture,lifecycle_state,trust_state,agent_eligible,service_version) VALUES($1,$2,'foreign','shared',$3,$4,'linux','amd64','pending','unverified',false,'pending')`,[foreignNode,workspaceId,userId,"e".repeat(64)]);await admin.query("INSERT INTO node_operations(id,workspace_id,node_id,type,status,expected_node_version,requested_by,idempotency_key,request_digest) VALUES($1,$2,$3,'repair','pending',1,$4,'foreign-event-key',$5)",[foreignOperation,workspaceId,foreignNode,userId,"f".repeat(64)]);await admin.query("INSERT INTO node_operation_events(id,operation_id,sequence,type,payload) VALUES($1,$2,0,'operation.pending','{}')",[foreignEvent,foreignOperation]);await assert.rejects(()=>service.eventBatch(principal,createdPlan.nodeId,foreignEvent),(e:unknown)=>e instanceof NodeHttpError&&e.code==="invalid_request");
    await assert.rejects(()=>service.getNode({userId:outsiderId,email:"outsider@example.test",displayName:"Outsider"},createdPlan.nodeId),(e:unknown)=>e instanceof NodeHttpError&&e.code==="membership_required");
    await admin.query("UPDATE node_install_plans SET issued_at=clock_timestamp()-interval '2 minutes',expires_at=clock_timestamp()-interval '1 minute' WHERE id=$1",[createdPlan.planId]);assert.deepEqual(await service.activate(activation,"activate-key",activationProof),await service.getNode(principal,createdPlan.nodeId));
    await admin.query("UPDATE node_identities SET issued_at=statement_timestamp()-interval '2 hours',expires_at=statement_timestamp()-interval '1 hour' WHERE node_id=$1 AND generation=1",[createdPlan.nodeId]);const expired=heartbeat("boot-b",1,3,at(6),"2");await assert.rejects(()=>service.heartbeat(expired.body,expired.proof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="identity_rejected");
    const own=await service.listNodes(principal,workspaceId);assert.equal(own.items.length,2);
    assert.equal((await service.listNodes(principal,otherWorkspaceId)).items.length,0);
    await assert.rejects(()=>service.createEnrollment(principal,otherWorkspaceId,"denied-key",{name:"ben-denied",mode:"fresh",platform:"linux",architecture:"amd64"}),(e:unknown)=>e instanceof NodeHttpError&&e.code==="permission_denied");
    const leaked=await admin.query("SELECT response_body::text body FROM workspace_idempotency_receipts WHERE principal_id=$1",[userId]);assert.equal(leaked.rows.some(r=>r.body.includes(first.token)),false);
  }finally{
    await admin.query("DELETE FROM workspaces WHERE id=ANY($1::uuid[])",[[workspaceId,otherWorkspaceId]]).catch(()=>{});await admin.query("DELETE FROM users WHERE id=ANY($1::uuid[])",[[userId,outsiderId]]).catch(()=>{});await runtime.end();await admin.end();
  }
});

function nodeProof(privateKey:ReturnType<typeof generateKeyPairSync>["privateKey"],prefix:string,body:unknown):string{return sign(null,Buffer.from(`${prefix}\n${canonicalJson(body)}`),privateKey).toString("base64url");}
