import { canonicalJson, sha256Hex } from "./node-crypto.js";

export const NODE_INSTALL_PROFILES=["ubuntu-26.04-amd64-worker/v1","existing-linux-worker-adopt/v1","macos-lima-worker-adopt/v1"] as const;
export type NodeInstallProfile=typeof NODE_INSTALL_PROFILES[number];
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const HEX=/^[0-9a-f]{64}$/;const DIGEST=/^sha256:[0-9a-f]{64}$/;const HOST=/^[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?$/;
const TOP=["schemaVersion","planId","nodeId","enrollmentId","workspaceId","idempotencyKey","approvedBy","approvedAt","hostname","mode","installProfile","cluster","target","registryTrust","components","nodeService","labels","taints","resourceBounds","mutations","validationTests","rollback","issuedAt","expiresAt","signingKeyId","digest","signature"];

export function validateSignedNodeInstallPlan(plan:Record<string,unknown>,expectedProfile:NodeInstallProfile,expectedKeyId:string):void{
  exact(plan,TOP,"plan");eq(plan.schemaVersion,"nodes/v1alpha1","schemaVersion");for(const k of ["planId","nodeId","enrollmentId","workspaceId","approvedBy"])pattern(plan[k],UUID,k);bounded(plan.idempotencyKey,8,128,"idempotencyKey");date(plan.approvedAt,"approvedAt");pattern(plan.hostname,/^[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?$/,"hostname");one(plan.mode,["fresh","adopt"],"mode");eq(plan.installProfile,expectedProfile,"installProfile");date(plan.issuedAt,"issuedAt");date(plan.expiresAt,"expiresAt");if(Date.parse(String(plan.approvedAt))>Date.parse(String(plan.issuedAt))||Date.parse(String(plan.issuedAt))>=Date.parse(String(plan.expiresAt)))fail("plan timestamps are not ordered");eq(plan.signingKeyId,expectedKeyId,"signingKeyId");pattern(plan.digest,DIGEST,"digest");pattern(plan.signature,/^[A-Za-z0-9_-]{86}$/,"signature");
  const unsigned={...plan};delete unsigned.digest;delete unsigned.signature;eq(plan.digest,`sha256:${sha256Hex(canonicalJson(unsigned))}`,"digest");
  validateCluster(record(plan.cluster,"cluster"));validateTarget(record(plan.target,"target"));const components=array(plan.components,64,"components");components.forEach((v,i)=>validateComponent(record(v,`components[${i}]`)));array(plan.registryTrust,16,"registryTrust").forEach((v,i)=>validateRegistry(record(v,`registryTrust[${i}]`)));validateService(record(plan.nodeService,"nodeService"));validateLabels(record(plan.labels,"labels"));array(plan.taints,16,"taints").forEach((v,i)=>validateTaint(record(v,`taints[${i}]`)));validateBounds(record(plan.resourceBounds,"resourceBounds"));const mutations=array(plan.mutations,256,"mutations");mutations.forEach((v,i)=>validateMutation(record(v,`mutations[${i}]`)));validateTests(array(plan.validationTests,32,"validationTests"));validateRollback(record(plan.rollback,"rollback"));
  if(plan.mode==="fresh"&&(components.length<1||mutations.length<1))fail("fresh profile requires components and mutations");validateProfile(plan,expectedProfile,components as Record<string,unknown>[],mutations as Record<string,unknown>[]);
}

function validateCluster(v:Record<string,unknown>){exact(v,["id","workerOnly","apiServer","kubernetesVersion","joinCredentialEndpoint","bootstrapTaint","expectedCaFingerprint","registryEndpoints"],"cluster");bounded(v.id,1,128,"cluster.id");eq(v.workerOnly,true,"cluster.workerOnly");uri(v.apiServer,"cluster.apiServer",true);pattern(v.kubernetesVersion,/^v[0-9]+\.[0-9]+\.[0-9]+$/,"cluster.kubernetesVersion");eq(v.joinCredentialEndpoint,"/v1/node-service/join-credentials","cluster.joinCredentialEndpoint");eq(v.bootstrapTaint,"blazn.dev/bootstrap=pending:NoSchedule","cluster.bootstrapTaint");pattern(v.expectedCaFingerprint,DIGEST,"cluster.expectedCaFingerprint");unique(array(v.registryEndpoints,16,"cluster.registryEndpoints"),"cluster.registryEndpoints").forEach((x)=>uri(x,"registry endpoint",true));}
function validateTarget(v:Record<string,unknown>){exact(v,["platform","architecture","machineFingerprint","nodePublicKeyFingerprint","minCpu","minMemoryBytes","minDiskBytes"],"target");one(v.platform,["linux","macos"],"target.platform");one(v.architecture,["amd64","arm64"],"target.architecture");pattern(v.machineFingerprint,HEX,"target.machineFingerprint");pattern(v.nodePublicKeyFingerprint,DIGEST,"target.nodePublicKeyFingerprint");integer(v.minCpu,1,undefined,"target.minCpu");integer(v.minMemoryBytes,1073741824,undefined,"target.minMemoryBytes");integer(v.minDiskBytes,10737418240,undefined,"target.minDiskBytes");}
function validateRegistry(v:Record<string,unknown>){exact(v,["hostname","caBundleSha256"],"registryTrust");pattern(v.hostname,HOST,"registryTrust.hostname");pattern(v.caBundleSha256,HEX,"registryTrust.caBundleSha256");}
function validateComponent(v:Record<string,unknown>){const base=["name","artifactType","sourceClass","version","publisher","sha256","ownership"];const type=one(v.artifactType,["package","binary","image","certificate","configuration"],"component.artifactType");const sourceClass=one(v.sourceClass,["https","current_binary","embedded"],"component.sourceClass");const sourceFields=sourceClass==="https"?["sourceHost","source"]:[];const extras=type==="package"?["repositoryOrigin"]:type==="image"?["registryHost","ociReference"]:[];exact(v,[...base,...sourceFields,...extras],"component");bounded(v.name,1,128,"component.name");bounded(v.version,1,128,"component.version");bounded(v.publisher,1,256,"component.publisher");pattern(v.sha256,HEX,"component.sha256");one(v.ownership,["install","adopt_exact"],"component.ownership");if(sourceClass==="https"){pattern(v.sourceHost,HOST,"component.sourceHost");const source=uri(v.source,"component.source",true);if(source.hostname!==v.sourceHost)fail("component source host differs from sourceHost");}if(sourceClass==="current_binary"&&type!=="binary")fail("current_binary source must be a binary");if(sourceClass==="embedded"&&type!=="certificate"&&type!=="configuration")fail("embedded source must be a certificate or configuration");if((type==="package"||type==="image")&&sourceClass!=="https")fail("package and image components require https sourceClass");if(type==="package"){const origin=uri(v.repositoryOrigin,"component.repositoryOrigin",true);if(origin.origin!==v.repositoryOrigin||origin.hostname!==v.sourceHost)fail("component repository origin is not exact or differs from sourceHost");}if(type==="image"){pattern(v.registryHost,HOST,"component.registryHost");const reference=pattern(v.ociReference,/^[A-Za-z0-9._:/-]+@sha256:[0-9a-f]{64}$/,"component.ociReference");if(!reference.startsWith(`${String(v.registryHost)}/`)||reference.split("@sha256:")[1]!==v.sha256)fail("component image registry or digest is not bound");}}
function validateService(v:Record<string,unknown>){exact(v,["manager","unitName","binaryPath","runAsUser","runAsGroup","definitionSha256"],"nodeService");one(v.manager,["systemd","launchd"],"nodeService.manager");bounded(v.unitName,1,256,"nodeService.unitName");pattern(v.binaryPath,/^\//,"nodeService.binaryPath");bounded(v.runAsUser,1,128,"nodeService.runAsUser");bounded(v.runAsGroup,1,128,"nodeService.runAsGroup");pattern(v.definitionSha256,HEX,"nodeService.definitionSha256");}
function validateLabels(v:Record<string,unknown>){if(Object.keys(v).length>64)fail("too many labels");for(const[k,value]of Object.entries(v)){pattern(k,/^blazn\.dev\/[a-z0-9][a-z0-9._-]{0,62}$/,"label key");if(typeof value!=="string"||value.length>128)fail("label value is invalid");}}
function validateTaint(v:Record<string,unknown>){exact(v,["key","value","effect"],"taint");pattern(v.key,/^blazn\.dev\/[a-z0-9][a-z0-9._-]{0,62}$/,"taint.key");if(typeof v.value!=="string"||v.value.length>128)fail("taint.value is invalid");one(v.effect,["NoSchedule","PreferNoSchedule","NoExecute"],"taint.effect");}
function validateBounds(v:Record<string,unknown>){exact(v,["reservedCpuMillis","reservedMemoryBytes","maxPods","maxConcurrentAgents"],"resourceBounds");integer(v.reservedCpuMillis,0,undefined,"reservedCpuMillis");integer(v.reservedMemoryBytes,0,undefined,"reservedMemoryBytes");integer(v.maxPods,1,4096,"maxPods");integer(v.maxConcurrentAgents,1,1024,"maxConcurrentAgents");}
function validateMutation(v:Record<string,unknown>){exact(v,["ordinal","kind","action","target","desired","desiredDigest","mode","uid","gid","rollback"],"mutation");integer(v.ordinal,1,undefined,"mutation.ordinal");const kind=one(v.kind,["group","user","package","file","directory","systemd_unit","launchd_unit","certificate","image","label","taint","firewall"],"mutation.kind");const action=one(v.action,["install","write","create","enable","pull","apply","adopt_exact"],"mutation.action");const target=bounded(v.target,1,1024,"mutation.target");if(target==="/"||/(?:^|\/)\.\.(?:\/|$)/.test(target))fail("mutation target is unsafe");pattern(v.desiredDigest,DIGEST,"mutation.desiredDigest");integer(v.mode,0,4095,"mutation.mode");integer(v.uid,0,undefined,"mutation.uid");integer(v.gid,0,undefined,"mutation.gid");one(v.rollback,["restore_prior","remove_if_owned","leave_and_report"],"mutation.rollback");const d=record(v.desired,"mutation.desired");if(Object.keys(d).length>32)fail("mutation desired has too many fields");
  if(kind==="group"){one(action,["create","adopt_exact"],"group.action");pattern(target,/^[a-z_][a-z0-9_-]{0,31}$/,"group.target");exact(d,["name","gid","system"],"group.desired");eq(d.name,target,"group.name");integer(d.gid,1,undefined,"group.gid");eq(v.mode,0,"group.mode");eq(v.uid,0,"group.uid");eq(v.gid,d.gid,"group gid binding");eq(d.system,true,"group.system");}
  else if(kind==="user"){one(action,["create","adopt_exact"],"user.action");pattern(target,/^[a-z_][a-z0-9_-]{0,31}$/,"user.target");exact(d,["name","group","uid","gid","home","shell","system"],"user.desired");eq(d.name,target,"user.name");pattern(d.group,/^[a-z_][a-z0-9_-]{0,31}$/,"user.group");integer(d.uid,1,undefined,"user.uid");integer(d.gid,1,undefined,"user.gid");eq(v.mode,0,"user.mode");eq(v.uid,d.uid,"user uid binding");eq(v.gid,d.gid,"user gid binding");eq(d.home,"/var/lib/blazn","user.home");one(d.shell,["/usr/sbin/nologin","/sbin/nologin"],"user.shell");eq(d.system,true,"user.system");}
  else if(kind==="package"){one(action,["install","adopt_exact"],"package.action");pattern(target,/^[a-z0-9][a-z0-9+.-]{0,127}$/,"package.target");exact(d,["manager","version","componentName"],"package.desired");one(d.manager,["apt","snap","brew"],"package.manager");bounded(d.version,1,128,"package.version");bounded(d.componentName,1,128,"package.componentName");}
  else if(kind==="file"||kind==="certificate"){one(action,["write","adopt_exact"],"file.action");pattern(target,/^\/(?:usr\/local\/bin|etc\/blazn|var\/lib\/blazn|Library\/Application Support\/Blazn)\//,"file.target");exact(d,["sourceComponent","contentSha256"],"file.desired");bounded(d.sourceComponent,1,128,"sourceComponent");pattern(d.contentSha256,HEX,"contentSha256");}
  else if(kind==="directory"){one(action,["create","adopt_exact"],"directory.action");pattern(target,/^\/(?:etc\/blazn|var\/lib\/blazn|opt\/blazn|Library\/Application Support\/Blazn)(?:\/|$)/,"directory.target");exact(d,[],"directory.desired");}
  else if(kind==="systemd_unit"){one(action,["write","enable","adopt_exact"],"systemd.action");pattern(target,/^\/etc\/systemd\/system\/[A-Za-z0-9_.@-]+\.service$/,"systemd.target");exact(d,["unitName","sourceComponent"],"systemd.desired");pattern(d.unitName,/^[A-Za-z0-9_.@-]+\.service$/,"unitName");bounded(d.sourceComponent,1,128,"sourceComponent");}
  else if(kind==="launchd_unit"){one(action,["write","enable","adopt_exact"],"launchd.action");pattern(target,/^\/Library\/LaunchDaemons\/[A-Za-z0-9_.-]+\.plist$/,"launchd.target");exact(d,["label","sourceComponent"],"launchd.desired");bounded(d.label,1,256,"label");bounded(d.sourceComponent,1,128,"sourceComponent");}
  else if(kind==="image"){one(action,["pull","adopt_exact"],"image.action");pattern(target,/^[A-Za-z0-9._:/-]+@sha256:[0-9a-f]{64}$/,"image.target");exact(d,["platform","componentName"],"image.desired");one(d.platform,["linux/amd64","linux/arm64"],"image.platform");bounded(d.componentName,1,128,"componentName");}
  else if(kind==="label"){eq(action,"apply","label.action");pattern(target,/^blazn\.dev\/[a-z0-9][a-z0-9._-]{0,62}$/,"label.target");exact(d,["value"],"label.desired");if(typeof d.value!=="string"||d.value.length>128)fail("label value is invalid");}
  else if(kind==="taint"){eq(action,"apply","taint.action");pattern(target,/^blazn\.dev\/[a-z0-9][a-z0-9._-]{0,62}$/,"taint.target");exact(d,["value","effect"],"taint.desired");if(typeof d.value!=="string"||d.value.length>128)fail("taint value is invalid");one(d.effect,["NoSchedule","PreferNoSchedule","NoExecute"],"taint.effect");}
  else if(kind==="firewall"){eq(action,"apply","firewall.action");pattern(target,/^blazn:[a-z0-9_-]{1,64}$/,"firewall.target");exact(d,["protocol","port","direction"],"firewall.desired");one(d.protocol,["tcp","udp"],"firewall.protocol");integer(d.port,1,65535,"firewall.port");one(d.direction,["ingress","egress"],"firewall.direction");}
}
function validateTests(v:unknown[]){if(v.length<1)fail("validationTests cannot be empty");unique(v,"validationTests");for(const item of v)one(item,["binary_digest","service_account","service_active","node_identity","cluster_ca","worker_only","lima_worker_binding","node_uid_binding","bootstrap_taint","capability_heartbeat","agent_eligibility"],"validationTest");}
function validateRollback(v:Record<string,unknown>){exact(v,["preserveUserData","preserveControlPlane","ambiguousOwnership","backupRootClass","backupRoot"],"rollback");eq(v.preserveUserData,true,"preserveUserData");eq(v.preserveControlPlane,true,"preserveControlPlane");eq(v.ambiguousOwnership,"recovery_required","ambiguousOwnership");const c=one(v.backupRootClass,["linux_var_lib","macos_library_application_support"],"backupRootClass");const p=bounded(v.backupRoot,1,1024,"backupRoot");if(/(?:^|\/)\.\.(?:\/|$)/.test(p))fail("backupRoot is unsafe");pattern(p,c==="linux_var_lib"?/^\/var\/lib\/blazn\/install-backups\/[A-Za-z0-9_-]{1,128}$/:/^\/Library\/Application Support\/Blazn\/install-backups\/[A-Za-z0-9_-]{1,128}$/,"backupRoot");}
function validateProfile(plan:Record<string,unknown>,profile:NodeInstallProfile,components:Record<string,unknown>[],mutations:Record<string,unknown>[]){const target=plan.target as Record<string,unknown>,service=plan.nodeService as Record<string,unknown>,rollback=plan.rollback as Record<string,unknown>,tests=plan.validationTests as unknown[];const componentNames=new Set(components.map(c=>String(c.name)));if(componentNames.size!==components.length)fail("component names must be unique");const ordinals=new Set(mutations.map(m=>Number(m.ordinal)));if(ordinals.size!==mutations.length)fail("mutation ordinals must be unique");const byName=new Map(components.map(c=>[String(c.name),c]));
  for(const m of mutations){const d=m.desired as Record<string,unknown>,componentName=d.componentName??d.sourceComponent;if(componentName!==undefined&&!componentNames.has(String(componentName)))fail(`mutation references missing component ${String(componentName)}`);const component=componentName===undefined?undefined:byName.get(String(componentName));if(m.kind==="package"){if(component?.artifactType!=="package"||m.target!==component.name||d.version!==component.version)fail("package mutation is not bound to its package component name, target, and version");const origin=uri(component.repositoryOrigin,"package.repositoryOrigin",true);if(origin.hostname!==component.sourceHost)fail("package repository origin differs from sourceHost");}else if(m.kind==="image"){if(component?.artifactType!=="image"||m.target!==component.ociReference||!String(m.target).startsWith(`${String(component.registryHost)}/`)||String(m.target).split("@sha256:")[1]!==component.sha256)fail("image mutation is not bound to its image component registry and digest");}else if(m.kind==="file"){if(!component||!(["binary","configuration"] as unknown[]).includes(component.artifactType)||d.contentSha256!==component.sha256||m.desiredDigest!==`sha256:${String(component.sha256)}`)fail("file mutation does not match its signed component");if(component.artifactType==="binary"&&(component.sourceClass!=="current_binary"||m.target!==service.binaryPath))fail("current binary may only populate the node service binary path");if(component.artifactType==="configuration"&&(component.sourceClass!=="embedded"||m.target===service.binaryPath))fail("embedded configuration cannot populate the node service binary path");}else if(m.kind==="certificate"){if(component?.artifactType!=="certificate"||component.sourceClass!=="embedded"||d.contentSha256!==component.sha256||m.desiredDigest!==`sha256:${String(component.sha256)}`)fail("certificate mutation does not match its embedded component");}else if(m.kind==="systemd_unit"||m.kind==="launchd_unit"){if(component?.artifactType!=="configuration"||component.sourceClass!=="embedded"||component.sha256!==service.definitionSha256||m.desiredDigest!==`sha256:${String(component.sha256)}`)fail("service mutation does not match its embedded signed definition");if(m.kind==="systemd_unit"&&String(m.target).split("/").at(-1)!==d.unitName)fail("systemd target basename differs from unitName");}}
  const serviceBinary=mutations.filter(m=>{const d=m.desired as Record<string,unknown>,c=byName.get(String(d.sourceComponent));return m.kind==="file"&&m.target===service.binaryPath&&m.action==="adopt_exact"&&c?.artifactType==="binary"&&c.sourceClass==="current_binary"&&c.ownership==="adopt_exact"&&d.contentSha256===c.sha256&&m.desiredDigest===`sha256:${String(c.sha256)}`;});if(!tests.includes("binary_digest")||serviceBinary.length!==1)fail("node service binary lacks one authenticated current-binary mutation");
  const mac=profile==="macos-lima-worker-adopt/v1",fresh=profile==="ubuntu-26.04-amd64-worker/v1";eq(plan.mode,fresh?"fresh":"adopt","profile mode");eq(target.platform,mac?"macos":"linux","profile platform");eq(target.architecture,mac?"arm64":"amd64","profile architecture");eq(service.manager,mac?"launchd":"systemd","profile service manager");eq(rollback.backupRootClass,mac?"macos_library_application_support":"linux_var_lib","profile backup root");if(mac){eq(service.runAsUser,"root","macOS service user");eq(service.runAsGroup,"wheel","macOS service group");if(mutations.some(m=>m.kind==="systemd_unit"||m.kind==="group"||m.kind==="user"||(m.kind==="package"&&(m.desired as Record<string,unknown>).manager!=="brew")))fail("macOS profile contains a Linux mutation");if(!tests.includes("lima_worker_binding"))fail("macOS profile must verify its Lima worker binding");const binding=components.find(c=>c.name==="lima-worker-binding"&&c.artifactType==="configuration"&&c.sourceClass==="embedded");if(!binding||!mutations.some(m=>{const d=m.desired as Record<string,unknown>;return m.kind==="file"&&m.target==="/Library/Application Support/Blazn/lima-worker-binding.json"&&d.sourceComponent==="lima-worker-binding"&&d.contentSha256===binding.sha256&&m.desiredDigest===`sha256:${String(binding.sha256)}`;}))fail("macOS profile requires an embedded Lima binding configuration");}else{eq(service.runAsUser,"blazn-node","Linux service user");eq(service.runAsGroup,"blazn-node","Linux service group");if(mutations.some(m=>m.kind==="launchd_unit"||(m.kind==="package"&&(m.desired as Record<string,unknown>).manager==="brew")))fail("Linux profile contains a macOS mutation");if(fresh){if(!tests.includes("service_account"))fail("fresh Linux profile must verify its service account");const groupMutation=mutations.find(m=>m.kind==="group"&&m.target===service.runAsGroup),userMutation=mutations.find(m=>m.kind==="user"&&m.target===service.runAsUser),dataMutation=mutations.find(m=>m.kind==="directory"&&m.target==="/var/lib/blazn");if(!groupMutation||!userMutation||!dataMutation)fail("fresh Linux profile must create its service account and data directory");const userDesired=userMutation.desired as Record<string,unknown>;eq(userDesired.group,service.runAsGroup,"fresh Linux user group");if(Number(groupMutation.ordinal)>=Number(userMutation.ordinal)||Number(userMutation.ordinal)>=Number(dataMutation.ordinal)||groupMutation.gid!==userMutation.gid||userMutation.uid!==dataMutation.uid||userMutation.gid!==dataMutation.gid||(Number(dataMutation.mode)&0o300)!==0o300)fail("fresh Linux service account and data ownership are not safely ordered and bound");}}for(const m of mutations)if(m.kind==="image")eq((m.desired as Record<string,unknown>).platform,mac?"linux/arm64":"linux/amd64","profile image platform");}

function exact(v:Record<string,unknown>,keys:string[],name:string){if(Object.keys(v).length!==keys.length||keys.some(k=>!(k in v))||Object.keys(v).some(k=>!keys.includes(k)))fail(`${name} has unsupported or missing fields`);}
function record(v:unknown,name:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))fail(`${name} must be an object`);return v as Record<string,unknown>;}
function array(v:unknown,max:number,name:string):unknown[]{if(!Array.isArray(v)||v.length>max)fail(`${name} must be an array with at most ${max} items`);return v;}
function unique(v:unknown[],name:string):unknown[]{const values=v.map(canonicalJson);if(new Set(values).size!==values.length)fail(`${name} contains duplicates`);return v;}
function bounded(v:unknown,min:number,max:number,name:string):string{if(typeof v!=="string"||v.length<min||v.length>max)fail(`${name} has invalid length`);return v;}
function pattern(v:unknown,p:RegExp,name:string):string{if(typeof v!=="string"||!p.test(v))fail(`${name} has invalid format`);return v;}
function integer(v:unknown,min:number,max:number|undefined,name:string){if(typeof v!=="number"||!Number.isSafeInteger(v)||v<min||(max!==undefined&&v>max))fail(`${name} is invalid`);}
function one<T extends string>(v:unknown,values:readonly T[],name:string):T{if(typeof v!=="string"||!values.includes(v as T))fail(`${name} is invalid`);return v as T;}
function eq(actual:unknown,expected:unknown,name:string){if(actual!==expected)fail(`${name} is invalid`);}
function date(v:unknown,name:string){if(typeof v!=="string"||!Number.isFinite(Date.parse(v))||new Date(v).toISOString()!==v)fail(`${name} must be a canonical date-time`);}
function uri(v:unknown,name:string,https:boolean):URL{const text=bounded(v,1,2048,name);let u:URL;try{u=new URL(text);}catch{fail(`${name} is not a URL`);}if(https&&u!.protocol!=="https:")fail(`${name} must use https`);return u!;}
function fail(message:string):never{throw new Error(`invalid NodeInstallPlan: ${message}`);}
