import assert from "node:assert/strict";
import { generateKeyPairSync, sign } from "node:crypto";
import test from "node:test";
import { canonicalJson, enrollmentToken, nodeInstallReceiptDigest, publicKeyFingerprint, renderedDigest, requestDigest, sha256Hex } from "./node-crypto.js";
import { NodeService, type HeartbeatInput } from "./node-service.js";
import type { NodeIdempotencyReceipt, NodeStore, NodeTransaction } from "./node-store.js";
import { NodeHttpError } from "./node-types.js";

const workspaceId="11111111-1111-4111-8111-111111111111",userId="22222222-2222-4222-8222-222222222222",nodeId="33333333-3333-4333-8333-333333333333";
const principal={userId,email:"operator@example.test",displayName:"Operator"};
const signingPublicKey="A".repeat(43);const planSigningKey={keyId:"test/v1",publicKey:signingPublicKey,fingerprint:`sha256:${publicKeyFingerprint(signingPublicKey)}`};
const planFactory={signingKey:async()=>planSigningKey,create:async()=>({digest:`sha256:${"a".repeat(64)}`,signature:"b".repeat(86),signingKeyId:"test/v1"}),signActivationGrant:async(unsigned:Record<string,unknown>)=>({...unsigned,signingKeyId:"test/v1",digest:`sha256:${"e".repeat(64)}`,signature:"f".repeat(86)})};

test("enrollment is authorized before replay and reconstructs no stored secret",async()=>{
  const key=Buffer.alloc(32,7);let authorized=true;const receipts=new Map<string,NodeIdempotencyReceipt>();let insertedTokenHash="";let enrollmentId="";let insertedEnrollment:Parameters<NodeTransaction["insertEnrollment"]>[0]|undefined;
  const tx=baseTx({
    authority:async()=>authorized?{workspaceId,role:"operator",workspaceStatus:"active"}:undefined,
    getIdempotency:async(_p,_o,k)=>receipts.get(k),
    putIdempotency:async(_p,_o,k,r)=>{receipts.set(k,r);},
    insertEnrollment:async(v)=>{insertedEnrollment=v;insertedTokenHash=v.tokenHash;enrollmentId=v.id;},
    enrollmentById:async()=>insertedEnrollment?{id:insertedEnrollment.id,workspaceId:insertedEnrollment.workspaceId,requestedName:insertedEnrollment.name,mode:insertedEnrollment.mode as "fresh",expectedPlatform:insertedEnrollment.platform as "linux",expectedArchitecture:"amd64",tokenHash:insertedEnrollment.tokenHash,tokenKeyId:"node-enrollment/v1",idempotencyKey:insertedEnrollment.idempotencyKey,createdBy:insertedEnrollment.createdBy,planSigningKey:insertedEnrollment.planSigningKey,expiresAt:insertedEnrollment.expiresAt,status:"pending",machineBinding:null,nodePublicKey:null,nodePublicKeyFingerprint:null,consumedByNodeId:null,version:1}:undefined,
  });
  const service=new NodeService(store(tx),async()=>key,planFactory,()=>new Date("2026-08-22T12:00:00Z"));
  const first=await service.createEnrollment(principal,workspaceId,"same-key-1",{name:"ben-new",mode:"fresh",platform:"linux",architecture:"amd64"});
  const replay=await service.createEnrollment(principal,workspaceId,"same-key-1",{name:"ben-new",mode:"fresh",platform:"linux",architecture:"amd64"});
  assert.equal(replay.token,first.token);assert.equal(replay.replayed,true);assert.equal(first.token,enrollmentToken(key,workspaceId,enrollmentId,userId,"same-key-1"));assert.equal(insertedTokenHash.length,64);
  assert.deepEqual(first.planSigningKey,planSigningKey);assert.deepEqual(replay.planSigningKey,planSigningKey);
  assert.equal(JSON.stringify([...receipts.values()]).includes(first.token),false);
  authorized=false;
  await assert.rejects(()=>service.createEnrollment(principal,workspaceId,"same-key-1",{name:"ben-new",mode:"fresh",platform:"linux",architecture:"amd64"}),(e:unknown)=>e instanceof NodeHttpError&&e.code==="membership_required");
});

test("enrollment exchange fails closed when the configured plan signer differs from pinned trust",async()=>{const token="t".repeat(43),pair=generateKeyPairSync("ed25519"),nodePublicKey=pair.publicKey.export({format:"jwk"}).x!;let plans=0;const enrollment={id:"44444444-4444-4444-8444-444444444444",workspaceId,requestedName:"ben-new",mode:"fresh" as const,expectedPlatform:"linux" as const,expectedArchitecture:"amd64" as const,tokenHash:sha256Hex(token),tokenKeyId:"node-enrollment/v1" as const,idempotencyKey:"exchange-key",createdBy:userId,planSigningKey,expiresAt:new Date("2026-08-22T12:15:00Z"),status:"pending" as const,machineBinding:null,nodePublicKey:null,nodePublicKeyFingerprint:null,consumedByNodeId:null,version:1};const rotatedPublicKey="B".repeat(43);const factory={signingKey:async()=>({keyId:"test/v2",publicKey:rotatedPublicKey,fingerprint:`sha256:${publicKeyFingerprint(rotatedPublicKey)}`}),create:async()=>{plans++;return{};}};const service=new NodeService(store(baseTx({enrollmentById:async()=>enrollment})),async()=>Buffer.alloc(32),factory,()=>new Date("2026-08-22T12:00:00Z"));await assert.rejects(()=>service.exchangeEnrollment(enrollment.id,{token,machineFingerprint:"c".repeat(64),nodePublicKey,platform:"linux",architecture:"amd64"}),/configured Node plan signer does not match enrollment-pinned trust/);assert.equal(plans,0);});

test("enrollment exchange maps a conflicting active machine to state_conflict",async()=>{const pair=generateKeyPairSync("ed25519"),nodePublicKey=pair.publicKey.export({format:"jwk"}).x!,conflict=Object.assign(new Error("duplicate machine"),{code:"23505"});const rejectingStore={transaction:async()=>{throw conflict;}} as unknown as NodeStore;const service=new NodeService(rejectingStore,async()=>Buffer.alloc(32),planFactory,()=>new Date("2026-08-22T12:00:00Z"));await assert.rejects(()=>service.exchangeEnrollment("44444444-4444-4444-8444-444444444444",{token:"t".repeat(43),machineFingerprint:"c".repeat(64),nodePublicKey,platform:"linux",architecture:"amd64"}),(error:unknown)=>error instanceof NodeHttpError&&error.code==="state_conflict"&&error.status===409);});

test("enrollment exchange rejects a plan signed after the key rotates between trust check and signing",async()=>{const token="r".repeat(43),nodePair=generateKeyPairSync("ed25519"),pinnedPair=generateKeyPairSync("ed25519"),rotatedPair=generateKeyPairSync("ed25519"),nodePublicKey=nodePair.publicKey.export({format:"jwk"}).x!,pinnedPublicKey=pinnedPair.publicKey.export({format:"jwk"}).x!,pinnedSigningKey={keyId:"test/v1",publicKey:pinnedPublicKey,fingerprint:`sha256:${publicKeyFingerprint(pinnedPublicKey)}`},digest=`sha256:${"d".repeat(64)}`,rotatedSignature=sign(null,Buffer.from(`blazn-node-install-plan-v1\n${digest}`),rotatedPair.privateKey).toString("base64url");let writes=0;const enrollment={id:"44444444-4444-4444-8444-444444444444",workspaceId,requestedName:"ben-new",mode:"fresh" as const,expectedPlatform:"linux" as const,expectedArchitecture:"amd64" as const,tokenHash:sha256Hex(token),tokenKeyId:"node-enrollment/v1" as const,idempotencyKey:"exchange-key",createdBy:userId,planSigningKey:pinnedSigningKey,expiresAt:new Date("2026-08-22T12:15:00Z"),status:"pending" as const,machineBinding:null,nodePublicKey:null,nodePublicKeyFingerprint:null,consumedByNodeId:null,version:1};const factory={signingKey:async()=>pinnedSigningKey,create:async()=>({signingKeyId:pinnedSigningKey.keyId,digest,signature:rotatedSignature})};const service=new NodeService(store(baseTx({enrollmentById:async()=>enrollment,createExchangedNode:async()=>{writes++;return{generation:1,signingKeyId:"node-identity/v1",publicKeyFingerprint:`sha256:${publicKeyFingerprint(nodePublicKey)}`,issuedAt:"2026-08-22T12:00:00.000Z",expiresAt:"2026-09-21T12:00:00.000Z"};}})),async()=>Buffer.alloc(32),factory,()=>new Date("2026-08-22T12:00:00Z"));await assert.rejects(()=>service.exchangeEnrollment(enrollment.id,{token,machineFingerprint:"c".repeat(64),nodePublicKey,platform:"linux",architecture:"amd64"}),/signature does not match enrollment-pinned trust/);assert.equal(writes,0);});

test("adopt enrollment replay rejects substituted Kubernetes binding",async()=>{const token="k".repeat(43),nodePair=generateKeyPairSync("ed25519"),nodePublicKey=nodePair.publicKey.export({format:"jwk"}).x!,fingerprint=publicKeyFingerprint(nodePublicKey),persisted={clusterId:"cluster-a",nodeName:"worker-a",nodeUid:"uid-a",resourceVersion:"7"},enrollment={id:"44444444-4444-4444-8444-444444444444",workspaceId,requestedName:"worker-a",mode:"adopt" as const,expectedPlatform:"linux" as const,expectedArchitecture:"amd64" as const,tokenHash:sha256Hex(token),tokenKeyId:"node-enrollment/v1" as const,idempotencyKey:"exchange-key",createdBy:userId,planSigningKey,expiresAt:new Date("2026-08-22T12:15:00Z"),status:"exchanged" as const,machineBinding:"c".repeat(64),nodePublicKey,nodePublicKeyFingerprint:fingerprint,consumedByNodeId:nodeId,version:2};let replayed=false;const service=new NodeService(store(baseTx({enrollmentById:async()=>enrollment,exchangeBindingByEnrollment:async()=>persisted,exchangeByEnrollment:async()=>{replayed=true;throw new Error("must not replay substituted binding");}})),async()=>Buffer.alloc(32),planFactory,()=>new Date("2026-08-22T12:00:00Z"));await assert.rejects(()=>service.exchangeEnrollment(enrollment.id,{token,machineFingerprint:enrollment.machineBinding,nodePublicKey,platform:"linux",architecture:"amd64",kubernetesBinding:{...persisted,nodeUid:"attacker-uid"}}),(error:unknown)=>error instanceof NodeHttpError&&error.code==="enrollment_consumed");assert.equal(replayed,false);});

test("initial adopt exchange rejects Kubernetes binding outside signed cluster and hostname",async()=>{const token="m".repeat(43),nodePair=generateKeyPairSync("ed25519"),nodePublicKey=nodePair.publicKey.export({format:"jwk"}).x!,enrollment={id:"44444444-4444-4444-8444-444444444444",workspaceId,requestedName:"worker-a",mode:"adopt" as const,expectedPlatform:"linux" as const,expectedArchitecture:"amd64" as const,tokenHash:sha256Hex(token),tokenKeyId:"node-enrollment/v1" as const,idempotencyKey:"exchange-key",createdBy:userId,planSigningKey,expiresAt:new Date("2026-08-22T12:15:00Z"),status:"pending" as const,machineBinding:null,nodePublicKey:null,nodePublicKeyFingerprint:null,consumedByNodeId:null,version:1};let writes=0;const factory={signingKey:async()=>planSigningKey,create:async()=>({cluster:{id:"cluster-signed"},hostname:"worker-a"})};const service=new NodeService(store(baseTx({enrollmentById:async()=>enrollment,createExchangedNode:async()=>{writes++;throw new Error("must not write mismatched binding");}})),async()=>Buffer.alloc(32),factory,()=>new Date("2026-08-22T12:00:00Z"));await assert.rejects(()=>service.exchangeEnrollment(enrollment.id,{token,machineFingerprint:"c".repeat(64),nodePublicKey,platform:"linux",architecture:"amd64",kubernetesBinding:{clusterId:"cluster-substituted",nodeName:"worker-a",nodeUid:"uid-a",resourceVersion:"7"}}),(error:unknown)=>error instanceof NodeHttpError&&error.code==="enrollment_invalid");assert.equal(writes,0);});

test("heartbeat advances opaque Kubernetes resource versions only from the signed exact prior",async()=>{
  const pair=generateKeyPairSync("ed25519");const jwk=pair.publicKey.export({format:"jwk"});const publicKey=jwk.x!;let prior:Awaited<ReturnType<NodeTransaction["heartbeatState"]>>;let writes=0;
  const binding={clusterId:"cluster-a",nodeName:"ben2",nodeUid:"uid-a",resourceVersion:"9"};
  let persistedBinding=binding;const tx=baseTx({activeIdentity:async()=>({nodeId,workspaceId,generation:1,publicKey,publicKeyFingerprint:"c".repeat(64),signingKeyId:"node/v1",lifecycleState:"active",trustState:"verified",nodeVersion:1}),nodeById:async()=>({id:nodeId,workspaceId,name:"ben2",kind:"shared",platform:"linux",architecture:"amd64",lifecycleState:"active",trustState:"verified",agentEligible:true,version:1,capabilityVersion:null,identity:null,kubernetesBinding:persistedBinding,createdAt:"2026-08-22T00:00:00Z",updatedAt:"2026-08-22T00:00:00Z"}),heartbeatState:async()=>prior,recordHeartbeat:async(v)=>{assert.equal(v.priorKubernetesResourceVersion,persistedBinding.resourceVersion);persistedBinding=v.kubernetesBinding;prior={identityGeneration:v.identityGeneration,bootId:v.bootId,sequence:v.sequence,sentAt:v.sentAt,capabilityDigest:v.capabilityDigest,requestDigest:v.requestDigest};writes++;}});
  const service=new NodeService(store(tx),async()=>Buffer.alloc(32),planFactory,()=>new Date("2026-08-22T12:00:00Z"));
  const capability={version:1,host:{platform:"linux",architecture:"amd64",cpuMillis:1000,memoryBytes:1024,diskBytes:1024,accelerators:[],health:{status:"healthy",reasonCodes:[]}},worker:{platform:"linux",architecture:"amd64",allocatableCpuMillis:1000,allocatableMemoryBytes:1024,allocatableDiskBytes:1024,labels:{},limits:{maxConcurrentSandboxes:2,maxConcurrentAgents:2},health:{status:"healthy",reasonCodes:[]},kubernetesBinding:binding},sandboxBackends:[],runtimeClasses:[],localModels:[]};
  const body:HeartbeatInput={nodeId,identityGeneration:1,bootId:"boot-a",sequence:0,sentAt:"2026-08-22T12:00:00.000Z",priorKubernetesResourceVersion:"9",capabilityDigest:renderedDigest("blazn-node-capability-v1",capability),capability};
  const proof=sign(null,Buffer.from(`blazn-node-heartbeat-v1\n${canonicalJson(body)}`),pair.privateKey).toString("base64url");
  await service.heartbeat(body,proof);assert.equal(writes,1);assert.equal(prior?.requestDigest,requestDigest(body));
  await service.heartbeat(body,proof);assert.equal(writes,1);
  const delayedReplay=new NodeService(store(tx),async()=>Buffer.alloc(32),planFactory,()=>new Date("2026-08-22T13:00:00Z"));await delayedReplay.heartbeat(body,proof);assert.equal(writes,1);
  const advancedCapability=structuredClone(capability);advancedCapability.worker.kubernetesBinding.resourceVersion="rv-b/opaque";const advanced={...body,sequence:1,capability:advancedCapability,capabilityDigest:renderedDigest("blazn-node-capability-v1",advancedCapability)};const advancedProof=sign(null,Buffer.from(`blazn-node-heartbeat-v1\n${canonicalJson(advanced)}`),pair.privateKey).toString("base64url");await service.heartbeat(advanced,advancedProof);assert.equal(persistedBinding.resourceVersion,"rv-b/opaque");
  const staleCapability=structuredClone(capability);staleCapability.worker.kubernetesBinding.resourceVersion="rv-stale";const stale={...body,sequence:2,capability:staleCapability,capabilityDigest:renderedDigest("blazn-node-capability-v1",staleCapability)};const staleProof=sign(null,Buffer.from(`blazn-node-heartbeat-v1\n${canonicalJson(stale)}`),pair.privateKey).toString("base64url");await assert.rejects(()=>service.heartbeat(stale,staleProof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="version_conflict");
  const opaqueCapability=structuredClone(capability);opaqueCapability.worker.kubernetesBinding.resourceVersion="a-not-ordered";const opaque={...body,priorKubernetesResourceVersion:"rv-b/opaque",sequence:2,capability:opaqueCapability,capabilityDigest:renderedDigest("blazn-node-capability-v1",opaqueCapability)};const opaqueProof=sign(null,Buffer.from(`blazn-node-heartbeat-v1\n${canonicalJson(opaque)}`),pair.privateKey).toString("base64url");await service.heartbeat(opaque,opaqueProof);assert.equal(persistedBinding.resourceVersion,"a-not-ordered");
  const substitutedCapability=structuredClone(capability);substitutedCapability.worker.kubernetesBinding={...persistedBinding,nodeUid:"substituted",resourceVersion:"next"};const substituted={...body,priorKubernetesResourceVersion:"a-not-ordered",sequence:3,capability:substitutedCapability,capabilityDigest:renderedDigest("blazn-node-capability-v1",substitutedCapability)};const substitutedProof=sign(null,Buffer.from(`blazn-node-heartbeat-v1\n${canonicalJson(substituted)}`),pair.privateKey).toString("base64url");await assert.rejects(()=>service.heartbeat(substituted,substitutedProof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="version_conflict");
  const unsafe={...body,sequence:2,capability:{...capability,worker:{...capability.worker,kubernetesBinding:persistedBinding},localModels:[{nested:{access_token:"leak"}}]}};unsafe.capabilityDigest=renderedDigest("blazn-node-capability-v1",unsafe.capability);const unsafeProof=sign(null,Buffer.from(`blazn-node-heartbeat-v1\n${canonicalJson(unsafe)}`),pair.privateKey).toString("base64url");
  await assert.rejects(()=>service.heartbeat(unsafe,unsafeProof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="invalid_request");
});

test("operation checks version, role, state, and exact destructive binding",async()=>{
  const node={id:nodeId,workspaceId,name:"ben2",kind:"shared" as const,platform:"linux" as const,architecture:"amd64" as const,lifecycleState:"active" as const,trustState:"verified" as const,agentEligible:true,version:4,capabilityVersion:1,identity:null,kubernetesBinding:{clusterId:"cluster-a",nodeName:"ben2",nodeUid:"uid-a",resourceVersion:"9"},createdAt:"2026-08-22T00:00:00Z",updatedAt:"2026-08-22T00:00:00Z"};let inserts=0;
  const tx=baseTx({nodeById:async()=>node,authority:async()=>({workspaceId,role:"operator",workspaceStatus:"active"}),insertOperation:async(v)=>{inserts++;return{id:v.id,nodeId:v.nodeId,type:v.type,status:"pending",expectedNodeVersion:v.expectedVersion,result:null,error:null,receipt:null,createdAt:"2026-08-22T12:00:00Z"};}});
  const service=new NodeService(store(tx),async()=>Buffer.alloc(32),planFactory);
  await service.createOperation(principal,nodeId,"remove-key",{type:"remove",expectedVersion:4,parameters:{clusterId:"cluster-a",expectedNodeUid:"uid-a",expectedResourceVersion:"9",confirm:true,preserveHostData:true}});assert.equal(inserts,1);
  await assert.rejects(()=>service.createOperation(principal,nodeId,"wrong-vers",{type:"pause",expectedVersion:3,parameters:{}}),(e:unknown)=>e instanceof NodeHttpError&&e.code==="version_conflict");
});

test("join consumption rejects revoked trust and removed lifecycle",async()=>{const pair=generateKeyPairSync("ed25519");const publicKey=pair.publicKey.export({format:"jwk"}).x!;const body={nodeId,enrollmentId:"55555555-5555-4555-8555-555555555555",planId:"66666666-6666-4666-8666-666666666666",joinedNodeUid:"uid-a",joinedNodeName:"node-a",resourceVersion:"1",clusterId:"cluster-a"};const proof=sign(null,Buffer.from(`blazn-node-join-v1\n${canonicalJson(body)}`),pair.privateKey).toString("base64url");for(const state of [{trustState:"revoked",lifecycleState:"active"},{trustState:"verified",lifecycleState:"removed"}]){let consumed=false;const tx=baseTx({activeIdentity:async()=>({nodeId,workspaceId,generation:1,publicKey,publicKeyFingerprint:"a".repeat(64),signingKeyId:"node/v1",nodeVersion:1,...state}),consumeJoin:async()=>{consumed=true;throw new Error("unexpected consume");}});const service=new NodeService(store(tx),async()=>Buffer.alloc(32),planFactory);await assert.rejects(()=>service.consumeJoin("77777777-7777-4777-8777-777777777777","consume-key",body,proof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="identity_rejected");assert.equal(consumed,false);}});

test("activation requires a current plan and exact terminal mutation evidence",async()=>{
  const pair=generateKeyPairSync("ed25519"),publicKey=pair.publicKey.export({format:"jwk"}).x!,fingerprint=publicKeyFingerprint(publicKey),planId="66666666-6666-4666-8666-666666666666",binding={clusterId:"cluster-a",nodeName:"worker-a",nodeUid:"uid-a",resourceVersion:"7"},desiredDigest=`sha256:${"d".repeat(64)}`;
  const canonicalPlan={mutations:[{ordinal:1,kind:"file",target:"/usr/local/bin/blazn",desiredDigest}]};
  const unsignedReceipt=():Record<string,unknown>=>({schemaVersion:"nodes/v1alpha1",receiptId:"77777777-7777-4777-8777-777777777777",planId,planDigest:`sha256:${"a".repeat(64)}`,nodeId,generation:1,nodeIdentityGeneration:1,signerKind:"node_identity",signerFingerprint:`sha256:${fingerprint}`,state:"active",currentStage:"complete",owner:{uid:0,pid:42,processStartIdentity:"start-1",nonce:"A".repeat(32)},binary:{path:"/usr/local/bin/blazn",digest:`sha256:${"b".repeat(64)}`},service:{manager:"systemd",name:"blazn-node.service",definitionDigest:`sha256:${"c".repeat(64)}`,priorEnabled:false,priorActive:false},mutations:[{ordinal:1,kind:"file",target:"/usr/local/bin/blazn",priorState:"absent",rollbackMaterial:{kind:"absent"},desiredDigest,status:"applied"}],residues:[],createdAt:"2026-08-22T12:00:00Z",updatedAt:"2026-08-22T12:01:00Z",signingKeyId:"node-identity/v1",digest:"",signature:""});
  const signed=(mutate?:(receipt:Record<string,unknown>)=>void)=>{const receipt=unsignedReceipt();mutate?.(receipt);receipt.digest=nodeInstallReceiptDigest(receipt);receipt.signature=sign(null,Buffer.from(`blazn-node-install-receipt-v1\n${receipt.digest}`),pair.privateKey).toString("base64url");const request={expectedVersion:2,receipt,kubernetesBinding:binding};return{request,proof:sign(null,Buffer.from(`blazn-node-activation-v1\n${canonicalJson(request)}`),pair.privateKey).toString("base64url")};};
  const authority=(overrides:Record<string,unknown>={})=>({nodeId,workspaceId,generation:1,publicKey,publicKeyFingerprint:fingerprint,signingKeyId:"node-identity/v1",lifecycleState:"verifying",trustState:"verifying",nodeVersion:2,planId,planDigest:"a".repeat(64),planStatus:"issued",planExpiresAt:new Date("2026-08-22T12:05:00Z"),controlPlaneNow:new Date("2026-08-22T12:02:00Z"),canonicalPlan,enrollmentId:"55555555-5555-4555-8555-555555555555",kubernetesBinding:binding,...overrides});
  let captured:Parameters<NodeTransaction["activateNode"]>[0]|undefined,replayGrant:Parameters<NodeTransaction["activateNode"]>[0]["activationGrant"]|undefined;const node={id:nodeId,workspaceId,name:"worker-a",kind:"shared" as const,platform:"linux" as const,architecture:"amd64" as const,lifecycleState:"active" as const,trustState:"verified" as const,agentEligible:true,version:3,capabilityVersion:null,identity:null,kubernetesBinding:binding,createdAt:"2026-08-22T12:00:00Z",updatedAt:"2026-08-22T12:01:00Z"};let currentAuthority=authority(),signerVersion="test/v1",signatures=0;const rotatingFactory={...planFactory,signActivationGrant:async(unsigned:Record<string,unknown>)=>{signatures++;return{...unsigned,signingKeyId:signerVersion,digest:`sha256:${"e".repeat(64)}`,signature:"f".repeat(86)};}};const service=new NodeService(store(baseTx({activationReplay:async()=>replayGrant,activationAuthority:async()=>currentAuthority,activateNode:async input=>{captured=input;return{node,activationGrant:input.activationGrant};}})),async()=>Buffer.alloc(32),rotatingFactory);
  const valid=signed();assert.equal((await service.activate(valid.request,"activate-key",valid.proof)).node.agentEligible,true);assert.equal(captured?.expectedVersion,2);const storedGrant=captured!.activationGrant;
  for(const overrides of [{planStatus:"revoked"},{planStatus:"expired"},{planExpiresAt:new Date("2026-08-22T12:02:00Z")}]){currentAuthority=authority(overrides);await assert.rejects(()=>service.activate(valid.request,"activate-key",valid.proof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="state_conflict");}
  replayGrant=storedGrant;currentAuthority=authority({planStatus:"accepted"});assert.equal((await service.activate(valid.request,"activate-key",valid.proof)).node.agentEligible,true);
  signerVersion="test/v2";currentAuthority=authority({planStatus:"accepted",planExpiresAt:new Date("2026-08-22T12:02:00Z"),lifecycleState:"active",trustState:"verified",nodeVersion:3,kubernetesBinding:{...binding,resourceVersion:"opaque-advanced-rv"}});const replayed=await service.activate(valid.request,"activate-key",valid.proof);assert.equal(replayed.node.agentEligible,true);assert.equal(replayed.activationGrant.kubernetesBinding.resourceVersion,"7");assert.equal(replayed.activationGrant.signingKeyId,"test/v1");assert.equal(signatures,1);replayGrant=undefined;
  currentAuthority=authority();for(const mutate of [(r:Record<string,unknown>)=>{(r.owner as Record<string,unknown>).pid=0;},(r:Record<string,unknown>)=>{(r.owner as Record<string,unknown>).nonce="short";},(r:Record<string,unknown>)=>{(r.service as Record<string,unknown>).manager="rc";},(r:Record<string,unknown>)=>{(r.mutations as Array<Record<string,unknown>>)[0]!.ordinal=0;},(r:Record<string,unknown>)=>{(r.mutations as Array<Record<string,unknown>>)[0]!.kind="script";},(r:Record<string,unknown>)=>{(r.mutations as Array<Record<string,unknown>>)[0]!.priorState="unknown";},(r:Record<string,unknown>)=>{const mutation=(r.mutations as Array<Record<string,unknown>>)[0]!;mutation.priorState="owned";mutation.rollbackMaterial={kind:"absent"};},(r:Record<string,unknown>)=>{(r.mutations as Array<Record<string,unknown>>)[0]!.status="pending";},(r:Record<string,unknown>)=>{(r.mutations as Array<Record<string,unknown>>)[0]!.rollbackMaterial={kind:"file_backup"};},(r:Record<string,unknown>)=>{r.mutations=[];}]){const candidate=signed(mutate);await assert.rejects(()=>service.activate(candidate.request,"activate-key",candidate.proof),(e:unknown)=>e instanceof NodeHttpError&&(e.code==="invalid_request"||e.code==="state_conflict"));}
  const duplicate=signed(r=>{(r.mutations as unknown[]).push(structuredClone((r.mutations as unknown[])[0]));});await assert.rejects(()=>service.activate(duplicate.request,"activate-key",duplicate.proof),(e:unknown)=>e instanceof NodeHttpError&&e.code==="invalid_request");
});

function store(tx:NodeTransaction):NodeStore{return{transaction:async action=>action(tx)}}
function baseTx(overrides:Partial<NodeTransaction>):NodeTransaction{
  const unsupported=async()=>{throw new Error("unexpected fake transaction method")};
  return {lockIdempotency:async()=>{},getIdempotency:async()=>undefined,putIdempotency:async()=>{},authority:unsupported,insertEnrollment:unsupported,enrollmentById:unsupported,exchangeByEnrollment:unsupported,exchangeBindingByEnrollment:unsupported,createExchangedNode:unsupported,nodeById:unsupported,listNodes:unsupported,activeIdentity:unsupported,activationReplay:async()=>undefined,activationAuthority:unsupported,activateNode:unsupported,heartbeatState:async()=>undefined,bootObserved:async()=>false,observeBoot:async()=>{},recordHeartbeat:unsupported,insertOperation:unsupported,listEvents:unsupported,consumeJoin:unsupported,...overrides} as NodeTransaction;
}
