import assert from "node:assert/strict";
import { generateKeyPairSync } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { FileNodePlanSigner, publicKeyFingerprint } from "./node-crypto.js";
import { TemplateNodePlanFactory } from "./node-plan.js";
import type { EnrollmentRecord } from "./node-types.js";

test("raw Ed25519 seed exposes one consistent trust tuple and signs every exact template profile",async()=>{const fixture=await fixtureFiles();try{for(const [mode,platform,architecture,profile] of [["fresh","linux","amd64","ubuntu-26.04-amd64-worker/v1"],["adopt","linux","amd64","existing-linux-worker-adopt/v1"],["adopt","macos","arm64","macos-lima-worker-adopt/v1"]] as const){const factory=new TemplateNodePlanFactory(fixture.bundle,new FileNodePlanSigner("control-plane-node-plan/v1",fixture.key));const trust=await factory.signingKey();assert.deepEqual(trust,{keyId:"control-plane-node-plan/v1",publicKey:fixture.publicKey,fingerprint:`sha256:${publicKeyFingerprint(fixture.publicKey)}`});const plan=await factory.create(context(mode,platform,architecture));assert.equal(plan.installProfile,profile);assert.equal(plan.signingKeyId,trust.keyId);assert.match(String(plan.digest),/^sha256:[0-9a-f]{64}$/);assert.match(String(plan.signature),/^[A-Za-z0-9_-]{86}$/);}}finally{await rm(fixture.root,{recursive:true});}});

test("PKCS8 Ed25519 material remains accepted for controlled key migration",async()=>{const fixture=await fixtureFiles(undefined,"pkcs8");try{const plan=await new TemplateNodePlanFactory(fixture.bundle,new FileNodePlanSigner("control-plane-node-plan/v1",fixture.key)).create(context("fresh","linux","amd64"));assert.match(String(plan.signature),/^[A-Za-z0-9_-]{86}$/);}finally{await rm(fixture.root,{recursive:true});}});

test("invalid nested template and profile semantics fail before persistence",async()=>{for(const mutate of [(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.cluster.extra=true;},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.nodeService.manager="launchd";},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.components.find(c=>c.sourceClass==="https")!.sourceHost="foreign.example";},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.components[0]!.source="https://forbidden.example/blazn";},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations[0]!.target="/../escape";},(b:Bundle)=>{const p=b.profiles["ubuntu-26.04-amd64-worker/v1"]!;p.components.push({...p.components[0]!});},(b:Bundle)=>{const p=b.profiles["ubuntu-26.04-amd64-worker/v1"]!;p.mutations.push({...p.mutations[0]!,desired:{}});},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations.find(m=>m.kind==="package")!.target="other-package";},(b:Bundle)=>{(b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations.find(m=>m.kind==="package")!.desired as Record<string,unknown>).version="v9.9.9";},(b:Bundle)=>{const m=b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations.find(m=>m.kind==="package")!;m.target="blazn-node";m.desired={manager:"snap",version:"v0.1.0",componentName:"blazn-node"};},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.components.find(c=>c.artifactType==="package")!.repositoryOrigin="https://foreign.example";},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations.find(m=>m.kind==="image")!.target=`registry.example.test/blazn/worker@sha256:${"9".repeat(64)}`;},(b:Bundle)=>{(b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations.find(m=>m.kind==="image")!.desired as Record<string,unknown>).componentName="blazn-node";},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations.find(m=>m.kind==="systemd_unit")!.target="/etc/systemd/system/other.service";},(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.validationTests=[];}]){const fixture=await fixtureFiles(mutate);try{const factory=new TemplateNodePlanFactory(fixture.bundle,new FileNodePlanSigner("control-plane-node-plan/v1",fixture.key));await assert.rejects(()=>factory.create(context("fresh","linux","amd64")),/invalid NodeInstallPlan/);}finally{await rm(fixture.root,{recursive:true});}}});

test("fresh service-account ordering and macOS Lima binding evidence are mandatory",async()=>{for(const [mutate,mode,platform,architecture] of [[(b:Bundle)=>{b.profiles["ubuntu-26.04-amd64-worker/v1"]!.mutations.find(m=>m.kind==="group")!.ordinal=9;},"fresh","linux","amd64"],[(b:Bundle)=>{b.profiles["macos-lima-worker-adopt/v1"]!.validationTests=[];},"adopt","macos","arm64"],[(b:Bundle)=>{b.profiles["macos-lima-worker-adopt/v1"]!.mutations=[];},"adopt","macos","arm64"]] as const){const fixture=await fixtureFiles(mutate);try{await assert.rejects(()=>new TemplateNodePlanFactory(fixture.bundle,new FileNodePlanSigner("control-plane-node-plan/v1",fixture.key)).create(context(mode,platform,architecture)),/invalid NodeInstallPlan/);}finally{await rm(fixture.root,{recursive:true});}}});

type Profile={cluster:Record<string,unknown>;registryTrust:unknown[];components:Record<string,unknown>[];nodeService:Record<string,unknown>;labels:Record<string,string>;taints:unknown[];resourceBounds:Record<string,unknown>;mutations:Record<string,unknown>[];validationTests:string[];rollback:Record<string,unknown>};type Bundle={schemaVersion:string;templateId:string;profiles:Record<string,Profile>};
async function fixtureFiles(mutate?:(bundle:Bundle)=>void,format:"raw"|"pkcs8"="raw"){const root=await mkdtemp(path.join(os.tmpdir(),"blazn-node-plan-"));const pair=generateKeyPairSync("ed25519");const der=pair.privateKey.export({format:"der",type:"pkcs8"});const publicKey=pair.publicKey.export({format:"jwk"}).x!;const key=path.join(root,"seed");await writeFile(key,format==="raw"?`${der.subarray(der.length-32).toString("base64url")}\n`:der,{mode:0o600});const bundleObject=bundle();mutate?.(bundleObject);const bundlePath=path.join(root,"bundle.json");await writeFile(bundlePath,JSON.stringify(bundleObject),{mode:0o600});return{root,key,bundle:bundlePath,publicKey};}
function bundle():Bundle{const linux=profile("systemd","blazn-node","blazn-node","linux_var_lib","/var/lib/blazn/install-backups/test");linux.mutations.push(groupMutation(1),userMutation(2),{ordinal:3,kind:"directory",action:"create",target:"/var/lib/blazn",desired:{},desiredDigest:`sha256:${"d".repeat(64)}`,mode:493,uid:0,gid:0,rollback:"remove_if_owned"});const imageDigest="8".repeat(64),imageReference=`registry.example.test/blazn/worker@sha256:${imageDigest}`;linux.components.push({name:"worker-image",artifactType:"image",sourceClass:"https",version:"v1.0.0",publisher:"Blazn",sourceHost:"registry.example.test",source:"https://registry.example.test/v2/blazn/worker",registryHost:"registry.example.test",ociReference:imageReference,sha256:imageDigest,ownership:"install"});linux.mutations.push({ordinal:4,kind:"image",action:"pull",target:imageReference,desired:{platform:"linux/amd64",componentName:"worker-image"},desiredDigest:`sha256:${"9".repeat(64)}`,mode:0,uid:0,gid:0,rollback:"remove_if_owned"});linux.components.push({name:"microk8s",artifactType:"package",sourceClass:"https",version:"v1.35.6",publisher:"Canonical",sourceHost:"api.snapcraft.io",source:"https://api.snapcraft.io/microk8s.snap",repositoryOrigin:"https://api.snapcraft.io",sha256:"7".repeat(64),ownership:"install"},{name:"node-unit",artifactType:"configuration",sourceClass:"embedded",version:"v1",publisher:"Blazn",sha256:"5".repeat(64),ownership:"install"});linux.mutations.push({ordinal:5,kind:"package",action:"install",target:"microk8s",desired:{manager:"snap",version:"v1.35.6",componentName:"microk8s"},desiredDigest:`sha256:${"6".repeat(64)}`,mode:0,uid:0,gid:0,rollback:"remove_if_owned"},{ordinal:6,kind:"systemd_unit",action:"write",target:"/etc/systemd/system/blazn-node.service",desired:{unitName:"blazn-node.service",sourceComponent:"node-unit"},desiredDigest:`sha256:${"4".repeat(64)}`,mode:420,uid:0,gid:0,rollback:"remove_if_owned"});const existing=structuredClone(linux);existing.mutations=existing.mutations.map(m=>m.kind==="group"||m.kind==="user"?{...m,action:"adopt_exact"}:m);const mac=profile("launchd","root","wheel","macos_library_application_support","/Library/Application Support/Blazn/install-backups/test");mac.components.push({name:"lima-binding",artifactType:"configuration",sourceClass:"embedded",version:"v1",publisher:"Blazn",sha256:"e".repeat(64),ownership:"adopt_exact"});mac.mutations.push({ordinal:1,kind:"file",action:"adopt_exact",target:"/Library/Application Support/Blazn/lima-worker-binding.json",desired:{sourceComponent:"lima-binding",contentSha256:"e".repeat(64)},desiredDigest:`sha256:${"f".repeat(64)}`,mode:420,uid:0,gid:0,rollback:"leave_and_report"});mac.validationTests.push("lima_worker_binding");return{schemaVersion:"blazn.dev/node-install-plan-templates/v1",templateId:"frontro-poc-worker/v1",profiles:{"ubuntu-26.04-amd64-worker/v1":linux,"existing-linux-worker-adopt/v1":existing,"macos-lima-worker-adopt/v1":mac}};}
function profile(manager:string,user:string,group:string,backupRootClass:string,backupRoot:string):Profile{return{cluster:{id:"frontro-poc",workerOnly:true,apiServer:"https://cluster.example.test:6443",kubernetesVersion:"v1.36.1",joinCredentialEndpoint:"/v1/node-service/join-credentials",bootstrapTaint:"blazn.dev/bootstrap=pending:NoSchedule",expectedCaFingerprint:`sha256:${"a".repeat(64)}`,registryEndpoints:[]},registryTrust:[],components:[{name:"blazn-node",artifactType:"binary",sourceClass:"current_binary",version:"v0.1.0",publisher:"Blazn",sha256:"b".repeat(64),ownership:"install"}],nodeService:{manager,unitName:manager==="systemd"?"blazn-node.service":"com.blazn.node",binaryPath:"/usr/local/bin/blazn",runAsUser:user,runAsGroup:group,definitionSha256:"c".repeat(64)},labels:{},taints:[],resourceBounds:{reservedCpuMillis:100,reservedMemoryBytes:1073741824,maxPods:10,maxConcurrentAgents:2},mutations:[],validationTests:["worker_only",...(manager==="systemd"?["service_account"]:[])],rollback:{preserveUserData:true,preserveControlPlane:true,ambiguousOwnership:"recovery_required",backupRootClass,backupRoot}};}
function groupMutation(ordinal:number):Record<string,unknown>{return{ordinal,kind:"group",action:"create",target:"blazn-node",desired:{name:"blazn-node",system:true},desiredDigest:`sha256:${"1".repeat(64)}`,mode:0,uid:0,gid:0,rollback:"remove_if_owned"};}
function userMutation(ordinal:number):Record<string,unknown>{return{ordinal,kind:"user",action:"create",target:"blazn-node",desired:{name:"blazn-node",group:"blazn-node",home:"/var/lib/blazn",shell:"/usr/sbin/nologin",system:true},desiredDigest:`sha256:${"2".repeat(64)}`,mode:0,uid:0,gid:0,rollback:"remove_if_owned"};}
function context(mode:"fresh"|"adopt",platform:"linux"|"macos",architecture:"amd64"|"arm64"){const enrollment:EnrollmentRecord={id:"00000000-0000-4000-8000-000000000001",workspaceId:"00000000-0000-4000-8000-000000000002",requestedName:"node-test",mode,expectedPlatform:platform,expectedArchitecture:architecture,tokenHash:"a".repeat(64),tokenKeyId:"node-enrollment/v1",idempotencyKey:"node-plan-test",createdBy:"00000000-0000-4000-8000-000000000003",planSigningKey:{keyId:"control-plane-node-plan/v1",publicKey:"A".repeat(43),fingerprint:`sha256:${"a".repeat(64)}`},expiresAt:new Date("2030-01-01T00:00:00.000Z"),status:"pending",machineBinding:null,nodePublicKey:null,nodePublicKeyFingerprint:null,consumedByNodeId:null,version:1};return{planId:"00000000-0000-4000-8000-000000000004",nodeId:"00000000-0000-4000-8000-000000000005",enrollment,architecture,machineFingerprint:"e".repeat(64),nodePublicKeyFingerprint:"f".repeat(64),issuedAt:new Date("2029-01-01T00:00:00.000Z"),expiresAt:new Date("2029-01-01T00:15:00.000Z")};}
