import { randomUUID } from "node:crypto";
import { canonicalJson, enrollmentToken, nodeInstallReceiptDigest, publicKeyFingerprint, renderedDigest, requestDigest, sha256Hex, verifyNodeInstallReceiptSignature, verifyNodePlanSignature, verifyNodeProof } from "./node-crypto.js";
import type { NodePlanFactory } from "./node-plan.js";
import type { NodeIdempotencyReceipt, NodeStore, NodeTransaction } from "./node-store.js";
import { nodeRoleAllows, NodeHttpError, type ExchangeNodeEnrollmentResponse, type KubernetesBinding, type NodeActivationRequest, type NodeActivationResponse, type NodeArchitecture, type NodeEvent, type NodeOperationType, type NodeOperationView, type NodePlanSigningKey, type NodePlatform, type NodePrincipal, type NodeView } from "./node-types.js";

export interface CreateEnrollmentInput { name: string; mode: "fresh" | "adopt"; platform: NodePlatform; architecture?: NodeArchitecture }
export interface ExchangeEnrollmentInput { token: string; machineFingerprint: string; nodePublicKey: string; platform: NodePlatform; architecture: NodeArchitecture; kubernetesBinding?: KubernetesBinding }
export interface HeartbeatInput { nodeId: string; identityGeneration: number; bootId: string; sequence: number; sentAt: string; priorKubernetesResourceVersion: string; capabilityDigest: string; capability: Record<string, unknown> }

export class NodeService {
  constructor(private readonly store: NodeStore, private readonly enrollmentKey: () => Promise<Buffer>, private readonly planFactory: NodePlanFactory, private readonly now: () => Date = () => new Date()) {}

  async createEnrollment(principal: NodePrincipal, workspaceId: string, idempotencyKey: string, input: CreateEnrollmentInput) {
    validIdempotency(idempotencyKey); validName(input.name); validPlatform(input.platform); if (input.architecture) validArchitecture(input.architecture);
    if (input.mode !== "fresh" && input.mode !== "adopt") invalid("mode is invalid");
    if (input.mode === "fresh" && (input.platform !== "linux" || (input.architecture && input.architecture !== "amd64"))) invalid("fresh POC enrollment requires linux/amd64");
    const digest = requestDigest(input); const key = await this.enrollmentKey();
    return this.store.transaction(async (tx) => {
      await tx.lockIdempotency(principal.userId,"node.enrollment.create",idempotencyKey);
      await authorize(tx,principal,workspaceId,true,true);
      const receipt=await tx.getIdempotency(principal.userId,"node.enrollment.create",idempotencyKey);
      if(receipt){ verifyReceipt(receipt,workspaceId,`workspace:${workspaceId}`,digest); const stored=receipt.responseBody as {id:string;tokenKeyId:"node-enrollment/v1";planSigningKey:NodePlanSigningKey;expiresAt:string};const enrollment=await tx.enrollmentById(stored.id);if(!enrollment||!sameSigningKey(enrollment.planSigningKey,stored.planSigningKey))throw new Error("enrollment signing trust does not match its idempotency receipt");return {...stored,token:enrollmentToken(key,workspaceId,stored.id,principal.userId,idempotencyKey),replayed:true}; }
      const planSigningKey=validSigningKey(await this.planFactory.signingKey());
      const id=randomUUID(); const expiresAt=new Date(this.now().getTime()+15*60_000); const token=enrollmentToken(key,workspaceId,id,principal.userId,idempotencyKey);
      await tx.insertEnrollment({id,workspaceId,name:input.name.trim(),mode:input.mode,platform:input.platform,architecture:input.architecture??null,tokenHash:sha256Hex(token),idempotencyKey,createdBy:principal.userId,planSigningKey,expiresAt});
      const stored={id,tokenKeyId:"node-enrollment/v1" as const,planSigningKey,expiresAt:expiresAt.toISOString()};
      await tx.putIdempotency(principal.userId,"node.enrollment.create",idempotencyKey,{workspaceId,targetKey:`workspace:${workspaceId}`,requestDigest:digest,responseStatus:201,responseBody:stored});
      return {...stored,token,replayed:false};
    });
  }

  async exchangeEnrollment(enrollmentId:string,input:ExchangeEnrollmentInput):Promise<ExchangeNodeEnrollmentResponse>{
    validUuid(enrollmentId,"enrollmentId"); validPlatform(input.platform); validArchitecture(input.architecture);
    if(!/^[A-Za-z0-9_-]{43,128}$/.test(input.token)) invalid("token is invalid");
    if(!/^[0-9a-f]{64}$/.test(input.machineFingerprint)) invalid("machineFingerprint is invalid");
    let fingerprint:string; try{fingerprint=publicKeyFingerprint(input.nodePublicKey);}catch{invalid("nodePublicKey is invalid");}
    if(input.kubernetesBinding) validateBinding(input.kubernetesBinding);
    return this.store.transaction(async(tx)=>{
      const enrollment=await tx.enrollmentById(enrollmentId,true); if(!enrollment) throw new NodeHttpError("enrollment_not_found","enrollment was not found");
      if(enrollment.tokenHash!==sha256Hex(input.token)) throw new NodeHttpError("enrollment_invalid","enrollment token is invalid");
      if(enrollment.expiresAt.getTime()<=this.now().getTime()) throw new NodeHttpError("enrollment_expired","enrollment has expired");
      if(enrollment.expectedPlatform!==input.platform || (enrollment.expectedArchitecture!==null&&enrollment.expectedArchitecture!==input.architecture)) throw new NodeHttpError("enrollment_invalid","enrollment target does not match this machine");
      if(enrollment.mode==="adopt"&&!input.kubernetesBinding) invalid("adoption requires kubernetesBinding");
      if(enrollment.mode==="fresh"&&input.kubernetesBinding) invalid("fresh enrollment cannot pre-bind Kubernetes");
      if(enrollment.status==="exchanged"){
        if(enrollment.machineBinding!==input.machineFingerprint||enrollment.nodePublicKey!==input.nodePublicKey||enrollment.nodePublicKeyFingerprint!==fingerprint) throw new NodeHttpError("enrollment_consumed","enrollment is bound to another machine identity");
        const persistedBinding=await tx.exchangeBindingByEnrollment(enrollment.id),requestedBinding=input.kubernetesBinding??null;if(persistedBinding===undefined)throw new Error("exchanged enrollment has no persisted Kubernetes binding");if(canonicalJson(persistedBinding)!==canonicalJson(requestedBinding))throw new NodeHttpError("enrollment_consumed","enrollment is bound to another Kubernetes identity");
        const replay=await tx.exchangeByEnrollment(enrollment.id); if(!replay) throw new Error("exchanged enrollment has no plan and identity"); return replay;
      }
      if(enrollment.status!=="pending") throw new NodeHttpError("enrollment_consumed","enrollment is no longer exchangeable");
      const configuredSigningKey=validSigningKey(await this.planFactory.signingKey());if(!sameSigningKey(configuredSigningKey,enrollment.planSigningKey))throw new Error("configured Node plan signer does not match enrollment-pinned trust");
      const issuedAt=this.now(),expiresAt=new Date(issuedAt.getTime()+15*60_000),nodeId=randomUUID(),planId=randomUUID();
      const plan=await this.planFactory.create({planId,nodeId,enrollment,architecture:input.architecture,machineFingerprint:input.machineFingerprint,nodePublicKeyFingerprint:fingerprint,issuedAt,expiresAt});
      if(input.kubernetesBinding){const cluster=plan.cluster;if(!cluster||typeof cluster!=="object"||Array.isArray(cluster)||input.kubernetesBinding.clusterId!==(cluster as Record<string,unknown>).id||input.kubernetesBinding.nodeName!==plan.hostname)throw new NodeHttpError("enrollment_invalid","adopted Kubernetes binding does not match the signed install target");}
      const digest=requiredRenderedDigest(plan.digest,"plan digest"); const signature=requiredSignature(plan.signature); const signingKeyId=requiredText(plan.signingKeyId,"signingKeyId",128);if(signingKeyId!==enrollment.planSigningKey.keyId||!verifyNodePlanSignature(enrollment.planSigningKey.publicKey,digest,signature))throw new Error("Node install plan signature does not match enrollment-pinned trust");
      const identity=await tx.createExchangedNode({nodeId,identityId:randomUUID(),enrollment,architecture:input.architecture,machineFingerprint:input.machineFingerprint,publicKey:input.nodePublicKey,publicKeyFingerprint:fingerprint,...(input.kubernetesBinding?{kubernetesBinding:input.kubernetesBinding}:{}),planId,plan,planDigest:digest.slice(7),signingKeyId,signature,issuedAt,expiresAt});
      if(identity.publicKeyFingerprint!==`sha256:${fingerprint}`||identity.issuedAt!==issuedAt.toISOString())throw new Error("created Node identity does not match enrollment exchange");
      return {plan,identity};
    });
  }

  async listNodes(principal:NodePrincipal,workspaceId:string):Promise<{items:NodeView[]}>{
    return this.store.transaction(async tx=>{await authorize(tx,principal,workspaceId,false,false);return{items:await tx.listNodes(workspaceId)}});
  }
  async getNode(principal:NodePrincipal,nodeId:string):Promise<NodeView>{
    return this.store.transaction(async tx=>{const node=await requiredNode(tx,nodeId,false);await authorize(tx,principal,node.workspaceId,false,false);return node;});
  }
  async eventBatch(principal:NodePrincipal,nodeId:string,afterId=""):Promise<NodeEvent[]>{
    return this.store.transaction(async tx=>{const node=await requiredNode(tx,nodeId,false);await authorize(tx,principal,node.workspaceId,false,false);return tx.listEvents(nodeId,afterId);}).catch(mapStoreError);
  }

  async createOperation(principal:NodePrincipal,nodeId:string,idempotencyKey:string,input:{type:NodeOperationType;expectedVersion:number;parameters:Record<string,unknown>}):Promise<NodeOperationView>{
    validIdempotency(idempotencyKey); validOperation(input); const digest=requestDigest(input);
    return this.store.transaction(async tx=>{
      await tx.lockIdempotency(principal.userId,`node.operation.${input.type}`,idempotencyKey);
      const node=await requiredNode(tx,nodeId,true); await authorize(tx,principal,node.workspaceId,true,true);
      const receipt=await tx.getIdempotency(principal.userId,`node.operation.${input.type}`,idempotencyKey);
      if(receipt){verifyReceipt(receipt,node.workspaceId,`node:${nodeId}`,digest);return receipt.responseBody as NodeOperationView;}
      if(node.version!==input.expectedVersion) throw new NodeHttpError("version_conflict","node version changed");
      validateOperationState(node,input.type,input.parameters);
      const operation=await tx.insertOperation({id:randomUUID(),workspaceId:node.workspaceId,nodeId,type:input.type,expectedVersion:input.expectedVersion,requestedBy:principal.userId,idempotencyKey,requestDigest:digest,parameters:input.parameters});
      await tx.putIdempotency(principal.userId,`node.operation.${input.type}`,idempotencyKey,{workspaceId:node.workspaceId,targetKey:`node:${nodeId}`,requestDigest:digest,responseStatus:202,responseBody:operation});
      return operation;
    }).catch(mapStoreError);
  }

  async heartbeat(input:HeartbeatInput,proof:string):Promise<void>{
    validateHeartbeat(input); const sentAt=new Date(input.sentAt); if(Math.abs(this.now().getTime()-sentAt.getTime())>5*60_000) throw new NodeHttpError("heartbeat_skew","heartbeat timestamp exceeds allowed clock skew");
    const digest=renderedDigest("blazn-node-capability-v1",input.capability); if(digest!==input.capabilityDigest) throw new NodeHttpError("capability_digest_invalid","capability digest does not match payload");
    rejectSecrets(input.capability); validateCapability(input.capability);
    await this.store.transaction(async tx=>{
      const identity=await tx.activeIdentity(input.nodeId,true); if(!identity||identity.trustState==="revoked"||identity.lifecycleState==="removed") throw new NodeHttpError("identity_rejected","node identity is not active");
      if(identity.generation!==input.identityGeneration||!verifyNodeProof(identity.publicKey,"blazn-node-heartbeat-v1",input,proof)) throw new NodeHttpError("identity_rejected","node proof could not be verified");
      const node=await requiredNode(tx,input.nodeId,false);const worker=input.capability.worker as Record<string,unknown>;const binding=worker.kubernetesBinding as KubernetesBinding;
      if(!node.kubernetesBinding||input.priorKubernetesResourceVersion!==node.kubernetesBinding.resourceVersion||!bindingAdvances(node.kubernetesBinding,binding))throw new NodeHttpError("version_conflict","heartbeat Kubernetes binding changed before this exact transition");
      const prior=await tx.heartbeatState(input.nodeId);
      if(prior&&prior.identityGeneration===input.identityGeneration){
        if(prior.bootId===input.bootId&&input.sequence<=prior.sequence) throw new NodeHttpError("heartbeat_replay","heartbeat sequence was already observed");
        if(prior.bootId!==input.bootId&&(input.sequence!==0||sentAt.getTime()<=prior.sentAt.getTime()||await tx.bootObserved(input.nodeId,input.identityGeneration,input.bootId))) throw new NodeHttpError("heartbeat_replay","new boot epoch is invalid or already observed");
      }
      const version=input.capability.version;
      if(typeof version!=="number"||!Number.isSafeInteger(version)||version<1) invalid("capability version is invalid");
      if(node.capabilityVersion!==null&&(version<node.capabilityVersion||(version===node.capabilityVersion&&prior?.capabilityDigest!==digest.slice(7))))throw new NodeHttpError("state_conflict","capability version cannot roll back or change content");
      if(!prior||prior.bootId!==input.bootId)await tx.observeBoot(input.nodeId,node.workspaceId,input.identityGeneration,input.bootId,sentAt);
      await tx.recordHeartbeat({nodeId:input.nodeId,identityGeneration:input.identityGeneration,bootId:input.bootId,sequence:input.sequence,sentAt,capabilityDigest:digest.slice(7),capability:input.capability,health:capabilityHealth(input.capability),priorKubernetesResourceVersion:node.kubernetesBinding.resourceVersion,kubernetesBinding:binding});
    }).catch(mapStoreError);
  }

  async activate(input:NodeActivationRequest,idempotencyKey:string,proof:string):Promise<NodeActivationResponse>{
    validIdempotency(idempotencyKey);if(!Number.isSafeInteger(input.expectedVersion)||input.expectedVersion<1)invalid("expectedVersion is invalid");validateBinding(input.kubernetesBinding);const receipt=validateInstallReceipt(input.receipt);const digest=nodeInstallReceiptDigest(receipt);if(receipt.digest!==digest)throw new NodeHttpError("invalid_request","install receipt digest does not match payload");const request={expectedVersion:input.expectedVersion,receipt,kubernetesBinding:input.kubernetesBinding};const activationDigest=requestDigest(request);
    return this.store.transaction(async tx=>{const authority=await tx.activationAuthority(String(receipt.nodeId),String(receipt.planId));if(!authority||authority.lifecycleState==="removed"||authority.trustState==="revoked")throw new NodeHttpError("identity_rejected","node activation identity is not active");const replay=await tx.activationReplay(String(receipt.nodeId),idempotencyKey,activationDigest,digest.slice(7)),currentPlan=["issued","accepted"].includes(authority.planStatus)&&authority.planExpiresAt.getTime()>authority.controlPlaneNow.getTime(),safeExpiredReplay=replay&&authority.planStatus==="accepted";if(!currentPlan&&!safeExpiredReplay)throw new NodeHttpError("state_conflict","node install plan is no longer current");if(authority.nodeVersion!==input.expectedVersion&&!replay)throw new NodeHttpError("version_conflict","node version changed");if(authority.generation!==receipt.nodeIdentityGeneration||authority.planId!==receipt.planId||`sha256:${authority.planDigest}`!==receipt.planDigest||authority.nodeId!==receipt.nodeId||authority.signingKeyId!==receipt.signingKeyId||`sha256:${authority.publicKeyFingerprint}`!==receipt.signerFingerprint||!authority.kubernetesBinding||(!replay&&canonicalJson(authority.kubernetesBinding)!==canonicalJson(input.kubernetesBinding)))throw new NodeHttpError("state_conflict","activation receipt or Kubernetes binding differs from trusted node state");verifyMutationCoverage(receipt,authority.canonicalPlan);if(!verifyNodeInstallReceiptSignature(authority.publicKey,digest,String(receipt.signature))||!verifyNodeProof(authority.publicKey,"blazn-node-activation-v1",request,proof))throw new NodeHttpError("identity_rejected","activation signatures could not be verified");const node=await tx.activateNode({nodeId:authority.nodeId,expectedVersion:input.expectedVersion,idempotencyKey,requestDigest:activationDigest,receipt,receiptId:String(receipt.receiptId),receiptDigest:digest.slice(7),planId:authority.planId,identityGeneration:Number(receipt.nodeIdentityGeneration),signerFingerprint:String(receipt.signerFingerprint).slice(7),signingKeyId:String(receipt.signingKeyId),signature:String(receipt.signature),kubernetesBinding:input.kubernetesBinding});if(!this.planFactory.signActivationGrant)throw new Error("Node activation signer is unavailable");const activationGrant=await this.planFactory.signActivationGrant({schemaVersion:"nodes/v1alpha1",kind:"node_capacity_activation",nodeId:authority.nodeId,planId:authority.planId,receiptDigest:digest,kubernetesBinding:input.kubernetesBinding});return{node,activationGrant:activationGrant as unknown as NodeActivationResponse["activationGrant"]};}).catch(mapStoreError);
  }

  async consumeJoin(issuanceId:string,idempotencyKey:string,input:{nodeId:string;enrollmentId:string;planId:string;joinedNodeUid:string;joinedNodeName:string;resourceVersion:string;clusterId:string},proof:string):Promise<NodeView>{
    validIdempotency(idempotencyKey);
    validUuid(issuanceId,"issuanceId"); for(const field of ["nodeId","enrollmentId","planId"] as const) validUuid(input[field],field); validateBinding({clusterId:input.clusterId,nodeName:input.joinedNodeName,nodeUid:input.joinedNodeUid,resourceVersion:input.resourceVersion});
    return this.store.transaction(async tx=>{const identity=await tx.activeIdentity(input.nodeId,true);if(!identity||identity.trustState==="revoked"||identity.lifecycleState==="removed"||!verifyNodeProof(identity.publicKey,"blazn-node-join-v1",input,proof))throw new NodeHttpError("identity_rejected","node identity is not active or proof could not be verified");
      return tx.consumeJoin({issuanceId,nodeId:input.nodeId,enrollmentId:input.enrollmentId,planId:input.planId,clusterId:input.clusterId,nodeName:input.joinedNodeName,nodeUid:input.joinedNodeUid,resourceVersion:input.resourceVersion,idempotencyKey,requestDigest:requestDigest({issuanceId,...input})});}).catch(mapStoreError);
  }
}

async function authorize(tx:NodeTransaction,principal:NodePrincipal,workspaceId:string,mutation:boolean,lock:boolean){const authority=await tx.authority(workspaceId,principal.userId,lock);if(!authority)throw new NodeHttpError("membership_required","active workspace membership is required");if(authority.workspaceStatus!=="active")throw new NodeHttpError("state_conflict","workspace is not active");if(!nodeRoleAllows(authority.role,mutation))throw new NodeHttpError("permission_denied","node action is not permitted");return authority;}
async function requiredNode(tx:NodeTransaction,nodeId:string,lock:boolean){validUuid(nodeId,"nodeId");const node=await tx.nodeById(nodeId,lock);if(!node)throw new NodeHttpError("node_not_found","node was not found");return node;}
function verifyReceipt(r:NodeIdempotencyReceipt,w:string,t:string,d:string){if(r.workspaceId!==w||r.targetKey!==t||r.requestDigest!==d)throw new NodeHttpError("idempotency_conflict","idempotency key is bound to another request");}
function validName(v:string){if(typeof v!=="string"||!v.trim()||v.length>128||!/^[a-z0-9](?:[a-z0-9.-]{0,126}[a-z0-9])?$/.test(v.trim()))invalid("name is invalid");}
function validPlatform(v:unknown):asserts v is NodePlatform{if(v!=="linux"&&v!=="macos")invalid("platform is invalid");}
function validArchitecture(v:unknown):asserts v is NodeArchitecture{if(v!=="amd64"&&v!=="arm64")invalid("architecture is invalid");}
function validUuid(v:string,f:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(v))invalid(`${f} must be a UUID`);}
function validIdempotency(v:string){if(typeof v!=="string"||v.length<8||v.length>128)invalid("Idempotency-Key is invalid");}
function validateBinding(v:KubernetesBinding){for(const [k,max] of [["clusterId",128],["nodeName",253],["nodeUid",128],["resourceVersion",128]] as const){const s=v[k];if(typeof s!=="string"||!s||s.length>max)invalid(`${k} is invalid`);}}
function requiredRenderedDigest(v:unknown,name:string):string{if(typeof v!=="string"||!/^sha256:[0-9a-f]{64}$/.test(v))throw new Error(`${name} is invalid`);return v;}
function requiredSignature(v:unknown):string{if(typeof v!=="string"||!/^[A-Za-z0-9_-]{86}$/.test(v))throw new Error("plan signature is invalid");return v;}
function requiredText(v:unknown,name:string,max:number):string{if(typeof v!=="string"||!v||v.length>max)throw new Error(`${name} is invalid`);return v;}
function validSigningKey(v:NodePlanSigningKey):NodePlanSigningKey{requiredText(v.keyId,"plan signing key ID",128);if(!/^[A-Za-z0-9_-]{43}$/.test(v.publicKey))throw new Error("plan signing public key is invalid");if(v.fingerprint!==`sha256:${publicKeyFingerprint(v.publicKey)}`)throw new Error("plan signing key fingerprint is inconsistent");return v;}
function sameSigningKey(a:NodePlanSigningKey,b:NodePlanSigningKey):boolean{return a.keyId===b.keyId&&a.publicKey===b.publicKey&&a.fingerprint===b.fingerprint;}
function validateHeartbeat(v:HeartbeatInput){validUuid(v.nodeId,"nodeId");if(!Number.isSafeInteger(v.identityGeneration)||v.identityGeneration<1)invalid("identityGeneration is invalid");if(typeof v.bootId!=="string"||!v.bootId||v.bootId.length>128)invalid("bootId is invalid");if(!Number.isSafeInteger(v.sequence)||v.sequence<0)invalid("sequence is invalid");if(!Number.isFinite(Date.parse(v.sentAt)))invalid("sentAt is invalid");if(typeof v.priorKubernetesResourceVersion!=="string"||!v.priorKubernetesResourceVersion||v.priorKubernetesResourceVersion.length>128)invalid("priorKubernetesResourceVersion is invalid");requiredRenderedDigest(v.capabilityDigest,"capabilityDigest");if(!v.capability||typeof v.capability!=="object"||Array.isArray(v.capability))invalid("capability is invalid");}
function validateInstallReceipt(value:Record<string,unknown>):Record<string,unknown>{
  const required=["schemaVersion","receiptId","planId","planDigest","nodeId","generation","nodeIdentityGeneration","signerKind","signerFingerprint","state","currentStage","owner","binary","service","mutations","residues","createdAt","updatedAt","signingKeyId","digest","signature"];
  exact(value,required);if(value.schemaVersion!=="nodes/v1alpha1"||value.signerKind!=="node_identity"||value.state!=="active"||value.currentStage!=="complete")invalid("install receipt terminal state is invalid");
  for(const field of ["receiptId","planId","nodeId"])validUuid(String(value[field]),field);for(const field of ["generation","nodeIdentityGeneration"]){if(!Number.isSafeInteger(value[field])||Number(value[field])<1)invalid(`install receipt ${field} is invalid`);}
  for(const field of ["planDigest","signerFingerprint","digest"])requiredRenderedDigest(value[field],field);requiredText(value.signingKeyId,"signingKeyId",128);requiredSignature(value.signature);
  const created=parseReceiptTime(value.createdAt,"createdAt"),updated=parseReceiptTime(value.updatedAt,"updatedAt");if(updated.getTime()<created.getTime())invalid("install receipt timestamps are invalid");
  const owner=record(value.owner,"owner");exact(owner,["uid","pid","processStartIdentity","nonce"]);if(!Number.isSafeInteger(owner.uid)||Number(owner.uid)<0||!Number.isSafeInteger(owner.pid)||Number(owner.pid)<1)invalid("install receipt owner is invalid");requiredText(owner.processStartIdentity,"owner.processStartIdentity",Number.MAX_SAFE_INTEGER);if(typeof owner.nonce!=="string"||!/^[A-Za-z0-9_-]{32,128}$/.test(owner.nonce))invalid("owner.nonce is invalid");
  const binary=record(value.binary,"binary");exact(binary,["path","digest"]);if(typeof binary.path!=="string"||!binary.path.startsWith("/"))invalid("binary.path is invalid");requiredRenderedDigest(binary.digest,"binary.digest");
  const service=record(value.service,"service");exact(service,["manager","name","definitionDigest","priorEnabled","priorActive"]);if(service.manager!=="systemd"&&service.manager!=="launchd")invalid("service.manager is invalid");requiredText(service.name,"service.name",256);requiredRenderedDigest(service.definitionDigest,"service.definitionDigest");if(typeof service.priorEnabled!=="boolean"||typeof service.priorActive!=="boolean")invalid("service prior state is invalid");
  const mutations=array(value.mutations,"mutations",256),seen=new Set<number>();for(const item of mutations){const mutation=record(item,"mutation");exact(mutation,["ordinal","kind","target","priorState","rollbackMaterial","desiredDigest","status"]);if(!Number.isSafeInteger(mutation.ordinal)||Number(mutation.ordinal)<1||seen.has(Number(mutation.ordinal)))invalid("mutation ordinal is invalid or duplicated");seen.add(Number(mutation.ordinal));if(!MUTATION_KINDS.has(String(mutation.kind))||typeof mutation.target!=="string"||!mutation.target||mutation.target.length>1024||!PRIOR_STATES.has(String(mutation.priorState))||mutation.status!=="applied")invalid("mutation evidence is invalid");if((mutation.kind==="group"||mutation.kind==="user")&&!/^[a-z_][a-z0-9_-]{0,31}$/.test(mutation.target))invalid("mutation account target is invalid");requiredRenderedDigest(mutation.desiredDigest,"mutation.desiredDigest");validateRollbackMaterial(String(mutation.priorState),String(mutation.kind),record(mutation.rollbackMaterial,"mutation.rollbackMaterial"));}
  const residues=array(value.residues,"residues",256);for(const item of residues){const residue=record(item,"residue");exact(residue,["target","reasonCode","safeMessage"]);if(typeof residue.target!=="string"||!residue.target||residue.target.length>1024||typeof residue.reasonCode!=="string"||!/^[a-z0-9_]{1,64}$/.test(residue.reasonCode)||typeof residue.safeMessage!=="string"||!residue.safeMessage||residue.safeMessage.length>512)invalid("install receipt residue is invalid");}if(residues.length!==0)invalid("active install receipt cannot contain residues");rejectSecrets(value);return value;
}
const MUTATION_KINDS=new Set(["group","user","package","file","directory","systemd_unit","launchd_unit","certificate","image","label","taint","firewall"]),PRIOR_STATES=new Set(["absent","owned","preexisting_exact"]),ROLLBACK_KINDS=new Set(["file_backup","package_snapshot","unit_snapshot","firewall_snapshot","metadata_snapshot"]);
function validateRollbackMaterial(priorState:string,kind:string,material:Record<string,unknown>):void{if(priorState==="absent"){exact(material,["kind"]);if(material.kind!=="absent")invalid("absent mutation rollback material is invalid");return;}exact(material,["kind","locator","digest","mode","uid","gid"]);if(!ROLLBACK_KINDS.has(String(material.kind))||typeof material.locator!=="string"||!/^receipt-backup:\/\/[A-Za-z0-9_-]{1,128}$/.test(material.locator))invalid("mutation rollback material is invalid");requiredRenderedDigest(material.digest,"mutation.rollbackMaterial.digest");for(const field of ["mode","uid","gid"]){if(!Number.isSafeInteger(material[field])||Number(material[field])<0)invalid(`mutation.rollbackMaterial.${field} is invalid`);}if(Number(material.mode)>4095||(kind==="group"||kind==="user")&&material.kind!=="metadata_snapshot")invalid("mutation rollback material is invalid");}
function parseReceiptTime(value:unknown,name:string):Date{const raw=typeof value==="string"?value:"",match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(?:Z|[+-](\d{2}):(\d{2}))$/.exec(raw);if(!match)invalid(`install receipt ${name} is invalid`);const year=Number(match[1]),month=Number(match[2]),day=Number(match[3]),hour=Number(match[4]),minute=Number(match[5]),second=Number(match[6]),offsetHour=Number(match[7]??0),offsetMinute=Number(match[8]??0);if(month<1||month>12||day<1||day>new Date(Date.UTC(year,month,0)).getUTCDate()||hour>23||minute>59||second>59||offsetHour>23||offsetMinute>59)invalid(`install receipt ${name} is invalid`);const parsed=new Date(raw);if(!Number.isFinite(parsed.getTime()))invalid(`install receipt ${name} is invalid`);return parsed;}
function verifyMutationCoverage(receipt:Record<string,unknown>,canonicalPlan:Record<string,unknown>):void{const evidence=receipt.mutations as Array<Record<string,unknown>>,planned=array(canonicalPlan.mutations,"canonical plan mutations",256).map(item=>record(item,"canonical plan mutation"));if(evidence.length!==planned.length)throw new NodeHttpError("state_conflict","install receipt does not cover the canonical plan mutations");const byOrdinal=new Map(evidence.map(item=>[Number(item.ordinal),item]));for(const mutation of planned){const ordinal=Number(mutation.ordinal),actual=byOrdinal.get(ordinal);if(!Number.isSafeInteger(ordinal)||ordinal<1||!actual||actual.kind!==mutation.kind||actual.target!==mutation.target||actual.desiredDigest!==mutation.desiredDigest||actual.status!=="applied")throw new NodeHttpError("state_conflict","install receipt mutation evidence differs from the canonical plan");}}
function bindingAdvances(current:KubernetesBinding,next:KubernetesBinding):boolean{return current.clusterId===next.clusterId&&current.nodeName===next.nodeName&&current.nodeUid===next.nodeUid&&current.resourceVersion.length>0&&next.resourceVersion.length>0;}
function rejectSecrets(value:unknown):void{if(Array.isArray(value)){for(const item of value)rejectSecrets(item);return;}if(value&&typeof value==="object"){for(const [key,child] of Object.entries(value)){const n=key.toLowerCase().replace(/[^a-z0-9]/g,"");if(["token","invitetoken","accesstoken","refreshtoken","authorization","password","secret","credential"].includes(n))invalid("capability contains a forbidden secret field");rejectSecrets(child);}}}
function validateCapability(c:Record<string,unknown>):void{
  exact(c,["version","host","worker","sandboxBackends","runtimeClasses","localModels"]);positiveInt(c.version,"capability.version");const host=record(c.host,"host"),worker=record(c.worker,"worker");
  exact(host,["platform","architecture","cpuMillis","memoryBytes","diskBytes","accelerators","health"]);validPlatform(host.platform);validArchitecture(host.architecture);for(const k of ["cpuMillis","memoryBytes","diskBytes"])positiveInt(host[k],`host.${k}`);validateHealth(record(host.health,"host.health"));array(host.accelerators,"host.accelerators",16).forEach((item)=>{const a=record(item,"accelerator");exact(a,["kind","count"]);boundedText(a.kind,"accelerator.kind",128);positiveInt(a.count,"accelerator.count");});
  exact(worker,["platform","architecture","allocatableCpuMillis","allocatableMemoryBytes","allocatableDiskBytes","labels","limits","health","kubernetesBinding"]);if(worker.platform!=="linux")invalid("worker.platform must be linux");validArchitecture(worker.architecture);for(const k of ["allocatableCpuMillis","allocatableMemoryBytes","allocatableDiskBytes"])positiveInt(worker[k],`worker.${k}`);const labels=record(worker.labels,"worker.labels");if(Object.keys(labels).length>64)invalid("worker labels are invalid");for(const [k,v] of Object.entries(labels)){if(!/^blazn\.dev\/[a-z0-9][a-z0-9._-]{0,62}$/.test(k)||typeof v!=="string"||v.length>128)invalid("worker labels are invalid");}const limits=record(worker.limits,"worker.limits");exact(limits,["maxConcurrentSandboxes","maxConcurrentAgents"]);for(const k of ["maxConcurrentSandboxes","maxConcurrentAgents"]){if(!Number.isSafeInteger(limits[k])||Number(limits[k])<0||Number(limits[k])>1024)invalid(`worker.limits.${k} is invalid`);}validateHealth(record(worker.health,"worker.health"));validateBinding(record(worker.kubernetesBinding,"worker.kubernetesBinding") as unknown as KubernetesBinding);
  for(const k of ["sandboxBackends","runtimeClasses"]){const values=array(c[k],k,128);if(new Set(values).size!==values.length||values.some(v=>typeof v!=="string"||v.length>128))invalid(`${k} is invalid`);}const models=array(c.localModels,"localModels",32);for(const item of models){const m=record(item,"localModel");exact(m,["routeId","displayName","model","protocol","endpointClass","capabilities","dataBoundary","healthy","maxConcurrency","maxContextTokens","maxOutputTokens"]);validUuid(boundedText(m.routeId,"routeId",64),"routeId");boundedText(m.displayName,"displayName",128);boundedText(m.model,"model",160);if(!["openai-chat","openai-responses"].includes(String(m.protocol))||!["loopback","authenticated_node_tunnel"].includes(String(m.endpointClass))||m.dataBoundary!=="local"||typeof m.healthy!=="boolean")invalid("local model routing metadata is invalid");const caps=array(m.capabilities,"capabilities",4);if(caps.length<1||new Set(caps).size!==caps.length||caps.some(v=>!["text","tools","structured_output","streaming"].includes(String(v))))invalid("local model capabilities are invalid");for(const k of ["maxConcurrency","maxContextTokens","maxOutputTokens"])positiveInt(m[k],`localModel.${k}`);}
}
function validateHealth(h:Record<string,unknown>){exact(h,["status","reasonCodes"]);if(!["healthy","degraded","unavailable"].includes(String(h.status)))invalid("health status is invalid");const reasons=array(h.reasonCodes,"reasonCodes",16);if(new Set(reasons).size!==reasons.length||reasons.some(v=>typeof v!=="string"||!/^[a-z0-9_]{1,64}$/.test(v)))invalid("health reasonCodes are invalid");}
function record(v:unknown,name:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))invalid(`${name} must be an object`);return v as Record<string,unknown>;}
function array(v:unknown,name:string,max:number):unknown[]{if(!Array.isArray(v)||v.length>max)invalid(`${name} must be an array with at most ${max} items`);return v;}
function positiveInt(v:unknown,name:string){if(typeof v!=="number"||!Number.isSafeInteger(v)||v<1)invalid(`${name} is invalid`);}
function boundedText(v:unknown,name:string,max:number):string{if(typeof v!=="string"||!v||v.length>max)invalid(`${name} is invalid`);return v;}
function capabilityHealth(c:Record<string,unknown>):unknown{const host=c.host,worker=c.worker;return{host:host&&typeof host==="object"?(host as Record<string,unknown>).health:null,worker:worker&&typeof worker==="object"?(worker as Record<string,unknown>).health:null};}
function validOperation(i:{type:NodeOperationType;expectedVersion:number;parameters:Record<string,unknown>}){if(!["pause","resume","label","cordon","uncordon","rotate_identity","repair","update","drain","remove"].includes(i.type))invalid("operation type is invalid");if(!Number.isSafeInteger(i.expectedVersion)||i.expectedVersion<1)invalid("expectedVersion is invalid");if(!i.parameters||typeof i.parameters!=="object"||Array.isArray(i.parameters))invalid("parameters must be an object");rejectSecrets(i.parameters);}
function exact(p:Record<string,unknown>,keys:string[]){if(Object.keys(p).length!==keys.length||keys.some(k=>!(k in p)))invalid("operation parameters are invalid");}
function validateOperationState(node:NodeView,type:NodeOperationType,p:Record<string,unknown>){if(node.lifecycleState==="removed")throw new NodeHttpError("state_conflict","removed node cannot be operated");if(type==="pause"&&node.lifecycleState!=="active")throw new NodeHttpError("state_conflict","only an active node can be paused");if(type==="resume"&&node.lifecycleState!=="paused")throw new NodeHttpError("state_conflict","only a paused node can be resumed");
  if(["pause","resume","rotate_identity","repair"].includes(type))exact(p,[]);
  if(type==="label"){exact(p,["key","value"]);if(typeof p.key!=="string"||!/^blazn\.dev\/[a-z0-9][a-z0-9._-]{0,62}$/.test(p.key)||typeof p.value!=="string"||p.value.length>128)invalid("label parameters are invalid");}
  if(type==="update"){exact(p,["targetVersion"]);if(typeof p.targetVersion!=="string"||!/^v[0-9]+\.[0-9]+\.[0-9]+(?:[-+][A-Za-z0-9.-]+)?$/.test(p.targetVersion)||p.targetVersion.length>128)invalid("update parameters are invalid");}
  if(["cordon","uncordon","drain","remove"].includes(type)){if(!node.kubernetesBinding)throw new NodeHttpError("state_conflict","operation requires a Kubernetes binding");const base=["clusterId","expectedNodeUid","expectedResourceVersion"];const extra=type==="drain"?["workspaceId","deadlineSeconds"]:type==="remove"?["confirm","preserveHostData"]:[];exact(p,[...base,...extra]);if(p.clusterId!==node.kubernetesBinding.clusterId||p.expectedNodeUid!==node.kubernetesBinding.nodeUid||p.expectedResourceVersion!==node.kubernetesBinding.resourceVersion)throw new NodeHttpError("version_conflict","Kubernetes binding changed");if(type==="drain"&&(p.workspaceId!==node.workspaceId||!Number.isSafeInteger(p.deadlineSeconds)||Number(p.deadlineSeconds)<60||Number(p.deadlineSeconds)>3600))invalid("drain parameters are invalid");if(type==="remove"&&(p.confirm!==true||p.preserveHostData!==true))invalid("remove confirmation is required");}
}
function mapStoreError(error:unknown):never{if(error instanceof NodeHttpError)throw error;if(error&&typeof error==="object"&&"nodeCode" in error)throw new NodeHttpError(error.nodeCode as never,error instanceof Error?error.message:"node request failed");if(error&&typeof error==="object"&&"code" in error&&error.code==="23505")throw new NodeHttpError("state_conflict","conflicting node state");throw error;}
function invalid(message:string):never{throw new NodeHttpError("invalid_request",message);}
