import assert from "node:assert/strict";
import test from "node:test";
import { createHash } from "node:crypto";
import { RunService } from "./run-service.js";
import { RunArtifactNameConflictError,RunArtifactSetError,RunProgressSequenceError,type RunStore,type RunTransaction } from "./run-store.js";
import { RunHttpError,type Artifact,type ArtifactStatus,type CompleteSyntheticRunInput,type Run,type RunAccess,type RunMessage,type RunMessageKind,type RunPrincipal,type RunReceipt,type RunStatus,type SyntheticArtifactUploadMetadata,type SyntheticRunProgressAck,type SyntheticRunProgressInput } from "./run-types.js";
import type { IdempotencyReceipt } from "./workspace-store.js";

const workspaceId="00000000-0000-4000-8000-000000000001",projectId="00000000-0000-4000-8000-000000000002",artifactId="00000000-0000-4000-8000-000000000005";
const owner:RunPrincipal={userId:"00000000-0000-4000-8000-000000000003",email:"owner@example.test",displayName:"Owner"};
const viewer:RunPrincipal={userId:"00000000-0000-4000-8000-000000000004",email:"viewer@example.test",displayName:"Viewer"};
const planDigest=`sha256:${"a".repeat(64)}`;

class MemoryRunStore implements RunStore,RunTransaction {
  runs=new Map<string,Run>();receipts=new Map<string,IdempotencyReceipt>();audits:string[]=[];progress=new Map<number,string>();messages:RunMessage[]=[];
  artifacts=new Map<string,Artifact>([[artifactId,{id:artifactId,workspaceId,projectId,kind:"source",mediaType:"video",name:"source.mp4",status:"ready",version:1,digest:`sha256:${"b".repeat(64)}`,sizeBytes:12,createdBy:owner.userId,createdAt:"2026-08-22T00:00:00Z",updatedAt:"2026-08-22T00:00:00Z",downloadAvailable:true}]]);
  async transaction<T>(action:(tx:RunTransaction)=>Promise<T>){return action(this);}async lockIdempotency(){}
  async getIdempotency(p:string,o:string,k:string){return this.receipts.get(`${p}:${o}:${k}`);}async putIdempotency(p:string,o:string,k:string,r:IdempotencyReceipt){this.receipts.set(`${p}:${o}:${k}`,r);}
  async getAccess(w:string,p:string,u:string):Promise<RunAccess|undefined>{if(w!==workspaceId)return undefined;const access:RunAccess={workspaceStatus:"active",role:u===viewer.userId?"viewer":"owner"};if(p===projectId)access.projectStatus="active";return access;}
  async createRun(i:{id:string;workspaceId:string;projectId:string;kind:string;proofClass:string;planDigest:string;outputNames:string[];requestedBy:string;inputArtifactIds:string[]}){const run:Run={...i,proofClass:i.proofClass as Run["proofClass"],status:"queued",version:1,placement:null,receipt:null,createdAt:"2026-08-22T00:00:00Z"};this.runs.set(i.id,run);return run;}
  async getRun(w:string,p:string,id:string){const run=this.runs.get(id);return run?.workspaceId===w&&run.projectId===p?run:undefined;}
  async listRuns(w:string,p:string,status:RunStatus|"all"){const items=[...this.runs.values()].filter(r=>r.workspaceId===w&&r.projectId===p&&(status==="all"||r.status===status));return{items,nextCursor:null};}
  async getRunMessage(w:string,p:string,r:string,id:string){return this.messages.find(message=>message.workspaceId===w&&message.projectId===p&&message.runId===r&&message.id===id);}
  async listRunMessages(w:string,p:string,r:string,cursor=""){const after=cursor===""?0:Number(cursor);return{items:this.messages.filter(message=>message.workspaceId===w&&message.projectId===p&&message.runId===r&&message.ordinal>after),nextCursor:null};}
  async insertRunMessage(input:{id:string;workspaceId:string;projectId:string;runId:string;kind:RunMessageKind;parentMessageId?:string;content:string;contentDigest:string;createdBy:string}){const message:RunMessage={...input,ordinal:this.messages.filter(value=>value.runId===input.runId).length+1,role:"user",status:"queued",createdAt:"2026-08-22T00:00:01Z"};this.messages.push(message);return message;}
  async cancelRun(current:Run){const receipt:RunReceipt={schemaVersion:"blazn.run/receipt/v1alpha1",proofClass:current.proofClass,outcome:"cancelled",planDigest:current.planDigest,artifactIds:[],summary:{steps:0,warnings:[]}};const run:Run={...current,status:"cancelled",version:current.version+1,completedAt:"2026-08-22T00:01:00Z",receipt};this.runs.set(run.id,run);return run;}
  async recordSyntheticProgress(current:Run,input:SyntheticRunProgressInput,digest:string):Promise<SyntheticRunProgressAck>{if(this.progress.has(input.sequence)||input.sequence!==this.progress.size)throw new RunProgressSequenceError();this.progress.set(input.sequence,digest);const run:Run=current.status==="queued"?{...current,status:"running",version:current.version+1,startedAt:"2026-08-22T00:00:01Z"}:current;this.runs.set(run.id,run);return{runId:run.id,sequence:input.sequence,runVersion:run.version,status:"running"};}
  async createSyntheticArtifact(current:Run,id:string,metadata:SyntheticArtifactUploadMetadata,_content:Buffer,createdBy:string){if([...this.artifacts.values()].some(value=>value.sourceRunId===current.id&&value.name===metadata.name))throw new RunArtifactNameConflictError();const artifact:Artifact={id,workspaceId:current.workspaceId,projectId:current.projectId,sourceRunId:current.id,kind:metadata.kind,mediaType:metadata.mediaType,name:metadata.name,status:"ready",version:1,digest:metadata.digest,sizeBytes:metadata.sizeBytes,createdBy,createdAt:"2026-08-22T00:00:02Z",updatedAt:"2026-08-22T00:00:02Z",downloadAvailable:true};this.artifacts.set(id,artifact);return artifact;}
  async completeSyntheticRun(current:Run,input:CompleteSyntheticRunInput){const artifacts=input.artifactIds.map(id=>this.artifacts.get(id));if(artifacts.some(value=>!value||value.sourceRunId!==current.id)||artifacts.map(value=>value!.name).sort().join("\n")!==[...current.outputNames].sort().join("\n"))throw new RunArtifactSetError();const receipt:RunReceipt={schemaVersion:"blazn.run/receipt/v1alpha1",proofClass:"synthetic",outcome:"succeeded",planDigest:current.planDigest,artifactIds:[...input.artifactIds],summary:{steps:input.summary.steps,warnings:[...input.summary.warnings]}};const run:Run={...current,status:"succeeded",version:current.version+1,completedAt:"2026-08-22T00:00:03Z",receipt};this.runs.set(run.id,run);return run;}
  async getArtifact(w:string,p:string,id:string){const artifact=this.artifacts.get(id);return artifact?.workspaceId===w&&artifact.projectId===p?artifact:undefined;}
  async listArtifacts(w:string,p:string,status:ArtifactStatus|"all"){return{items:[...this.artifacts.values()].filter(a=>a.workspaceId===w&&a.projectId===p&&(status==="all"||a.status===status)),nextCursor:null};}
  async insertAudit(_id:string,_w:string,_u:string,type:string){this.audits.push(type);}
}

test("Run creation is idempotent, tenant-bound, and validates structured inputs",async()=>{const store=new MemoryRunStore(),service=new RunService(store);const input={kind:"content.render",proofClass:"synthetic" as const,planDigest,inputArtifactIds:[artifactId],outputNames:["preview.mp4"]};const first=await service.createRun(owner,workspaceId,projectId,"run-create-1",input),replay=await service.createRun(owner,workspaceId,projectId,"run-create-1",input);assert.equal(first.run.id,replay.run.id);assert.deepEqual(first.run.inputArtifactIds,[artifactId]);assert.deepEqual(store.audits,["run.created"]);await assert.rejects(()=>service.createRun(owner,workspaceId,projectId,"run-create-1",{...input,kind:"content.other"}),isCode("idempotency_conflict"));await assert.rejects(()=>service.createRun(owner,workspaceId,projectId,"run-create-2",{...input,outputNames:["same","same"]}),isCode("invalid_request"));await assert.rejects(()=>service.createRun(owner,workspaceId,"00000000-0000-4000-8000-000000000099","run-create-3",input),isCode("project_not_found"));});

test("Run reads allow viewers while create and cancellation require operate",async()=>{const store=new MemoryRunStore(),service=new RunService(store),input={kind:"content.render",proofClass:"synthetic" as const,planDigest,inputArtifactIds:[],outputNames:[]};const created=await service.createRun(owner,workspaceId,projectId,"run-create-4",input);assert.equal((await service.listRuns(viewer,workspaceId,projectId)).items.length,1);assert.equal((await service.getRun(viewer,workspaceId,projectId,created.run.id)).run.id,created.run.id);assert.equal((await service.getArtifact(viewer,workspaceId,projectId,artifactId)).artifact.id,artifactId);await assert.rejects(()=>service.createRun(viewer,workspaceId,projectId,"run-create-5",input),isCode("permission_denied"));await assert.rejects(()=>service.cancelRun(viewer,workspaceId,projectId,created.run.id,"run-cancel-1",1),isCode("permission_denied"));});

test("Run cancellation records a bound terminal receipt and enforces optimistic versions",async()=>{const store=new MemoryRunStore(),service=new RunService(store),created=await service.createRun(owner,workspaceId,projectId,"run-create-6",{kind:"content.render",proofClass:"synthetic",planDigest,inputArtifactIds:[],outputNames:[]});const cancelled=await service.cancelRun(owner,workspaceId,projectId,created.run.id,"run-cancel-2",1);assert.equal(cancelled.run.status,"cancelled");assert.equal(cancelled.run.version,2);assert.equal(cancelled.run.receipt?.planDigest,planDigest);assert.equal((await service.cancelRun(owner,workspaceId,projectId,created.run.id,"run-cancel-2",1)).run.version,2);await assert.rejects(()=>service.cancelRun(owner,workspaceId,projectId,created.run.id,"run-cancel-3",1),isCode("version_conflict"));assert.deepEqual(store.audits,["run.created","run.cancelled"]);});

test("Run messages preserve prompt, queued follow-up, steering, parent, tenant, and idempotency semantics",async()=>{const store=new MemoryRunStore(),service=new RunService(store),created=await service.createRun(owner,workspaceId,projectId,"run-create-message-1",{kind:"agent.task",proofClass:"sandbox",planDigest,inputArtifactIds:[],outputNames:[]}),runId=created.run.id;await assert.rejects(()=>service.sendRunMessage(owner,workspaceId,projectId,runId,"message-followup-first",{kind:"followup",content:"later"}),isCode("message_conflict"));const prompt=await service.sendRunMessage(owner,workspaceId,projectId,runId,"message-prompt-1",{kind:"prompt",content:"Inspect the repository"});assert.equal(prompt.message.ordinal,1);assert.equal(prompt.message.contentDigest,`sha256:${createHash("sha256").update("Inspect the repository").digest("hex")}`);assert.equal((await service.sendRunMessage(owner,workspaceId,projectId,runId,"message-prompt-1",{kind:"prompt",content:"Inspect the repository"})).message.id,prompt.message.id);await assert.rejects(()=>service.sendRunMessage(owner,workspaceId,projectId,runId,"message-prompt-2",{kind:"prompt",content:"replacement"}),isCode("message_conflict"));const followup=await service.sendRunMessage(owner,workspaceId,projectId,runId,"message-followup-1",{kind:"followup",content:"Also run tests",parentMessageId:prompt.message.id});assert.equal(followup.message.ordinal,2);assert.equal((await service.listRunMessages(viewer,workspaceId,projectId,runId)).items.length,2);await assert.rejects(()=>service.sendRunMessage(owner,workspaceId,projectId,runId,"message-steer-queued",{kind:"steer",content:"Stop editing"}),isCode("message_conflict"));store.runs.set(runId,{...created.run,status:"running",version:2,startedAt:"2026-08-22T00:00:02Z",placement:{nodeId:"00000000-0000-4000-8000-000000000010",sandboxId:"00000000-0000-4000-8000-000000000011"}});assert.equal((await service.sendRunMessage(owner,workspaceId,projectId,runId,"message-steer-1",{kind:"steer",content:"Only change documentation"})).message.ordinal,3);await assert.rejects(()=>service.sendRunMessage(viewer,workspaceId,projectId,runId,"message-viewer-1",{kind:"followup",content:"denied"}),isCode("permission_denied"));assert.deepEqual(store.audits,["run.created","run.message_queued","run.message_queued","run.message_queued"]);});

test("synthetic execution records monotonic progress, verified Artifacts, and a bound terminal receipt",async()=>{const store=new MemoryRunStore(),service=new RunService(store),created=await service.createRun(owner,workspaceId,projectId,"run-create-synthetic-1",{kind:"content.render",proofClass:"synthetic",planDigest,inputArtifactIds:[],outputNames:["preview.mp4"]});const first=await service.recordSyntheticProgress(owner,workspaceId,projectId,created.run.id,"progress-key-0",{sequence:0,phase:"render.plan",percent:0,message:"not persisted"});assert.equal(first.status,"running");assert.equal(first.runVersion,2);assert.deepEqual(await service.recordSyntheticProgress(owner,workspaceId,projectId,created.run.id,"progress-key-0",{sequence:0,phase:"render.plan",percent:0,message:"not persisted"}),first);await assert.rejects(()=>service.recordSyntheticProgress(owner,workspaceId,projectId,created.run.id,"progress-key-2",{sequence:2,phase:"render",percent:50}),isCode("run_sequence_conflict"));const content=Buffer.from("hello world!"),digest=`sha256:${createHash("sha256").update(content).digest("hex")}`,uploaded=await service.uploadSyntheticArtifact(owner,workspaceId,projectId,created.run.id,"upload-key-1",{name:"preview.mp4",kind:"content.video",mediaType:"video",sizeBytes:content.length,digest},content);assert.equal(uploaded.artifact.sourceRunId,created.run.id);assert.equal((await service.uploadSyntheticArtifact(owner,workspaceId,projectId,created.run.id,"upload-key-1",{name:"preview.mp4",kind:"content.video",mediaType:"video",sizeBytes:content.length,digest},content)).artifact.id,uploaded.artifact.id);const completed=await service.completeSyntheticRun(owner,workspaceId,projectId,created.run.id,"complete-key-1",{expectedVersion:2,planDigest,artifactIds:[uploaded.artifact.id],summary:{steps:1,warnings:[]}});assert.equal(completed.run.status,"succeeded");assert.equal(completed.run.receipt?.artifactIds[0],uploaded.artifact.id);assert.equal((await service.preflightSyntheticUpload(owner,workspaceId,projectId,created.run.id,"upload-key-1",{name:"preview.mp4",kind:"content.video",mediaType:"video",sizeBytes:content.length,digest}))?.artifact.id,uploaded.artifact.id);assert.deepEqual(store.audits,["run.created","run.synthetic_progress","artifact.synthetic_uploaded","run.synthetic_completed"]);});

test("synthetic authority rejects other principals, proof classes, digest drift, and undeclared outputs",async()=>{const store=new MemoryRunStore(),service=new RunService(store),created=await service.createRun(owner,workspaceId,projectId,"run-create-synthetic-2",{kind:"content.render",proofClass:"synthetic",planDigest,inputArtifactIds:[],outputNames:["preview.mp4"]});await assert.rejects(()=>service.recordSyntheticProgress(viewer,workspaceId,projectId,created.run.id,"progress-viewer",{sequence:0,phase:"render",percent:0}),isCode("permission_denied"));await service.recordSyntheticProgress(owner,workspaceId,projectId,created.run.id,"progress-owner",{sequence:0,phase:"render",percent:0});const content=Buffer.from("x"),digest=`sha256:${createHash("sha256").update(content).digest("hex")}`;await assert.rejects(()=>service.uploadSyntheticArtifact(owner,workspaceId,projectId,created.run.id,"upload-other",{name:"other.mp4",kind:"content.video",mediaType:"video",sizeBytes:1,digest},content),isCode("artifact_name_conflict"));await assert.rejects(()=>service.uploadSyntheticArtifact(owner,workspaceId,projectId,created.run.id,"upload-digest",{name:"preview.mp4",kind:"content.video",mediaType:"video",sizeBytes:1,digest:`sha256:${"f".repeat(64)}`},content),isCode("artifact_digest_mismatch"));await assert.rejects(()=>service.completeSyntheticRun(owner,workspaceId,projectId,created.run.id,"complete-drift",{expectedVersion:2,planDigest:`sha256:${"f".repeat(64)}`,artifactIds:[],summary:{steps:0,warnings:[]}}),isCode("invalid_request"));});

function isCode(code:string){return(error:unknown)=>error instanceof RunHttpError&&error.code===code;}
