import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import test from "node:test";
import { createDatabase } from "./db.js";
import { RunService } from "./run-service.js";
import { PgRunStore } from "./run-store.js";
import { RunHttpError,type RunPrincipal } from "./run-types.js";

const runtimeUrl=process.env.BLAZN_RUN_TEST_DATABASE_URL,adminUrl=process.env.BLAZN_RUN_TEST_ADMIN_DATABASE_URL;
test("PostgreSQL Run, message, and Artifact runtime enforces idempotency, tenancy, receipts, and no-delete history",{skip:!runtimeUrl||!adminUrl},async()=>{const runtime=createDatabase(runtimeUrl!),admin=createDatabase(adminUrl!),owner=principal(),viewer=principal(),outsider=principal(),workspaceId=randomUUID(),otherWorkspaceId=randomUUID(),projectId=randomUUID(),otherProjectId=randomUUID(),artifactId=randomUUID();try{
  for(const user of [owner,viewer,outsider])await admin.query("INSERT INTO users(id,email,display_name,password_salt,password_hash) VALUES($1,$2,$3,'salt','hash')",[user.userId,user.email,user.displayName]);
  await admin.query("INSERT INTO workspaces(id,slug,name,created_by) VALUES($1,$2,'Run Test',$3),($4,$5,'Other Run Test',$6)",[workspaceId,`run-${owner.userId.slice(0,8)}`,owner.userId,otherWorkspaceId,`other-${outsider.userId.slice(0,8)}`,outsider.userId]);
  await admin.query("INSERT INTO workspace_memberships(workspace_id,user_id,role) VALUES($1,$2,'owner'),($1,$3,'viewer'),($4,$5,'owner')",[workspaceId,owner.userId,viewer.userId,otherWorkspaceId,outsider.userId]);
  await admin.query("INSERT INTO projects(id,workspace_id,slug,kind,name,created_by) VALUES($1,$2,'content','content','Content',$3),($4,$5,'other','content','Other',$6)",[projectId,workspaceId,owner.userId,otherProjectId,otherWorkspaceId,outsider.userId]);
  await admin.query("INSERT INTO artifacts(id,workspace_id,project_id,kind,media_type,name,status,digest,size_bytes,object_key,created_by) VALUES($1,$2,$3,'source','video','source.mp4','ready',$4,12,'workspaces/test/source.mp4',$5)",[artifactId,workspaceId,projectId,`sha256:${"b".repeat(64)}`,owner.userId]);
  const service=new RunService(new PgRunStore(runtime)),input={kind:"content.render",proofClass:"synthetic" as const,planDigest:`sha256:${"a".repeat(64)}`,inputArtifactIds:[artifactId],outputNames:["preview.mp4"]};
  const [first,replay]=await Promise.all([service.createRun(owner,workspaceId,projectId,"run-create-pg-1",input),service.createRun(owner,workspaceId,projectId,"run-create-pg-1",input)]);assert.equal(first.run.id,replay.run.id);assert.deepEqual(first.run.inputArtifactIds,[artifactId]);
  await assert.rejects(()=>service.createRun(owner,workspaceId,projectId,"run-create-pg-1",{...input,kind:"content.other"}),isCode("idempotency_conflict"));await assert.rejects(()=>service.createRun(owner,workspaceId,projectId,"run-create-pg-2",{...input,inputArtifactIds:[randomUUID()]}),isCode("artifact_not_found"));
  assert.equal((await service.listRuns(viewer,workspaceId,projectId)).items.length,1);assert.equal((await service.getRun(viewer,workspaceId,projectId,first.run.id)).run.id,first.run.id);const artifact=(await service.getArtifact(viewer,workspaceId,projectId,artifactId)).artifact;assert.equal(artifact.downloadAvailable,true);assert.equal("objectKey" in artifact,false);await assert.rejects(()=>service.getRun(outsider,otherWorkspaceId,otherProjectId,first.run.id),isCode("run_not_found"));const prompt=await service.sendRunMessage(owner,workspaceId,projectId,first.run.id,"message-pg-prompt",{kind:"prompt",content:"Inspect the repository"}),followup=await service.sendRunMessage(owner,workspaceId,projectId,first.run.id,"message-pg-followup",{kind:"followup",content:"Also run tests",parentMessageId:prompt.message.id});assert.equal(followup.message.ordinal,2);assert.deepEqual((await service.listRunMessages(viewer,workspaceId,projectId,first.run.id)).items.map(message=>message.content),["Inspect the repository","Also run tests"]);await assert.rejects(()=>service.sendRunMessage(viewer,workspaceId,projectId,first.run.id,"message-pg-viewer",{kind:"followup",content:"denied"}),isCode("permission_denied"));await assert.rejects(()=>service.cancelRun(viewer,workspaceId,projectId,first.run.id,"run-cancel-pg-viewer",1),isCode("permission_denied"));
  const [cancelled,cancelReplay]=await Promise.all([service.cancelRun(owner,workspaceId,projectId,first.run.id,"run-cancel-pg-1",1),service.cancelRun(owner,workspaceId,projectId,first.run.id,"run-cancel-pg-1",1)]);assert.equal(cancelled.run.status,"cancelled");assert.equal(cancelReplay.run.version,2);assert.equal(cancelled.run.receipt?.outcome,"cancelled");assert.equal(cancelled.run.receipt?.planDigest,input.planDigest);
  const receipt=await admin.query("SELECT proof_class,outcome,plan_digest,receipt FROM run_receipts WHERE run_id=$1",[first.run.id]);assert.equal(receipt.rows[0]?.proof_class,"synthetic");assert.equal(receipt.rows[0]?.outcome,"cancelled");assert.equal(receipt.rows[0]?.receipt.schemaVersion,"blazn.run/receipt/v1alpha1");const events=await admin.query<{type:string}>("SELECT type FROM run_events WHERE run_id=$1 ORDER BY sequence",[first.run.id]);assert.deepEqual(events.rows.map(row=>row.type),["run.queued","message.queued","message.queued","run.cancelled"]);const stored=await admin.query("SELECT ordinal,kind,status,content,content_digest FROM run_messages WHERE run_id=$1 ORDER BY ordinal",[first.run.id]);assert.equal(stored.rows.length,2);assert.equal(stored.rows[0]?.content_digest,`sha256:${createHash("sha256").update("Inspect the repository").digest("hex")}`);
  const synthetic=await service.createRun(owner,workspaceId,projectId,"run-create-pg-synthetic",{...input,inputArtifactIds:[],outputNames:["preview.mp4"]});const ack=await service.recordSyntheticProgress(owner,workspaceId,projectId,synthetic.run.id,"progress-pg-0",{sequence:0,phase:"render.plan",percent:0,message:"discarded"});assert.equal(ack.runVersion,2);const content=Buffer.from("hello world!"),contentDigest=`sha256:${createHash("sha256").update(content).digest("hex")}`,uploaded=await service.uploadSyntheticArtifact(owner,workspaceId,projectId,synthetic.run.id,"upload-pg-1",{name:"preview.mp4",kind:"content.video",mediaType:"video",sizeBytes:content.length,digest:contentDigest},content);assert.equal(uploaded.artifact.downloadAvailable,true);const completed=await service.completeSyntheticRun(owner,workspaceId,projectId,synthetic.run.id,"complete-pg-1",{expectedVersion:2,planDigest:input.planDigest,artifactIds:[uploaded.artifact.id],summary:{steps:1,warnings:[]}});assert.equal(completed.run.status,"succeeded");assert.equal(completed.run.receipt?.artifactIds[0],uploaded.artifact.id);const uploadReplay=await service.preflightSyntheticUpload(owner,workspaceId,projectId,synthetic.run.id,"upload-pg-1",{name:"preview.mp4",kind:"content.video",mediaType:"video",sizeBytes:content.length,digest:contentDigest});assert.equal(uploadReplay?.artifact.id,uploaded.artifact.id);const progress=await admin.query("SELECT sequence,phase,percent FROM run_synthetic_progress WHERE run_id=$1",[synthetic.run.id]);assert.deepEqual(progress.rows,[{sequence:"0",phase:"render.plan",percent:0}]);const blob=await admin.query("SELECT octet_length(content) AS size FROM synthetic_artifact_blobs WHERE artifact_id=$1",[uploaded.artifact.id]);assert.equal(Number(blob.rows[0]?.size),content.length);
  const runEvents=await service.listRunEvents(viewer,workspaceId,projectId,synthetic.run.id);assert.deepEqual(runEvents.items.map(entry=>entry.type),["run.queued","run.progress","artifact.ready","run.succeeded"]);assert.equal(runEvents.nextCursor,null);const runEventsAfter=await service.listRunEvents(viewer,workspaceId,projectId,synthetic.run.id,String(runEvents.items[0]!.sequence));assert.equal(runEventsAfter.items[0]?.type,"run.progress");const progressList=await service.listRunProgress(viewer,workspaceId,projectId,synthetic.run.id);assert.deepEqual(progressList.items.map(entry=>[entry.sequence,entry.phase,entry.percent]),[[0,"render.plan",0]]);const runArtifacts=await service.listRunArtifacts(viewer,workspaceId,projectId,synthetic.run.id);assert.deepEqual(runArtifacts.items.map(artifact=>artifact.name),["preview.mp4"]);await assert.rejects(()=>service.listRunEvents(outsider,workspaceId,projectId,synthetic.run.id),isCode("workspace_not_found"));
  await assert.rejects(()=>runtime.query("DELETE FROM runs WHERE id=$1",[first.run.id]),pgCode("42501"));await assert.rejects(()=>runtime.query("DELETE FROM run_messages WHERE run_id=$1",[first.run.id]),pgCode("42501"));await assert.rejects(()=>runtime.query("DELETE FROM artifacts WHERE id=$1",[artifactId]),pgCode("42501"));
}finally{await admin.query("DELETE FROM workspaces WHERE id=ANY($1::uuid[])",[[workspaceId,otherWorkspaceId]]).catch(()=>{});await admin.query("DELETE FROM users WHERE id=ANY($1::uuid[])",[[owner.userId,viewer.userId,outsider.userId]]).catch(()=>{});await runtime.end();await admin.end();}});
function principal():RunPrincipal{const userId=randomUUID();return{userId,email:`${userId}@example.test`,displayName:userId.slice(0,8)};}function isCode(code:string){return(error:unknown)=>error instanceof RunHttpError&&error.code===code;}function pgCode(code:string){return(error:unknown)=>!!error&&typeof error==="object"&&"code" in error&&error.code===code;}
