import assert from "node:assert/strict";
import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import test from "node:test";
import { RunHttpRouter } from "./run-http.js";
import type { RunService } from "./run-service.js";
import { RunHttpError } from "./run-types.js";

const workspaceId="00000000-0000-4000-8000-000000000001",projectId="00000000-0000-4000-8000-000000000002",runId="00000000-0000-4000-8000-000000000003",artifactId="00000000-0000-4000-8000-000000000004";
const principal={userId:"00000000-0000-4000-8000-000000000005",email:"user@example.test",displayName:"User"};
function run(){return{id:runId,workspaceId,projectId,kind:"content.render",proofClass:"synthetic" as const,status:"queued" as const,version:1,planDigest:`sha256:${"a".repeat(64)}`,inputArtifactIds:[],outputNames:[],requestedBy:principal.userId,placement:null,receipt:null,createdAt:"2026-08-22T00:00:00Z"};}
test("Run HTTP routes preserve idempotency, defaults, and resource IDs",async()=>{const calls:Array<{method:string;values:unknown[]}>=[];const service={async createRun(...values:unknown[]){calls.push({method:"create",values});return{run:run()};},async listRuns(...values:unknown[]){calls.push({method:"listRuns",values});return{items:[run()],nextCursor:null};},async getRun(...values:unknown[]){calls.push({method:"getRun",values});return{run:run()};},async cancelRun(...values:unknown[]){calls.push({method:"cancel",values});return{run:{...run(),status:"cancelled"}};},async listArtifacts(...values:unknown[]){calls.push({method:"listArtifacts",values});return{items:[],nextCursor:null};},async getArtifact(...values:unknown[]){calls.push({method:"getArtifact",values});return{artifact:{id:artifactId}};}} as unknown as RunService;const server=fixtureServer(new RunHttpRouter(service));await listen(server);try{const origin=base(server);let response=await fetch(`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/runs`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":"run-create-1"},body:JSON.stringify({kind:"content.render",proofClass:"synthetic",planDigest:`sha256:${"a".repeat(64)}`,inputArtifactIds:[],outputNames:[]})});assert.equal(response.status,202);response=await fetch(`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/runs`);assert.equal(response.status,200);response=await fetch(`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/runs/${runId}`);assert.equal(response.status,200);response=await fetch(`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/runs/${runId}/cancel`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":"run-cancel-1"},body:JSON.stringify({expectedVersion:1})});assert.equal(response.status,200);response=await fetch(`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/artifacts`);assert.equal(response.status,200);response=await fetch(`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/artifacts/${artifactId}`);assert.equal(response.status,200);assert.deepEqual(calls.map(c=>c.method),["create","listRuns","getRun","cancel","listArtifacts","getArtifact"]);assert.deepEqual(calls[1]!.values.slice(3),["all",""]);assert.deepEqual(calls[4]!.values.slice(3),["ready",""]);assert.equal(calls[0]!.values[3],"run-create-1");}finally{await close(server);}});
test("Run HTTP rejects unknown fields, repeated filters, unsafe IDs, and methods",async()=>{const service=new Proxy({}, {get(){return async()=>{throw new Error("must not call");};}}) as RunService;const server=fixtureServer(new RunHttpRouter(service));await listen(server);try{const origin=base(server),body={kind:"content.render",proofClass:"synthetic",planDigest:`sha256:${"a".repeat(64)}`,inputArtifactIds:[],outputNames:[],apiKey:"forbidden"};for(const [url,init] of [[`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/runs`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":"run-create-1"},body:JSON.stringify(body)}],[`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/runs?status=all&status=queued`,{method:"GET"}],[`${origin}/v1/workspaces/not-a-uuid/projects/${projectId}/runs`,{method:"GET"}],[`${origin}/v1/workspaces/${workspaceId}/projects/${projectId}/artifacts`,{method:"POST"}]] as Array<[string,RequestInit]>){const response=await fetch(url,init);assert.ok(response.status>=400);}}finally{await close(server);}});
function fixtureServer(router:RunHttpRouter){return createServer((request,response)=>{const url=new URL(request.url??"/","http://127.0.0.1");router.handle(request,response,url,principal).catch((error:unknown)=>{const failure=error instanceof RunHttpError?error:new RunHttpError("invalid_request","failed");response.writeHead(failure.status,{"content-type":"application/json"});response.end(JSON.stringify({code:failure.code}));});});}
async function listen(server:ReturnType<typeof createServer>){await new Promise<void>((resolve,reject)=>server.listen(0,"127.0.0.1",resolve).once("error",reject));}async function close(server:ReturnType<typeof createServer>){await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}function base(server:ReturnType<typeof createServer>){return`http://127.0.0.1:${(server.address() as AddressInfo).port}`;}
