import type { PoolClient, QueryResultRow } from "pg";
import type { Database } from "./db.js";
import type { IdempotencyReceipt } from "./workspace-store.js";
import type { Artifact, ArtifactStatus, CompleteSyntheticRunInput, Run, RunAccess, RunMessage, RunMessageClaim, RunMessageKind, RunReceipt, RunStatus, SyntheticArtifactUploadMetadata, SyntheticRunProgressAck, SyntheticRunProgressInput } from "./run-types.js";

export interface RunTransaction {
  lockIdempotency(principalId:string,operation:string,key:string):Promise<void>;
  getIdempotency(principalId:string,operation:string,key:string):Promise<IdempotencyReceipt|undefined>;
  putIdempotency(principalId:string,operation:string,key:string,receipt:IdempotencyReceipt):Promise<void>;
  getAccess(workspaceId:string,projectId:string,userId:string,lock?:boolean):Promise<RunAccess|undefined>;
  createRun(input:{id:string;workspaceId:string;projectId:string;kind:string;proofClass:string;planDigest:string;outputNames:string[];requestedBy:string;inputArtifactIds:string[]}):Promise<Run>;
  getRun(workspaceId:string,projectId:string,runId:string,lock?:boolean):Promise<Run|undefined>;
  listRuns(workspaceId:string,projectId:string,status:RunStatus|"all",cursor?:string):Promise<{items:Run[];nextCursor:string|null}>;
  getRunMessage(workspaceId:string,projectId:string,runId:string,messageId:string):Promise<RunMessage|undefined>;
  listRunMessages(workspaceId:string,projectId:string,runId:string,cursor?:string):Promise<{items:RunMessage[];nextCursor:string|null}>;
  hasUndeliveredRunMessages(runId:string):Promise<boolean>;
  insertRunMessage(input:{id:string;workspaceId:string;projectId:string;runId:string;kind:RunMessageKind;parentMessageId?:string;content:string;contentDigest:string;createdBy:string}):Promise<RunMessage>;
  claimRunMessage(run:Run,claimedBy:string,claimId:string,leaseSeconds:number):Promise<RunMessageClaim|undefined>;
  renewRunMessageClaim(run:Run,messageId:string,claimedBy:string,claimId:string,leaseSeconds:number):Promise<RunMessageClaim|undefined>;
  deliverRunMessage(run:Run,messageId:string,claimedBy:string,claimId:string):Promise<RunMessage|undefined>;
  cancelRun(run:Run):Promise<Run|undefined>;
  recordSyntheticProgress(run:Run,input:SyntheticRunProgressInput,requestDigest:string):Promise<SyntheticRunProgressAck>;
  createSyntheticArtifact(run:Run,id:string,metadata:SyntheticArtifactUploadMetadata,content:Buffer,createdBy:string):Promise<Artifact>;
  completeSyntheticRun(run:Run,input:CompleteSyntheticRunInput):Promise<Run|undefined>;
  getArtifact(workspaceId:string,projectId:string,artifactId:string):Promise<Artifact|undefined>;
  listArtifacts(workspaceId:string,projectId:string,status:ArtifactStatus|"all",cursor?:string):Promise<{items:Artifact[];nextCursor:string|null}>;
  insertAudit(id:string,workspaceId:string,actorUserId:string,type:string,payload:unknown):Promise<void>;
}
export interface RunStore { transaction<T>(action:(transaction:RunTransaction)=>Promise<T>):Promise<T> }

export class PgRunStore implements RunStore {
  constructor(private readonly database:Database){}
  async transaction<T>(action:(transaction:RunTransaction)=>Promise<T>):Promise<T>{
    const client=await this.database.connect(); try{await client.query("BEGIN");const result=await action(new PgRunTransaction(client));await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
  }
}

class PgRunTransaction implements RunTransaction {
  constructor(private readonly client:PoolClient){}
  async lockIdempotency(principalId:string,operation:string,key:string){await this.client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`${principalId}\n${operation}\n${key}`]);}
  async getIdempotency(principalId:string,operation:string,key:string){const result=await this.client.query("SELECT workspace_id,target_key,request_digest,response_status,response_body FROM workspace_idempotency_receipts WHERE principal_id=$1 AND operation=$2 AND idempotency_key=$3",[principalId,operation,key]);const row=result.rows[0];return row?{workspaceId:row.workspace_id,targetKey:row.target_key,requestDigest:row.request_digest.trim(),responseStatus:row.response_status,responseBody:row.response_body}:undefined;}
  async putIdempotency(principalId:string,operation:string,key:string,receipt:IdempotencyReceipt){await this.client.query("INSERT INTO workspace_idempotency_receipts(principal_id,workspace_id,operation,target_key,idempotency_key,request_digest,response_status,response_body) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[principalId,receipt.workspaceId,operation,receipt.targetKey,key,receipt.requestDigest,receipt.responseStatus,receipt.responseBody]);}
  async getAccess(workspaceId:string,projectId:string,userId:string,lock=false):Promise<RunAccess|undefined>{
    const suffix=lock?" FOR SHARE OF w,m":"";const result=await this.client.query(`SELECT w.status AS workspace_status,m.role FROM workspaces w JOIN workspace_memberships m ON m.workspace_id=w.id AND m.user_id=$2 AND m.status='active' WHERE w.id=$1${suffix}`,[workspaceId,userId]);const row=result.rows[0];if(!row)return undefined;const project=await this.client.query(`SELECT status FROM projects WHERE workspace_id=$1 AND id=$2${lock?" FOR SHARE":""}`,[workspaceId,projectId]);const access:RunAccess={workspaceStatus:row.workspace_status,role:row.role};if(project.rows[0])access.projectStatus=project.rows[0].status;return access;
  }
  async createRun(input:{id:string;workspaceId:string;projectId:string;kind:string;proofClass:string;planDigest:string;outputNames:string[];requestedBy:string;inputArtifactIds:string[]}):Promise<Run>{
    const inserted=await this.client.query("INSERT INTO runs(id,workspace_id,project_id,kind,proof_class,plan_digest,output_names,requested_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[input.id,input.workspaceId,input.projectId,input.kind,input.proofClass,input.planDigest,input.outputNames,input.requestedBy]);
    if(input.inputArtifactIds.length){const linked=await this.client.query(`INSERT INTO run_input_artifacts(run_id,workspace_id,project_id,artifact_id,ordinal) SELECT $1,$2,$3,v.artifact_id,v.ordinal FROM unnest($4::uuid[]) WITH ORDINALITY AS v(artifact_id,ordinal) JOIN artifacts a ON a.id=v.artifact_id AND a.workspace_id=$2 AND a.project_id=$3 AND a.status='ready' RETURNING artifact_id`,[input.id,input.workspaceId,input.projectId,input.inputArtifactIds]);if(linked.rowCount!==input.inputArtifactIds.length)throw new RunInputArtifactError();}
    await this.insertEvent(input.id,input.workspaceId,input.projectId,"run.queued",{});return runRow(inserted.rows[0]!,input.inputArtifactIds,null);
  }
  async getRun(workspaceId:string,projectId:string,runId:string,lock=false):Promise<Run|undefined>{if(lock){const locked=await this.client.query("SELECT id FROM runs WHERE workspace_id=$1 AND project_id=$2 AND id=$3 FOR UPDATE",[workspaceId,projectId,runId]);if(!locked.rows[0])return undefined;}const result=await this.client.query(runSelect+" WHERE r.workspace_id=$1 AND r.project_id=$2 AND r.id=$3 GROUP BY r.id,rr.receipt",[workspaceId,projectId,runId]);return result.rows[0]?runRow(result.rows[0]):undefined;}
  async listRuns(workspaceId:string,projectId:string,status:RunStatus|"all",cursor=""){const result=await this.client.query(runSelect+" WHERE r.workspace_id=$1 AND r.project_id=$2 AND ($3='all' OR r.status=$3) AND ($4='' OR r.id::text>$4) GROUP BY r.id,rr.receipt ORDER BY r.id LIMIT 101",[workspaceId,projectId,status,cursor]);const items=result.rows.slice(0,100).map(row=>runRow(row));return{items,nextCursor:result.rows.length>100?items.at(-1)?.id??null:null};}
  async getRunMessage(workspaceId:string,projectId:string,runId:string,messageId:string){const result=await this.client.query("SELECT * FROM run_messages WHERE workspace_id=$1 AND project_id=$2 AND run_id=$3 AND id=$4",[workspaceId,projectId,runId,messageId]);return result.rows[0]?messageRow(result.rows[0]):undefined;}
  async listRunMessages(workspaceId:string,projectId:string,runId:string,cursor=""){const after=cursor===""?0:Number(cursor);const result=await this.client.query("SELECT * FROM run_messages WHERE workspace_id=$1 AND project_id=$2 AND run_id=$3 AND ordinal>$4 ORDER BY ordinal LIMIT 101",[workspaceId,projectId,runId,after]);const items=result.rows.slice(0,100).map(messageRow);return{items,nextCursor:result.rows.length>100?String(items.at(-1)?.ordinal??""):null};}
  async hasUndeliveredRunMessages(runId:string){const result=await this.client.query<{pending:boolean}>("SELECT EXISTS(SELECT 1 FROM run_messages WHERE run_id=$1 AND status<>'delivered') AS pending",[runId]);return result.rows[0]?.pending===true;}
  async insertRunMessage(input:{id:string;workspaceId:string;projectId:string;runId:string;kind:RunMessageKind;parentMessageId?:string;content:string;contentDigest:string;createdBy:string}){const inserted=await this.client.query(`INSERT INTO run_messages(id,workspace_id,project_id,run_id,ordinal,role,kind,status,parent_message_id,content,content_digest,created_by)
      SELECT $1,$2,$3,$4,coalesce(max(ordinal)+1,1),'user',$5,'queued',$6,$7,$8,$9 FROM run_messages WHERE run_id=$4 RETURNING *`,[input.id,input.workspaceId,input.projectId,input.runId,input.kind,input.parentMessageId??null,input.content,input.contentDigest,input.createdBy]);const message=messageRow(inserted.rows[0]!);await this.insertEvent(input.runId,input.workspaceId,input.projectId,"message.queued",{messageId:message.id,ordinal:message.ordinal,kind:message.kind,contentDigest:message.contentDigest,parentMessageId:message.parentMessageId??null});return message;}
  async claimRunMessage(run:Run,claimedBy:string,claimId:string,leaseSeconds:number){await this.client.query("UPDATE run_messages SET status='queued',claimed_by=NULL,claim_id=NULL,lease_expires_at=NULL WHERE run_id=$1 AND status='claimed' AND lease_expires_at<=clock_timestamp()",[run.id]);const claimed=await this.client.query(`WITH candidate AS (SELECT id FROM run_messages WHERE run_id=$1 AND status='queued' ORDER BY CASE kind WHEN 'prompt' THEN 0 WHEN 'steer' THEN 1 ELSE 2 END,ordinal FOR UPDATE SKIP LOCKED LIMIT 1)
      UPDATE run_messages m SET status='claimed',claimed_by=$2,claim_id=$3,lease_expires_at=clock_timestamp()+($4*interval '1 second') FROM candidate WHERE m.id=candidate.id RETURNING m.*`,[run.id,claimedBy,claimId,leaseSeconds]);if(!claimed.rows[0])return undefined;const message=messageRow(claimed.rows[0]),leaseExpiresAt=timestamp(claimed.rows[0].lease_expires_at);await this.insertEvent(run.id,run.workspaceId,run.projectId,"message.claimed",{messageId:message.id,ordinal:message.ordinal,kind:message.kind,leaseExpiresAt});return{message,claimId,leaseExpiresAt};}
  async renewRunMessageClaim(run:Run,messageId:string,claimedBy:string,claimId:string,leaseSeconds:number){const renewed=await this.client.query("UPDATE run_messages SET lease_expires_at=clock_timestamp()+($5*interval '1 second') WHERE run_id=$1 AND id=$2 AND status='claimed' AND claimed_by=$3 AND claim_id=$4 RETURNING *",[run.id,messageId,claimedBy,claimId,leaseSeconds]);if(!renewed.rows[0])return undefined;const message=messageRow(renewed.rows[0]),leaseExpiresAt=timestamp(renewed.rows[0].lease_expires_at);await this.insertEvent(run.id,run.workspaceId,run.projectId,"message.claim_renewed",{messageId:message.id,ordinal:message.ordinal,kind:message.kind,leaseExpiresAt});return{message,claimId,leaseExpiresAt};}
  async deliverRunMessage(run:Run,messageId:string,claimedBy:string,claimId:string){const delivered=await this.client.query("UPDATE run_messages SET status='delivered',lease_expires_at=NULL,delivered_at=clock_timestamp() WHERE run_id=$1 AND id=$2 AND status='claimed' AND claimed_by=$3 AND claim_id=$4 AND lease_expires_at>clock_timestamp() RETURNING *",[run.id,messageId,claimedBy,claimId]);if(!delivered.rows[0])return undefined;const message=messageRow(delivered.rows[0]);await this.insertEvent(run.id,run.workspaceId,run.projectId,"message.delivered",{messageId:message.id,ordinal:message.ordinal,kind:message.kind});return message;}
  async cancelRun(run:Run):Promise<Run|undefined>{
    const receipt:RunReceipt={schemaVersion:"blazn.run/receipt/v1alpha1",proofClass:run.proofClass,outcome:"cancelled",planDigest:run.planDigest,artifactIds:[],summary:{steps:0,warnings:[]}};
    await this.client.query("INSERT INTO run_receipts(run_id,workspace_id,project_id,proof_class,outcome,plan_digest,receipt) VALUES($1,$2,$3,$4,'cancelled',$5,$6)",[run.id,run.workspaceId,run.projectId,run.proofClass,run.planDigest,receipt]);
    const result=await this.client.query("UPDATE runs SET status='cancelled',version=version+1,completed_at=clock_timestamp(),error_code=NULL WHERE id=$1 AND workspace_id=$2 AND project_id=$3 AND version=$4 AND status IN ('queued','running') RETURNING *",[run.id,run.workspaceId,run.projectId,run.version]);if(!result.rows[0])return undefined;
    await this.insertEvent(run.id,run.workspaceId,run.projectId,"run.cancelled",{expectedVersion:run.version});return runRow(result.rows[0],run.inputArtifactIds,receipt);
  }
  async recordSyntheticProgress(run:Run,input:SyntheticRunProgressInput,requestDigest:string):Promise<SyntheticRunProgressAck>{
    const existing=await this.client.query("SELECT request_digest FROM run_synthetic_progress WHERE run_id=$1 AND sequence=$2",[run.id,input.sequence]);if(existing.rows[0])throw new RunProgressSequenceError();
    const prior=await this.client.query<{sequence:string}>("SELECT sequence FROM run_synthetic_progress WHERE run_id=$1 ORDER BY sequence DESC LIMIT 1",[run.id]);const expected=prior.rows[0]?Number(prior.rows[0].sequence)+1:0;if(input.sequence!==expected)throw new RunProgressSequenceError();
    let version=run.version;if(run.status==="queued"){const updated=await this.client.query("UPDATE runs SET status='running',version=version+1,started_at=clock_timestamp() WHERE id=$1 AND workspace_id=$2 AND project_id=$3 AND version=$4 AND status='queued' RETURNING version",[run.id,run.workspaceId,run.projectId,run.version]);if(!updated.rows[0])throw new RunProgressSequenceError();version=Number(updated.rows[0].version);}
    await this.client.query("INSERT INTO run_synthetic_progress(run_id,workspace_id,project_id,sequence,request_digest,phase,percent) VALUES($1,$2,$3,$4,$5,$6,$7)",[run.id,run.workspaceId,run.projectId,input.sequence,requestDigest,input.phase,input.percent]);await this.insertEvent(run.id,run.workspaceId,run.projectId,"run.progress",{sourceSequence:input.sequence,phase:input.phase,percent:input.percent});return{runId:run.id,sequence:input.sequence,runVersion:version,status:"running"};
  }
  async createSyntheticArtifact(run:Run,id:string,metadata:SyntheticArtifactUploadMetadata,content:Buffer,createdBy:string):Promise<Artifact>{
    try{const inserted=await this.client.query("INSERT INTO artifacts(id,workspace_id,project_id,source_run_id,kind,media_type,name,status,digest,size_bytes,object_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,'ready',$8,$9,$10,$11) RETURNING *",[id,run.workspaceId,run.projectId,run.id,metadata.kind,metadata.mediaType,metadata.name,metadata.digest,metadata.sizeBytes,`synthetic-db/${id}`,createdBy]);await this.client.query("INSERT INTO synthetic_artifact_blobs(artifact_id,content) VALUES($1,$2)",[id,content]);await this.insertEvent(run.id,run.workspaceId,run.projectId,"artifact.ready",{artifactId:id,name:metadata.name,digest:metadata.digest,sizeBytes:metadata.sizeBytes});return artifactRow(inserted.rows[0]);}catch(error){if(error&&typeof error==="object"&&"code" in error&&error.code==="23505")throw new RunArtifactNameConflictError();throw error;}
  }
  async completeSyntheticRun(run:Run,input:CompleteSyntheticRunInput):Promise<Run|undefined>{
    const artifacts=input.artifactIds.length?await this.client.query<{id:string;name:string}>("SELECT id,name FROM artifacts WHERE workspace_id=$1 AND project_id=$2 AND source_run_id=$3 AND status='ready' AND id=ANY($4::uuid[]) ORDER BY name,id",[run.workspaceId,run.projectId,run.id,input.artifactIds]):{rows:[]};if(artifacts.rows.length!==input.artifactIds.length)throw new RunArtifactSetError();const actualNames=artifacts.rows.map(row=>row.name).sort(),expectedNames=[...run.outputNames].sort();if(actualNames.length!==expectedNames.length||actualNames.some((name,index)=>name!==expectedNames[index]))throw new RunArtifactSetError();
    const receipt:RunReceipt={schemaVersion:"blazn.run/receipt/v1alpha1",proofClass:"synthetic",outcome:"succeeded",planDigest:run.planDigest,artifactIds:[...input.artifactIds],summary:{steps:input.summary.steps,warnings:[...input.summary.warnings]}};await this.client.query("INSERT INTO run_receipts(run_id,workspace_id,project_id,proof_class,outcome,plan_digest,receipt) VALUES($1,$2,$3,'synthetic','succeeded',$4,$5)",[run.id,run.workspaceId,run.projectId,run.planDigest,receipt]);const result=await this.client.query("UPDATE runs SET status='succeeded',version=version+1,completed_at=clock_timestamp(),error_code=NULL WHERE id=$1 AND workspace_id=$2 AND project_id=$3 AND version=$4 AND status='running' RETURNING *",[run.id,run.workspaceId,run.projectId,run.version]);if(!result.rows[0])return undefined;await this.insertEvent(run.id,run.workspaceId,run.projectId,"run.succeeded",{artifactIds:input.artifactIds,steps:input.summary.steps});return runRow(result.rows[0],run.inputArtifactIds,receipt);
  }
  async getArtifact(workspaceId:string,projectId:string,artifactId:string){const result=await this.client.query("SELECT * FROM artifacts WHERE workspace_id=$1 AND project_id=$2 AND id=$3",[workspaceId,projectId,artifactId]);return result.rows[0]?artifactRow(result.rows[0]):undefined;}
  async listArtifacts(workspaceId:string,projectId:string,status:ArtifactStatus|"all",cursor=""){const result=await this.client.query("SELECT * FROM artifacts WHERE workspace_id=$1 AND project_id=$2 AND ($3='all' OR status=$3) AND ($4='' OR id::text>$4) ORDER BY id LIMIT 101",[workspaceId,projectId,status,cursor]);const items=result.rows.slice(0,100).map(artifactRow);return{items,nextCursor:result.rows.length>100?items.at(-1)?.id??null:null};}
  async insertAudit(id:string,workspaceId:string,actorUserId:string,type:string,payload:unknown){await this.client.query("INSERT INTO workspace_audit_events(id,workspace_id,actor_user_id,event_type,payload) VALUES($1,$2,$3,$4,$5)",[id,workspaceId,actorUserId,type,payload]);}
  private async insertEvent(runId:string,workspaceId:string,projectId:string,type:string,payload:unknown){await this.client.query("INSERT INTO run_events(run_id,workspace_id,project_id,sequence,type,payload) SELECT $1,$2,$3,coalesce(max(sequence)+1,0),$4,$5 FROM run_events WHERE run_id=$1",[runId,workspaceId,projectId,type,payload]);}
}

export class RunInputArtifactError extends Error {}
export class RunProgressSequenceError extends Error {}
export class RunArtifactNameConflictError extends Error {}
export class RunArtifactSetError extends Error {}
const runSelect=`SELECT r.*,rr.receipt,coalesce(array_agg(ri.artifact_id ORDER BY ri.ordinal) FILTER (WHERE ri.artifact_id IS NOT NULL),'{}'::uuid[]) AS input_artifact_ids FROM runs r LEFT JOIN run_receipts rr ON rr.run_id=r.id LEFT JOIN run_input_artifacts ri ON ri.run_id=r.id`;
function runRow(row:QueryResultRow,inputIds?:string[],receipt?:RunReceipt|null):Run{const placement:Record<string,string>={};if(row.node_id)placement.nodeId=row.node_id;if(row.sandbox_id)placement.sandboxId=row.sandbox_id;if(row.model_route_id)placement.modelRouteId=row.model_route_id;const value:Run={id:row.id,workspaceId:row.workspace_id,projectId:row.project_id,kind:row.kind,proofClass:row.proof_class,status:row.status,version:Number(row.version),planDigest:row.plan_digest,inputArtifactIds:inputIds??row.input_artifact_ids??[],outputNames:row.output_names,requestedBy:row.requested_by,placement:Object.keys(placement).length?placement:null,receipt:receipt===undefined?(row.receipt??null):receipt,createdAt:timestamp(row.created_at)};if(row.started_at)value.startedAt=timestamp(row.started_at);if(row.completed_at)value.completedAt=timestamp(row.completed_at);if(row.error_code)value.errorCode=row.error_code;return value;}
function artifactRow(row:QueryResultRow):Artifact{const value:Artifact={id:row.id,workspaceId:row.workspace_id,projectId:row.project_id,kind:row.kind,mediaType:row.media_type,name:row.name,status:row.status,version:Number(row.version),createdBy:row.created_by,createdAt:timestamp(row.created_at),updatedAt:timestamp(row.updated_at),downloadAvailable:row.status==="ready"};if(row.source_run_id)value.sourceRunId=row.source_run_id;if(row.digest)value.digest=row.digest;if(row.size_bytes!==null&&row.size_bytes!==undefined)value.sizeBytes=Number(row.size_bytes);return value;}
function messageRow(row:QueryResultRow):RunMessage{const value:RunMessage={id:row.id,workspaceId:row.workspace_id,projectId:row.project_id,runId:row.run_id,ordinal:Number(row.ordinal),role:row.role,kind:row.kind,status:row.status,content:row.content,contentDigest:row.content_digest,createdBy:row.created_by,createdAt:timestamp(row.created_at)};if(row.parent_message_id)value.parentMessageId=row.parent_message_id;return value;}
function timestamp(value:Date|string):string{return value instanceof Date?value.toISOString():new Date(value).toISOString();}
