import { createHash, randomUUID } from "node:crypto";
import { requestDigest } from "./workspace-crypto.js";
import type { IdempotencyReceipt } from "./workspace-store.js";
import { roleAllows } from "./workspace-types.js";
import { RunArtifactNameConflictError, RunArtifactSetError, RunInputArtifactError, RunProgressSequenceError, type RunStore, type RunTransaction } from "./run-store.js";
import { RunHttpError, type Artifact, type ArtifactStatus, type ClaimRunMessageInput, type CompleteSyntheticRunInput, type ProofClass, type RunMessageClaim, type RunMessageKind, type RunPrincipal, type RunStatus, type SendRunMessageInput, type SyntheticArtifactUploadMetadata, type SyntheticRunProgressInput } from "./run-types.js";

export interface CreateRunInput { kind:string;proofClass:ProofClass;planDigest:string;inputArtifactIds:string[];outputNames:string[] }

export class RunService {
  constructor(private readonly store:RunStore){}
  async createRun(principal:RunPrincipal,workspaceId:string,projectId:string,key:string,input:CreateRunInput){
    const normalized=validateCreate(input);const digest=requestDigest({workspaceId,projectId,...normalized});
    return this.idempotent(principal,workspaceId,projectId,"run.create",key,`project:${projectId}`,digest,"operate",async tx=>{
      try{const run=await tx.createRun({id:randomUUID(),workspaceId,projectId,...normalized,requestedBy:principal.userId});await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"run.created",{projectId,runId:run.id,kind:run.kind,proofClass:run.proofClass,planDigest:run.planDigest});return{run};}
      catch(error){if(error instanceof RunInputArtifactError)throw new RunHttpError("artifact_not_found","one or more input Artifacts were unavailable");throw error;}
    },202);
  }
  async listRuns(principal:RunPrincipal,workspaceId:string,projectId:string,status:RunStatus|"all"="all",cursor=""){validRunStatus(status);validCursor(cursor);return this.store.transaction(async tx=>{await this.authorize(tx,principal,workspaceId,projectId,"read",true);return tx.listRuns(workspaceId,projectId,status,cursor);});}
  async getRun(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string){return this.store.transaction(async tx=>{await this.authorize(tx,principal,workspaceId,projectId,"read",true);const run=await tx.getRun(workspaceId,projectId,runId);if(!run)throw new RunHttpError("run_not_found","Run was not found");return{run};});}
  async cancelRun(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,key:string,expectedVersion:number){
    positive(expectedVersion);const digest=requestDigest({workspaceId,projectId,runId,expectedVersion});return this.idempotent(principal,workspaceId,projectId,"run.cancel",key,`run:${runId}`,digest,"operate",async tx=>{
      const current=await tx.getRun(workspaceId,projectId,runId,true);if(!current)throw new RunHttpError("run_not_found","Run was not found");if(current.version!==expectedVersion)throw new RunHttpError("version_conflict","Run version changed");if(["succeeded","failed","cancelled"].includes(current.status))throw new RunHttpError("run_terminal","Run is already terminal");
      const run=await tx.cancelRun(current);if(!run)throw new RunHttpError("version_conflict","Run version changed");await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"run.cancelled",{projectId,runId,expectedVersion,proofClass:run.proofClass});return{run};
    },200);
  }
  async listRunMessages(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,cursor=""){
    if(cursor!==""&&(!/^[1-9][0-9]*$/.test(cursor)||!Number.isSafeInteger(Number(cursor))))invalid("message cursor is invalid");return this.store.transaction(async tx=>{await this.authorize(tx,principal,workspaceId,projectId,"read",false);if(!await tx.getRun(workspaceId,projectId,runId))throw new RunHttpError("run_not_found","Run was not found");return tx.listRunMessages(workspaceId,projectId,runId,cursor);});
  }
  async sendRunMessage(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,key:string,input:SendRunMessageInput){
    const normalized=validateMessage(input),digest=requestDigest({workspaceId,projectId,runId,...normalized});return this.idempotent(principal,workspaceId,projectId,"run.message.send",key,`run:${runId}:messages`,digest,"operate",async tx=>{
      const run=await tx.getRun(workspaceId,projectId,runId,true);if(!run)throw new RunHttpError("run_not_found","Run was not found");if(["succeeded","failed","cancelled"].includes(run.status))throw new RunHttpError("run_terminal","Run is already terminal");const existing=await tx.listRunMessages(workspaceId,projectId,runId,"");
      if(normalized.kind==="prompt"&&(run.status!=="queued"||existing.items.length!==0))throw new RunHttpError("message_conflict","initial prompt requires a queued Run with no messages");if(normalized.kind!=="prompt"&&existing.items.length===0)throw new RunHttpError("message_conflict","follow-up or steering requires an initial prompt");if(normalized.kind==="steer"&&run.status!=="running")throw new RunHttpError("message_conflict","steering requires a running Run");if(normalized.parentMessageId&&!await tx.getRunMessage(workspaceId,projectId,runId,normalized.parentMessageId))throw new RunHttpError("message_parent_not_found","parent message was not found in this Run");
      const contentDigest=`sha256:${createHash("sha256").update(normalized.content).digest("hex")}`,message=await tx.insertRunMessage({id:randomUUID(),workspaceId,projectId,runId,...normalized,contentDigest,createdBy:principal.userId});await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"run.message_queued",{projectId,runId,messageId:message.id,ordinal:message.ordinal,kind:message.kind,contentDigest,parentMessageId:message.parentMessageId??null});return{message};
    },201);
  }
  async claimRunMessage(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,key:string,input:ClaimRunMessageInput){const leaseSeconds=input.leaseSeconds;if(!Number.isSafeInteger(leaseSeconds)||leaseSeconds<5||leaseSeconds>300)invalid("message leaseSeconds is invalid");validKey(key);const operation="run.message.claim",targetKey=`run:${runId}:message-claim`,digest=requestDigest({workspaceId,projectId,runId,leaseSeconds});return this.store.transaction(async tx=>{await tx.lockIdempotency(principal.userId,operation,key);const receipt=await tx.getIdempotency(principal.userId,operation,key);if(receipt)verifyReceipt(receipt,workspaceId,targetKey,digest);await this.authorize(tx,principal,workspaceId,projectId,"operate",true);const run=await tx.getRun(workspaceId,projectId,runId,true);if(!run)throw new RunHttpError("run_not_found","Run was not found");if(run.requestedBy!==principal.userId)throw new RunHttpError("permission_denied","only the Run requester can claim its messages");if(run.status!=="queued"&&run.status!=="running")throw new RunHttpError("message_conflict","messages can be claimed only while the Run is active");if(receipt){const replay=receipt.responseBody as {claim:RunMessageClaim|null};if(replay.claim===null)return replay;const renewed=await tx.renewRunMessageClaim(run,replay.claim.message.id,principal.userId,replay.claim.claimId,leaseSeconds);if(!renewed)throw new RunHttpError("message_conflict","replayed message claim is no longer active");await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"run.message_claim_renewed",{projectId,runId,messageId:renewed.message.id,ordinal:renewed.message.ordinal,kind:renewed.message.kind,leaseExpiresAt:renewed.leaseExpiresAt});return{claim:renewed};}const claim=await tx.claimRunMessage(run,principal.userId,randomUUID(),leaseSeconds);if(claim)await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"run.message_claimed",{projectId,runId,messageId:claim.message.id,ordinal:claim.message.ordinal,kind:claim.message.kind,leaseExpiresAt:claim.leaseExpiresAt});const response={claim:claim??null};await tx.putIdempotency(principal.userId,operation,key,{workspaceId,targetKey,requestDigest:digest,responseStatus:200,responseBody:response});return response;});}
  async deliverRunMessage(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,messageId:string,key:string,claimId:string){if(!uuid(messageId)||!uuid(claimId))invalid("messageId and claimId must be UUIDs");const digest=requestDigest({workspaceId,projectId,runId,messageId,claimId});return this.idempotent(principal,workspaceId,projectId,"run.message.deliver",key,`run:${runId}:message:${messageId}`,digest,"operate",async tx=>{const run=await tx.getRun(workspaceId,projectId,runId,true);if(!run)throw new RunHttpError("run_not_found","Run was not found");if(run.requestedBy!==principal.userId)throw new RunHttpError("permission_denied","only the Run requester can deliver its messages");if(run.status!=="queued"&&run.status!=="running")throw new RunHttpError("message_conflict","messages can be delivered only while the Run is active");const message=await tx.deliverRunMessage(run,messageId,principal.userId,claimId);if(!message)throw new RunHttpError("message_conflict","message claim is missing, expired, or owned by another executor");await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"run.message_delivered",{projectId,runId,messageId:message.id,ordinal:message.ordinal,kind:message.kind});return{message};},200);}
  async listArtifacts(principal:RunPrincipal,workspaceId:string,projectId:string,status:ArtifactStatus|"all"="ready",cursor=""){validArtifactStatus(status);validCursor(cursor);return this.store.transaction(async tx=>{await this.authorize(tx,principal,workspaceId,projectId,"read",true);return tx.listArtifacts(workspaceId,projectId,status,cursor);});}
  async getArtifact(principal:RunPrincipal,workspaceId:string,projectId:string,artifactId:string){return this.store.transaction(async tx=>{await this.authorize(tx,principal,workspaceId,projectId,"read",true);const artifact=await tx.getArtifact(workspaceId,projectId,artifactId);if(!artifact)throw new RunHttpError("artifact_not_found","Artifact was not found");return{artifact};});}
  async recordSyntheticProgress(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,key:string,input:SyntheticRunProgressInput){const normalized=validateProgress(input),digest=requestDigest({workspaceId,projectId,runId,...normalized});return this.idempotent(principal,workspaceId,projectId,"run.synthetic.progress",key,`run:${runId}:progress:${normalized.sequence}`,digest,"operate",async tx=>{const current=await this.syntheticRun(tx,principal,workspaceId,projectId,runId);if(current.status!=="queued"&&current.status!=="running")throw new RunHttpError("run_terminal","Run is already terminal");try{const ack=await tx.recordSyntheticProgress(current,normalized,digest);await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"run.synthetic_progress",{projectId,runId,sequence:normalized.sequence,phase:normalized.phase,percent:normalized.percent});return ack;}catch(error){if(error instanceof RunProgressSequenceError)throw new RunHttpError("run_sequence_conflict","Run progress sequence is not the next monotonic value");throw error;}},200);}
  async preflightSyntheticUpload(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,key:string,metadata:SyntheticArtifactUploadMetadata):Promise<{artifact:Artifact}|undefined>{validKey(key);const normalized=validateUploadMetadata(metadata),digest=requestDigest({workspaceId,projectId,runId,...normalized});return this.store.transaction(async tx=>{await this.authorize(tx,principal,workspaceId,projectId,"operate",true);await tx.lockIdempotency(principal.userId,"artifact.synthetic.upload",key);const receipt=await tx.getIdempotency(principal.userId,"artifact.synthetic.upload",key);if(receipt){verifyReceipt(receipt,workspaceId,`run:${runId}:artifact:${normalized.name}`,digest);return receipt.responseBody as {artifact:Artifact};}const current=await this.syntheticRun(tx,principal,workspaceId,projectId,runId);if(current.status!=="running")throw new RunHttpError("run_terminal","Run is not accepting Artifacts");if(!current.outputNames.includes(normalized.name))throw new RunHttpError("artifact_name_conflict","Artifact name is not a declared Run output");return undefined;});}
  async uploadSyntheticArtifact(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,key:string,metadata:SyntheticArtifactUploadMetadata,content:Buffer){const normalized=validateUpload(metadata,content),digest=requestDigest({workspaceId,projectId,runId,...normalized});return this.idempotent(principal,workspaceId,projectId,"artifact.synthetic.upload",key,`run:${runId}:artifact:${normalized.name}`,digest,"operate",async tx=>{const current=await this.syntheticRun(tx,principal,workspaceId,projectId,runId);if(current.status!=="running")throw new RunHttpError("run_terminal","Run is not accepting Artifacts");if(!current.outputNames.includes(normalized.name))throw new RunHttpError("artifact_name_conflict","Artifact name is not a declared Run output");try{const artifact=await tx.createSyntheticArtifact(current,randomUUID(),normalized,content,principal.userId);await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"artifact.synthetic_uploaded",{projectId,runId,artifactId:artifact.id,name:artifact.name,digest:artifact.digest,sizeBytes:artifact.sizeBytes});return{artifact};}catch(error){if(error instanceof RunArtifactNameConflictError)throw new RunHttpError("artifact_name_conflict","Artifact name is already active for this Run");throw error;}},201);}
  async completeSyntheticRun(principal:RunPrincipal,workspaceId:string,projectId:string,runId:string,key:string,input:CompleteSyntheticRunInput){const normalized=validateCompletion(input),digest=requestDigest({workspaceId,projectId,runId,...normalized});return this.idempotent(principal,workspaceId,projectId,"run.synthetic.complete",key,`run:${runId}`,digest,"operate",async tx=>{const current=await this.syntheticRun(tx,principal,workspaceId,projectId,runId);if(current.version!==normalized.expectedVersion)throw new RunHttpError("version_conflict","Run version changed");if(current.status!=="running")throw new RunHttpError("run_terminal","Run is not running");if(current.planDigest!==normalized.planDigest)throw new RunHttpError("invalid_request","planDigest does not match the Run");if(await tx.hasUndeliveredRunMessages(runId))throw new RunHttpError("message_conflict","Run has accepted messages that have not been delivered");try{const run=await tx.completeSyntheticRun(current,normalized);if(!run)throw new RunHttpError("version_conflict","Run version changed");await tx.insertAudit(randomUUID(),workspaceId,principal.userId,"run.synthetic_completed",{projectId,runId,artifactIds:normalized.artifactIds,planDigest:normalized.planDigest});return{run};}catch(error){if(error instanceof RunArtifactSetError)throw new RunHttpError("artifact_not_found","one or more completion Artifacts were unavailable");throw error;}},200);}

  private async syntheticRun(tx:RunTransaction,principal:RunPrincipal,workspaceId:string,projectId:string,runId:string){const current=await tx.getRun(workspaceId,projectId,runId,true);if(!current)throw new RunHttpError("run_not_found","Run was not found");if(current.requestedBy!==principal.userId||current.proofClass!=="synthetic")throw new RunHttpError("permission_denied","synthetic Run execution is not permitted");return current;}

  private async authorize(tx:RunTransaction,principal:RunPrincipal,workspaceId:string,projectId:string,capability:"read"|"operate",lock:boolean){const access=await tx.getAccess(workspaceId,projectId,principal.userId,lock);if(!access||access.workspaceStatus!=="active")throw new RunHttpError("workspace_not_found","Workspace was not found");if(!access.projectStatus)throw new RunHttpError("project_not_found","Project was not found");if(access.projectStatus!=="active"&&capability==="operate")throw new RunHttpError("project_not_found","Project was not found");if(!roleAllows(access.role,capability))throw new RunHttpError("permission_denied","Run action is not permitted");}
  private async idempotent<T>(principal:RunPrincipal,workspaceId:string,projectId:string,operation:string,key:string,targetKey:string,digest:string,capability:"read"|"operate",execute:(tx:RunTransaction)=>Promise<T>,status:number):Promise<T>{validKey(key);return this.store.transaction(async tx=>{await tx.lockIdempotency(principal.userId,operation,key);const receipt=await tx.getIdempotency(principal.userId,operation,key);if(receipt){verifyReceipt(receipt,workspaceId,targetKey,digest);await this.authorize(tx,principal,workspaceId,projectId,capability,true);return receipt.responseBody as T;}await this.authorize(tx,principal,workspaceId,projectId,capability,true);const response=await execute(tx);await tx.putIdempotency(principal.userId,operation,key,{workspaceId,targetKey,requestDigest:digest,responseStatus:status,responseBody:response});return response;});}
}

const maxSyntheticArtifactBytes=16*1024*1024;
function validateProgress(input:SyntheticRunProgressInput):SyntheticRunProgressInput{if(!Number.isSafeInteger(input.sequence)||input.sequence<0||!/^[a-z][a-z0-9._-]{0,95}$/.test(input.phase)||!Number.isSafeInteger(input.percent)||input.percent<0||input.percent>100||(input.message!==undefined&&(typeof input.message!=="string"||input.message.length>512)))invalid("synthetic progress is invalid");const value:SyntheticRunProgressInput={sequence:input.sequence,phase:input.phase,percent:input.percent};if(input.message!==undefined)value.message=input.message;return value;}
function validateMessage(input:SendRunMessageInput):SendRunMessageInput{if(!input||typeof input!=="object"||!["prompt","followup","steer"].includes(input.kind as RunMessageKind)||typeof input.content!=="string"||input.content.trim().length===0||Array.from(input.content).length>16384||input.content.includes("\u0000")||(input.parentMessageId!==undefined&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(input.parentMessageId)))invalid("Run message is invalid");const value:SendRunMessageInput={kind:input.kind,content:input.content};if(input.parentMessageId)value.parentMessageId=input.parentMessageId;return value;}
function validateCompletion(input:CompleteSyntheticRunInput):CompleteSyntheticRunInput{positive(input.expectedVersion);if(!/^sha256:[0-9a-f]{64}$/.test(input.planDigest)||!Array.isArray(input.artifactIds)||input.artifactIds.length>1000||input.artifactIds.some(id=>!uuid(id))||new Set(input.artifactIds).size!==input.artifactIds.length||!input.summary||!Number.isSafeInteger(input.summary.steps)||input.summary.steps<0||!Array.isArray(input.summary.warnings)||input.summary.warnings.length>100||input.summary.warnings.some(value=>typeof value!=="string"||value.length>512))invalid("synthetic completion is invalid");return{expectedVersion:input.expectedVersion,planDigest:input.planDigest,artifactIds:[...input.artifactIds],summary:{steps:input.summary.steps,warnings:[...input.summary.warnings]}};}
function validateUploadMetadata(metadata:SyntheticArtifactUploadMetadata):SyntheticArtifactUploadMetadata{if(!metadata||typeof metadata.name!=="string"||metadata.name.length<1||metadata.name.length>256||!validArtifactName(metadata.name)||!/^[a-z][a-z0-9.-]{0,95}$/.test(metadata.kind)||!["image","video","audio","document","data","other"].includes(metadata.mediaType)||!Number.isSafeInteger(metadata.sizeBytes)||metadata.sizeBytes<0||metadata.sizeBytes>1073741824||!/^sha256:[0-9a-f]{64}$/.test(metadata.digest))invalid("synthetic Artifact metadata is invalid");if(metadata.sizeBytes>maxSyntheticArtifactBytes)throw new RunHttpError("upload_too_large",`synthetic Artifact upload exceeds ${maxSyntheticArtifactBytes} bytes`);return{name:metadata.name,kind:metadata.kind,mediaType:metadata.mediaType,sizeBytes:metadata.sizeBytes,digest:metadata.digest};}
function validateUpload(metadata:SyntheticArtifactUploadMetadata,content:Buffer):SyntheticArtifactUploadMetadata{const normalized=validateUploadMetadata(metadata);if(content.length!==normalized.sizeBytes)throw new RunHttpError("artifact_size_mismatch","Artifact byte count does not match metadata");const actual=`sha256:${createHash("sha256").update(content).digest("hex")}`;if(actual!==normalized.digest)throw new RunHttpError("artifact_digest_mismatch","Artifact digest does not match metadata");return normalized;}
function validArtifactName(value:string){return !/[\u0000-\u001f\u007f]/.test(value)&&value!=="."&&value!=="..";}

function validateCreate(input:CreateRunInput):CreateRunInput{if(!/^[a-z][a-z0-9.-]{0,95}$/.test(input.kind))invalid("Run kind is invalid");if(!["synthetic","local","sandbox","provider"].includes(input.proofClass))invalid("proofClass is invalid");if(!/^sha256:[0-9a-f]{64}$/.test(input.planDigest))invalid("planDigest is invalid");if(!Array.isArray(input.inputArtifactIds)||input.inputArtifactIds.length>1000||input.inputArtifactIds.some(id=>!uuid(id))||new Set(input.inputArtifactIds).size!==input.inputArtifactIds.length)invalid("inputArtifactIds are invalid");if(!Array.isArray(input.outputNames)||input.outputNames.length>1000||input.outputNames.some(name=>!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(name))||new Set(input.outputNames).size!==input.outputNames.length)invalid("outputNames are invalid");return{kind:input.kind,proofClass:input.proofClass,planDigest:input.planDigest,inputArtifactIds:[...input.inputArtifactIds],outputNames:[...input.outputNames]};}
function validRunStatus(value:string){if(!["queued","running","succeeded","failed","cancelled","all"].includes(value))invalid("Run status filter is invalid");}
function validArtifactStatus(value:string){if(!["pending","ready","failed","deleted","all"].includes(value))invalid("Artifact status filter is invalid");}
function validCursor(value:string){if(value.length>512||(value!==""&&!uuid(value)))invalid("cursor is invalid");}
function validKey(value:string){if(typeof value!=="string"||value.length<8||value.length>128)invalid("Idempotency-Key is invalid");}
function positive(value:number){if(!Number.isSafeInteger(value)||value<1)invalid("expectedVersion must be a positive integer");}
function uuid(value:string){return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(value);}
function verifyReceipt(receipt:IdempotencyReceipt,workspaceId:string,targetKey:string,digest:string){if(receipt.workspaceId!==workspaceId||receipt.targetKey!==targetKey||receipt.requestDigest!==digest)throw new RunHttpError("idempotency_conflict","Idempotency key is bound to another request");}
function invalid(message:string):never{throw new RunHttpError("invalid_request",message);}
