import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { SandboxService } from "./sandbox-service.js";
import type { SandboxIdempotencyReceipt,SandboxStore,SandboxTransaction } from "./sandbox-store.js";
import { SandboxHttpError,type SandboxAccessGrant,type SandboxArtifact,type SandboxEvent,type SandboxOperation,type SandboxPrincipal,type SandboxTemplate,type SandboxTemplateManifest,type SandboxView } from "./sandbox-types.js";

const here=path.dirname(fileURLToPath(import.meta.url));
const fixture=async()=>JSON.parse(await readFile(path.resolve(here,"../../../packages/contracts/testdata/sandbox/template-good.json"),"utf8")) as SandboxTemplateManifest;
const owner:SandboxPrincipal={userId:"10000000-0000-4000-8000-000000000001",sessionId:"30000000-0000-4000-8000-000000000001",email:"owner@example.test",displayName:"Owner"};
const member:SandboxPrincipal={userId:"10000000-0000-4000-8000-000000000002",sessionId:"30000000-0000-4000-8000-000000000002",email:"member@example.test",displayName:"Member"};
const workspaceId="40000000-0000-4000-8000-000000000001";

test("template mutations validate, persist no secret, replay idempotently, and redact drafts",async()=>{const memory=new MemoryStore();const service=new SandboxService(memory as unknown as SandboxStore);const manifest=await fixture();const created=await service.createTemplate(owner,workspaceId,"template-key-0001",manifest);const replay=await service.createTemplate(owner,workspaceId,"template-key-0001",manifest);assert.equal(replay.template.id,created.template.id);assert.equal(memory.templateCreates,1);assert.match(created.template.draftDigest!,/^sha256:[0-9a-f]{64}$/);assert.equal(JSON.stringify(memory.receipts).includes("accessToken"),false);
  memory.roles.set(member.userId,"member");memory.templates[0]!.publishedVersionId="50000000-0000-4000-8000-000000000001";const listed=await service.listTemplates(member,workspaceId);assert.equal(listed.items.length,1);assert.equal("draftManifest" in listed.items[0]!,false);assert.equal("draftDigest" in listed.items[0]!,false);
  const bad=structuredClone(manifest) as SandboxTemplateManifest&{spec:Record<string,unknown>};bad.spec.secret={value:"no"};await assert.rejects(service.createTemplate(owner,workspaceId,"template-key-0002",bad),isCode("invalid_request"));
});

test("template validation rejects malformed collections and idempotency conflicts",async()=>{const memory=new MemoryStore(),service=new SandboxService(memory as unknown as SandboxStore),manifest=await fixture();for(const field of ["repositories","artifacts"]){const bad=structuredClone(manifest) as unknown as {spec:Record<string,unknown>};bad.spec[field]=null;await assert.rejects(service.createTemplate(owner,workspaceId,`null-${field}-key`,bad as unknown as SandboxTemplateManifest),isCode("invalid_request"));}for(const field of ["variants","repositories","artifacts"])for(const [label,value] of [["null",null],["number",7]] as const){const bad=structuredClone(manifest) as unknown as {spec:Record<string,unknown>};bad.spec[field]=[value];await assert.rejects(service.createTemplate(owner,workspaceId,`${label}-${field}-item-key`,bad as unknown as SandboxTemplateManifest),isCode("invalid_request"));}await service.createTemplate(owner,workspaceId,"conflict-key-1",manifest);const changed=structuredClone(manifest);changed.spec.description="changed";await assert.rejects(service.createTemplate(owner,workspaceId,"conflict-key-1",changed),isCode("idempotency_conflict"));});

test("template validation rejects nested source mounts and non-443 HTTPS",async()=>{const memory=new MemoryStore(),service=new SandboxService(memory as unknown as SandboxStore);for(const order of ["parent-first","child-first"]){const manifest=await fixture();const parent={name:"parent",url:"https://example.test/parent.git",destination:"/workspace/src/repo",writable:false};const child={name:"child",url:"https://example.test/child.git",destination:"/workspace/src/repo/vendor",writable:false};manifest.spec.repositories=order==="parent-first"?[parent,child]:[child,parent];await assert.rejects(service.createTemplate(owner,workspaceId,`nested-${order}`,manifest),isCode("invalid_request"));}const intervening=await fixture();intervening.spec.repositories=[{name:"parent",url:"https://example.test/parent",destination:"/workspace/src/a",writable:false},{name:"sibling",url:"https://example.test/sibling",destination:"/workspace/src/a-foo",writable:false},{name:"child",url:"https://example.test/child",destination:"/workspace/src/a/x",writable:false}];await assert.rejects(service.createTemplate(owner,workspaceId,"nested-intervening",intervening),isCode("invalid_request"));const port=await fixture();port.spec.repositories![0]!.url="https://example.test:8443/repo.git";await assert.rejects(service.createTemplate(owner,workspaceId,"source-port",port),isCode("invalid_request"));});

test("unpublished template version identity is hidden from non-administrative roles",async()=>{const memory=new MemoryStore(),service=new SandboxService(memory as unknown as SandboxStore),manifest=await fixture();const created=await service.createTemplate(owner,workspaceId,"draft-versions-key",manifest);for(const role of ["operator","member","viewer"]){memory.roles.set(member.userId,role);await assert.rejects(service.listVersions(member,created.template.id),isCode("template_not_found"));}assert.deepEqual((await service.listVersions(owner,created.template.id)).items,[]);});

test("commit validation accepts only exact SHA-1 or SHA-256 widths",async()=>{const memory=new MemoryStore(),service=new SandboxService(memory as unknown as SandboxStore);memory.publishedManifest=await fixture();for(const width of [40,64]){const created=await service.createSandbox(owner,workspaceId,`commit-${width}-key`,{template:{name:"coding-small",version:"v1"},architecture:"amd64",allocationMode:"direct",expiresInSeconds:60,sources:[{repository:"source",commit:"a".repeat(width)}],approvedNonSensitive:true});assert.equal(created.sandbox.sourceBindings[0]?.commit,"a".repeat(width));assert.equal(memory.lastExpiresInSeconds,60);}for(const width of [0,39,41,63,65])await assert.rejects(service.createSandbox(owner,workspaceId,`commit-${width}-key`,{template:{name:"coding-small",version:"v1"},architecture:"amd64",allocationMode:"direct",expiresInSeconds:60,sources:[{repository:"source",commit:"a".repeat(width)}],approvedNonSensitive:true}),isCode("invalid_request"));});

test("sandbox creation delegates integer duration to the database-clock entrypoint",async()=>{const source=await readFile(path.resolve(here,"../src/sandbox-store.ts"),"utf8");assert.match(source,/SELECT sandbox_create_bound_sandbox_for_duration\(\$1,\$2,\$3,\$4,\$5,\$6,\$7,\$8::jsonb,\$9,\$10,\$11\)/);assert.doesNotMatch(source,/SELECT sandbox_create_bound_sandbox\(/);});

test("sandbox access is requester-only with owner override audit and grants are fresh non-idempotent bearer material",async()=>{const memory=new MemoryStore();memory.sandboxValue=sandbox();const service=new SandboxService(memory as unknown as SandboxStore,()=>new Date("2026-08-22T00:00:00Z"));memory.roles.set(member.userId,"operator");await assert.rejects(service.getSandbox(member,memory.sandboxValue.id),isCode("sandbox_not_found"));const own={...memory.sandboxValue,requestedBy:member.userId};memory.sandboxValue=own;const first=await service.createAccessGrant(member,own.id,{kind:"exec",expiresInSeconds:30});const second=await service.createAccessGrant(member,own.id,{kind:"exec",expiresInSeconds:30});assert.notEqual(first.grant.id,second.grant.id);assert.notEqual(first.accessToken,second.accessToken);assert.equal(memory.grants.length,2);assert.equal(JSON.stringify(memory.grants).includes(first.accessToken),false);
  memory.sandboxValue={...own,requestedBy:member.userId};await service.getSandbox(owner,own.id);assert.equal(memory.audits.some(a=>a.override===true),true);
});

test("grant creation rechecks the locked session and preserves the one-second TTL boundary",async()=>{const memory=new MemoryStore();memory.sandboxValue=sandbox();const service=new SandboxService(memory as unknown as SandboxStore);const minimum=await service.createAccessGrant(owner,memory.sandboxValue.id,{kind:"download",expiresInSeconds:1});assert.equal(Date.parse(minimum.grant.expiresAt)-Date.parse(minimum.grant.createdAt),1_000);for(const expiresInSeconds of [0,61])await assert.rejects(service.createAccessGrant(owner,memory.sandboxValue.id,{kind:"download",expiresInSeconds}),isCode("invalid_request"));memory.session={revokedAt:new Date(),accessExpired:false};await assert.rejects(service.createAccessGrant(owner,memory.sandboxValue.id,{kind:"exec",expiresInSeconds:1}),isCode("session_revoked"));memory.session={revokedAt:null,accessExpired:true};await assert.rejects(service.createAccessGrant(owner,memory.sandboxValue.id,{kind:"exec",expiresInSeconds:1}),isCode("access_expired"));assert.equal(memory.grants.length,1);
  const source=await readFile(path.resolve(here,"../src/sandbox-store.ts"),"utf8");assert.match(source,/FROM sessions WHERE id=\$1 AND user_id=\$2 FOR SHARE/);assert.match(source,/access_expires_at<=clock_timestamp\(\)/);assert.match(source,/WITH effective AS \(SELECT clock_timestamp\(\) AS created_at\)/);assert.match(source,/created_at\+\$8\*interval '1 second'/);
});

test("idempotency replay rechecks current role",async()=>{const memory=new MemoryStore();const service=new SandboxService(memory as unknown as SandboxStore);const manifest=await fixture();await service.createTemplate(owner,workspaceId,"template-key-0003",manifest);memory.roles.set(owner.userId,"viewer");await assert.rejects(service.createTemplate(owner,workspaceId,"template-key-0003",manifest),isCode("permission_denied"));});

test("concurrent idempotent replay creates once and role gates mutations",async()=>{const memory=new MemoryStore(),service=new SandboxService(memory as unknown as SandboxStore),manifest=await fixture();const [a,b]=await Promise.all([service.createTemplate(owner,workspaceId,"concurrent-key-1",manifest),service.createTemplate(owner,workspaceId,"concurrent-key-1",manifest)]);assert.equal(a.template.id,b.template.id);assert.equal(memory.templateCreates,1);memory.roles.set(member.userId,"member");await assert.rejects(service.createTemplate(member,workspaceId,"member-create-1",manifest),isCode("permission_denied"));});

test("stop and delete enforce type-specific states and optimistic versions",async()=>{const memory=new MemoryStore();memory.roles.set(member.userId,"operator");memory.sandboxValue={...sandbox(),requestedBy:member.userId};const service=new SandboxService(memory as unknown as SandboxStore);const direct=await service.createOperation(member,memory.sandboxValue.id,"direct-delete-1",{type:"delete",expectedVersion:1});assert.equal(direct.sandbox.state,"deleting");assert.equal(direct.sandbox.version,2);
  memory.sandboxValue={...sandbox(),requestedBy:member.userId};const stopped=await service.createOperation(member,memory.sandboxValue.id,"stop-first-1",{type:"stop",expectedVersion:1});assert.equal(stopped.sandbox.state,"stopping");assert.equal(stopped.sandbox.version,2);memory.sandboxValue={...stopped.sandbox,state:"stopped",desiredState:"stopped",version:3,stoppedAt:"2026-08-22T00:01:00.000Z"};await assert.rejects(service.createOperation(member,memory.sandboxValue.id,"stop-again-1",{type:"stop",expectedVersion:3}),isCode("sandbox_state_conflict"));const deleted=await service.createOperation(member,memory.sandboxValue.id,"delete-stopped-1",{type:"delete",expectedVersion:3});assert.equal(deleted.sandbox.state,"deleting");assert.equal(deleted.sandbox.version,4);
});

test("operation idempotency replays one transition and rejects changed identity",async()=>{const memory=new MemoryStore();memory.roles.set(member.userId,"operator");memory.sandboxValue={...sandbox(),requestedBy:member.userId};const service=new SandboxService(memory as unknown as SandboxStore);const first=await service.createOperation(member,memory.sandboxValue.id,"operation-replay-1",{type:"stop",expectedVersion:1});const replay=await service.createOperation(member,memory.sandboxValue.id,"operation-replay-1",{type:"stop",expectedVersion:1});assert.equal(replay.operation.id,first.operation.id);assert.equal(memory.transitions,1);await assert.rejects(service.createOperation(member,memory.sandboxValue.id,"operation-replay-1",{type:"stop",expectedVersion:2}),isCode("idempotency_conflict"));});

test("pagination cursors and authorized receipt, artifact, and event retrieval stay scoped",async()=>{const memory=new MemoryStore();memory.sandboxValue=sandbox();memory.nextCursor="next-page";const artifact=memory.artifactValue!,operation=memory.operationValue!,event=memory.events[0]!,service=new SandboxService(memory as unknown as SandboxStore),manifest=await fixture();await service.createTemplate(owner,workspaceId,"pagination-template",manifest);assert.equal((await service.listTemplates(owner,workspaceId,"template-cursor")).nextCursor,"next-page");assert.equal(memory.cursors.templates,"template-cursor");assert.equal(memory.includeDrafts,true);await service.listVersions(owner,memory.templates[0]!.id,"version-cursor");assert.equal(memory.cursors.versions,"version-cursor");assert.equal((await service.listSandboxes(owner,workspaceId,"sandbox-cursor")).nextCursor,"next-page");assert.equal(memory.cursors.sandboxes,"sandbox-cursor");await service.listArtifacts(owner,memory.sandboxValue.id,"artifact-cursor");assert.equal(memory.cursors.artifacts,"artifact-cursor");assert.equal((await service.eventBatch(owner,memory.sandboxValue.id,"event-cursor")).at(0)?.eventId,event.eventId);assert.equal(memory.cursors.events,"event-cursor");assert.equal((await service.getOperation(owner,operation.id)).receipt?.id,operation.receipt?.id);assert.equal((await service.getArtifact(owner,artifact.id)).sha256,artifact.sha256);
  memory.roles.set(member.userId,"operator");await service.listSandboxes(member,workspaceId,"member-cursor");assert.equal(memory.lastRequestedBy,member.userId);await assert.rejects(service.getOperation(member,operation.id),isCode("sandbox_operation_not_found"));await assert.rejects(service.getArtifact(member,artifact.id),isCode("sandbox_artifact_not_found"));
});

class MemoryStore {
  readonly roles=new Map([[owner.userId,"owner"]]);readonly receipts=new Map<string,SandboxIdempotencyReceipt>();readonly templates:SandboxTemplate[]=[];readonly grants:SandboxAccessGrant[]=[];readonly audits:{type:string;override:boolean}[]=[];readonly events:SandboxEvent[]=[{eventId:"91000000-0000-4000-8000-000000000001",sandboxId:"70000000-0000-4000-8000-000000000001",operationId:null,sequence:0,type:"sandbox.ready",payload:{},createdAt:"2026-08-22T00:00:01.000Z"}];readonly cursors:Record<string,string>={};templateCreates=0;transitions=0;sandboxValue?:SandboxView;publishedManifest?:SandboxTemplateManifest;nextCursor:string|null=null;includeDrafts=false;lastRequestedBy:string|undefined;lastExpiresInSeconds:number|undefined;session={revokedAt:null as Date|null,accessExpired:false};private tail=Promise.resolve();artifactValue:SandboxArtifact={id:"a0000000-0000-4000-8000-000000000001",workspaceId,sandboxId:"70000000-0000-4000-8000-000000000001",name:"patch",path:"/workspace/artifacts/change.patch",mediaType:"text/plain",size:1,sha256:`sha256:${"e".repeat(64)}`,exportedAt:"2026-08-22T00:01:00.000Z",download:{endpoint:"https://blazn.benpelo.com/v1/sandbox-artifacts/a0000000-0000-4000-8000-000000000001/content",size:1,sha256:`sha256:${"e".repeat(64)}`,mediaType:"text/plain"}};operationValue:SandboxOperation&{workspaceId:string;requestedBy:string}={id:"90000000-0000-4000-8000-000000000001",workspaceId,sandboxId:"70000000-0000-4000-8000-000000000001",requestedBy:owner.userId,type:"create",status:"succeeded",expectedSandboxVersion:1,receipt:{id:"92000000-0000-4000-8000-000000000001",operationId:"90000000-0000-4000-8000-000000000001",operationType:"create",status:"succeeded",cleanupComplete:false,artifactExportComplete:false,grantsRevoked:false,backendDestroyed:false,backend:{present:true,uid:"uid",resourceVersion:"1"},result:null,error:null,createdAt:"2026-08-22T00:00:01.000Z"},createdAt:"2026-08-22T00:00:00.000Z",completedAt:"2026-08-22T00:00:01.000Z"};
  async transaction<T>(fn:(tx:SandboxTransaction)=>Promise<T>){let release!:()=>void;const previous=this.tail;this.tail=new Promise<void>(done=>{release=done;});await previous;try{return await fn(this as unknown as SandboxTransaction);}finally{release();}}async lockIdempotency(){}async getIdempotency(p:string,o:string,k:string){return this.receipts.get(`${p}:${o}:${k}`);}async putIdempotency(p:string,o:string,k:string,r:SandboxIdempotencyReceipt){this.receipts.set(`${p}:${o}:${k}`,r);}async membership(_w:string,u:string){const role=this.roles.get(u);return role?{role,status:"active"}:undefined;}
  async lockWorkspace(){return true;}
  async createTemplate(id:string,w:string,n:string,spec:SandboxTemplateManifest["spec"],digest:string){this.templateCreates++;const t:SandboxTemplate={id,workspaceId:w,name:n,draftVersion:1,draftManifest:{apiVersion:"blazn.dev/v1alpha1",kind:"SandboxTemplate",metadata:{name:n},spec},draftDigest:`sha256:${digest}`,publishedVersionId:null,createdAt:"2026-08-22T00:00:00.000Z",updatedAt:"2026-08-22T00:00:00.000Z"};this.templates.push(t);return t;}async listTemplates(_w:string,cursor="",includeDrafts=false){this.cursors.templates=cursor;this.includeDrafts=includeDrafts;return{items:this.templates,nextCursor:this.nextCursor};}async listVersions(_t:string,cursor=""){this.cursors.versions=cursor;return{items:[],nextCursor:this.nextCursor};}async template(id:string){return this.templates.find(t=>t.id===id);}async publishedVersion(){if(!this.publishedManifest)return undefined;return{id:"60000000-0000-4000-8000-000000000001",workspaceId,templateId:"50000000-0000-4000-8000-000000000001",name:this.publishedManifest.metadata.name,version:this.publishedManifest.spec.version,contentDigest:`sha256:${"a".repeat(64)}`,manifest:this.publishedManifest,status:"published",createdAt:"2026-08-22T00:00:00.000Z"};}async createBoundSandbox(i:{id:string;userId:string;sources:{repository:string;commit:string}[];expiresInSeconds:number}){this.lastExpiresInSeconds=i.expiresInSeconds;this.sandboxValue={...sandbox(),id:i.id,requestedBy:i.userId,sourceBindings:i.sources.map(source=>({...source,url:"https://github.com/blazncloud/blazn.git",destination:"/workspace/src/blazn",writable:false}))};}async sandbox(){return this.sandboxValue;}
  async sessionState(){return this.session;}
  async createGrant(i:{id:string;workspaceId:string;sandboxId:string;kind:"exec"|"upload"|"download";expiresInSeconds:number}){const g:SandboxAccessGrant={id:i.id,workspaceId:i.workspaceId,sandboxId:i.sandboxId,kind:i.kind,scope:`sandbox.${i.kind}`,state:"active",expiresAt:new Date(Date.parse("2026-08-22T00:00:00Z")+i.expiresInSeconds*1000).toISOString(),createdAt:"2026-08-22T00:00:00.000Z"};this.grants.push(g);return g;}async insertAudit(_id:string,_w:string,_s:string|undefined,_u:string,_session:string,type:string,override:boolean){this.audits.push({type,override});}
  async transitionSandbox(_id:string,version:number,type:"stop"|"delete"){if(!this.sandboxValue||this.sandboxValue.version!==version)return undefined;this.transitions++;this.sandboxValue={...this.sandboxValue,state:type==="stop"?"stopping":"deleting",desiredState:type==="stop"?"stopped":"deleted",version:version+1};return this.sandboxValue;}async insertOperation(i:{id:string;sandboxId:string;type:"create"|"stop"|"delete";expectedVersion:number}){return{id:i.id,sandboxId:i.sandboxId,type:i.type,status:"pending" as const,expectedSandboxVersion:i.expectedVersion,receipt:null,createdAt:"2026-08-22T00:00:00.000Z",completedAt:null};}async insertEvent(){}async operation(id:string){return this.operationValue.id===id?this.operationValue:undefined;}async artifact(id:string){return this.artifactValue.id===id?this.artifactValue:undefined;}async listArtifacts(_s:string,cursor=""){this.cursors.artifacts=cursor;return{items:[this.artifactValue],nextCursor:this.nextCursor};}async listEvents(_s:string,cursor=""){this.cursors.events=cursor;return this.events;}async listSandboxes(_w:string,cursor="",requestedBy?:string){this.cursors.sandboxes=cursor;this.lastRequestedBy=requestedBy;const items=this.sandboxValue&&(!requestedBy||this.sandboxValue.requestedBy===requestedBy)?[this.sandboxValue]:[];return{items,nextCursor:this.nextCursor};}
}
function sandbox():SandboxView{return{id:"70000000-0000-4000-8000-000000000001",workspaceId,requestedBy:owner.userId,templateId:"50000000-0000-4000-8000-000000000001",templateVersionId:"60000000-0000-4000-8000-000000000001",templateName:"coding-small",templateVersion:"bootstrap-1",templateDigest:`sha256:${"a".repeat(64)}`,variantName:"linux-amd64",imageIndexDigest:`registry.invalid/poc@sha256:${"b".repeat(64)}`,imageDigest:`registry.invalid/poc@sha256:${"c".repeat(64)}`,architecture:"amd64",allocationMode:"direct",sourceBindings:[],artifactContract:{digest:`sha256:${"d".repeat(64)}`,items:[]},state:"ready",desiredState:"ready",version:1,queueName:"blazn-poc",admissionId:null,isolation:"approved-non-sensitive-poc",expiresAt:"2026-08-22T00:15:00.000Z",conditions:[],createdAt:"2026-08-22T00:00:00.000Z",updatedAt:"2026-08-22T00:00:00.000Z"};}
function isCode(code:string){return(e:unknown)=>e instanceof SandboxHttpError&&e.code===code;}
