import type { PoolClient,QueryResultRow } from "pg";
import type { Database } from "./db.js";
import type { WorkspaceRole } from "./workspace-types.js";
import type { SandboxAccessGrant,SandboxArtifact,SandboxEvent,SandboxGrantKind,SandboxOperation,SandboxOperationType,SandboxTemplate,SandboxTemplateManifest,SandboxTemplateSpec,SandboxTemplateVersion,SandboxView } from "./sandbox-types.js";

export interface SandboxIdempotencyReceipt {workspaceId:string;requestDigest:string;responseStatus:number;responseBody:unknown}
export interface SandboxMembership {role:WorkspaceRole;status:string}
export interface SandboxTransaction {
  lockIdempotency(principalId:string,operation:string,key:string):Promise<void>; getIdempotency(principalId:string,operation:string,key:string):Promise<SandboxIdempotencyReceipt|undefined>; putIdempotency(principalId:string,operation:string,key:string,receipt:SandboxIdempotencyReceipt):Promise<void>;
  lockWorkspace(workspaceId:string):Promise<boolean>;
  membership(workspaceId:string,userId:string,lock?:boolean):Promise<SandboxMembership|undefined>;
  sessionState(sessionId:string,userId:string):Promise<{revokedAt:Date|null;accessExpired:boolean}|undefined>;
  createTemplate(id:string,workspaceId:string,name:string,spec:SandboxTemplateSpec,digest:string,userId:string):Promise<SandboxTemplate>;
  template(templateId:string,lock?:boolean):Promise<SandboxTemplate|undefined>; replaceDraft(templateId:string,expectedVersion:number,spec:SandboxTemplateSpec,digest:string):Promise<SandboxTemplate|undefined>;
  publishVersion(versionId:string,workspaceId:string,templateId:string,expectedVersion:number,canonical:Buffer,digest:string,userId:string):Promise<void>;
  templateVersion(versionId:string):Promise<SandboxTemplateVersion|undefined>; publishedVersion(workspaceId:string,name:string,version:string):Promise<SandboxTemplateVersion|undefined>;
  createBoundSandbox(input:{id:string;workspaceId:string;versionId:string;architecture:string;allocationMode:string;expiresAt:Date;queueName:string;sources:unknown;artifactCanonical:Buffer;artifactDigest:string;userId:string}):Promise<void>;
  sandbox(id:string,lock?:boolean):Promise<SandboxView|undefined>; insertOperation(input:{id:string;workspaceId:string;sandboxId:string;type:SandboxOperationType;expectedVersion:number;userId:string;idempotencyKey:string;requestDigest:string}):Promise<SandboxOperation>;
  transitionSandbox(id:string,expectedVersion:number,type:"stop"|"delete"):Promise<SandboxView|undefined>; insertEvent(id:string,operationId:string,workspaceId:string,sandboxId:string,type:string,payload?:unknown):Promise<void>;
  operation(id:string):Promise<(SandboxOperation&{workspaceId:string;requestedBy:string})|undefined>;
  createGrant(input:{id:string;workspaceId:string;sandboxId:string;userId:string;sessionId:string;kind:SandboxGrantKind;tokenHash:string;expiresInSeconds:number}):Promise<SandboxAccessGrant>;
  artifact(id:string):Promise<SandboxArtifact|undefined>; listArtifacts(sandboxId:string,cursor?:string):Promise<{items:SandboxArtifact[];nextCursor:string|null}>; listEvents(sandboxId:string,afterId?:string):Promise<SandboxEvent[]>;
  listTemplates(workspaceId:string,cursor?:string,includeDrafts?:boolean):Promise<{items:SandboxTemplate[];nextCursor:string|null}>; listVersions(templateId:string,cursor?:string):Promise<{items:SandboxTemplateVersion[];nextCursor:string|null}>; listSandboxes(workspaceId:string,cursor?:string,requestedBy?:string):Promise<{items:SandboxView[];nextCursor:string|null}>;
  insertAudit(id:string,workspaceId:string,sandboxId:string|undefined,userId:string,sessionId:string,type:string,overrideUsed:boolean,payload?:unknown):Promise<void>;
}
export interface SandboxStore {transaction<T>(fn:(tx:SandboxTransaction)=>Promise<T>):Promise<T>;listTemplates(workspaceId:string,cursor?:string,includeDrafts?:boolean):Promise<{items:SandboxTemplate[];nextCursor:string|null}>;listVersions(templateId:string,cursor?:string):Promise<{items:SandboxTemplateVersion[];nextCursor:string|null}>;listSandboxes(workspaceId:string,cursor?:string,requestedBy?:string):Promise<{items:SandboxView[];nextCursor:string|null}>}

export class PgSandboxStore implements SandboxStore {
  constructor(private readonly db:Database){}
  async transaction<T>(fn:(tx:SandboxTransaction)=>Promise<T>):Promise<T>{const client=await this.db.connect();try{await client.query("BEGIN");const value=await fn(new PgSandboxTransaction(client));await client.query("COMMIT");return value;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
  async listTemplates(workspaceId:string,cursor="",includeDrafts=false){const r=await this.db.query("SELECT * FROM sandbox_templates WHERE workspace_id=$1 AND ($2='' OR id::text>$2) AND ($3 OR current_published_version_id IS NOT NULL) ORDER BY id LIMIT 101",[workspaceId,cursor,includeDrafts]);const items=r.rows.slice(0,100).map(templateRow);return{items,nextCursor:r.rows.length>100?items.at(-1)?.id??null:null};}
  async listVersions(templateId:string,cursor=""){const r=await this.db.query(versionSelect+" WHERE v.template_id=$1 AND ($2='' OR v.id::text>$2) ORDER BY v.id LIMIT 101",[templateId,cursor]);const items=r.rows.slice(0,100).map(versionRow);return{items,nextCursor:r.rows.length>100?items.at(-1)?.id??null:null};}
  async listSandboxes(workspaceId:string,cursor="",requestedBy?:string){const r=await this.db.query(sandboxSelect+" WHERE s.workspace_id=$1 AND ($2='' OR s.id::text>$2) AND ($3::uuid IS NULL OR s.requested_by=$3) GROUP BY s.id ORDER BY s.id LIMIT 101",[workspaceId,cursor,requestedBy??null]);const items=r.rows.slice(0,100).map(sandboxRow);return{items,nextCursor:r.rows.length>100?items.at(-1)?.id??null:null};}
}

class PgSandboxTransaction implements SandboxTransaction {
  constructor(private readonly c:PoolClient){}
  async lockIdempotency(p:string,o:string,k:string){await this.c.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`${p}\n${o}\n${k}`]);}
  async getIdempotency(p:string,o:string,k:string){const r=await this.c.query("SELECT workspace_id,request_digest,response_status,response_body FROM sandbox_idempotency_receipts WHERE principal_id=$1 AND operation=$2 AND idempotency_key=$3",[p,o,k]);const x=r.rows[0];return x?{workspaceId:x.workspace_id,requestDigest:x.request_digest.trim(),responseStatus:x.response_status,responseBody:x.response_body}:undefined;}
  async putIdempotency(p:string,o:string,k:string,x:SandboxIdempotencyReceipt){await this.c.query("INSERT INTO sandbox_idempotency_receipts(principal_id,workspace_id,operation,idempotency_key,request_digest,response_status,response_body) VALUES($1,$2,$3,$4,$5,$6,$7)",[p,x.workspaceId,o,k,x.requestDigest,x.responseStatus,x.responseBody]);}
  async lockWorkspace(w:string){const r=await this.c.query("SELECT id FROM workspaces WHERE id=$1 FOR SHARE",[w]);return !!r.rows[0];}
  async membership(w:string,u:string,lock=false){const r=await this.c.query(`SELECT role,status FROM workspace_memberships WHERE workspace_id=$1 AND user_id=$2${lock?" FOR SHARE":""}`,[w,u]);return r.rows[0] as SandboxMembership|undefined;}
  async sessionState(s:string,u:string){const r=await this.c.query("SELECT revoked_at,access_expires_at<=clock_timestamp() AS access_expired FROM sessions WHERE id=$1 AND user_id=$2",[s,u]);const x=r.rows[0];return x?{revokedAt:x.revoked_at,accessExpired:x.access_expired}:undefined;}
  async createTemplate(id:string,w:string,n:string,s:SandboxTemplateSpec,d:string,u:string){const r=await this.c.query("INSERT INTO sandbox_templates(id,workspace_id,name,draft_spec,draft_digest,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[id,w,n,s,d,u]);return templateRow(r.rows[0]);}
  async template(id:string,lock=false){const r=await this.c.query(`SELECT * FROM sandbox_templates WHERE id=$1${lock?" FOR UPDATE":""}`,[id]);return r.rows[0]?templateRow(r.rows[0]):undefined;}
  async replaceDraft(id:string,v:number,s:SandboxTemplateSpec,d:string){const r=await this.c.query("UPDATE sandbox_templates SET draft_spec=$3,draft_digest=$4,draft_revision=draft_revision+1,updated_at=clock_timestamp() WHERE id=$1 AND draft_revision=$2 RETURNING *",[id,v,s,d]);return r.rows[0]?templateRow(r.rows[0]):undefined;}
  async publishVersion(id:string,w:string,t:string,v:number,b:Buffer,d:string,u:string){await this.c.query("SELECT sandbox_publish_template_version($1,$2,$3,$4,$5,$6,$7)",[id,w,t,v,b,d,u]);}
  async templateVersion(id:string){const r=await this.c.query(versionSelect+" WHERE v.id=$1",[id]);return r.rows[0]?versionRow(r.rows[0]):undefined;}
  async publishedVersion(w:string,n:string,v:string){const r=await this.c.query(versionSelect+" WHERE v.workspace_id=$1 AND t.name=$2 AND v.version=$3 AND st.status='published'",[w,n,v]);return r.rows[0]?versionRow(r.rows[0]):undefined;}
  async createBoundSandbox(i:{id:string;workspaceId:string;versionId:string;architecture:string;allocationMode:string;expiresAt:Date;queueName:string;sources:unknown;artifactCanonical:Buffer;artifactDigest:string;userId:string}){await this.c.query("SELECT sandbox_create_bound_sandbox($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11)",[i.id,i.workspaceId,i.versionId,i.architecture,i.allocationMode,i.expiresAt,i.queueName,JSON.stringify(i.sources),i.artifactCanonical,i.artifactDigest,i.userId]);}
  async sandbox(id:string,lock=false){if(lock){const locked=await this.c.query("SELECT id FROM sandboxes WHERE id=$1 FOR UPDATE",[id]);if(!locked.rows[0])return undefined;}const r=await this.c.query(sandboxSelect+" WHERE s.id=$1 GROUP BY s.id",[id]);return r.rows[0]?sandboxRow(r.rows[0]):undefined;}
  async insertOperation(i:{id:string;workspaceId:string;sandboxId:string;type:SandboxOperationType;expectedVersion:number;userId:string;idempotencyKey:string;requestDigest:string}){const r=await this.c.query("INSERT INTO sandbox_operations(id,workspace_id,sandbox_id,type,status,expected_sandbox_version,requested_by,idempotency_key,request_digest) VALUES($1,$2,$3,$4,'pending',$5,$6,$7,$8) RETURNING *",[i.id,i.workspaceId,i.sandboxId,i.type,i.expectedVersion,i.userId,i.idempotencyKey,i.requestDigest]);return operationRow(r.rows[0]);}
  async transitionSandbox(id:string,v:number,type:"stop"|"delete"){const state=type==="stop"?"stopping":"deleting",desired=type==="stop"?"stopped":"deleted";const r=await this.c.query("UPDATE sandboxes SET state=$3,desired_state=$4,version=version+1,updated_at=clock_timestamp() WHERE id=$1 AND version=$2 AND state NOT IN ('stopping','deleting','stopped','deleted') RETURNING id",[id,v,state,desired]);return r.rows[0]?this.sandbox(id):undefined;}
  async insertEvent(id:string,op:string,w:string,s:string,type:string,payload:unknown={}){await this.c.query("INSERT INTO sandbox_events(id,operation_id,workspace_id,sandbox_id,sequence,type,payload) SELECT $1,$2,$3,$4,coalesce(max(sequence)+1,0),$5,$6 FROM sandbox_events WHERE sandbox_id=$4",[id,op,w,s,type,payload]);}
  async operation(id:string){const r=await this.c.query(operationSelect+" WHERE o.id=$1",[id]);return r.rows[0]?{...operationRow(r.rows[0]),workspaceId:r.rows[0].workspace_id,requestedBy:r.rows[0].requested_by}:undefined;}
  async createGrant(i:{id:string;workspaceId:string;sandboxId:string;userId:string;sessionId:string;kind:SandboxGrantKind;tokenHash:string;expiresInSeconds:number}){const r=await this.c.query("INSERT INTO sandbox_access_grants(id,workspace_id,sandbox_id,user_id,session_id,scope,kind,token_hash,token_key_id,expires_at) VALUES($1,$2,$3,$4,$5,'sandbox.'||$6,$6,$7,'sandbox-access-grant/v1',now()+$8*interval '1 second') RETURNING *",[i.id,i.workspaceId,i.sandboxId,i.userId,i.sessionId,i.kind,i.tokenHash,i.expiresInSeconds]);return grantRow(r.rows[0]);}
  async artifact(id:string){const r=await this.c.query("SELECT * FROM sandbox_artifacts WHERE id=$1",[id]);return r.rows[0]?artifactRow(r.rows[0]):undefined;}
  async listArtifacts(s:string,cursor=""){const r=await this.c.query("SELECT * FROM sandbox_artifacts WHERE sandbox_id=$1 AND ($2='' OR id::text>$2) ORDER BY id LIMIT 101",[s,cursor]);const items=r.rows.slice(0,100).map(artifactRow);return{items,nextCursor:r.rows.length>100?items.at(-1)?.id??null:null};}
  async listEvents(s:string,after=""){const r=await this.c.query("SELECT * FROM sandbox_events WHERE sandbox_id=$1 AND ($2='' OR sequence>(SELECT sequence FROM sandbox_events WHERE sandbox_id=$1 AND id::text=$2)) ORDER BY sequence LIMIT 100",[s,after]);return r.rows.map(eventRow);}
  async listTemplates(w:string,cursor="",includeDrafts=false){const r=await this.c.query("SELECT * FROM sandbox_templates WHERE workspace_id=$1 AND ($2='' OR id::text>$2) AND ($3 OR current_published_version_id IS NOT NULL) ORDER BY id LIMIT 101",[w,cursor,includeDrafts]);const items=r.rows.slice(0,100).map(templateRow);return{items,nextCursor:r.rows.length>100?items.at(-1)?.id??null:null};}
  async listVersions(t:string,cursor=""){const r=await this.c.query(versionSelect+" WHERE v.template_id=$1 AND ($2='' OR v.id::text>$2) ORDER BY v.id LIMIT 101",[t,cursor]);const items=r.rows.slice(0,100).map(versionRow);return{items,nextCursor:r.rows.length>100?items.at(-1)?.id??null:null};}
  async listSandboxes(w:string,cursor="",requestedBy?:string){const r=await this.c.query(sandboxSelect+" WHERE s.workspace_id=$1 AND ($2='' OR s.id::text>$2) AND ($3::uuid IS NULL OR s.requested_by=$3) GROUP BY s.id ORDER BY s.id LIMIT 101",[w,cursor,requestedBy??null]);const items=r.rows.slice(0,100).map(sandboxRow);return{items,nextCursor:r.rows.length>100?items.at(-1)?.id??null:null};}
  async insertAudit(id:string,w:string,s:string|undefined,u:string,session:string,type:string,override:boolean,payload:unknown={}){await this.c.query("INSERT INTO sandbox_audit_events(id,workspace_id,sandbox_id,actor_user_id,actor_session_id,event_type,override_used,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[id,w,s??null,u,session,type,override,payload]);}
}

const versionSelect=`SELECT v.*,t.name,st.status FROM sandbox_template_versions v JOIN sandbox_templates t ON t.id=v.template_id JOIN sandbox_template_version_status st ON st.version_id=v.id`;
const operationSelect=`SELECT o.*,r.id receipt_id,r.status receipt_status,r.operation_type,r.result,r.error,r.cleanup_complete,r.artifact_export_complete,r.grants_revoked,r.backend_destroyed,r.backend_present,r.backend_uid,r.backend_resource_version,r.created_at receipt_created_at FROM sandbox_operations o LEFT JOIN sandbox_operation_terminal_receipts r ON r.id=o.terminal_receipt_id`;
const sandboxSelect=`SELECT s.*,coalesce(jsonb_agg(DISTINCT jsonb_build_object('repository',src.repository_name,'url',repo.url,'destination',repo.destination,'writable',repo.writable,'commit',src.commit)) FILTER(WHERE src.repository_name IS NOT NULL),'[]') sources,coalesce(jsonb_agg(DISTINCT jsonb_build_object('name',a.name,'path',a.path,'mediaType',a.media_type,'required',a.required)) FILTER(WHERE a.name IS NOT NULL),'[]') artifacts FROM sandboxes s LEFT JOIN sandbox_sources src ON src.sandbox_id=s.id LEFT JOIN sandbox_template_version_repositories repo ON repo.version_id=s.template_version_id AND repo.name=src.repository_name LEFT JOIN sandbox_artifact_contract_entries a ON a.sandbox_id=s.id`;
function manifest(name:string,spec:SandboxTemplateSpec):SandboxTemplateManifest{return{apiVersion:"blazn.dev/v1alpha1",kind:"SandboxTemplate",metadata:{name},spec};}
function iso(v:Date|string){return typeof v==="string"?new Date(v).toISOString():v.toISOString();}
function templateRow(r:QueryResultRow):SandboxTemplate{return{id:r.id,workspaceId:r.workspace_id,name:r.name,draftVersion:Number(r.draft_revision),draftManifest:manifest(r.name,r.draft_spec),draftDigest:`sha256:${r.draft_digest.trim()}`,publishedVersionId:r.current_published_version_id,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)};}
function versionRow(r:QueryResultRow):SandboxTemplateVersion{return{id:r.id,workspaceId:r.workspace_id,templateId:r.template_id,name:r.name,version:r.version,contentDigest:`sha256:${r.content_digest.trim()}`,manifest:manifest(r.name,r.spec),status:r.status,createdAt:iso(r.created_at)};}
function sandboxRow(r:QueryResultRow):SandboxView{return{id:r.id,workspaceId:r.workspace_id,requestedBy:r.requested_by,templateId:r.template_id,templateVersionId:r.template_version_id,templateName:r.template_name,templateVersion:r.template_version,templateDigest:`sha256:${r.template_digest.trim()}`,variantName:r.variant_name,imageIndexDigest:r.image_index_digest,imageDigest:r.image_child_digest,architecture:r.architecture,allocationMode:r.allocation_mode,sourceBindings:r.sources,artifactContract:{digest:`sha256:${r.artifact_contract_digest.trim()}`,items:r.artifacts},state:r.state,desiredState:r.desired_state,version:Number(r.version),queueName:r.queue_name,admissionId:r.admission_id,isolation:r.isolation,expiresAt:iso(r.expires_at),conditions:r.conditions,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at),...(r.stopped_at?{stoppedAt:iso(r.stopped_at)}:{}),...(r.deleted_at?{deletedAt:iso(r.deleted_at)}:{})};}
function operationRow(r:QueryResultRow):SandboxOperation{const receipt=r.receipt_id?{id:r.receipt_id,operationId:r.id,operationType:r.operation_type,status:r.receipt_status,cleanupComplete:r.cleanup_complete,artifactExportComplete:r.artifact_export_complete,grantsRevoked:r.grants_revoked,backendDestroyed:r.backend_destroyed,backend:{present:r.backend_present,uid:r.backend_uid,resourceVersion:r.backend_resource_version},result:r.result,error:r.error,createdAt:iso(r.receipt_created_at)}:null;return{id:r.id,sandboxId:r.sandbox_id,type:r.type,status:r.status,expectedSandboxVersion:Number(r.expected_sandbox_version),receipt,createdAt:iso(r.created_at),completedAt:r.completed_at?iso(r.completed_at):null};}
function grantRow(r:QueryResultRow):SandboxAccessGrant{return{id:r.id,sandboxId:r.sandbox_id,workspaceId:r.workspace_id,scope:r.scope,kind:r.kind,state:r.state,expiresAt:iso(r.expires_at),createdAt:iso(r.created_at)};}
function eventRow(r:QueryResultRow):SandboxEvent{return{eventId:r.id,sandboxId:r.sandbox_id,operationId:r.operation_id,sequence:Number(r.sequence),type:r.type,payload:r.payload,createdAt:iso(r.created_at)};}
function artifactRow(r:QueryResultRow):SandboxArtifact{const digest=`sha256:${r.content_digest.trim()}`,size=Number(r.size_bytes),endpoint=`https://blazn.benpelo.com/v1/sandbox-artifacts/${r.id}/content`;return{id:r.id,workspaceId:r.workspace_id,sandboxId:r.sandbox_id,name:r.name,path:r.path,mediaType:r.media_type,size,sha256:digest,exportedAt:iso(r.exported_at),download:{endpoint,size,sha256:digest,mediaType:r.media_type}};}
