import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { createServer,type ServerResponse } from "node:http";
import test from "node:test";
import { SandboxHttpRouter,writeSandboxSse } from "./sandbox-http.js";
import type { SandboxService } from "./sandbox-service.js";
import { SandboxHttpError,type SandboxPrincipal } from "./sandbox-types.js";

const principal:SandboxPrincipal={userId:"10000000-0000-4000-8000-000000000001",sessionId:"30000000-0000-4000-8000-000000000001",email:"owner@example.test",displayName:"Owner"};
const workspace="40000000-0000-4000-8000-000000000001",sandbox="70000000-0000-4000-8000-000000000001";

test("sandbox router maps exact operation identity and idempotency",async()=>{let received:unknown;const service={createOperation:async(...args:unknown[])=>{received=args;return{accepted:true};}};const router=new SandboxHttpRouter(service as unknown as SandboxService);const reply=await request(router,"POST",`/v1/sandboxes/${sandbox}/operations`,{"idempotency-key":"operation-key-1"},{type:"stop",expectedVersion:7});assert.equal(reply.status,202);assert.deepEqual(received,[principal,sandbox,"operation-key-1",{type:"stop",expectedVersion:7}]);});

test("access grant creation rejects idempotency and unsupported fields before issuing bearer material",async()=>{let calls=0;const service={createAccessGrant:async()=>{calls++;return{};}};const router=new SandboxHttpRouter(service as unknown as SandboxService);const withKey=await request(router,"POST",`/v1/sandboxes/${sandbox}/access-grants`,{"idempotency-key":"grant-key-0001"},{kind:"exec",expiresInSeconds:30});assert.equal(withKey.status,400);assert.equal(withKey.body.code,"invalid_request");const extra=await request(router,"POST",`/v1/sandboxes/${sandbox}/access-grants`,{}, {kind:"exec",expiresInSeconds:30,accessToken:"forbidden"});assert.equal(extra.status,400);assert.equal(calls,0);});

test("persistence router does not capture grant transport or artifact-content routes",()=>{const router=new SandboxHttpRouter({} as SandboxService);assert.equal(router.matches(`/v1/sandboxes/${sandbox}/events`),true);assert.equal(router.matches(`/v1/sandbox-access-grants/${sandbox}/exec`),false);assert.equal(router.matches(`/v1/sandbox-artifacts/${sandbox}/content`),false);assert.equal(router.matches(`/v1/workspaces/${workspace}/sandboxes`),true);});

test("wrong methods and duplicate cursors use only frozen errors",async()=>{const router=new SandboxHttpRouter({listSandboxes:async()=>({items:[],nextCursor:null})} as unknown as SandboxService);const wrong=await request(router,"PATCH",`/v1/workspaces/${workspace}/sandboxes`,{},{});assert.equal(wrong.status,400);assert.equal(wrong.body.code,"invalid_request");const duplicate=await request(router,"GET",`/v1/workspaces/${workspace}/sandboxes?cursor=a&cursor=b`,{},undefined);assert.equal(duplicate.status,400);assert.equal(duplicate.body.code,"invalid_request");});

test("SSE emits only real typed event ids and reconnects from Last-Event-ID",async()=>{const event={eventId:"91000000-0000-4000-8000-000000000001",sandboxId:sandbox,operationId:null,sequence:1,type:"sandbox.ready",payload:{state:"ready"},createdAt:"2026-08-22T00:00:00.000Z"};const cursors:string[]=[];let calls=0,auth=0;const service={eventBatch:async(_p:unknown,_id:string,cursor:string)=>{cursors.push(cursor);return calls++===0?[event]:[];}};const router=new SandboxHttpRouter(service as unknown as SandboxService,2,8);const reply=await streamRequest(router,`/v1/sandboxes/${sandbox}/events`,{"last-event-id":"90000000-0000-4000-8000-000000000001"},async()=>{auth++;return principal;});assert.match(reply,/event: sandbox\.ready\nid: 91000000-/);assert.doesNotMatch(reply,/event: ready|data: \{\}\nid:/);assert.deepEqual(cursors.slice(0,2),["90000000-0000-4000-8000-000000000001","91000000-0000-4000-8000-000000000001"]);assert.ok(auth>1);});

test("empty and oversized SSE batches expose no synthetic or oversized event identity",async()=>{const empty=new SandboxHttpRouter({eventBatch:async()=>[]} as unknown as SandboxService,2,5);const heartbeat=await streamRequest(empty,`/v1/sandboxes/${sandbox}/events`,{},async()=>principal);assert.match(heartbeat,/^: connected/);assert.doesNotMatch(heartbeat,/^(?:id|event|data):/m);const huge={eventId:"91000000-0000-4000-8000-000000000002",sandboxId:sandbox,operationId:null,sequence:2,type:"sandbox.output",payload:{text:"x".repeat(1024)},createdAt:"2026-08-22T00:00:00.000Z"};const bounded=new SandboxHttpRouter({eventBatch:async()=>[huge]} as unknown as SandboxService,2,5,1,1,5,128);assert.equal(await streamRequest(bounded,`/v1/sandboxes/${sandbox}/events`,{},async()=>principal),"");});

test("SSE rejects persisted event identities outside the frozen grammar",async()=>{for(const event of [{eventId:"not-a-uuid",type:"sandbox.ready"},{eventId:"91000000-0000-4000-8000-000000000003",type:"sandbox\nforged"}]){const service={eventBatch:async()=>[{...event,sandboxId:sandbox,operationId:null,sequence:3,payload:{},createdAt:"2026-08-22T00:00:00.000Z"}]};const reply=await streamRequest(new SandboxHttpRouter(service as unknown as SandboxService,2,5),`/v1/sandboxes/${sandbox}/events`,{},async()=>principal);assert.equal(reply,"");}});

test("SSE writer drains or destroys a stalled response within its bound",async()=>{const drained=new FakeResponse(false);const pending=writeSandboxSse(drained as unknown as ServerResponse,"event",50);queueMicrotask(()=>drained.emit("drain"));assert.equal(await pending,true);const stalled=new FakeResponse(false);assert.equal(await writeSandboxSse(stalled as unknown as ServerResponse,"event",2),false);assert.equal(stalled.destroyed,true);});
test("SSE capacity is deterministic and releases slots",()=>{const router=new SandboxHttpRouter({} as SandboxService,1,10,1,1);const reserve=(router as unknown as {reserve:(userId:string)=>()=>void}).reserve.bind(router);const release=reserve(principal.userId);assert.throws(()=>reserve(principal.userId),isCode("rate_limited"));release();assert.doesNotThrow(()=>reserve(principal.userId)());});

async function request(router:SandboxHttpRouter,method:string,path:string,headers:Record<string,string>,body:unknown){const server=createServer(async(req,res)=>{try{await router.handle(req,res,new URL(req.url!,"http://localhost"),async()=>principal);}catch(e){const error=e instanceof SandboxHttpError?e:new SandboxHttpError("internal_error","request failed");const payload=JSON.stringify({code:error.code,message:error.message});res.writeHead(error.status,{"content-type":"application/json"});res.end(payload);}});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));try{const address=server.address();assert.ok(address&&typeof address==="object");const response=await fetch(`http://127.0.0.1:${address.port}${path}`,{method,headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});return{status:response.status,body:await response.json() as Record<string,unknown>};}finally{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));}}
async function streamRequest(router:SandboxHttpRouter,path:string,headers:Record<string,string>,authenticate:()=>Promise<SandboxPrincipal>){const server=createServer(async(req,res)=>{try{await router.handle(req,res,new URL(req.url!,"http://localhost"),authenticate);}catch(e){const error=e instanceof SandboxHttpError?e:new SandboxHttpError("internal_error","request failed");res.writeHead(error.status);res.end(error.code);}});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));try{const address=server.address();assert.ok(address&&typeof address==="object");const response=await fetch(`http://127.0.0.1:${address.port}${path}`,{headers});return await response.text();}finally{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));}}
class FakeResponse extends EventEmitter {destroyed=false;writableEnded=false;constructor(private readonly writable:boolean){super();}write(){return this.writable;}destroy(){this.destroyed=true;this.emit("close");return this;}}
function isCode(code:string){return(e:unknown)=>e instanceof SandboxHttpError&&e.code===code;}
