import type { IncomingMessage,ServerResponse } from "node:http";
import { jsonBody,sendJson } from "./http.js";
import type { SandboxService } from "./sandbox-service.js";
import { SandboxHttpError,type SandboxAllocationMode,type SandboxArchitecture,type SandboxGrantKind,type SandboxPrincipal,type SandboxSource,type SandboxTemplateManifest } from "./sandbox-types.js";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
export class SandboxHttpRouter {
  private readonly streamsByUser=new Map<string,number>();private streamCount=0;
  constructor(private readonly service:SandboxService,private readonly pollIntervalMs=1_000,private readonly maxLifetimeMs=15*60_000,private readonly globalStreamLimit=256,private readonly perUserStreamLimit=8,private readonly drainTimeoutMs=5_000){for(const value of [pollIntervalMs,maxLifetimeMs,globalStreamLimit,perUserStreamLimit,drainTimeoutMs])if(!Number.isSafeInteger(value)||value<1)throw new Error("sandbox stream limits must be positive integers");}
  matches(path:string){return /^\/v1\/workspaces\/[^/]+\/(?:sandbox-templates|sandboxes)$/.test(path)||path.startsWith("/v1/sandbox-templates/")||path.startsWith("/v1/sandbox-template-versions/")||path.startsWith("/v1/sandboxes/")||path.startsWith("/v1/sandbox-operations/")||(/^\/v1\/sandbox-artifacts\/[^/]+$/.test(path));}
  async handle(request:IncomingMessage,response:ServerResponse,url:URL,authenticate:()=>Promise<SandboxPrincipal>):Promise<void>{
    const p=url.pathname;
    const templates=p.match(/^\/v1\/workspaces\/([^/]+)\/sandbox-templates$/);if(templates){const principal=await authenticate(),workspaceId=uuid(templates[1]!,"workspaceId");if(request.method==="GET")return sendJson(response,200,await this.service.listTemplates(principal,workspaceId,cursor(url)));if(request.method==="POST"){noQuery(url);const body=await jsonBody(request,1024*1024);return sendJson(response,201,await this.service.createTemplate(principal,workspaceId,idempotency(request),body as unknown as SandboxTemplateManifest));}throw method();}
    const draft=p.match(/^\/v1\/sandbox-templates\/([^/]+)\/draft$/);if(draft){if(request.method!=="PUT")throw method();noQuery(url);const body=await jsonBody(request,1024*1024);exact(body,["expectedDraftVersion","manifest"]);return sendJson(response,200,await this.service.replaceDraft(await authenticate(),uuid(draft[1]!,"templateId"),idempotency(request),{expectedDraftVersion:integer(body.expectedDraftVersion,"expectedDraftVersion",1),manifest:object(body.manifest,"manifest") as unknown as SandboxTemplateManifest}));}
    const versions=p.match(/^\/v1\/sandbox-templates\/([^/]+)\/versions$/);if(versions){const templateId=uuid(versions[1]!,"templateId"),principal=await authenticate();if(request.method==="GET")return sendJson(response,200,await this.service.listVersions(principal,templateId,cursor(url)));if(request.method==="POST"){noQuery(url);const body=await jsonBody(request);exact(body,["expectedDraftVersion"]);return sendJson(response,201,await this.service.publishVersion(principal,templateId,idempotency(request),{expectedDraftVersion:integer(body.expectedDraftVersion,"expectedDraftVersion",1)}));}throw method();}
    const template=p.match(/^\/v1\/sandbox-templates\/([^/]+)$/);if(template){if(request.method!=="GET")throw method();noQuery(url);return sendJson(response,200,await this.service.getTemplate(await authenticate(),uuid(template[1]!,"templateId")));}
    const version=p.match(/^\/v1\/sandbox-template-versions\/([^/]+)$/);if(version){if(request.method!=="GET")throw method();noQuery(url);return sendJson(response,200,await this.service.getVersion(await authenticate(),uuid(version[1]!,"versionId")));}
    const sandboxes=p.match(/^\/v1\/workspaces\/([^/]+)\/sandboxes$/);if(sandboxes){const principal=await authenticate(),workspaceId=uuid(sandboxes[1]!,"workspaceId");if(request.method==="GET")return sendJson(response,200,await this.service.listSandboxes(principal,workspaceId,cursor(url)));if(request.method==="POST"){noQuery(url);const body=await jsonBody(request);exact(body,["template","architecture","allocationMode","expiresInSeconds","sources","approvedNonSensitive"]);const templateBody=object(body.template,"template");exact(templateBody,["name","version"]);if(!Array.isArray(body.sources))invalid("sources must be an array");const sources=body.sources.map((item,index)=>{const source=object(item,`sources[${index}]`);exact(source,["repository","commit"]);return{repository:string(source.repository,"repository",63),commit:string(source.commit,"commit",64)};});return sendJson(response,202,await this.service.createSandbox(principal,workspaceId,idempotency(request),{template:{name:string(templateBody.name,"name",63),version:string(templateBody.version,"version",128)},architecture:one(body.architecture,"architecture",["amd64","arm64"]) as SandboxArchitecture,allocationMode:one(body.allocationMode,"allocationMode",["direct","claim"]) as SandboxAllocationMode,expiresInSeconds:integer(body.expiresInSeconds,"expiresInSeconds",60),sources:sources as SandboxSource[],approvedNonSensitive:literalTrue(body.approvedNonSensitive)}));}throw method();}
    const events=p.match(/^\/v1\/sandboxes\/([^/]+)\/events$/);if(events){if(request.method!=="GET")throw method();noQuery(url);return this.stream(request,response,uuid(events[1]!,"sandboxId"),authenticate);}
    const operations=p.match(/^\/v1\/sandboxes\/([^/]+)\/operations$/);if(operations){if(request.method!=="POST")throw method();noQuery(url);const body=await jsonBody(request);exact(body,["type","expectedVersion"]);return sendJson(response,202,await this.service.createOperation(await authenticate(),uuid(operations[1]!,"sandboxId"),idempotency(request),{type:one(body.type,"type",["stop","delete"]),expectedVersion:integer(body.expectedVersion,"expectedVersion",1)}));}
    const grants=p.match(/^\/v1\/sandboxes\/([^/]+)\/access-grants$/);if(grants){if(request.method!=="POST")throw method();noQuery(url);if(request.headers["idempotency-key"]!==undefined)invalid("Idempotency-Key is not accepted for access grant creation");const body=await jsonBody(request);exact(body,["kind","expiresInSeconds"]);return sendJson(response,201,await this.service.createAccessGrant(await authenticate(),uuid(grants[1]!,"sandboxId"),{kind:one(body.kind,"kind",["exec","upload","download"]) as SandboxGrantKind,expiresInSeconds:integer(body.expiresInSeconds,"expiresInSeconds",1)}));}
    const artifacts=p.match(/^\/v1\/sandboxes\/([^/]+)\/artifacts$/);if(artifacts){if(request.method!=="GET")throw method();return sendJson(response,200,await this.service.listArtifacts(await authenticate(),uuid(artifacts[1]!,"sandboxId"),cursor(url)));}
    const sandbox=p.match(/^\/v1\/sandboxes\/([^/]+)$/);if(sandbox){if(request.method!=="GET")throw method();noQuery(url);return sendJson(response,200,await this.service.getSandbox(await authenticate(),uuid(sandbox[1]!,"sandboxId")));}
    const operation=p.match(/^\/v1\/sandbox-operations\/([^/]+)$/);if(operation){if(request.method!=="GET")throw method();noQuery(url);return sendJson(response,200,await this.service.getOperation(await authenticate(),uuid(operation[1]!,"operationId")));}
    const artifact=p.match(/^\/v1\/sandbox-artifacts\/([^/]+)$/);if(artifact){if(request.method!=="GET")throw method();noQuery(url);return sendJson(response,200,await this.service.getArtifact(await authenticate(),uuid(artifact[1]!,"artifactId")));}
    throw new SandboxHttpError("sandbox_not_found","sandbox route was not found");
  }
  private async stream(request:IncomingMessage,response:ServerResponse,id:string,authenticate:()=>Promise<SandboxPrincipal>){const values=request.headersDistinct["last-event-id"]??[];if(values.length>1||(values[0]&&!UUID.test(values[0])))invalid("Last-Event-ID is invalid");let cursor=values[0]??"",principal=await authenticate();await this.service.eventBatch(principal,id,cursor);const release=this.reserve(principal.userId),started=Date.now();try{response.writeHead(200,{"content-type":"text/event-stream","cache-control":"no-store",connection:"keep-alive"});if(!await write(response,`event: ready\nid: ${cursor}\ndata: {}\n\n`,this.drainTimeoutMs))return;while(!response.destroyed&&!response.writableEnded&&Date.now()-started<this.maxLifetimeMs){await new Promise(r=>setTimeout(r,this.pollIntervalMs));if(response.destroyed||response.writableEnded)break;try{principal=await authenticate();const events=await this.service.eventBatch(principal,id,cursor);for(const event of events){cursor=event.eventId;if(!await write(response,`event: ${event.type}\nid: ${event.eventId}\ndata: ${JSON.stringify(event)}\n\n`,this.drainTimeoutMs))return;}if(events.length===0&&!await write(response,": heartbeat\n\n",this.drainTimeoutMs))return;}catch{break;}}}finally{if(!response.destroyed&&!response.writableEnded)response.end();release();}}
  private reserve(userId:string){const user=this.streamsByUser.get(userId)??0;if(this.streamCount>=this.globalStreamLimit||user>=this.perUserStreamLimit)throw new SandboxHttpError("rate_limited","sandbox event stream capacity is exhausted");this.streamCount++;this.streamsByUser.set(userId,user+1);let released=false;return()=>{if(released)return;released=true;this.streamCount--;const remaining=(this.streamsByUser.get(userId)??1)-1;if(remaining===0)this.streamsByUser.delete(userId);else this.streamsByUser.set(userId,remaining);};}
}
function exact(v:Record<string,unknown>,required:string[]){if(required.some(k=>!(k in v))||Object.keys(v).some(k=>!required.includes(k)))invalid(`request body must contain exactly: ${required.join(", ")}`);}function object(v:unknown,n:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))invalid(`${n} must be an object`);return v as Record<string,unknown>;}function string(v:unknown,n:string,max:number){if(typeof v!=="string"||!v||v.length>max)invalid(`${n} is invalid`);return v;}function integer(v:unknown,n:string,min:number){if(typeof v!=="number"||!Number.isSafeInteger(v)||v<min)invalid(`${n} is invalid`);return v;}function one<T extends string>(v:unknown,n:string,a:readonly T[]):T{if(typeof v!=="string"||!a.includes(v as T))invalid(`${n} is invalid`);return v as T;}function literalTrue(v:unknown):true{if(v!==true)invalid("approvedNonSensitive must be true");return true;}function uuid(v:string,n:string){if(!UUID.test(v))invalid(`${n} must be a UUID`);return v;}function cursor(u:URL){const unknown=[...u.searchParams.keys()].filter(k=>k!=="cursor");const values=u.searchParams.getAll("cursor");if(unknown.length||values.length>1)invalid("query parameters are invalid");const v=values[0]??"";if(v.length>512)invalid("cursor is invalid");return v;}function noQuery(u:URL){if(u.search!=="")invalid("query parameters are not accepted");}function idempotency(r:IncomingMessage){const v=r.headersDistinct["idempotency-key"]??[];if(v.length!==1||v[0]!.length<8||v[0]!.length>128)invalid("Idempotency-Key is required");return v[0]!;}function method(){return new SandboxHttpError("method_not_allowed","method is not allowed for this route");}function invalid(m:string):never{throw new SandboxHttpError("invalid_request",m);}function write(response:ServerResponse,chunk:string,timeoutMs:number):Promise<boolean>{if(response.destroyed||response.writableEnded)return Promise.resolve(false);if(response.write(chunk))return Promise.resolve(true);return new Promise(resolve=>{let done=false;let timer:NodeJS.Timeout;const finish=(value:boolean)=>{if(done)return;done=true;clearTimeout(timer);response.off("drain",drained);response.off("close",closed);response.off("error",closed);resolve(value);};const drained=()=>finish(true),closed=()=>finish(false);timer=setTimeout(()=>{response.destroy();finish(false);},timeoutMs);response.once("drain",drained);response.once("close",closed);response.once("error",closed);});}
