ALTER DEFAULT PRIVILEGES FOR ROLE blazn_migration IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;
GRANT EXECUTE ON FUNCTION workspace_json_contains_secret_key(jsonb) TO blazn_runtime;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM blazn_node_broker;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM blazn_node_broker;
ALTER DEFAULT PRIVILEGES FOR ROLE blazn_migration IN SCHEMA public
  REVOKE ALL ON TABLES FROM blazn_node_broker;
ALTER DEFAULT PRIVILEGES FOR ROLE blazn_migration IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM blazn_node_broker;
ALTER DEFAULT PRIVILEGES FOR ROLE blazn_migration IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM blazn_node_broker;
